#!/usr/bin/env python3
"""AP1 Softwareentwicklung - 100 handgeschriebene Fragen."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from qlib import S, M, T, build

Q = [
# ---------------------------------------------------------------- single (32)
S("ap1-swe-r01",
  "Ein Programm soll speichern, ob ein Kunde zugestimmt hat. Welcher Datentyp passt?",
  ("boolean", "integer", "string mit fester Zeichenlänge", "float mit doppelter Genauigkeit"), 0,
  "Ein boolean kennt genau die beiden Zustände true und false und bildet eine Ja-Nein-Entscheidung exakt ab. Zahlen oder Texte dafür zu missbrauchen macht den Code unnötig fehleranfällig.",
  "A program needs to store whether a customer has agreed. Which data type fits?",
  ("boolean", "integer", "string with a fixed character length", "float with double precision"),
  "A boolean knows exactly the two states true and false and models a yes-no decision precisely. Misusing numbers or text for it makes the code needlessly error-prone."),

S("ap1-swe-r02",
  "Welche Schleifenart durchläuft ihren Rumpf garantiert mindestens einmal?",
  ("Die fußgesteuerte do-while-Schleife",
   "Die kopfgesteuerte while-Schleife",
   "Die Zählschleife mit Startwert über dem Endwert",
   "Keine, denn jede Schleife lässt sich überspringen"), 0,
  "Bei der fußgesteuerten Schleife steht die Bedingung nach dem Rumpf, der Rumpf läuft also vor der ersten Prüfung. Kopfgesteuerte Schleifen prüfen zuerst und können komplett übersprungen werden.",
  "Which kind of loop is guaranteed to run its body at least once?",
  ("The foot-controlled do-while loop",
   "The head-controlled while loop",
   "The counting loop with start above end value",
   "None, since every loop can be skipped entirely"),
  "In a foot-controlled loop the condition sits after the body, so the body runs before the first check. Head-controlled loops check first and can be skipped completely."),

S("ap1-swe-r03",
  "Ein Programm lässt sich nicht übersetzen, weil ein Semikolon fehlt. Um welche Fehlerart handelt es sich?",
  ("Syntaxfehler", "Laufzeitfehler", "Logischer Fehler", "Fehler in der Programmdokumentation"), 0,
  "Syntaxfehler verstoßen gegen die Sprachregeln und fallen schon beim Übersetzen auf. Laufzeitfehler treten erst bei der Ausführung auf, logische Fehler liefern lauffähigen, aber falschen Code.",
  "A program will not compile because a semicolon is missing. Which kind of error is this?",
  ("Syntax error", "Runtime error", "Logical error", "Error in the program documentation"),
  "Syntax errors violate the language rules and show up during compilation. Runtime errors appear only during execution, logical errors produce running but wrong code."),

S("ap1-swe-r04",
  "Ein Programm läuft durch, berechnet aber durchweg falsche Summen. Welche Fehlerart liegt vor?",
  ("Ein logischer Fehler im Algorithmus",
   "Ein Syntaxfehler in der Quelldatei",
   "Ein Fehler beim Übersetzen des Programms",
   "Ein Fehler in der eingesetzten Entwicklungsumgebung"), 0,
  "Ein logischer Fehler ist sprachlich korrekt, bildet aber die Anforderung falsch ab - der Compiler kann ihn nicht bemerken. Genau solche Fehler findet man nur durch Testfälle mit bekanntem Sollergebnis.",
  "A program runs through but consistently computes wrong totals. Which kind of error is this?",
  ("A logical error in the algorithm",
   "A syntax error in the source file",
   "An error while compiling the program",
   "An error in the development environment used"),
  "A logical error is linguistically correct but models the requirement wrongly - the compiler cannot notice it. Such errors are found only through test cases with a known expected result."),

S("ap1-swe-r05",
  "Welchen dezimalen Wert hat die Binärzahl 10110?",
  ("22", "20", "24", "26"), 0,
  "Stellenwerte von rechts sind 1, 2, 4, 8 und 16: also 16 + 0 + 4 + 2 + 0 = 22.",
  "What decimal value does the binary number 10110 have?",
  ("22", "20", "24", "26"),
  "The place values from the right are 1, 2, 4, 8 and 16: so 16 + 0 + 4 + 2 + 0 = 22."),

S("ap1-swe-r06",
  "In einem Team soll nachvollziehbar bleiben, wer wann welche Änderung gemacht hat. Was setzt ihr ein?",
  ("Eine Versionsverwaltung wie Git",
   "Eine gemeinsame Ablage auf dem Netzlaufwerk",
   "Eine Namenskonvention mit Datum im Dateinamen",
   "Eine wöchentliche Sicherungskopie des Projektordners"), 0,
  "Versionsverwaltung speichert jede Änderung mit Autor, Zeitpunkt und Beschreibung und erlaubt paralleles Arbeiten in Branches. Dateinamen mit Datum und Sicherungen liefern nichts davon.",
  "A team needs to keep track of who changed what and when. What do you use?",
  ("A version control system such as Git",
   "A shared folder on the network drive",
   "A naming convention with the date in the file name",
   "A weekly backup copy of the project directory"),
  "Version control stores every change with author, timestamp and description and allows parallel work in branches. File names with dates and backups deliver none of that."),

S("ap1-swe-r07",
  "Was beschreibt ein Struktogramm nach Nassi-Shneiderman?",
  ("Den Ablauf eines Algorithmus in geschachtelten Blöcken",
   "Den Aufbau einer Datenbank mit ihren Tabellen",
   "Die Verteilung der Komponenten auf mehrere Server",
   "Die zeitliche Planung der Arbeitspakete im Projekt"), 0,
  "Struktogramme stellen Sequenz, Verzweigung und Wiederholung als ineinander liegende Rechtecke dar und erzwingen dadurch strukturierte Programmierung ohne Sprünge.",
  "What does a Nassi-Shneiderman diagram describe?",
  ("The flow of an algorithm in nested blocks",
   "The structure of a database with its tables",
   "The distribution of components across servers",
   "The scheduling of work packages in a project"),
  "Structograms represent sequence, selection and iteration as nested rectangles and thereby enforce structured programming without jumps."),

S("ap1-swe-r08",
  "Ein Datenfeld soll 50 Namen aufnehmen, die über einen Index ansprechbar sind. Was nutzt du?",
  ("Ein Array", "Eine einzelne Variable", "Eine Konstante", "Einen Kommentar"), 0,
  "Ein Array fasst gleichartige Werte unter einem Namen zusammen und macht sie über einen Index erreichbar. Einzelvariablen für 50 Namen wären unwartbar.",
  "A data field must hold 50 names addressable by an index. What do you use?",
  ("An array", "A single variable", "A constant", "A comment"),
  "An array groups values of the same kind under one name and makes them reachable by index. Fifty individual variables would be unmaintainable."),

S("ap1-swe-r09",
  "Welche Aussage über eine Konstante trifft zu?",
  ("Ihr Wert steht fest und darf zur Laufzeit nicht wechseln",
   "Ihr Wert wird bei jedem Programmstart neu ausgewürfelt",
   "Sie belegt grundsätzlich weniger Speicher als Variablen",
   "Sie ist nur innerhalb von Schleifen gültig und sichtbar"), 0,
  "Konstanten machen feste Werte wie den Mehrwertsteuersatz sprechend und verhindern versehentliches Überschreiben. Mit Speicherbedarf oder Schleifen hat das nichts zu tun.",
  "Which statement about a constant is correct?",
  ("Its value is fixed and must not change at runtime",
   "Its value is randomised at every program start",
   "It fundamentally uses less memory than variables",
   "It is valid and visible only inside loops"),
  "Constants give fixed values such as a VAT rate a readable name and prevent accidental overwriting. This has nothing to do with memory usage or loops."),

S("ap1-swe-r10",
  "Was unterscheidet einen Compiler von einem Interpreter?",
  ("Der Compiler übersetzt vorab komplett, der Interpreter zur Laufzeit",
   "Der Compiler prüft nur die Rechtschreibung der Bezeichner",
   "Der Interpreter erzeugt stets eine ausführbare Programmdatei",
   "Der Interpreter arbeitet grundsätzlich schneller als Compiler"), 0,
  "Der Compiler erzeugt vor der Ausführung Maschinencode, der Interpreter übersetzt Zeile für Zeile beim Laufen. Deshalb starten interpretierte Programme schnell, laufen aber meist langsamer.",
  "What distinguishes a compiler from an interpreter?",
  ("The compiler translates fully in advance, the interpreter at runtime",
   "The compiler only checks the spelling of identifiers",
   "The interpreter always produces an executable program file",
   "The interpreter is fundamentally faster than a compiler"),
  "A compiler produces machine code before execution, an interpreter translates line by line while running. Interpreted programs therefore start quickly but usually run slower."),

S("ap1-swe-r11",
  "Welches Vorgehensmodell arbeitet in kurzen Zyklen mit regelmäßigem Kundenfeedback?",
  ("Scrum", "Das Wasserfallmodell", "Das V-Modell in seiner klassischen Form",
   "Die sequenzielle Phasenplanung mit Meilensteinen"), 0,
  "Scrum liefert in Sprints von zwei bis vier Wochen lauffähige Zwischenstände. Wasserfall und V-Modell legen die Anforderungen dagegen früh fest und liefern erst am Ende.",
  "Which process model works in short cycles with regular customer feedback?",
  ("Scrum", "The waterfall model", "The V-model in its classic form",
   "Sequential phase planning with milestones"),
  "Scrum delivers running increments in sprints of two to four weeks. Waterfall and the V-model fix requirements early and deliver only at the end."),

S("ap1-swe-r12",
  "Der Auftraggeber beschreibt, was er haben will. Wie heißt dieses Dokument?",
  ("Lastenheft", "Pflichtenheft", "Abnahmeprotokoll", "Betriebshandbuch"), 0,
  "Das Lastenheft kommt vom Auftraggeber und nennt das Was. Der Auftragnehmer antwortet mit dem Pflichtenheft und beschreibt darin das Wie.",
  "The client describes what they want. What is this document called?",
  ("Requirements specification", "Functional specification", "Acceptance record", "Operations manual"),
  "The requirements specification comes from the client and states the what. The contractor replies with the functional specification describing the how."),

S("ap1-swe-r13",
  "In einer Klasse sollen Attribute nur über Methoden zugänglich sein. Wie heißt das Prinzip?",
  ("Kapselung", "Vererbung", "Polymorphie", "Instanziierung"), 0,
  "Kapselung verbirgt den inneren Zustand und lässt Zugriff nur über definierte Methoden zu. Dadurch bleiben Objekte in einem gültigen Zustand.",
  "In a class, attributes should be accessible only through methods. What is this principle called?",
  ("Encapsulation", "Inheritance", "Polymorphism", "Instantiation"),
  "Encapsulation hides the internal state and permits access only through defined methods. That keeps objects in a valid state."),

S("ap1-swe-r14",
  "Eine Klasse Sportwagen soll alle Eigenschaften der Klasse Fahrzeug übernehmen. Was nutzt du?",
  ("Vererbung", "Kapselung", "Überladung", "Rekursion"), 0,
  "Die abgeleitete Klasse erbt Attribute und Methoden der Basisklasse und ergänzt eigene. So wird gemeinsamer Code nur einmal geschrieben.",
  "A class SportsCar should take over all properties of the class Vehicle. What do you use?",
  ("Inheritance", "Encapsulation", "Overloading", "Recursion"),
  "The derived class inherits attributes and methods of the base class and adds its own. Shared code is thereby written only once."),

S("ap1-swe-r15",
  "Was ist der Unterschied zwischen einer Klasse und einem Objekt?",
  ("Die Klasse ist der Bauplan, das Objekt die konkrete Ausprägung",
   "Die Klasse ist die Ausprägung, das Objekt der zugehörige Bauplan",
   "Beide bezeichnen dasselbe und werden beliebig verwendet",
   "Die Klasse existiert nur zur Laufzeit, das Objekt im Quelltext"), 0,
  "Aus einer Klasse lassen sich beliebig viele Objekte erzeugen, jedes mit eigenen Attributwerten. Die Klasse selbst beschreibt nur Struktur und Verhalten.",
  "What is the difference between a class and an object?",
  ("The class is the blueprint, the object the concrete instance",
   "The class is the instance, the object the matching blueprint",
   "Both mean the same and are used interchangeably",
   "The class exists only at runtime, the object in source code"),
  "Any number of objects can be created from a class, each with its own attribute values. The class itself only describes structure and behaviour."),

S("ap1-swe-r16",
  "Welche Suchmethode findet einen Wert in einer sortierten Liste am schnellsten?",
  ("Die binäre Suche", "Die lineare Suche", "Die zufällige Stichprobe", "Das vollständige Auslesen"), 0,
  "Die binäre Suche halbiert den Suchbereich in jedem Schritt und braucht deshalb nur logarithmisch viele Vergleiche. Voraussetzung ist allerdings, dass die Liste sortiert vorliegt.",
  "Which search method finds a value in a sorted list fastest?",
  ("Binary search", "Linear search", "Random sampling", "Reading out everything"),
  "Binary search halves the search range at every step and therefore needs only logarithmically many comparisons. It does require the list to be sorted."),

S("ap1-swe-r17",
  "Eine Methode ruft sich selbst mit kleiner werdenden Werten auf. Wie nennt man das?",
  ("Rekursion", "Iteration", "Vererbung", "Kapselung"), 0,
  "Rekursion löst ein Problem, indem sie es auf kleinere Teilprobleme zurückführt. Ohne Abbruchbedingung endet das in einem Überlauf des Aufrufstapels.",
  "A method calls itself with ever smaller values. What is this called?",
  ("Recursion", "Iteration", "Inheritance", "Encapsulation"),
  "Recursion solves a problem by reducing it to smaller subproblems. Without a termination condition it ends in a call stack overflow."),

S("ap1-swe-r18",
  "Welche Datenstruktur arbeitet nach dem Prinzip zuletzt hinein, zuerst heraus?",
  ("Der Stapel", "Die Warteschlange", "Das sortierte Feld", "Die verkettete Ringliste"), 0,
  "Ein Stack legt Elemente oben ab und nimmt sie dort wieder weg. Die Warteschlange arbeitet umgekehrt nach zuerst hinein, zuerst heraus.",
  "Which data structure works on the last in, first out principle?",
  ("The stack", "The queue", "The sorted array", "The circular linked list"),
  "A stack pushes elements on top and pops them from there. A queue works the other way round on first in, first out."),

S("ap1-swe-r19",
  "Ein Testfall prüft nur die Ein- und Ausgaben ohne Kenntnis des Quelltexts. Wie heißt das Verfahren?",
  ("Blackbox-Test", "Whitebox-Test", "Regressionstest", "Abnahmetest durch den Auftraggeber"), 0,
  "Beim Blackbox-Test wird gegen die Spezifikation getestet, ohne in den Code zu schauen. Der Whitebox-Test nutzt dagegen die innere Struktur zur Auswahl der Testfälle.",
  "A test case checks only inputs and outputs without knowledge of the source code. What is this called?",
  ("Black box test", "White box test", "Regression test", "Acceptance test by the client"),
  "A black box test checks against the specification without looking at the code. A white box test uses the internal structure to select test cases."),

S("ap1-swe-r20",
  "Warum werden aussagekräftige Variablennamen empfohlen?",
  ("Sie machen den Code ohne zusätzliche Erklärung lesbar",
   "Sie verkürzen spürbar die Laufzeit des Programms",
   "Sie verringern den Speicherbedarf des Programms",
   "Sie sind für den Compiler zwingend vorgeschrieben"), 0,
  "Code wird weit häufiger gelesen als geschrieben. Ein Name wie anzahlKunden erklärt sich selbst, während x eine Erklärung im Kommentar braucht. Auf Laufzeit und Speicher hat der Name keinen Einfluss.",
  "Why are meaningful variable names recommended?",
  ("They make the code readable without extra explanation",
   "They noticeably shorten the program's runtime",
   "They reduce the memory footprint of the program",
   "They are strictly required by the compiler"),
  "Code is read far more often than it is written. A name like customerCount explains itself, while x needs a comment. The name has no influence on runtime or memory."),

S("ap1-swe-r21",
  "Welcher Operator prüft in vielen Sprachen auf Gleichheit zweier Werte?",
  ("==", "=", "!=", "<="), 0,
  "Ein einfaches Gleichheitszeichen weist zu, ein doppeltes vergleicht. Diese Verwechslung ist eine klassische Fehlerquelle in Bedingungen.",
  "Which operator checks two values for equality in many languages?",
  ("==", "=", "!=", "<="),
  "A single equals sign assigns, a double one compares. Confusing the two is a classic source of errors in conditions."),

S("ap1-swe-r22",
  "Ein Kunde meldet einen Fehler, der nach jeder Auslieferung erneut auftritt. Welcher Test hätte das verhindert?",
  ("Ein Regressionstest nach jeder Änderung",
   "Ein einmaliger Lasttest vor dem Projektstart",
   "Ein Abnahmetest allein durch den Auftraggeber",
   "Ein Blick in die Programmdokumentation"), 0,
  "Regressionstests wiederholen bestehende Testfälle nach jeder Änderung und decken auf, wenn etwas Repariertes wieder kaputtgeht. Genau dafür lohnt sich Automatisierung.",
  "A customer reports a bug that reappears after every release. Which test would have prevented this?",
  ("A regression test after every change",
   "A one-off load test before the project starts",
   "An acceptance test by the client alone",
   "A look into the program documentation"),
  "Regression tests repeat existing test cases after every change and reveal when something already fixed breaks again. This is exactly where automation pays off."),

S("ap1-swe-r23",
  "Was bewirkt ein Commit in einer Versionsverwaltung?",
  ("Er hält einen Änderungsstand mit Beschreibung dauerhaft fest",
   "Er überträgt die Änderungen sofort auf den Produktivserver",
   "Er löscht alle vorherigen Versionen des Projekts",
   "Er sperrt die Dateien für alle anderen Teammitglieder"), 0,
  "Der Commit erzeugt einen benannten Punkt in der Historie, zu dem man zurückkehren kann. Das Veröffentlichen auf einem Server ist ein eigener Schritt, meist push genannt.",
  "What does a commit do in a version control system?",
  ("It records a change set with a description permanently",
   "It transfers the changes to the production server at once",
   "It deletes all previous versions of the project",
   "It locks the files for all other team members"),
  "A commit creates a named point in the history that you can return to. Publishing to a server is a separate step, usually called push."),

S("ap1-swe-r24",
  "Wozu dient ein Branch in der Versionsverwaltung?",
  ("Er erlaubt paralleles Arbeiten ohne den Hauptstand zu stören",
   "Er verkleinert die Datenmenge des gesamten Projekts",
   "Er ersetzt die Notwendigkeit einer Datensicherung",
   "Er beschleunigt das Übersetzen des Quelltexts"), 0,
  "In einem Branch entsteht ein eigener Entwicklungsstrang, der später über einen Merge zurückfließt. So bleibt der Hauptzweig jederzeit lauffähig.",
  "What is a branch used for in version control?",
  ("It allows parallel work without disturbing the main line",
   "It reduces the total data volume of the project",
   "It removes the need for a separate data backup",
   "It speeds up the compilation of the source code"),
  "A branch creates its own development line that is merged back later. The main branch therefore stays runnable at all times."),

S("ap1-swe-r25",
  "Welche Aussage über Pseudocode ist richtig?",
  ("Er beschreibt Algorithmen sprachunabhängig und ist nicht ausführbar",
   "Er wird vor der Nutzung von einem Compiler übersetzt",
   "Er ist eine Programmiersprache mit fester Syntaxregel",
   "Er dient ausschließlich der Dokumentation nach Projektende"), 0,
  "Pseudocode steht zwischen Umgangssprache und Programmcode und dient dem Entwurf. Genau weil er keine feste Syntax hat, lässt er sich in jede Zielsprache übertragen.",
  "Which statement about pseudocode is correct?",
  ("It describes algorithms language-independently and is not executable",
   "It is translated by a compiler before it can be used",
   "It is a programming language with fixed syntax rules",
   "It serves solely for documentation after project completion"),
  "Pseudocode sits between plain language and program code and serves the design phase. Precisely because it has no fixed syntax, it can be transferred to any target language."),

S("ap1-swe-r26",
  "Ein Programm greift auf das elfte Element eines Arrays mit zehn Feldern zu. Was passiert typischerweise?",
  ("Es entsteht ein Laufzeitfehler beim Zugriff",
   "Der Compiler verweigert grundsätzlich die Übersetzung",
   "Das Array vergrößert sich automatisch um ein Feld",
   "Das Programm liefert stillschweigend immer eine Null"), 0,
  "Der Zugriff außerhalb der Grenzen ist syntaktisch korrekt und fällt daher erst zur Laufzeit auf. Viele Sprachen werfen dann eine Ausnahme, andere lesen unkontrolliert fremden Speicher.",
  "A program accesses the eleventh element of an array with ten slots. What typically happens?",
  ("A runtime error occurs on the access",
   "The compiler fundamentally refuses to translate it",
   "The array grows automatically by one slot",
   "The program silently always returns a zero"),
  "Access outside the bounds is syntactically correct and therefore surfaces only at runtime. Many languages then throw an exception, others read foreign memory uncontrolled."),

S("ap1-swe-r27",
  "Was beschreibt ein Use-Case-Diagramm in UML?",
  ("Wer welche fachlichen Funktionen des Systems nutzt",
   "Wie die Klassen des Systems voneinander erben",
   "In welcher Reihenfolge Nachrichten ausgetauscht werden",
   "Wie die Daten physisch auf Servern verteilt sind"), 0,
  "Das Anwendungsfalldiagramm zeigt Akteure und ihre Anwendungsfälle aus fachlicher Sicht. Vererbung zeigt das Klassendiagramm, Nachrichtenfolgen das Sequenzdiagramm.",
  "What does a use case diagram in UML describe?",
  ("Who uses which business functions of the system",
   "How the system's classes inherit from each other",
   "In which order messages are exchanged",
   "How the data is physically distributed on servers"),
  "The use case diagram shows actors and their use cases from a business perspective. Inheritance is shown by the class diagram, message sequences by the sequence diagram."),

S("ap1-swe-r28",
  "Warum wird Quelltext kommentiert?",
  ("Um die Absicht hinter einer Lösung nachvollziehbar zu machen",
   "Um die Ausführungsgeschwindigkeit des Programms zu erhöhen",
   "Um dem Compiler zusätzliche Optimierungen zu erlauben",
   "Um die Anzahl der benötigten Variablen zu verringern"), 0,
  "Was der Code tut, steht im Code; warum er es so tut, gehört in den Kommentar. Auf die Ausführung haben Kommentare keinerlei Einfluss, da der Compiler sie entfernt.",
  "Why is source code commented?",
  ("To make the intention behind a solution traceable",
   "To increase the execution speed of the program",
   "To allow the compiler additional optimisations",
   "To reduce the number of variables required"),
  "What the code does is in the code; why it does it that way belongs in a comment. Comments have no effect on execution since the compiler removes them."),

S("ap1-swe-r29",
  "Welche Kontrollstruktur setzt du ein, wenn abhängig von einer Bedingung unterschiedlicher Code laufen soll?",
  ("Eine Verzweigung", "Eine Sequenz", "Eine Zählschleife", "Eine Konstantendeklaration"), 0,
  "Die Verzweigung wählt zwischen Alternativen. Sequenz bedeutet Abarbeitung nacheinander, die Schleife wiederholt, und eine Deklaration steuert gar nichts.",
  "Which control structure do you use when different code should run depending on a condition?",
  ("A selection", "A sequence", "A counting loop", "A constant declaration"),
  "Selection chooses between alternatives. Sequence means running one after another, a loop repeats, and a declaration controls nothing at all."),

S("ap1-swe-r30",
  "Was liefert eine Methode mit dem Rückgabetyp void?",
  ("Keinen Wert, sie führt nur eine Aktion aus",
   "Immer den Wert null als Ergebnis zurück",
   "Eine leere Zeichenkette als Standardergebnis",
   "Den zuletzt berechneten Wert der Methode"), 0,
  "void kennzeichnet Methoden ohne Rückgabewert, etwa eine Ausgabe auf dem Bildschirm. Wer ein Ergebnis braucht, deklariert einen passenden Rückgabetyp.",
  "What does a method with return type void deliver?",
  ("No value, it only performs an action",
   "Always the value null as its result",
   "An empty string as a default result",
   "The most recently computed value"),
  "void marks methods without a return value, such as printing to the screen. Anyone needing a result declares a matching return type."),

S("ap1-swe-r31",
  "Eine Anwendung soll nach einer Änderung schnell auf alte Fehler geprüft werden. Was hilft dauerhaft?",
  ("Automatisierte Testfälle im Projekt hinterlegen",
   "Vor jeder Auslieferung das Handbuch überarbeiten",
   "Die Anzahl der Kommentare im Quelltext erhöhen",
   "Nach jedem Release die Versionsnummer hochzählen"), 0,
  "Automatisierte Tests laufen bei jeder Änderung mit und melden Rückschritte sofort. Handbücher, Kommentare und Versionsnummern dokumentieren, prüfen aber nichts.",
  "An application should be quickly checked for old bugs after a change. What helps permanently?",
  ("Store automated test cases in the project",
   "Revise the manual before every release",
   "Increase the number of comments in the code",
   "Increment the version number after each release"),
  "Automated tests run on every change and report regressions immediately. Manuals, comments and version numbers document but verify nothing."),

S("ap1-swe-r32",
  "Was bedeutet der Begriff Debugging?",
  ("Das gezielte Suchen und Beheben von Programmfehlern",
   "Das Übersetzen des Quelltexts in Maschinencode",
   "Das Aufteilen eines Programms in mehrere Module",
   "Das Verkleinern des Programms für die Auslieferung"), 0,
  "Beim Debuggen hält man das Programm an, prüft Variablenwerte und geht Schritt für Schritt durch den Ablauf. Übersetzen, Modularisieren und Verkleinern sind eigene Vorgänge.",
  "What does the term debugging mean?",
  ("The targeted finding and fixing of program errors",
   "The translation of source code into machine code",
   "The splitting of a program into several modules",
   "The shrinking of a program for distribution"),
  "When debugging you pause the program, inspect variable values and step through the flow. Compiling, modularising and shrinking are separate activities."),

# -------------------------------------------------------------- multiple (32)
M("ap1-swe-r33",
  "Welche Kontrollstrukturen kennt die strukturierte Programmierung?",
  ("Sequenz als Abfolge von Anweisungen", "Auswahl als Verzweigung",
   "Wiederholung als Schleife", "Verschachtelung dieser Grundformen",
   "Unbedingter Sprung mit GOTO", "Das Übersetzen des Quelltexts"),
  (0, 1, 2, 3),
  "Sequenz, Auswahl und Wiederholung genügen für jeden Algorithmus und lassen sich beliebig schachteln. Der unbedingte Sprung wird bewusst vermieden, und Übersetzen ist keine Kontrollstruktur.",
  "Which control structures does structured programming know?",
  ("Sequence as a series of statements", "Selection as a branch",
   "Iteration as a loop", "Nesting of these basic forms",
   "Unconditional jump using GOTO", "The compilation of the source code"),
  "Sequence, selection and iteration suffice for any algorithm and can be nested arbitrarily. The unconditional jump is deliberately avoided, and compilation is not a control structure."),

M("ap1-swe-r34",
  "Welche Eigenschaften sollte ein guter Testfall haben?",
  ("Er hat ein vorab festgelegtes Sollergebnis",
   "Er ist wiederholbar und liefert gleiche Ergebnisse",
   "Er prüft eine klar abgegrenzte Anforderung",
   "Er ist unabhängig von anderen Testfällen",
   "Er wird erst nach dem Auftreten eines Fehlers geschrieben",
   "Er prüft möglichst viele Anforderungen gleichzeitig"),
  (0, 1, 2, 3),
  "Nur mit bekanntem Sollwert lässt sich überhaupt bewerten, ob ein Test bestanden ist. Unabhängigkeit und klare Abgrenzung machen die Fehlersuche schnell, Sammeltests dagegen mehrdeutig.",
  "Which properties should a good test case have?",
  ("It has a predefined expected result",
   "It is repeatable and yields the same results",
   "It checks one clearly delimited requirement",
   "It is independent of other test cases",
   "It is written only after a bug has appeared",
   "It checks as many requirements as possible at once"),
  "Only with a known expected value can you judge whether a test passed at all. Independence and clear scope make debugging fast, while combined tests are ambiguous."),

M("ap1-swe-r35",
  "Welche Angaben gehören in ein Pflichtenheft?",
  ("Beschreibung der geplanten Umsetzung",
   "Abgrenzung des Lieferumfangs",
   "Anforderungen an die Schnittstellen",
   "Kriterien für die Abnahme",
   "Der private Terminkalender des Entwicklers",
   "Die Farbwahl des Firmenlogos des Kunden"),
  (0, 1, 2, 3),
  "Das Pflichtenheft beantwortet, wie und womit die Anforderungen des Lastenhefts umgesetzt werden, inklusive Abgrenzung und Abnahmekriterien. Persönliche Termine und Logofarben gehören nicht hinein.",
  "Which items belong in a functional specification?",
  ("Description of the planned implementation",
   "Delimitation of the scope of delivery",
   "Requirements for the interfaces",
   "Criteria for acceptance",
   "The developer's private calendar",
   "The colour choice of the client's logo"),
  "The functional specification answers how and with what the requirements will be implemented, including scope and acceptance criteria. Private appointments and logo colours do not belong there."),

M("ap1-swe-r36",
  "Welche Aussagen über objektorientierte Programmierung sind zutreffend?",
  ("Objekte bündeln Daten und Verhalten",
   "Klassen dienen als Bauplan für Objekte",
   "Vererbung ermöglicht Wiederverwendung von Code",
   "Kapselung schützt den inneren Zustand",
   "Objekte lassen sich nur einmal je Programm erzeugen",
   "Klassen ersetzen die Notwendigkeit von Variablen"),
  (0, 1, 2, 3),
  "Objekte vereinen Attribute und Methoden, Klassen beschreiben sie, Vererbung spart Doppelungen und Kapselung sichert die Konsistenz. Beliebig viele Objekte je Klasse sind gerade der Sinn der Sache.",
  "Which statements about object-oriented programming are correct?",
  ("Objects bundle data and behaviour",
   "Classes serve as a blueprint for objects",
   "Inheritance enables reuse of code",
   "Encapsulation protects the internal state",
   "Objects can be created only once per program",
   "Classes remove the need for variables"),
  "Objects unite attributes and methods, classes describe them, inheritance avoids duplication and encapsulation secures consistency. Creating any number of objects per class is exactly the point."),

M("ap1-swe-r37",
  "Welche Schritte gehören zum klassischen Ablauf der Softwareentwicklung?",
  ("Anforderungen erheben und abstimmen",
   "Lösung entwerfen und modellieren",
   "Umsetzung in Quelltext",
   "Testen gegen die Anforderungen",
   "Die Preisliste des Vertriebs erstellen",
   "Die Büromöbel des Teams auswählen"),
  (0, 1, 2, 3),
  "Analyse, Entwurf, Implementierung und Test bilden den Kern jedes Vorgehensmodells, gefolgt von Einführung und Wartung. Vertriebs- und Bürothemen liegen außerhalb.",
  "Which steps belong to the classic software development sequence?",
  ("Elicit and agree the requirements",
   "Design and model the solution",
   "Implement in source code",
   "Test against the requirements",
   "Create the sales price list",
   "Choose the team's office furniture"),
  "Analysis, design, implementation and testing form the core of every process model, followed by rollout and maintenance. Sales and office topics lie outside."),

M("ap1-swe-r38",
  "Welche Aussagen zu Git treffen zu?",
  ("Ein Commit hält einen Änderungsstand fest",
   "Ein Branch erlaubt paralleles Arbeiten",
   "Ein Merge führt Entwicklungsstände zusammen",
   "Die Historie bleibt vollständig nachvollziehbar",
   "Git ersetzt vollständig eine Datensicherung",
   "Jede Datei kann nur von einer Person bearbeitet werden"),
  (0, 1, 2, 3),
  "Commit, Branch, Merge und lückenlose Historie sind die Kernbegriffe. Ein Repository allein ist aber keine Sicherung, und paralleles Bearbeiten derselben Datei ist ausdrücklich vorgesehen.",
  "Which statements about Git are correct?",
  ("A commit records a set of changes",
   "A branch allows parallel work",
   "A merge brings development lines together",
   "The history stays fully traceable",
   "Git completely replaces a data backup",
   "Each file can be edited by only one person"),
  "Commit, branch, merge and a complete history are the core concepts. A repository alone is not a backup, though, and parallel editing of the same file is explicitly supported."),

M("ap1-swe-r39",
  "Welche Datentypen sind in den meisten Sprachen als Grunddatentypen vorhanden?",
  ("Ganzzahl", "Gleitkommazahl", "Wahrheitswert", "Einzelzeichen",
   "Datenbanktabelle", "Netzwerkverbindung"),
  (0, 1, 2, 3),
  "Ganzzahl, Gleitkommazahl, Wahrheitswert und Zeichen sind die üblichen primitiven Typen, aus denen sich komplexere Strukturen zusammensetzen. Tabellen und Verbindungen sind Bibliotheksobjekte.",
  "Which data types exist as primitive types in most languages?",
  ("Integer", "Floating point number", "Boolean", "Single character",
   "Database table", "Network connection"),
  "Integer, float, boolean and character are the usual primitive types from which more complex structures are built. Tables and connections are library objects."),

M("ap1-swe-r40",
  "Welche Vorteile bringt die Aufteilung eines Programms in Module?",
  ("Einzelne Teile lassen sich getrennt testen",
   "Fehler bleiben leichter eingrenzbar",
   "Teile lassen sich in anderen Projekten wiederverwenden",
   "Mehrere Entwickler können parallel arbeiten",
   "Die Zahl der Programmzeilen sinkt zwangsläufig",
   "Das Programm läuft dadurch immer schneller"),
  (0, 1, 2, 3),
  "Modularisierung wirkt vor allem organisatorisch: Testbarkeit, Fehlereingrenzung, Wiederverwendung und Arbeitsteilung. Auf Zeilenzahl und Laufzeit hat sie keinen automatischen Einfluss.",
  "Which advantages come from splitting a program into modules?",
  ("Individual parts can be tested separately",
   "Faults remain easier to isolate",
   "Parts can be reused in other projects",
   "Several developers can work in parallel",
   "The number of code lines necessarily drops",
   "The program always runs faster as a result"),
  "Modularisation works mainly on the organisational level: testability, fault isolation, reuse and division of labour. It has no automatic effect on line count or runtime."),

M("ap1-swe-r41",
  "Welche Aussagen über Schleifen sind korrekt?",
  ("Die while-Schleife prüft vor dem Durchlauf",
   "Die do-while-Schleife prüft nach dem Durchlauf",
   "Die for-Schleife eignet sich für bekannte Wiederholungszahlen",
   "Eine fehlende Abbruchbedingung führt zur Endlosschleife",
   "Jede Schleife läuft mindestens einmal durch",
   "Schleifen lassen sich nicht ineinander schachteln"),
  (0, 1, 2, 3),
  "Der Prüfzeitpunkt unterscheidet kopf- und fußgesteuerte Schleifen, die Zählschleife passt bei bekannter Anzahl. Nur die fußgesteuerte läuft garantiert einmal, und Schachtelung ist gängige Praxis.",
  "Which statements about loops are correct?",
  ("The while loop checks before each pass",
   "The do-while loop checks after each pass",
   "The for loop suits known repetition counts",
   "A missing exit condition causes an endless loop",
   "Every loop runs through at least once",
   "Loops cannot be nested inside each other"),
  "The check position distinguishes head- and foot-controlled loops, and the counting loop fits a known count. Only the foot-controlled one is guaranteed to run once, and nesting is common practice."),

M("ap1-swe-r42",
  "Welche Merkmale kennzeichnen agile Vorgehensweisen?",
  ("Kurze Entwicklungszyklen mit lauffähigem Ergebnis",
   "Regelmäßige Rückmeldung durch den Auftraggeber",
   "Anpassbarkeit der Anforderungen im Projektverlauf",
   "Selbstorganisierte Teams",
   "Vollständige Festlegung aller Details zu Beginn",
   "Verzicht auf jegliche Dokumentation"),
  (0, 1, 2, 3),
  "Agile Modelle setzen auf kurze Zyklen, Feedback, Wandelbarkeit und Eigenverantwortung. Vollständige Vorabplanung kennzeichnet den Wasserfall, und Dokumentation entfällt keineswegs, sie wird nur schlanker.",
  "Which characteristics define agile approaches?",
  ("Short development cycles with a working result",
   "Regular feedback from the client",
   "Adaptability of requirements during the project",
   "Self-organising teams",
   "Complete specification of all details at the start",
   "Doing away with documentation entirely"),
  "Agile models rely on short cycles, feedback, adaptability and self-responsibility. Complete upfront planning characterises waterfall, and documentation is by no means dropped, only made leaner."),

M("ap1-swe-r43",
  "Welche Aussagen über Arrays sind zutreffend?",
  ("Sie fassen Werte gleichen Typs zusammen",
   "Der Zugriff erfolgt über einen Index",
   "Der Index beginnt in vielen Sprachen bei null",
   "Zugriffe außerhalb der Grenzen führen zu Fehlern",
   "Ihre Größe passt sich immer automatisch an",
   "Sie können Werte beliebig gemischter Typen speichern"),
  (0, 1, 2, 3),
  "Ein klassisches Array ist typgleich, indiziert und in der Größe fest - deshalb sind Grenzverletzungen ein Laufzeitproblem. Dynamische, gemischte Sammlungen bieten erst Listen und ähnliche Strukturen.",
  "Which statements about arrays are correct?",
  ("They group values of the same type",
   "Access happens through an index",
   "The index starts at zero in many languages",
   "Access outside the bounds causes errors",
   "Their size always adjusts automatically",
   "They can store values of arbitrarily mixed types"),
  "A classic array is type-uniform, indexed and fixed in size - which is why bound violations are a runtime problem. Dynamic, mixed collections are provided by lists and similar structures."),

M("ap1-swe-r44",
  "Welche Aufgaben erfüllt eine Entwicklungsumgebung?",
  ("Sie bietet einen Editor mit Syntaxhervorhebung",
   "Sie startet Übersetzung und Ausführung",
   "Sie stellt einen Debugger bereit",
   "Sie bindet die Versionsverwaltung ein",
   "Sie schreibt die Anforderungen des Kunden",
   "Sie ersetzt die fachliche Abnahme durch den Kunden"),
  (0, 1, 2, 3),
  "Eine IDE bündelt Editor, Übersetzer, Debugger und Versionsverwaltung an einer Oberfläche. Anforderungen und Abnahme bleiben Aufgaben der Menschen im Projekt.",
  "Which tasks does an integrated development environment perform?",
  ("It provides an editor with syntax highlighting",
   "It starts compilation and execution",
   "It supplies a debugger",
   "It integrates version control",
   "It writes the customer's requirements",
   "It replaces formal acceptance by the customer"),
  "An IDE bundles editor, compiler, debugger and version control in one interface. Requirements and acceptance remain tasks for the people in the project."),

M("ap1-swe-r45",
  "Welche Aussagen zu Sortierverfahren sind richtig?",
  ("Sortieren ordnet Daten nach einem Kriterium",
   "Verfahren unterscheiden sich im Aufwand",
   "Sortierte Daten ermöglichen die binäre Suche",
   "Der Aufwand hängt von der Anzahl der Elemente ab",
   "Jedes Sortierverfahren braucht gleich viele Schritte",
   "Sortieren ist nur bei Zahlen möglich"),
  (0, 1, 2, 3),
  "Der entscheidende Unterschied zwischen Verfahren liegt im Aufwand bei wachsender Datenmenge, und erst Sortierung macht die schnelle binäre Suche möglich. Sortieren lässt sich alles mit definierter Ordnung.",
  "Which statements about sorting methods are correct?",
  ("Sorting orders data by a criterion",
   "Methods differ in their effort",
   "Sorted data enables binary search",
   "The effort depends on the number of elements",
   "Every sorting method needs the same number of steps",
   "Sorting is only possible with numbers"),
  "The decisive difference between methods is effort as data volume grows, and only sorting makes fast binary search possible. Anything with a defined ordering can be sorted."),

M("ap1-swe-r46",
  "Welche Diagrammarten gehören zu UML?",
  ("Klassendiagramm", "Anwendungsfalldiagramm", "Sequenzdiagramm",
   "Aktivitätsdiagramm", "Netzplan nach Vorgangsknoten", "Balkenplan nach Gantt"),
  (0, 1, 2, 3),
  "UML beschreibt Struktur und Verhalten von Software in Klassen-, Anwendungsfall-, Sequenz- und Aktivitätsdiagrammen. Netzplan und Balkenplan sind Werkzeuge des Projektmanagements.",
  "Which diagram types belong to UML?",
  ("Class diagram", "Use case diagram", "Sequence diagram",
   "Activity diagram", "Activity-on-node network plan", "Gantt bar chart"),
  "UML describes the structure and behaviour of software in class, use case, sequence and activity diagrams. Network plans and bar charts are project management tools."),

M("ap1-swe-r47",
  "Welche Fehlerarten unterscheidet man in der Programmierung?",
  ("Syntaxfehler beim Übersetzen",
   "Laufzeitfehler während der Ausführung",
   "Logische Fehler mit falschem Ergebnis",
   "Semantische Fehler in der Bedeutung",
   "Farbfehler in der Entwicklungsumgebung",
   "Tastaturfehler der Hardware"),
  (0, 1, 2, 3),
  "Die drei klassischen Kategorien sind Syntax, Laufzeit und Logik, wobei semantische Fehler eng mit den logischen zusammenhängen. Werkzeug- und Hardwareprobleme sind keine Programmfehlerarten.",
  "Which kinds of errors are distinguished in programming?",
  ("Syntax errors during compilation",
   "Runtime errors during execution",
   "Logical errors producing a wrong result",
   "Semantic errors in meaning",
   "Colour errors in the development environment",
   "Keyboard faults of the hardware"),
  "The three classic categories are syntax, runtime and logic, with semantic errors closely related to logical ones. Tooling and hardware problems are not categories of program error."),

M("ap1-swe-r48",
  "Welche Aussagen über Funktionen und Methoden sind korrekt?",
  ("Sie bündeln wiederverwendbaren Code",
   "Sie können Parameter entgegennehmen",
   "Sie können einen Wert zurückgeben",
   "Sie machen ein Programm besser lesbar",
   "Sie dürfen nur einmal je Programm aufgerufen werden",
   "Sie verlangen zwingend mindestens drei Parameter"),
  (0, 1, 2, 3),
  "Der Sinn von Funktionen ist die Wiederverwendung: Parameter hinein, Ergebnis heraus, und der Aufrufer bleibt lesbar. Mehrfachaufrufe sind gerade der Zweck, und Parameter sind optional.",
  "Which statements about functions and methods are correct?",
  ("They bundle reusable code",
   "They can accept parameters",
   "They can return a value",
   "They make a program more readable",
   "They may be called only once per program",
   "They strictly require at least three parameters"),
  "The point of functions is reuse: parameters in, result out, and the caller stays readable. Multiple calls are precisely the purpose, and parameters are optional."),

M("ap1-swe-r49",
  "Welche Punkte gehören zu einer sinnvollen Programmdokumentation?",
  ("Beschreibung der Schnittstellen",
   "Erläuterung nicht offensichtlicher Entscheidungen",
   "Hinweise zur Installation und Konfiguration",
   "Angaben zu bekannten Einschränkungen",
   "Eine Abschrift des gesamten Quelltexts",
   "Die Urlaubsplanung des Entwicklungsteams"),
  (0, 1, 2, 3),
  "Dokumentation soll erklären, was der Code nicht selbst sagt: Schnittstellen, Begründungen, Betrieb und Grenzen. Den Quelltext abzuschreiben verdoppelt nur den Pflegeaufwand.",
  "Which points belong in useful program documentation?",
  ("Description of the interfaces",
   "Explanation of non-obvious decisions",
   "Notes on installation and configuration",
   "Statements about known limitations",
   "A transcript of the entire source code",
   "The holiday planning of the development team"),
  "Documentation should explain what the code cannot say itself: interfaces, rationale, operation and limits. Transcribing the source only doubles the maintenance effort."),

M("ap1-swe-r50",
  "Welche Aussagen über Variablen sind richtig?",
  ("Sie besitzen einen Namen und einen Datentyp",
   "Ihr Wert kann sich zur Laufzeit ändern",
   "Ihr Gültigkeitsbereich ist begrenzt",
   "Sie belegen Speicherplatz im Arbeitsspeicher",
   "Ihr Datentyp ändert sich bei jedem Zugriff",
   "Sie behalten ihren Wert auch nach Programmende"),
  (0, 1, 2, 3),
  "Name, Typ, Gültigkeitsbereich und Speicherbedarf sind die Kernmerkmale. Der Typ liegt in typisierten Sprachen fest, und ohne Speichern in einer Datei ist der Wert nach Programmende weg.",
  "Which statements about variables are correct?",
  ("They have a name and a data type",
   "Their value can change at runtime",
   "Their scope of validity is limited",
   "They occupy space in main memory",
   "Their data type changes on every access",
   "They keep their value after the program ends"),
  "Name, type, scope and memory usage are the core characteristics. The type is fixed in typed languages, and without saving to a file the value is gone once the program ends."),

M("ap1-swe-r51",
  "Welche Aussagen zum Vergleich von Wasserfall- und agilem Modell treffen zu?",
  ("Der Wasserfall legt Phasen fest nacheinander an",
   "Agile Modelle liefern früh nutzbare Zwischenstände",
   "Der Wasserfall erschwert späte Änderungen",
   "Agile Modelle brauchen enge Kundenbeteiligung",
   "Agile Modelle verzichten auf jede Planung",
   "Der Wasserfall ist grundsätzlich immer schneller"),
  (0, 1, 2, 3),
  "Wasserfall plant vollständig vorab und wird bei späten Änderungen teuer; agile Modelle tauschen das gegen kurze Zyklen und Kundennähe. Planung gibt es dort weiterhin, nur kleinteiliger.",
  "Which statements comparing the waterfall and agile models are correct?",
  ("Waterfall arranges phases strictly one after another",
   "Agile models deliver usable increments early",
   "Waterfall makes late changes difficult",
   "Agile models need close customer involvement",
   "Agile models do away with planning entirely",
   "Waterfall is fundamentally always faster"),
  "Waterfall plans fully upfront and becomes expensive with late changes; agile models trade that for short cycles and customer proximity. Planning still exists there, just in smaller pieces."),

M("ap1-swe-r52",
  "Welche Aussagen zu Datenstrukturen sind korrekt?",
  ("Ein Stapel arbeitet nach zuletzt hinein, zuerst heraus",
   "Eine Warteschlange arbeitet nach zuerst hinein, zuerst heraus",
   "Eine Liste erlaubt das Einfügen an beliebiger Stelle",
   "Ein Baum ordnet Elemente hierarchisch",
   "Ein Stapel erlaubt wahlfreien Zugriff auf jedes Element",
   "Eine Warteschlange sortiert ihre Elemente automatisch"),
  (0, 1, 2, 3),
  "Stapel und Warteschlange unterscheiden sich genau in der Entnahmereihenfolge, Listen und Bäume in Flexibilität und Ordnung. Wahlfreier Zugriff und automatisches Sortieren gehören nicht dazu.",
  "Which statements about data structures are correct?",
  ("A stack works last in, first out",
   "A queue works first in, first out",
   "A list allows insertion at any position",
   "A tree orders elements hierarchically",
   "A stack allows random access to every element",
   "A queue sorts its elements automatically"),
  "Stack and queue differ precisely in removal order, lists and trees in flexibility and ordering. Random access and automatic sorting are not part of it."),

M("ap1-swe-r53",
  "Welche Aussagen über Boolesche Operatoren sind zutreffend?",
  ("UND liefert wahr, wenn beide Bedingungen wahr sind",
   "ODER liefert wahr, wenn mindestens eine wahr ist",
   "NICHT kehrt einen Wahrheitswert um",
   "Sie lassen sich in Bedingungen kombinieren",
   "UND liefert wahr, sobald eine Bedingung wahr ist",
   "NICHT verknüpft immer genau zwei Bedingungen"),
  (0, 1, 2, 3),
  "UND fordert alles, ODER genügt eines, NICHT dreht um - kombiniert ergeben sie beliebig komplexe Bedingungen. Die letzten beiden Aussagen vertauschen genau diese Definitionen.",
  "Which statements about boolean operators are correct?",
  ("AND yields true when both conditions are true",
   "OR yields true when at least one is true",
   "NOT inverts a truth value",
   "They can be combined in conditions",
   "AND yields true as soon as one condition is true",
   "NOT always joins exactly two conditions"),
  "AND demands everything, OR settles for one, NOT inverts - combined they build arbitrarily complex conditions. The last two statements swap exactly these definitions."),

M("ap1-swe-r54",
  "Welche Gründe sprechen für den Einsatz einer Bibliothek statt einer Eigenentwicklung?",
  ("Der Aufwand für die Umsetzung sinkt",
   "Die Lösung ist bereits vielfach erprobt",
   "Fehler werden zentral durch den Hersteller behoben",
   "Es entsteht Zeit für die eigentliche Fachlogik",
   "Die eigene Anwendung wird dadurch immer kleiner",
   "Lizenzfragen entfallen bei Bibliotheken vollständig"),
  (0, 1, 2, 3),
  "Erprobte Bibliotheken sparen Aufwand und Fehler und lassen Zeit für das, was die Anwendung ausmacht. Die Programmgröße wächst durch Abhängigkeiten eher, und Lizenzen wollen genau geprüft sein.",
  "Which reasons argue for using a library instead of writing your own?",
  ("The implementation effort drops",
   "The solution is already widely proven",
   "Bugs are fixed centrally by the vendor",
   "Time is freed up for the actual business logic",
   "The application itself always becomes smaller",
   "Licensing questions disappear entirely with libraries"),
  "Proven libraries save effort and bugs and free up time for what makes the application. Program size tends to grow through dependencies, and licences need careful checking."),

M("ap1-swe-r55",
  "Welche Aussagen zur binären Suche sind richtig?",
  ("Sie setzt eine sortierte Datenmenge voraus",
   "Sie halbiert den Suchbereich in jedem Schritt",
   "Sie ist bei großen Mengen deutlich schneller als lineares Suchen",
   "Sie vergleicht zuerst mit dem mittleren Element",
   "Sie funktioniert auch auf unsortierten Daten",
   "Sie prüft grundsätzlich jedes Element einmal"),
  (0, 1, 2, 3),
  "Sortierung, Halbierung und der Start in der Mitte sind das Prinzip, daraus folgt der große Vorsprung bei vielen Elementen. Jedes Element zu prüfen wäre gerade die lineare Suche.",
  "Which statements about binary search are correct?",
  ("It requires a sorted data set",
   "It halves the search range at every step",
   "It is much faster than linear search on large sets",
   "It first compares against the middle element",
   "It also works on unsorted data",
   "It fundamentally checks every element once"),
  "Sorting, halving and starting in the middle are the principle, from which the large advantage on many elements follows. Checking every element would be linear search."),

M("ap1-swe-r56",
  "Welche Angaben beschreiben eine Methode in einem Klassendiagramm?",
  ("Der Name der Methode", "Die Parameterliste", "Der Rückgabetyp",
   "Die Sichtbarkeit", "Die Anzahl der Aufrufe zur Laufzeit", "Der Speicherort der Quelldatei"),
  (0, 1, 2, 3),
  "Signatur und Sichtbarkeit beschreiben eine Methode statisch und vollständig. Laufzeitverhalten und Dateiablage gehören nicht in ein Strukturdiagramm.",
  "Which details describe a method in a class diagram?",
  ("The name of the method", "The parameter list", "The return type",
   "The visibility", "The number of runtime calls", "The location of the source file"),
  "Signature and visibility describe a method statically and completely. Runtime behaviour and file location do not belong in a structural diagram."),

M("ap1-swe-r57",
  "Welche Maßnahmen erhöhen die Wartbarkeit von Quelltext?",
  ("Sprechende Namen für Variablen und Methoden",
   "Kurze, klar abgegrenzte Funktionen",
   "Einheitliche Formatierung im gesamten Projekt",
   "Vermeidung von doppeltem Code",
   "Möglichst viele Aufgaben in einer Funktion bündeln",
   "Verzicht auf jede Art von Struktur zugunsten des Tempos"),
  (0, 1, 2, 3),
  "Lesbarkeit entsteht durch Benennung, Größe, Einheitlichkeit und fehlende Wiederholung. Alleskönner-Funktionen und Strukturlosigkeit erzeugen genau das Gegenteil.",
  "Which measures increase the maintainability of source code?",
  ("Meaningful names for variables and methods",
   "Short, clearly delimited functions",
   "Consistent formatting across the project",
   "Avoidance of duplicated code",
   "Bundling as many tasks as possible into one function",
   "Dropping all structure in favour of speed"),
  "Readability comes from naming, size, consistency and absence of repetition. Do-everything functions and structurelessness produce exactly the opposite."),

M("ap1-swe-r58",
  "Welche Aussagen über Parameterübergabe sind zutreffend?",
  ("Bei Wertübergabe erhält die Methode eine Kopie",
   "Bei Referenzübergabe wirkt die Änderung nach außen",
   "Die Reihenfolge der Parameter ist bedeutsam",
   "Parameter können Standardwerte besitzen",
   "Parameter werden immer als Text übergeben",
   "Eine Methode darf höchstens einen Parameter haben"),
  (0, 1, 2, 3),
  "Wert oder Referenz entscheidet, ob Änderungen im Aufrufer sichtbar werden - eine häufige Fehlerquelle. Reihenfolge zählt, Standardwerte sind verbreitet, und die Anzahl ist nicht begrenzt.",
  "Which statements about parameter passing are correct?",
  ("With pass by value the method receives a copy",
   "With pass by reference the change is visible outside",
   "The order of the parameters matters",
   "Parameters can have default values",
   "Parameters are always passed as text",
   "A method may have at most one parameter"),
  "Value or reference decides whether changes become visible in the caller - a frequent source of bugs. Order matters, default values are common, and the count is not limited."),

M("ap1-swe-r59",
  "Welche Aussagen über Zahlensysteme sind richtig?",
  ("Das Dualsystem nutzt zwei Ziffern",
   "Das Hexadezimalsystem nutzt sechzehn Ziffern",
   "Vier Bit entsprechen einer Hexadezimalziffer",
   "Rechner arbeiten intern dual",
   "Das Hexadezimalsystem nutzt nur Buchstaben",
   "Das Dualsystem kennt die Ziffer zwei"),
  (0, 1, 2, 3),
  "Dual mit 0 und 1, hexadezimal mit 0 bis 9 und A bis F, und vier Bit passen genau in eine Hexziffer - deshalb die kompakte Schreibweise. Die Ziffer zwei gibt es im Dualsystem nicht.",
  "Which statements about number systems are correct?",
  ("The binary system uses two digits",
   "The hexadecimal system uses sixteen digits",
   "Four bits correspond to one hexadecimal digit",
   "Computers work internally in binary",
   "The hexadecimal system uses only letters",
   "The binary system knows the digit two"),
  "Binary with 0 and 1, hexadecimal with 0 to 9 and A to F, and four bits fit exactly into one hex digit - hence the compact notation. The digit two does not exist in binary."),

M("ap1-swe-r60",
  "Welche Aufgaben hat ein Debugger?",
  ("Das Programm an definierten Stellen anhalten",
   "Variablenwerte zur Laufzeit anzeigen",
   "Den Ablauf schrittweise nachvollziehen",
   "Den Aufrufstapel sichtbar machen",
   "Fehler eigenständig im Quelltext beheben",
   "Die Anforderungen des Kunden erheben"),
  (0, 1, 2, 3),
  "Haltepunkte, Variableneinblick, Einzelschritt und Aufrufstapel machen unsichtbares Verhalten sichtbar. Die Korrektur schreibt weiterhin der Mensch, und Anforderungen erhebt niemand mit einem Debugger.",
  "Which tasks does a debugger have?",
  ("Halt the program at defined points",
   "Show variable values at runtime",
   "Step through the flow gradually",
   "Make the call stack visible",
   "Fix bugs in the source code by itself",
   "Elicit the customer's requirements"),
  "Breakpoints, variable inspection, single stepping and the call stack make invisible behaviour visible. The fix is still written by a human, and nobody elicits requirements with a debugger."),

M("ap1-swe-r61",
  "Welche Aussagen zum Programmablaufplan sind korrekt?",
  ("Er stellt den Ablauf grafisch mit Symbolen dar",
   "Verzweigungen werden als Raute gezeichnet",
   "Start und Ende haben eigene Symbole",
   "Er ist unabhängig von der Programmiersprache",
   "Er ersetzt vollständig den späteren Quelltext",
   "Er darf nur von einer Person gelesen werden"),
  (0, 1, 2, 3),
  "Der PAP verbindet genormte Symbole durch Pfeile und beschreibt den Ablauf sprachneutral - ein Entwurfswerkzeug, kein lauffähiges Programm.",
  "Which statements about the program flowchart are correct?",
  ("It shows the flow graphically with symbols",
   "Branches are drawn as a diamond",
   "Start and end have their own symbols",
   "It is independent of the programming language",
   "It completely replaces the later source code",
   "It may only be read by a single person"),
  "The flowchart links standardised symbols with arrows and describes the flow language-neutrally - a design tool, not a runnable program."),

M("ap1-swe-r62",
  "Welche Aussagen über Ausnahmen sind zutreffend?",
  ("Sie melden außergewöhnliche Situationen zur Laufzeit",
   "Sie lassen sich gezielt abfangen und behandeln",
   "Unbehandelt führen sie zum Programmabbruch",
   "Sie trennen Fehlerbehandlung vom Normalablauf",
   "Sie werden bereits beim Übersetzen ausgelöst",
   "Sie ersetzen die Prüfung von Benutzereingaben"),
  (0, 1, 2, 3),
  "Ausnahmen halten den Normalfall lesbar und bündeln die Fehlerbehandlung an einer Stelle. Sie entstehen zur Laufzeit und ersetzen keine Eingabeprüfung, die den Fehler von vornherein vermeidet.",
  "Which statements about exceptions are correct?",
  ("They signal exceptional situations at runtime",
   "They can be caught and handled deliberately",
   "Unhandled, they terminate the program",
   "They separate error handling from the normal flow",
   "They are already raised during compilation",
   "They replace validation of user input"),
  "Exceptions keep the normal case readable and concentrate error handling in one place. They arise at runtime and do not replace input validation, which avoids the error in the first place."),

M("ap1-swe-r63",
  "Welche Schritte gehören zur Aufnahme von Anforderungen beim Kunden?",
  ("Gespräche mit den späteren Nutzern führen",
   "Bestehende Abläufe beobachten und aufnehmen",
   "Anforderungen schriftlich festhalten",
   "Unklarheiten gezielt nachfragen",
   "Die Umsetzung ohne Rücksprache festlegen",
   "Anforderungen nach eigenem Geschmack ändern"),
  (0, 1, 2, 3),
  "Anforderungen entstehen im Dialog: zuhören, beobachten, schriftlich festhalten und Unklarheiten klären. Alleingänge führen zu Software, die am Bedarf vorbeigeht.",
  "Which steps belong to gathering requirements at the customer?",
  ("Hold conversations with the later users",
   "Observe and record existing workflows",
   "Record requirements in writing",
   "Ask specifically about ambiguities",
   "Decide the implementation without consultation",
   "Change requirements to personal taste"),
  "Requirements emerge in dialogue: listen, observe, write down and clarify ambiguities. Going it alone produces software that misses the actual need."),

M("ap1-swe-r64",
  "Welche Aussagen über Konstanten und Variablen sind richtig?",
  ("Konstanten behalten ihren Wert während der Laufzeit",
   "Variablen können ihren Wert ändern",
   "Konstanten machen feste Werte im Code lesbar",
   "Beide besitzen einen Namen und einen Typ",
   "Konstanten lassen sich zur Laufzeit überschreiben",
   "Variablen benötigen grundsätzlich keinen Datentyp"),
  (0, 1, 2, 3),
  "Der Unterschied liegt allein in der Veränderbarkeit; Name und Typ haben beide. Genau deshalb schützt eine Konstante vor versehentlichem Überschreiben fester Werte.",
  "Which statements about constants and variables are correct?",
  ("Constants keep their value during runtime",
   "Variables can change their value",
   "Constants make fixed values in code readable",
   "Both have a name and a type",
   "Constants can be overwritten at runtime",
   "Variables fundamentally need no data type"),
  "The difference lies solely in mutability; both have a name and a type. That is exactly why a constant protects fixed values from accidental overwriting."),

# ------------------------------------------------------------------ text (36)
T("ap1-swe-r65", "Welchen Dezimalwert hat die Binärzahl 1010?", "10",
  "Stellenwerte von rechts: 8 + 0 + 2 + 0 ergibt 10.",
  "What decimal value does the binary number 1010 have?", "10",
  "Place values from the right: 8 + 0 + 2 + 0 gives 10."),

T("ap1-swe-r66", "Welcher Datentyp speichert genau die Werte wahr und falsch?", "boolean",
  "Ein boolean bildet Ja-Nein-Entscheidungen exakt ab und braucht dafür nur ein einziges Bit an Information.",
  "Which data type stores exactly the values true and false?", "boolean",
  "A boolean models yes-no decisions precisely and needs only a single bit of information for it."),

T("ap1-swe-r67", "Wie heißt ein Fehler, der das Übersetzen verhindert, weil Sprachregeln verletzt sind?", "Syntaxfehler",
  "Der Compiler meldet ihn samt Zeilennummer, bevor das Programm überhaupt laufen kann.",
  "What is an error preventing compilation because language rules are broken called?", "Syntax error",
  "The compiler reports it with a line number before the program can even run."),

T("ap1-swe-r68", "Welches Dokument beschreibt aus Sicht des Auftraggebers, was gefordert wird?", "Lastenheft",
  "Es nennt das Was. Die Antwort des Auftragnehmers mit dem Wie steht im Pflichtenheft.",
  "Which document describes from the client's point of view what is required?", "Requirements specification",
  "It states the what. The contractor's answer with the how is in the functional specification."),

T("ap1-swe-r69", "Wie heißt das Prinzip, bei dem eine Klasse Eigenschaften einer anderen übernimmt?", "Vererbung",
  "Die abgeleitete Klasse erbt Attribute und Methoden und ergänzt eigene - so wird gemeinsamer Code nur einmal geschrieben.",
  "What is the principle of one class taking over the properties of another called?", "Inheritance",
  "The derived class inherits attributes and methods and adds its own - shared code is written only once."),

T("ap1-swe-r70", "Wie nennt man den Vorgang, bei dem sich eine Methode selbst aufruft?", "Rekursion",
  "Ohne Abbruchbedingung läuft der Aufrufstapel über und das Programm stürzt ab.",
  "What is the process of a method calling itself called?", "Recursion",
  "Without a termination condition the call stack overflows and the program crashes."),

T("ap1-swe-r71", "Welche Datenstruktur arbeitet nach dem Prinzip zuerst hinein, zuerst heraus?", "Warteschlange",
  "Auf Englisch Queue. Der Stapel arbeitet genau umgekehrt nach zuletzt hinein, zuerst heraus.",
  "Which data structure works on the first in, first out principle?", "Queue",
  "The stack works exactly the other way round, last in first out."),

T("ap1-swe-r72", "Wie heißt ein gespeicherter Änderungsstand in einer Versionsverwaltung?", "Commit",
  "Er enthält Autor, Zeitpunkt und eine Beschreibung und dient als Rückkehrpunkt in der Historie.",
  "What is a stored set of changes in a version control system called?", "Commit",
  "It contains author, timestamp and a description and serves as a return point in the history."),

T("ap1-swe-r73", "Wie nennt man einen eigenen Entwicklungsstrang in der Versionsverwaltung?", "Branch",
  "In ihm lässt sich arbeiten, ohne den Hauptstand zu stören; per Merge fließt das Ergebnis zurück.",
  "What is a separate development line in version control called?", "Branch",
  "Work happens in it without disturbing the main line; a merge brings the result back."),

T("ap1-swe-r74", "Welches Suchverfahren halbiert in jedem Schritt den Suchbereich?", "Binäre Suche",
  "Sie setzt sortierte Daten voraus und braucht dadurch nur logarithmisch viele Vergleiche.",
  "Which search method halves the search range at every step?", "Binary search",
  "It requires sorted data and therefore needs only logarithmically many comparisons."),

T("ap1-swe-r75", "Welchen Rückgabetyp trägt eine Methode, die keinen Wert zurückgibt?", "void",
  "Sie führt nur eine Aktion aus, etwa eine Ausgabe, und liefert dem Aufrufer kein Ergebnis.",
  "Which return type does a method that returns no value carry?", "void",
  "It only performs an action, such as printing, and gives the caller no result."),

T("ap1-swe-r76", "Wie nennt man das grafische Ablaufmodell aus geschachtelten Rechtecken?", "Struktogramm",
  "Nach Nassi-Shneiderman benannt. Es erzwingt strukturierte Programmierung ohne Sprünge.",
  "What is the graphical flow model made of nested rectangles called?", "Structogram",
  "Named after Nassi-Shneiderman. It enforces structured programming without jumps."),

T("ap1-swe-r77", "Welcher Operator vergleicht in vielen Sprachen zwei Werte auf Gleichheit?", "==",
  "Ein einfaches Gleichheitszeichen weist dagegen zu - eine klassische Fehlerquelle in Bedingungen.",
  "Which operator compares two values for equality in many languages?", "==",
  "A single equals sign assigns instead - a classic source of errors in conditions."),

T("ap1-swe-r78", "Wie heißt der Test, der ohne Kenntnis des Quelltexts nur Ein- und Ausgaben prüft?", "Blackbox-Test",
  "Getestet wird gegen die Spezifikation. Der Whitebox-Test nutzt dagegen die innere Struktur.",
  "What is a test checking only inputs and outputs without knowledge of the code called?", "Black box test",
  "Testing happens against the specification. A white box test uses the internal structure instead."),

T("ap1-swe-r79", "Welchen Dezimalwert hat die Binärzahl 11111111?", "255",
  "Acht gesetzte Bits ergeben den größtmöglichen Wert eines Bytes.",
  "What decimal value does the binary number 11111111 have?", "255",
  "Eight set bits give the largest possible value of one byte."),

T("ap1-swe-r80", "Wie nennt man das Zusammenführen zweier Entwicklungsstände in Git?", "Merge",
  "Bestehen widersprüchliche Änderungen an derselben Stelle, entsteht ein Konflikt und muss von Hand gelöst werden.",
  "What is combining two development lines in Git called?", "Merge",
  "If contradictory changes hit the same place, a conflict arises and must be resolved by hand."),

T("ap1-swe-r81", "Wie heißt das Vorgehensmodell mit Sprints, Daily und Product Owner?", "Scrum",
  "Es liefert in kurzen Zyklen lauffähige Zwischenstände und holt regelmäßig Rückmeldung ein.",
  "What is the process model with sprints, dailies and a product owner called?", "Scrum",
  "It delivers running increments in short cycles and gathers feedback regularly."),

T("ap1-swe-r82", "Bei welchem Index beginnt in vielen Programmiersprachen das erste Element eines Arrays?", "0",
  "Der Index gibt den Abstand zum Anfang an, deshalb hat das erste Element den Abstand null.",
  "At which index does the first element of an array start in many languages?", "0",
  "The index states the offset from the start, so the first element has offset zero."),

T("ap1-swe-r83", "Wie nennt man das Verbergen des inneren Zustands eines Objekts hinter Methoden?", "Kapselung",
  "Der Zugriff läuft nur über definierte Methoden, wodurch das Objekt in einem gültigen Zustand bleibt.",
  "What is hiding an object's internal state behind methods called?", "Encapsulation",
  "Access happens only through defined methods, keeping the object in a valid state."),

T("ap1-swe-r84", "Welches Werkzeug übersetzt Quelltext vorab vollständig in Maschinencode?", "Compiler",
  "Der Interpreter übersetzt dagegen zur Laufzeit Zeile für Zeile.",
  "Which tool translates source code fully into machine code in advance?", "Compiler",
  "An interpreter by contrast translates line by line at runtime."),

T("ap1-swe-r85", "Wie heißt ein Fehler, der erst während der Ausführung auftritt?", "Laufzeitfehler",
  "Typische Auslöser sind Division durch null oder Zugriffe außerhalb der Feldgrenzen.",
  "What is an error that occurs only during execution called?", "Runtime error",
  "Typical triggers are division by zero or access outside array bounds."),

T("ap1-swe-r86", "Wie nennt man eine Schleife, die ihre Bedingung erst nach dem Rumpf prüft?", "Fußgesteuerte Schleife",
  "Sie läuft deshalb garantiert mindestens einmal durch, typischerweise als do-while geschrieben.",
  "What is a loop checking its condition only after the body called?", "Foot-controlled loop",
  "It therefore runs at least once, typically written as do-while."),

T("ap1-swe-r87", "Welches UML-Diagramm zeigt Akteure und ihre fachlichen Anwendungsfälle?", "Anwendungsfalldiagramm",
  "Auf Englisch Use-Case-Diagramm. Es beschreibt, wer welche Funktion nutzt, nicht wie sie umgesetzt wird.",
  "Which UML diagram shows actors and their business use cases?", "Use case diagram",
  "It describes who uses which function, not how it is implemented."),

T("ap1-swe-r88", "Wie viele Zustände kann ein boolescher Wert annehmen?", "2",
  "Wahr oder falsch. Auf dieser Zweiwertigkeit bauen alle logischen Verknüpfungen auf.",
  "How many states can a boolean value take?", "2",
  "True or false. All logical operations build on this two-valued nature."),

T("ap1-swe-r89", "Wie heißt eine Sammlung wiederverwendbarer Funktionen und Klassen?", "Bibliothek",
  "Sie spart Entwicklungsaufwand und bündelt erprobte Lösungen, bringt aber Abhängigkeiten und Lizenzfragen mit.",
  "What is a collection of reusable functions and classes called?", "Library",
  "It saves development effort and bundles proven solutions but brings dependencies and licensing questions."),

T("ap1-swe-r90", "Wie nennt man den Test, der nach jeder Änderung alte Fehler ausschließt?", "Regressionstest",
  "Er wiederholt bestehende Testfälle und meldet, wenn bereits Behobenes wieder auftritt.",
  "What is the test ruling out old bugs after every change called?", "Regression test",
  "It repeats existing test cases and reports when something already fixed reappears."),

T("ap1-swe-r91", "Welche Fehlerart liegt vor, wenn ein Programm läuft, aber falsch rechnet?", "Logischer Fehler",
  "Der Compiler kann ihn nicht bemerken; entdeckt wird er nur durch Tests mit bekanntem Sollergebnis.",
  "Which kind of error is it when a program runs but computes wrongly?", "Logical error",
  "The compiler cannot notice it; it is found only through tests with a known expected result."),

T("ap1-swe-r92", "Wie heißt der Bereich, in dem eine Variable gültig und sichtbar ist?", "Gültigkeitsbereich",
  "Auf Englisch Scope. Eine lokale Variable existiert nur innerhalb ihres Blocks.",
  "What is the area in which a variable is valid and visible called?", "Scope",
  "A local variable exists only within its block."),

T("ap1-swe-r93", "Welchen Dezimalwert hat die Hexadezimalzahl A?", "10",
  "A bis F stehen für die Werte 10 bis 15, weil das Hexadezimalsystem sechzehn Ziffern braucht.",
  "What decimal value does the hexadecimal number A have?", "10",
  "A to F represent the values 10 to 15, because hexadecimal needs sixteen digits."),

T("ap1-swe-r94", "Wie nennt man einen konkret erzeugten Vertreter einer Klasse?", "Objekt",
  "Auch Instanz genannt. Aus einer Klasse lassen sich beliebig viele davon mit eigenen Attributwerten erzeugen.",
  "What is a concretely created representative of a class called?", "Object",
  "Also called an instance. Any number of them with their own attribute values can be created from a class."),

T("ap1-swe-r95", "Wie heißt die Fehlersuche mit Haltepunkten und Einzelschrittausführung?", "Debugging",
  "Das Programm wird angehalten, Variablenwerte werden geprüft und der Ablauf Schritt für Schritt verfolgt.",
  "What is fault finding with breakpoints and single stepping called?", "Debugging",
  "The program is paused, variable values are inspected and the flow followed step by step."),

T("ap1-swe-r96", "Welches Symbol stellt in einem Programmablaufplan eine Verzweigung dar?", "Die Raute",
  "Aus ihr führen zwei beschriftete Wege heraus, üblicherweise für ja und nein.",
  "Which symbol represents a branch in a program flowchart?", "The diamond",
  "Two labelled paths lead out of it, usually for yes and no."),

T("ap1-swe-r97", "Wie nennt man Text im Quelltext, den der Compiler ignoriert?", "Kommentar",
  "Er erklärt die Absicht hinter einer Lösung und hat keinerlei Einfluss auf die Ausführung.",
  "What is text in source code that the compiler ignores called?", "Comment",
  "It explains the intention behind a solution and has no effect on execution whatsoever."),

T("ap1-swe-r98", "Welches Modell prüft jede Entwicklungsphase gegen eine zugehörige Teststufe?", "V-Modell",
  "Jeder Entwurfsstufe links steht rechts eine passende Teststufe gegenüber, von Modultest bis Abnahmetest.",
  "Which model checks each development phase against a matching test level?", "V-model",
  "Every design level on the left has a matching test level on the right, from unit test to acceptance test."),

T("ap1-swe-r99", "Wie nennt man eine Schleife ohne erreichbare Abbruchbedingung?", "Endlosschleife",
  "Das Programm reagiert dann nicht mehr und muss von außen beendet werden.",
  "What is a loop with no reachable exit condition called?", "Endless loop",
  "The program then stops responding and has to be terminated from outside."),

T("ap1-swe-r100", "Wie viele Grundkontrollstrukturen genügen der strukturierten Programmierung?", "3",
  "Sequenz, Auswahl und Wiederholung reichen aus, um jeden Algorithmus zu formulieren.",
  "How many basic control structures suffice for structured programming?", "3",
  "Sequence, selection and iteration are enough to express any algorithm."),
]

build("ap1-softwareentwicklung.json", "Softwareentwicklung", "Software Development", Q)
