#!/usr/bin/env python3
"""AP1 IT-Sicherheit & Datenschutz - 100 handgeschriebene Fragen."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from qlib import S, M, T, build

Q = [
# ---------------------------------------------------------------- single (32)
S("ap1-sec-r01",
  "Ein Verschlüsselungstrojaner hat alle Dateien auf dem Fileserver unbrauchbar gemacht. Was rettet die Daten?",
  ("Eine Sicherung, die vom Netz getrennt aufbewahrt wird",
   "Der Virenscanner, der die Dateien wieder entschlüsselt",
   "Die Zahlung des geforderten Betrags an die Erpresser",
   "Die Wiederherstellung aus dem Papierkorb des Servers"), 0,
  "Ransomware verschlüsselt auch erreichbare Netzlaufwerke und Sicherungen. Nur eine offline oder unveränderbar gelagerte Kopie überlebt. Zahlungen bieten keine Garantie und finanzieren das Geschäftsmodell.",
  "A ransomware trojan has made all files on the file server unusable. What saves the data?",
  ("A backup that is kept disconnected from the network",
   "The virus scanner, which decrypts the files again",
   "Paying the demanded sum to the extortionists",
   "Restoring the files from the server's recycle bin"),
  "Ransomware also encrypts reachable network drives and backups. Only a copy stored offline or immutably survives. Payment offers no guarantee and funds the business model."),

S("ap1-sec-r02",
  "Eine Mail fordert dich auf, dein Passwort über einen Link zu bestätigen. Der Absender wirkt bekannt. Was tust du?",
  ("Den Link ignorieren und die Mail der IT melden",
   "Den Link öffnen und die Seite auf Echtheit prüfen",
   "Das Passwort dort eingeben, aber danach sofort ändern",
   "Die Mail löschen und den Vorfall nicht weiter erwähnen"), 0,
  "Kein seriöser Dienst fordert Zugangsdaten per Mail an. Auch das bloße Öffnen kann Nachladeinhalte auslösen. Stilles Löschen verhindert zwar den eigenen Schaden, warnt aber die Kollegen nicht.",
  "An email asks you to confirm your password via a link. The sender looks familiar. What do you do?",
  ("Ignore the link and report the mail to IT",
   "Open the link and check the page for authenticity",
   "Enter the password there but change it immediately after",
   "Delete the mail and never mention the incident again"),
  "No reputable service requests credentials by email. Even opening the link can trigger loaded content. Silently deleting it prevents your own damage but leaves colleagues unwarned."),

S("ap1-sec-r03",
  "Ein Angreifer hat Preise in der Artikeldatenbank unbemerkt verändert. Welches Schutzziel wurde verletzt?",
  ("Integrität", "Vertraulichkeit", "Verfügbarkeit", "Verbindlichkeit"), 0,
  "Integrität bedeutet, dass Daten nicht unbemerkt verändert werden können. Vertraulichkeit wäre bei Mitlesen betroffen, Verfügbarkeit bei einem Ausfall, Verbindlichkeit beim Abstreiten einer Handlung.",
  "An attacker has quietly altered prices in the article database. Which security objective was violated?",
  ("Integrity", "Confidentiality", "Availability", "Non-repudiation"),
  "Integrity means data cannot be altered unnoticed. Confidentiality would be affected by eavesdropping, availability by an outage, non-repudiation by denying an action."),

S("ap1-sec-r04",
  "Der Onlineshop ist durch eine Flut von Anfragen nicht mehr erreichbar. Welches Schutzziel leidet?",
  ("Verfügbarkeit", "Vertraulichkeit", "Integrität", "Authentizität"), 0,
  "Bei einem Denial-of-Service-Angriff bleiben die Daten korrekt und geheim, sie sind nur nicht nutzbar. Genau das beschreibt das Schutzziel Verfügbarkeit.",
  "The online shop is unreachable because of a flood of requests. Which objective suffers?",
  ("Availability", "Confidentiality", "Integrity", "Authenticity"),
  "In a denial-of-service attack the data stays correct and secret, it is simply unusable. That is exactly what the availability objective describes."),

S("ap1-sec-r05",
  "Du willst einer Kollegin eine vertrauliche Datei asymmetrisch verschlüsselt schicken. Welchen Schlüssel nutzt du?",
  ("Ihren öffentlichen Schlüssel",
   "Deinen privaten Schlüssel",
   "Euren gemeinsamen Sitzungsschlüssel",
   "Ihren privaten Schlüssel"), 0,
  "Verschlüsselt wird mit dem öffentlichen Schlüssel des Empfängers, entschlüsseln kann nur er mit seinem privaten. Mit dem eigenen privaten Schlüssel wird signiert, nicht verschlüsselt.",
  "You want to send a colleague a confidential file using asymmetric encryption. Which key do you use?",
  ("Her public key",
   "Your private key",
   "Your shared session key",
   "Her private key"),
  "Encryption uses the recipient's public key, and only they can decrypt with their private one. Your own private key is used for signing, not encrypting."),

S("ap1-sec-r06",
  "Warum werden Passwörter als Hashwert statt im Klartext gespeichert?",
  ("Aus dem Hashwert lässt sich das Passwort nicht zurückrechnen",
   "Der Hashwert braucht deutlich weniger Speicherplatz",
   "Der Hashwert lässt sich schneller mit der Eingabe vergleichen",
   "Der Hashwert wird bei jeder Anmeldung neu vergeben"), 0,
  "Hashfunktionen sind Einwegfunktionen: gleiche Eingabe ergibt gleichen Hash, aber der Weg zurück ist praktisch unmöglich. Bei einem Datenbankdiebstahl bleiben die Passwörter dadurch geschützt.",
  "Why are passwords stored as a hash value instead of plain text?",
  ("The password cannot be computed back from the hash",
   "The hash value needs considerably less storage space",
   "The hash value compares faster against the user input",
   "The hash value is reassigned on every single login"),
  "Hash functions are one-way: the same input yields the same hash, but the way back is practically impossible. If the database is stolen, the passwords stay protected."),

S("ap1-sec-r07",
  "Auf dem Firmenparkplatz liegt ein USB-Stick ohne Beschriftung. Wie gehst du damit um?",
  ("Nicht anstecken und bei der IT-Abteilung abgeben",
   "An einem alten Rechner anstecken, um den Besitzer zu finden",
   "Am eigenen Rechner öffnen, aber nur die Dateiliste ansehen",
   "Formatieren und danach als Ersatzstick weiterverwenden"), 0,
  "Ausgelegte Datenträger sind ein bekannter Angriffsweg, weil sie Schadcode schon beim Anstecken ausführen können. Auch ein alter Rechner hängt am selben Netz und wäre ein Einstiegspunkt.",
  "An unlabelled USB stick is lying in the company car park. How do you handle it?",
  ("Do not plug it in and hand it to the IT department",
   "Plug it into an old machine to find the owner",
   "Open it on your own PC but only view the file list",
   "Format it and keep using it as a spare stick"),
  "Planted storage devices are a known attack route because they can execute malicious code on insertion. An old machine hangs on the same network and would be an entry point too."),

S("ap1-sec-r08",
  "Welche Angabe ist nach DSGVO ein personenbezogenes Datum?",
  ("Die dienstliche Telefonnummer eines Mitarbeiters",
   "Der Jahresumsatz einer Aktiengesellschaft",
   "Die Seriennummer eines Netzwerkswitches",
   "Die Öffnungszeiten einer Filiale"), 0,
  "Personenbezogen ist alles, was sich auf eine identifizierte oder identifizierbare natürliche Person bezieht - dazu zählt auch eine dienstliche Rufnummer. Angaben zu Firmen und Geräten fallen nicht darunter.",
  "Which item counts as personal data under the GDPR?",
  ("An employee's business telephone number",
   "The annual revenue of a public company",
   "The serial number of a network switch",
   "The opening hours of a branch office"),
  "Personal data is anything relating to an identified or identifiable natural person, including a business phone number. Details about companies and devices do not qualify."),

S("ap1-sec-r09",
  "Innerhalb welcher Frist muss eine meldepflichtige Datenpanne der Aufsichtsbehörde gemeldet werden?",
  ("Innerhalb von 72 Stunden", "Innerhalb von 24 Stunden",
   "Innerhalb von 7 Werktagen", "Innerhalb von 30 Tagen"), 0,
  "Artikel 33 DSGVO nennt 72 Stunden ab Kenntnis. Ist die Meldung später, muss die Verzögerung begründet werden; bei hohem Risiko sind zusätzlich die Betroffenen zu informieren.",
  "Within which deadline must a reportable data breach be notified to the supervisory authority?",
  ("Within 72 hours", "Within 24 hours",
   "Within 7 working days", "Within 30 days"),
  "Article 33 GDPR states 72 hours from becoming aware. If the notification is later, the delay must be justified; at high risk the data subjects must also be informed."),

S("ap1-sec-r10",
  "Eine Mitarbeiterin wechselt vom Vertrieb in die Buchhaltung. Was ist beim Zugriff zu tun?",
  ("Alte Rechte entziehen und neue passend vergeben",
   "Die neuen Rechte ergänzen und die alten belassen",
   "Ein zusätzliches zweites Benutzerkonto einrichten",
   "Vorerst alle Rechte lassen und später aufräumen"), 0,
  "Sammeln sich Rechte über Jahre an, entsteht eine Rechteanhäufung, die dem Prinzip der minimalen Berechtigung widerspricht. Zwei Konten erschweren zusätzlich die Nachvollziehbarkeit.",
  "An employee moves from sales to accounting. What has to happen to her access?",
  ("Revoke the old rights and grant fitting new ones",
   "Add the new rights and leave the old ones in place",
   "Set up an additional second user account for her",
   "Leave all rights for now and clean up later"),
  "If rights accumulate over the years, privilege creep results, which contradicts the principle of least privilege. Two accounts additionally make actions harder to trace."),

S("ap1-sec-r11",
  "Was besagt das Prinzip der minimalen Rechtevergabe?",
  ("Jeder erhält nur die Rechte, die er für seine Aufgabe braucht",
   "Jeder erhält dieselben Rechte, um Rückfragen zu vermeiden",
   "Rechte werden nur an Vorgesetzte und Vertreter vergeben",
   "Rechte werden erst nach einem schriftlichen Antrag entzogen"), 0,
  "Weniger Rechte bedeuten weniger Schaden, wenn ein Konto übernommen wird oder jemand einen Fehler macht. Einheitliche Rechte für alle wären das genaue Gegenteil davon.",
  "What does the principle of least privilege state?",
  ("Everyone gets only the rights their task actually requires",
   "Everyone gets the same rights to avoid follow-up questions",
   "Rights are granted only to managers and their deputies",
   "Rights are revoked only after a written application"),
  "Fewer rights mean less damage when an account is taken over or someone makes a mistake. Uniform rights for everyone would be the exact opposite."),

S("ap1-sec-r12",
  "Bei einer Begehung klebt an mehreren Monitoren das Anmeldepasswort. Was ist die richtige Reaktion?",
  ("Passwörter ändern lassen und die Nutzer schulen",
   "Die Zettel entfernen und den Vorgang nicht weiter verfolgen",
   "Die betroffenen Konten dauerhaft sperren lassen",
   "Nichts tun, solange der Raum abgeschlossen wird"), 0,
  "Ein sichtbar notiertes Passwort gilt als kompromittiert und muss gewechselt werden. Damit das Problem nicht wiederkehrt, braucht es Aufklärung über Passwortmanager statt nur eine Aufräumaktion.",
  "During a walkthrough, login passwords are stuck to several monitors. What is the right response?",
  ("Have the passwords changed and train the users",
   "Remove the notes and take the matter no further",
   "Have the affected accounts permanently disabled",
   "Do nothing as long as the room gets locked"),
  "A visibly written password counts as compromised and must be changed. To stop the problem recurring, users need education about password managers, not just a tidy-up."),

S("ap1-sec-r13",
  "Was ist der Sicherheitsgewinn einer Zwei-Faktor-Authentisierung?",
  ("Ein gestohlenes Passwort allein reicht nicht mehr aus",
   "Das Passwort muss dadurch seltener gewechselt werden",
   "Der Anmeldevorgang läuft dadurch spürbar schneller ab",
   "Die Übertragung der Anmeldedaten wird verschlüsselt"), 0,
  "Der zweite Faktor stammt aus einer anderen Kategorie - Wissen, Besitz oder Biometrie. Ein Angreifer bräuchte beides gleichzeitig, was den Aufwand erheblich erhöht.",
  "What is the security benefit of two-factor authentication?",
  ("A stolen password alone is no longer sufficient",
   "The password has to be changed less frequently",
   "The login process becomes noticeably faster",
   "The transfer of credentials becomes encrypted"),
  "The second factor comes from a different category - knowledge, possession or biometrics. An attacker would need both at once, which raises the effort considerably."),

S("ap1-sec-r14",
  "Was unterscheidet einen Wurm von einem klassischen Virus?",
  ("Er verbreitet sich selbstständig ohne Wirtsdatei",
   "Er verschlüsselt zusätzlich die befallenen Dateien",
   "Er wird ausschließlich über USB-Sticks weitergegeben",
   "Er wird erst zu einem festen Datum überhaupt aktiv"), 0,
  "Der Wurm nutzt Netzwerkdienste und Schwachstellen, um sich ohne Zutun weiterzuverbreiten. Ein Virus hängt sich dagegen an eine Wirtsdatei und braucht deren Ausführung.",
  "What distinguishes a worm from a classic virus?",
  ("It spreads by itself without needing a host file",
   "It additionally encrypts the files it infects",
   "It is passed on exclusively via USB sticks",
   "It only becomes active on a fixed calendar date"),
  "A worm uses network services and vulnerabilities to spread without any action. A virus by contrast attaches to a host file and needs that file to be executed."),

S("ap1-sec-r15",
  "Ein Server läuft seit 14 Monaten ohne Sicherheitsupdates, weil ein Neustart stört. Wie bewertest du das?",
  ("Ein Wartungsfenster planen und die Updates nachziehen",
   "Vertretbar, solange der Server hinter einer Firewall steht",
   "Vertretbar, solange ein Virenscanner installiert ist",
   "Erst beim nächsten Hardwaretausch mit erneuern"), 0,
  "Bekannte Lücken werden aktiv ausgenutzt, oft wenige Tage nach Veröffentlichung. Firewall und Virenscanner sind ergänzende Schichten, ersetzen aber kein Patchmanagement.",
  "A server has run 14 months without security updates because a reboot is disruptive. How do you judge that?",
  ("Schedule a maintenance window and apply the updates",
   "Acceptable as long as the server sits behind a firewall",
   "Acceptable as long as a virus scanner is installed",
   "Renew it only with the next hardware replacement"),
  "Known vulnerabilities are actively exploited, often days after disclosure. Firewalls and virus scanners are complementary layers but do not replace patch management."),

S("ap1-sec-r16",
  "Welche Aufgabe hat eine Firewall am Übergang ins Internet?",
  ("Sie erlaubt oder verwirft Verbindungen nach festen Regeln",
   "Sie entfernt Schadsoftware von bereits befallenen Rechnern",
   "Sie sichert die Daten der Arbeitsplätze regelmäßig",
   "Sie verschlüsselt sämtlichen Verkehr im lokalen Netz"), 0,
  "Die Firewall entscheidet anhand von Adressen, Ports und Zustand, welcher Verkehr passieren darf. Schadcode entfernen ist Sache des Virenschutzes, Sicherung und Verschlüsselung übernehmen andere Systeme.",
  "What is the task of a firewall at the internet edge?",
  ("It permits or discards connections by fixed rules",
   "It removes malware from already infected machines",
   "It backs up the workstations' data on a regular basis",
   "It encrypts all traffic inside the local network"),
  "The firewall decides which traffic may pass based on addresses, ports and connection state. Removing malicious code is the antivirus's job; backup and encryption belong to other systems."),

S("ap1-sec-r17",
  "Ein Außendienstler arbeitet im Hotel-WLAN mit Firmendaten. Welche Maßnahme ist entscheidend?",
  ("Die Verbindung ins Firmennetz über ein VPN aufbauen",
   "Die WLAN-Verbindung nach jeder Sitzung neu aufbauen",
   "Den Rechnernamen im Netzwerk unkenntlich machen",
   "Ausschließlich über den Browser statt Programme arbeiten"), 0,
  "In fremden Netzen kann der Verkehr mitgelesen werden. Ein VPN baut einen verschlüsselten Tunnel bis ins Firmennetz auf. Ein anderer Rechnername oder der Browser allein ändern daran nichts.",
  "A field worker uses hotel Wi-Fi with company data. Which measure is decisive?",
  ("Connect to the company network through a VPN",
   "Re-establish the Wi-Fi connection after every session",
   "Make the computer name unrecognisable on the network",
   "Work exclusively via the browser instead of applications"),
  "In foreign networks traffic can be intercepted. A VPN builds an encrypted tunnel into the company network. A different computer name or the browser alone change nothing."),

S("ap1-sec-r18",
  "Der Browser meldet beim Aufruf des Kundenportals ein ungültiges Zertifikat. Wie reagierst du?",
  ("Abbrechen und die Ursache mit der IT klären",
   "Die Warnung bestätigen, da die Adresse stimmt",
   "Die Warnung dauerhaft für diese Seite abschalten",
   "Auf HTTP wechseln, um die Warnung zu umgehen"), 0,
  "Eine Zertifikatswarnung kann auf ein abgelaufenes Zertifikat, aber auch auf einen Man-in-the-Middle-Angriff hindeuten. Die Warnung wegzuklicken oder auf HTTP auszuweichen entfernt nur den Hinweis, nicht die Gefahr.",
  "The browser reports an invalid certificate when opening the customer portal. How do you react?",
  ("Abort and clarify the cause with the IT team",
   "Confirm the warning, since the address is correct",
   "Disable the warning permanently for this site",
   "Switch to HTTP in order to avoid the warning"),
  "A certificate warning can indicate an expired certificate but also a man-in-the-middle attack. Clicking the warning away or falling back to HTTP removes the notice, not the danger."),

S("ap1-sec-r19",
  "Was fordert die 3-2-1-Regel für Datensicherungen?",
  ("Drei Kopien auf zwei Medien, eine davon außer Haus",
   "Drei Sicherungen pro Tag auf zwei getrennten Servern",
   "Drei Generationen, zwei Prüfungen und ein Protokoll",
   "Drei Berechtigte, zwei Standorte und ein Passwort"), 0,
  "Drei Kopien schützen vor Einzelfehlern, zwei verschiedene Medien vor einem Medienschaden, und die auswärtige Kopie überlebt Brand oder Diebstahl am Hauptstandort.",
  "What does the 3-2-1 rule for backups require?",
  ("Three copies on two media, one of them off site",
   "Three backups per day on two separate servers",
   "Three generations, two checks and one log file",
   "Three authorised people, two sites and one password"),
  "Three copies protect against single failures, two different media against a media defect, and the off-site copy survives fire or theft at the main location."),

S("ap1-sec-r20",
  "Die Sicherung läuft seit Jahren fehlerfrei, wurde aber nie zurückgespielt. Was folgt daraus?",
  ("Die Wiederherstellung muss regelmäßig getestet werden",
   "Die Sicherung ist durch die Protokolle ausreichend belegt",
   "Es genügt, die Größe der Sicherungsdateien zu prüfen",
   "Ein Test ist erst nach einem echten Schadensfall nötig"), 0,
  "Erst der Rückspieltest zeigt, ob die Daten vollständig und lesbar sind und wie lange es dauert. Ein grünes Protokoll sagt nur, dass der Schreibvorgang durchlief.",
  "The backup has run without errors for years but was never restored. What follows from that?",
  ("Restores must be tested on a regular schedule",
   "The log files prove the backup sufficiently already",
   "Checking the size of the backup files is enough",
   "A test is only needed after a real incident occurs"),
  "Only a restore test shows whether the data is complete and readable and how long it takes. A green log only says the write operation finished."),

S("ap1-sec-r21",
  "Ein Anrufer gibt sich als Geschäftsführer aus und drängt auf eine sofortige Überweisung. Was tust du?",
  ("Über eine bekannte Nummer zurückrufen und prüfen",
   "Die Überweisung ausführen, da Eile geboten ist",
   "Die Überweisung ausführen und danach nachfragen",
   "Die Anweisung an einen Kollegen weitergeben"), 0,
  "Zeitdruck und Autorität sind die typischen Hebel beim CEO-Fraud. Der Rückruf über eine selbst herausgesuchte Nummer bricht die Täuschung, weil der Angreifer den Kanal nicht kontrolliert.",
  "A caller claims to be the managing director and pushes for an immediate transfer. What do you do?",
  ("Call back on a known number and verify the request",
   "Execute the transfer, since the matter is urgent",
   "Execute the transfer and ask questions afterwards",
   "Pass the instruction on to a colleague instead"),
  "Time pressure and authority are the typical levers in CEO fraud. Calling back on a number you looked up yourself breaks the deception, because the attacker does not control that channel."),

S("ap1-sec-r22",
  "Welche Maßnahme schützt den Serverraum am wirksamsten vor unbefugtem Zutritt?",
  ("Eine Zutrittskontrolle mit protokollierter Vereinzelung",
   "Ein Hinweisschild mit dem Verbot des Zutritts",
   "Ein Kennwort für die Konsole der Serverschränke",
   "Eine Überwachungskamera im Flur vor dem Raum"), 0,
  "Nur eine technische Zutrittskontrolle verhindert das Betreten und dokumentiert zugleich, wer wann drin war. Schilder appellieren nur, und Kameras oder Konsolenpasswörter greifen erst, wenn jemand bereits im Raum steht.",
  "Which measure protects the server room most effectively against unauthorised entry?",
  ("Access control with logged single-person entry",
   "A sign stating that entry is prohibited",
   "A password for the server cabinet consoles",
   "A surveillance camera in the corridor outside"),
  "Only technical access control prevents entry and simultaneously documents who was inside and when. Signs merely appeal, and cameras or console passwords take effect only once someone is already in the room."),

S("ap1-sec-r23",
  "Wozu dient eine USV im Serverraum?",
  ("Sie überbrückt Stromausfälle für ein geordnetes Herunterfahren",
   "Sie verteilt die Last gleichmäßig auf mehrere Server",
   "Sie kühlt die Serverschränke bei hoher Auslastung",
   "Sie sichert die Daten der Server auf ein zweites Medium"), 0,
  "Die unterbrechungsfreie Stromversorgung hält den Betrieb für Minuten aufrecht und meldet den Ausfall, damit Systeme kontrolliert herunterfahren. Kühlung, Lastverteilung und Sicherung sind eigene Aufgaben.",
  "What is a UPS in the server room for?",
  ("It bridges power failures for an orderly shutdown",
   "It distributes load evenly across several servers",
   "It cools the server cabinets under heavy load",
   "It backs up the servers' data to a second medium"),
  "The uninterruptible power supply keeps operation alive for minutes and signals the outage so systems shut down in a controlled way. Cooling, load balancing and backup are separate jobs."),

S("ap1-sec-r24",
  "Ausgemusterte Festplatten mit Kundendaten sollen entsorgt werden. Was ist fachlich korrekt?",
  ("Nachweislich löschen oder physisch vernichten lassen",
   "Die Partitionen entfernen und die Platten verkaufen",
   "Die Dateien löschen und den Papierkorb leeren",
   "Die Platten formatieren und im Lager aufbewahren"), 0,
  "Schnellformatierung und gelöschte Partitionen lassen die Daten auf dem Medium zurück und sind wiederherstellbar. Nötig ist sicheres Überschreiben oder mechanische Vernichtung mit Nachweis.",
  "Decommissioned hard disks holding customer data are to be disposed of. What is professionally correct?",
  ("Have them verifiably wiped or physically destroyed",
   "Remove the partitions and then sell the disks",
   "Delete the files and empty the recycle bin",
   "Format the disks and store them in the stockroom"),
  "Quick formatting and deleted partitions leave the data on the medium and it can be recovered. Secure overwriting or mechanical destruction with a certificate is required."),

S("ap1-sec-r25",
  "Ein Dienstnotebook wird im Zug gestohlen. Was begrenzt den Schaden am stärksten?",
  ("Eine vollständige Verschlüsselung der Festplatte",
   "Ein Anmeldekennwort für das Benutzerkonto",
   "Ein Bildschirmschoner mit kurzer Sperrzeit",
   "Ein Aufkleber mit der Anschrift der Firma"), 0,
  "Ohne Verschlüsselung lässt sich die Platte einfach ausbauen und an einem anderen Rechner auslesen - das Anmeldekennwort schützt dann gar nicht mehr. Nur die Verschlüsselung macht die Daten unbrauchbar.",
  "A company laptop is stolen on a train. What limits the damage most?",
  ("Full disk encryption of the internal drive",
   "A login password for the user account",
   "A screen saver with a short lock timeout",
   "A sticker showing the company's address"),
  "Without encryption the drive can simply be removed and read on another machine - the login password then protects nothing at all. Only encryption makes the data useless."),

S("ap1-sec-r26",
  "Ein externer Dienstleister verarbeitet Kundendaten im Auftrag. Was ist dafür erforderlich?",
  ("Ein Vertrag zur Auftragsverarbeitung nach Artikel 28",
   "Eine schriftliche Einwilligung aller Beschäftigten",
   "Eine Anmeldung des Dienstleisters beim Finanzamt",
   "Eine Löschung der Daten nach jedem Arbeitstag"), 0,
  "Der Auftragsverarbeitungsvertrag regelt Weisungsbindung, technische Maßnahmen und Löschung nach Auftragsende. Ohne ihn fehlt der Datenweitergabe die Rechtsgrundlage.",
  "An external service provider processes customer data on your behalf. What is required for that?",
  ("A data processing agreement under Article 28",
   "Written consent from all of your employees",
   "A registration of the provider with the tax office",
   "Deletion of the data after every working day"),
  "The data processing agreement governs instruction-bound processing, technical measures and deletion once the contract ends. Without it, passing on the data lacks a legal basis."),

S("ap1-sec-r27",
  "Adressen aus dem Bestellsystem sollen für eine Werbeaktion genutzt werden. Welcher Grundsatz steht dem entgegen?",
  ("Die Zweckbindung der ursprünglichen Erhebung",
   "Die Pflicht zur Verschlüsselung der Datenbank",
   "Die Aufbewahrungsfrist aus dem Handelsrecht",
   "Das Recht auf Datenübertragbarkeit der Kunden"), 0,
  "Daten dürfen nur für den Zweck genutzt werden, für den sie erhoben wurden. Für Werbung braucht es eine eigene Rechtsgrundlage, in der Regel eine Einwilligung.",
  "Addresses from the ordering system are to be used for an advertising campaign. Which principle opposes that?",
  ("The purpose limitation of the original collection",
   "The obligation to encrypt the customer database",
   "The retention period required by commercial law",
   "The customers' right to data portability"),
  "Data may only be used for the purpose it was collected for. Advertising needs its own legal basis, usually consent."),

S("ap1-sec-r28",
  "Warum werden Anmeldevorgänge auf Servern protokolliert?",
  ("Um Zugriffe im Nachhinein nachvollziehen zu können",
   "Um die Anmeldung beim nächsten Mal zu beschleunigen",
   "Um die Passwörter der Nutzer zentral zu sichern",
   "Um die Auslastung der Festplatten zu begrenzen"), 0,
  "Protokolle machen sichtbar, wer wann was getan hat, und sind bei der Aufklärung eines Vorfalls oft die einzige Quelle. Passwörter gehören dagegen nie ins Protokoll.",
  "Why are login events logged on servers?",
  ("So that access can be traced retrospectively",
   "So that the next login runs noticeably faster",
   "So that user passwords are stored centrally",
   "So that disk utilisation stays within limits"),
  "Logs make visible who did what and when, and are often the only source when investigating an incident. Passwords, by contrast, never belong in a log."),

S("ap1-sec-r29",
  "Ein Angreifer probiert massenhaft Zeichenkombinationen an einem Login durch. Wie heißt das Vorgehen?",
  ("Brute-Force-Angriff", "Man-in-the-Middle-Angriff",
   "Denial-of-Service-Angriff", "Cross-Site-Scripting-Angriff"), 0,
  "Brute Force probiert systematisch alle Möglichkeiten durch. Wirksame Gegenmittel sind lange Passwörter, Sperren nach Fehlversuchen und ein zweiter Faktor.",
  "An attacker tries out huge numbers of character combinations at a login. What is this called?",
  ("Brute force attack", "Man-in-the-middle attack",
   "Denial-of-service attack", "Cross-site scripting attack"),
  "Brute force systematically tries every possibility. Effective countermeasures are long passwords, lockout after failed attempts and a second factor."),

S("ap1-sec-r30",
  "Ein Administrator surft und liest Mails mit seinem Administratorkonto. Warum ist das problematisch?",
  ("Schadcode liefe sofort mit vollen Systemrechten",
   "Das Konto wird durch die Nutzung schneller gesperrt",
   "Die Protokolle werden dadurch unnötig umfangreich",
   "Die Lizenzbedingungen verbieten diese Nutzung"), 0,
  "Alles, was in der Sitzung startet, erbt deren Rechte. Für Alltagsaufgaben gehört ein normales Benutzerkonto her, das Administratorkonto nur für die Administration.",
  "An administrator browses and reads mail using their administrator account. Why is that a problem?",
  ("Malicious code would run with full system rights",
   "The account gets locked out faster through use",
   "The log files grow unnecessarily large this way",
   "The licence terms prohibit this kind of usage"),
  "Everything started within the session inherits its rights. Everyday tasks belong in a normal user account, the administrator account only in administration."),

S("ap1-sec-r31",
  "Eine Rechnung kommt als Word-Datei und bittet um Aktivierung der Makros. Wie ist das einzuschätzen?",
  ("Ein typischer Weg, Schadcode zur Ausführung zu bringen",
   "Ein üblicher Schritt, damit die Formatierung stimmt",
   "Ein Hinweis darauf, dass die Datei beschädigt ist",
   "Ein Zeichen für eine besonders alte Office-Version"), 0,
  "Makros sind ausführbarer Code im Dokument. Die Aufforderung, sie zu aktivieren, ist ein klassisches Merkmal von Schaddokumenten, weil Office sie sonst blockiert.",
  "An invoice arrives as a Word file and asks you to enable macros. How should that be judged?",
  ("A typical way of getting malicious code to execute",
   "A common step so that the formatting displays right",
   "An indication that the file has become corrupted",
   "A sign of an especially old version of Office"),
  "Macros are executable code inside the document. Being asked to enable them is a classic hallmark of malicious documents, because Office otherwise blocks them."),

S("ap1-sec-r32",
  "Wozu dient ein Notfallhandbuch in der IT?",
  ("Es beschreibt Zuständigkeiten und Schritte im Schadensfall",
   "Es listet die Anschaffungspreise aller Geräte auf",
   "Es ersetzt die regelmäßige Datensicherung im Betrieb",
   "Es dokumentiert die Urlaubsplanung der Abteilung"), 0,
  "Im Ernstfall fehlt die Zeit zum Nachdenken: Wer ist zu informieren, welche Systeme zuerst, welche Ersatzwege gibt es. Genau das hält das Notfallhandbuch vorab fest.",
  "What is the purpose of an IT emergency manual?",
  ("It describes responsibilities and steps in an incident",
   "It lists the purchase prices of all the equipment",
   "It replaces regular data backups during operation",
   "It documents the department's holiday planning"),
  "In a real incident there is no time to think: who must be informed, which systems come first, which fallbacks exist. That is exactly what the emergency manual records in advance."),

# -------------------------------------------------------------- multiple (32)
M("ap1-sec-r33",
  "Welche Schutzziele gehören zu den klassischen Grundwerten der Informationssicherheit?",
  ("Vertraulichkeit", "Integrität", "Verfügbarkeit", "Authentizität",
   "Wirtschaftlichkeit", "Benutzerfreundlichkeit"),
  (0, 1, 2, 3),
  "Vertraulichkeit, Integrität und Verfügbarkeit bilden den Kern, Authentizität und Verbindlichkeit werden meist ergänzt. Wirtschaftlichkeit und Bedienkomfort sind Projektziele, keine Schutzziele.",
  "Which objectives belong to the classic core values of information security?",
  ("Confidentiality", "Integrity", "Availability", "Authenticity",
   "Cost efficiency", "Ease of use"),
  "Confidentiality, integrity and availability form the core, with authenticity and non-repudiation usually added. Cost efficiency and usability are project goals, not security objectives."),

M("ap1-sec-r34",
  "Woran lässt sich eine Phishing-Mail häufig erkennen?",
  ("Erzeugter Zeitdruck und Drohung mit Sperrung",
   "Absenderadresse weicht bei genauem Hinsehen ab",
   "Der Link zeigt beim Überfahren ein fremdes Ziel",
   "Unpersönliche Anrede trotz bestehendem Konto",
   "Die Mail enthält eine korrekte Signatur der Firma",
   "Die Mail kommt während der üblichen Bürozeiten an"),
  (0, 1, 2, 3),
  "Druck, gefälschte Absender, abweichende Linkziele und unpersönliche Anreden sind die typischen Merkmale. Eine plausible Signatur und der Empfangszeitpunkt sagen dagegen nichts über die Echtheit aus.",
  "How can a phishing mail often be recognised?",
  ("Manufactured time pressure and threats of lockout",
   "The sender address differs on closer inspection",
   "Hovering the link reveals a foreign destination",
   "Impersonal salutation despite an existing account",
   "The mail contains a correct company signature",
   "The mail arrives during normal office hours"),
  "Pressure, forged senders, mismatched link targets and impersonal salutations are the typical signs. A plausible signature and the time of arrival say nothing about authenticity."),

M("ap1-sec-r35",
  "Welche Eigenschaften kennzeichnen ein starkes Passwort?",
  ("Ausreichende Länge von mindestens zwölf Zeichen",
   "Keine Wiederverwendung bei anderen Diensten",
   "Keine Bezüge zu Namen oder Geburtsdaten",
   "Verwaltung in einem Passwortmanager",
   "Regelmäßiger Wechsel im festen Monatsrhythmus",
   "Ersetzen von Buchstaben durch ähnliche Zeichen"),
  (0, 1, 2, 3),
  "Länge, Einzigartigkeit und fehlender Personenbezug tragen wirklich, ein Manager macht das praktikabel. Erzwungene Wechselintervalle und Zeichentricks wie a zu at gelten heute als überholt.",
  "Which properties characterise a strong password?",
  ("Sufficient length of at least twelve characters",
   "No reuse across other services",
   "No reference to names or dates of birth",
   "Management in a password manager",
   "Regular rotation on a fixed monthly cycle",
   "Replacing letters with lookalike characters"),
  "Length, uniqueness and no personal reference genuinely help, and a manager makes that practical. Forced rotation intervals and character tricks such as a to at are now considered outdated."),

M("ap1-sec-r36",
  "Welche Rechte stehen betroffenen Personen nach der DSGVO zu?",
  ("Auskunft über die gespeicherten Daten",
   "Berichtigung unrichtiger Angaben",
   "Löschung unter bestimmten Voraussetzungen",
   "Übertragung der Daten an einen anderen Anbieter",
   "Kostenlose Nutzung des Dienstes auf Dauer",
   "Einsicht in die Gehälter der Beschäftigten"),
  (0, 1, 2, 3),
  "Auskunft, Berichtigung, Löschung und Datenübertragbarkeit sind zentrale Betroffenenrechte, ergänzt um Einschränkung und Widerspruch. Kostenfreiheit und Gehaltseinsicht gehören nicht dazu.",
  "Which rights do data subjects have under the GDPR?",
  ("Access to the data stored about them",
   "Rectification of incorrect entries",
   "Erasure under certain conditions",
   "Transfer of the data to another provider",
   "Free use of the service indefinitely",
   "Insight into the salaries of employees"),
  "Access, rectification, erasure and portability are core data subject rights, complemented by restriction and objection. Free usage and salary insight are not among them."),

M("ap1-sec-r37",
  "Welche Maßnahmen zählen zu den technischen und organisatorischen Maßnahmen?",
  ("Verschlüsselung gespeicherter Daten",
   "Rollenbasierte Vergabe von Berechtigungen",
   "Protokollierung von Zugriffen",
   "Schulung der Beschäftigten",
   "Erhöhung des Werbebudgets",
   "Verkürzung der Lieferzeiten"),
  (0, 1, 2, 3),
  "Verschlüsselung und Berechtigungen sind technisch, Protokollierung und Schulung eher organisatorisch - zusammen bilden sie die geforderten Maßnahmen. Budget und Lieferzeit sind betriebswirtschaftliche Größen.",
  "Which measures count as technical and organisational measures?",
  ("Encryption of stored data",
   "Role-based assignment of permissions",
   "Logging of access events",
   "Training of the employees",
   "Increasing the advertising budget",
   "Shortening the delivery times"),
  "Encryption and permissions are technical, logging and training more organisational - together they form the required measures. Budget and delivery time are commercial figures."),

M("ap1-sec-r38",
  "Welche Wege nutzt Schadsoftware typischerweise, um auf einen Rechner zu gelangen?",
  ("Anhänge in E-Mails", "Präparierte Webseiten im Browser",
   "Ungepatchte Schwachstellen in Diensten", "Infizierte Wechseldatenträger",
   "Der eingebaute Lüfter des Gehäuses", "Die Anzahl der Bildschirme am Arbeitsplatz"),
  (0, 1, 2, 3),
  "Mailanhänge, manipulierte Webseiten, offene Lücken und Wechselmedien sind die verbreiteten Eintrittspunkte. Hardwaremerkmale wie Lüfter oder Monitore spielen dabei keine Rolle.",
  "Which routes does malware typically use to reach a computer?",
  ("Attachments in emails", "Prepared web pages in the browser",
   "Unpatched vulnerabilities in services", "Infected removable media",
   "The built-in fan of the case", "The number of screens at the workstation"),
  "Mail attachments, manipulated web pages, open vulnerabilities and removable media are the common entry points. Hardware features such as fans or monitors play no role."),

M("ap1-sec-r39",
  "Welche Aussagen über symmetrische Verschlüsselung sind richtig?",
  ("Zum Ver- und Entschlüsseln dient derselbe Schlüssel",
   "Sie ist bei großen Datenmengen deutlich schneller",
   "Der Schlüssel muss sicher ausgetauscht werden",
   "AES ist ein verbreitetes Verfahren dieser Art",
   "Jeder Teilnehmer veröffentlicht seinen Schlüssel",
   "Sie eignet sich besonders für digitale Signaturen"),
  (0, 1, 2, 3),
  "Ein gemeinsamer Schlüssel macht das Verfahren schnell, verlagert das Problem aber auf den sicheren Austausch - AES ist der Standardvertreter. Veröffentlichte Schlüssel und Signaturen gehören zur asymmetrischen Welt.",
  "Which statements about symmetric encryption are correct?",
  ("The same key is used to encrypt and decrypt",
   "It is considerably faster for large volumes of data",
   "The key has to be exchanged securely",
   "AES is a widely used method of this kind",
   "Every participant publishes their own key",
   "It is particularly suited to digital signatures"),
  "A shared key makes the method fast but shifts the problem to secure exchange - AES is the standard representative. Published keys and signatures belong to the asymmetric world."),

M("ap1-sec-r40",
  "Welche Angaben gehören in die Meldung einer Datenschutzverletzung?",
  ("Art der Verletzung und betroffene Datenkategorien",
   "Ungefähre Zahl der betroffenen Personen",
   "Wahrscheinliche Folgen der Verletzung",
   "Ergriffene und geplante Gegenmaßnahmen",
   "Der Umsatz des laufenden Geschäftsjahres",
   "Die private Anschrift des Geschäftsführers"),
  (0, 1, 2, 3),
  "Die Aufsichtsbehörde braucht Art, Umfang, Folgen und Maßnahmen, um das Risiko zu bewerten. Umsatzzahlen und Privatanschriften sind dafür ohne Bedeutung.",
  "Which details belong in the notification of a personal data breach?",
  ("Nature of the breach and categories of data affected",
   "Approximate number of individuals affected",
   "Likely consequences of the breach",
   "Countermeasures taken and planned",
   "The revenue of the current financial year",
   "The private address of the managing director"),
  "The supervisory authority needs nature, scope, consequences and measures in order to assess the risk. Revenue figures and private addresses are irrelevant for that."),

M("ap1-sec-r41",
  "Welche Faktoren dürfen bei einer Mehr-Faktor-Authentisierung kombiniert werden?",
  ("Etwas, das man weiß, etwa ein Kennwort",
   "Etwas, das man besitzt, etwa ein Token",
   "Etwas, das man ist, etwa ein Fingerabdruck",
   "Ein Einmalcode aus einer Authenticator-App",
   "Zwei verschiedene Kennwörter nacheinander",
   "Der Benutzername zusätzlich zum Kennwort"),
  (0, 1, 2, 3),
  "Echte Mehr-Faktor-Verfahren kombinieren verschiedene Kategorien: Wissen, Besitz und Biometrie. Zwei Kennwörter bleiben beides Wissen, und der Benutzername ist kein Geheimnis.",
  "Which factors may be combined in multi-factor authentication?",
  ("Something you know, such as a password",
   "Something you have, such as a token",
   "Something you are, such as a fingerprint",
   "A one-time code from an authenticator app",
   "Two different passwords entered in sequence",
   "The username in addition to the password"),
  "Genuine multi-factor schemes combine different categories: knowledge, possession and biometrics. Two passwords are both knowledge, and the username is not a secret."),

M("ap1-sec-r42",
  "Welche Vorkehrungen gehören zu einem tragfähigen Sicherungskonzept?",
  ("Festgelegte Sicherungsintervalle",
   "Aufbewahrung einer Kopie außer Haus",
   "Regelmäßige Wiederherstellungstests",
   "Schutz der Sicherung vor Veränderung",
   "Ablage der Sicherung im selben Serverschrank",
   "Verzicht auf Protokolle zur Vereinfachung"),
  (0, 1, 2, 3),
  "Intervalle, Auslagerung, Tests und Schreibschutz machen eine Sicherung im Ernstfall brauchbar. Eine Kopie im selben Schrank teilt jedes Risiko, und ohne Protokoll merkt niemand einen stillen Fehler.",
  "Which provisions belong to a viable backup concept?",
  ("Defined backup intervals",
   "Keeping one copy off site",
   "Regular restore tests",
   "Protecting the backup against modification",
   "Storing the backup in the same server cabinet",
   "Dropping log files to keep things simple"),
  "Intervals, off-site storage, tests and write protection make a backup usable in an emergency. A copy in the same cabinet shares every risk, and without logs nobody notices a silent failure."),

M("ap1-sec-r43",
  "Welche Beispiele sind Social Engineering?",
  ("Ein angeblicher Techniker bittet um Zutritt zum Serverraum",
   "Ein Anrufer fragt unter Zeitdruck nach Zugangsdaten",
   "Jemand schaut beim Eintippen des Kennworts zu",
   "Ein Fremder folgt dicht hinter einem durch die Schleuse",
   "Ein Dienst wird durch massenhafte Anfragen lahmgelegt",
   "Eine Festplatte fällt nach fünf Jahren Betrieb aus"),
  (0, 1, 2, 3),
  "Social Engineering zielt auf den Menschen: vorgetäuschte Rollen, Zeitdruck, Beobachten der Eingabe und Mitgehen durch die Tür. Überlastangriffe und Hardwaredefekte sind rein technische Ereignisse.",
  "Which examples are social engineering?",
  ("A supposed technician asks for access to the server room",
   "A caller demands credentials under time pressure",
   "Someone watches while a password is typed in",
   "A stranger follows closely through the access gate",
   "A service is paralysed by masses of requests",
   "A hard disk fails after five years of operation"),
  "Social engineering targets people: faked roles, time pressure, watching the keyboard and following through the door. Overload attacks and hardware defects are purely technical events."),

M("ap1-sec-r44",
  "Welche Aussagen zu Sicherungsarten sind korrekt?",
  ("Die Vollsicherung kopiert alle ausgewählten Daten",
   "Die differenzielle Sicherung bezieht sich auf die letzte Vollsicherung",
   "Die inkrementelle Sicherung sichert Änderungen seit der letzten Sicherung",
   "Inkrementelle Sicherungen brauchen beim Rückspielen die ganze Kette",
   "Die Vollsicherung ist die schnellste Sicherungsart",
   "Differenzielle Sicherungen werden mit der Zeit immer kleiner"),
  (0, 1, 2, 3),
  "Voll, differenziell und inkrementell unterscheiden sich im Bezugspunkt und damit im Aufwand beim Sichern und Zurückspielen. Die Vollsicherung dauert am längsten, und differenzielle Sicherungen wachsen bis zur nächsten Vollsicherung an.",
  "Which statements about backup types are correct?",
  ("A full backup copies all selected data",
   "A differential backup refers to the last full backup",
   "An incremental backup saves changes since the last backup",
   "Incremental backups need the whole chain to restore",
   "The full backup is the fastest backup type",
   "Differential backups get smaller over time"),
  "Full, differential and incremental differ in their reference point and therefore in effort when backing up and restoring. The full backup takes longest, and differential backups grow until the next full backup."),

M("ap1-sec-r45",
  "Welche Maßnahmen begrenzen den Schaden nach einem Befall mit Schadsoftware?",
  ("Das betroffene System sofort vom Netz trennen",
   "Den Vorfall an die zuständige Stelle melden",
   "Zugangsdaten der betroffenen Konten wechseln",
   "Das System aus einer sauberen Sicherung neu aufsetzen",
   "Das System weiterlaufen lassen, um Daten zu retten",
   "Die Protokolldateien zur Entlastung löschen"),
  (0, 1, 2, 3),
  "Trennen stoppt die Ausbreitung, Melden setzt die Reaktion in Gang, neue Zugangsdaten entwerten abgeflossene, und ein sauberer Neuaufbau beseitigt Reste. Weiterlaufen lassen und Protokolle löschen verschlimmern die Lage.",
  "Which measures limit the damage after a malware infection?",
  ("Disconnect the affected system from the network at once",
   "Report the incident to the responsible team",
   "Change the credentials of the affected accounts",
   "Rebuild the system from a clean backup",
   "Keep the system running in order to rescue data",
   "Delete the log files to reduce liability"),
  "Disconnecting stops the spread, reporting starts the response, new credentials devalue stolen ones, and a clean rebuild removes leftovers. Leaving it running and deleting logs make things worse."),

M("ap1-sec-r46",
  "Welche Aussagen über digitale Zertifikate treffen zu?",
  ("Sie binden einen öffentlichen Schlüssel an eine Identität",
   "Sie werden von einer Zertifizierungsstelle ausgestellt",
   "Sie besitzen eine begrenzte Gültigkeitsdauer",
   "Sie können vor Ablauf zurückgezogen werden",
   "Sie enthalten den privaten Schlüssel des Inhabers",
   "Sie ersetzen die Notwendigkeit einer Verschlüsselung"),
  (0, 1, 2, 3),
  "Ein Zertifikat bestätigt, wem ein öffentlicher Schlüssel gehört, ist befristet und kann gesperrt werden. Der private Schlüssel bleibt immer beim Inhaber und steht nie im Zertifikat.",
  "Which statements about digital certificates are true?",
  ("They bind a public key to an identity",
   "They are issued by a certification authority",
   "They have a limited period of validity",
   "They can be revoked before they expire",
   "They contain the holder's private key",
   "They remove the need for encryption"),
  "A certificate confirms who owns a public key, is time-limited and can be revoked. The private key always stays with the holder and never appears in the certificate."),

M("ap1-sec-r47",
  "Welche Grundsätze nennt die DSGVO für die Verarbeitung personenbezogener Daten?",
  ("Zweckbindung der Erhebung",
   "Datenminimierung auf das Erforderliche",
   "Richtigkeit der gespeicherten Daten",
   "Speicherbegrenzung auf die nötige Dauer",
   "Maximierung der gesammelten Datenmenge",
   "Weitergabe an Dritte ohne Einschränkung"),
  (0, 1, 2, 3),
  "Zweckbindung, Datenminimierung, Richtigkeit und Speicherbegrenzung stehen in Artikel 5, ergänzt um Rechtmäßigkeit, Integrität und Rechenschaftspflicht. Datensammeln auf Vorrat ist ausdrücklich unerwünscht.",
  "Which principles does the GDPR state for processing personal data?",
  ("Purpose limitation of the collection",
   "Data minimisation to what is necessary",
   "Accuracy of the stored data",
   "Storage limitation to the necessary period",
   "Maximisation of the volume of data collected",
   "Unrestricted disclosure to third parties"),
  "Purpose limitation, data minimisation, accuracy and storage limitation appear in Article 5, complemented by lawfulness, integrity and accountability. Collecting data as a precaution is expressly unwanted."),

M("ap1-sec-r48",
  "Welche Punkte sollte eine Sicherheitsrichtlinie für Beschäftigte regeln?",
  ("Umgang mit Passwörtern und Zugangsdaten",
   "Nutzung privater Geräte für dienstliche Zwecke",
   "Verhalten bei einem Sicherheitsvorfall",
   "Umgang mit mobilen Datenträgern",
   "Die Sitzordnung im Großraumbüro",
   "Die Auswahl der Kantinengerichte"),
  (0, 1, 2, 3),
  "Eine Richtlinie muss die Punkte abdecken, an denen Beschäftigte täglich Entscheidungen treffen: Passwörter, Privatgeräte, Meldewege und Wechselmedien. Sitzordnung und Verpflegung berühren die Sicherheit nicht.",
  "Which points should a security policy for employees cover?",
  ("Handling of passwords and credentials",
   "Use of private devices for work purposes",
   "Behaviour during a security incident",
   "Handling of mobile storage media",
   "The seating arrangement in the open-plan office",
   "The selection of dishes in the canteen"),
  "A policy must cover the points where employees make daily decisions: passwords, private devices, reporting paths and removable media. Seating and catering do not touch security."),

M("ap1-sec-r49",
  "Welche Merkmale hat ein Trojaner?",
  ("Er tarnt sich als nützliches Programm",
   "Er wird vom Nutzer selbst gestartet",
   "Er bringt versteckte Schadfunktionen mit",
   "Er kann eine Hintertür für Angreifer öffnen",
   "Er verbreitet sich selbstständig über das Netz",
   "Er wirkt ausschließlich auf Serverbetriebssystemen"),
  (0, 1, 2, 3),
  "Der Trojaner lebt von der Täuschung: außen nützlich, innen schädlich, und der Nutzer startet ihn selbst. Selbstständige Verbreitung ist das Merkmal des Wurms.",
  "Which characteristics does a trojan have?",
  ("It disguises itself as a useful program",
   "It is started by the user themselves",
   "It carries hidden malicious functions",
   "It can open a backdoor for attackers",
   "It spreads by itself across the network",
   "It only affects server operating systems"),
  "A trojan lives on deception: useful on the outside, harmful inside, and the user starts it themselves. Spreading autonomously is the hallmark of a worm."),

M("ap1-sec-r50",
  "Welche Vorkehrungen schützen den Serverraum vor physischen Gefahren?",
  ("Rauchmelder und Brandfrüherkennung",
   "Klimatisierung mit Temperaturüberwachung",
   "Unterbrechungsfreie Stromversorgung",
   "Wassermelder im Bodenbereich",
   "Ein Getränkeautomat für kurze Wege",
   "Ein Kartonlager für Verpackungsmaterial"),
  (0, 1, 2, 3),
  "Feuer, Hitze, Stromausfall und Wasser sind die klassischen physischen Risiken und brauchen je eigene Melder und Vorkehrungen. Getränke und brennbares Lagergut haben im Serverraum nichts verloren.",
  "Which precautions protect the server room against physical hazards?",
  ("Smoke detectors and early fire detection",
   "Air conditioning with temperature monitoring",
   "Uninterruptible power supply",
   "Water detectors at floor level",
   "A drinks machine to save walking",
   "A cardboard store for packaging material"),
  "Fire, heat, power loss and water are the classic physical risks and each needs its own detector and provision. Drinks and flammable storage have no place in a server room."),

M("ap1-sec-r51",
  "Welche Aussagen zu Berechtigungen auf einem Fileserver sind sinnvoll?",
  ("Rechte werden über Gruppen statt einzeln vergeben",
   "Rechte richten sich nach der Rolle im Unternehmen",
   "Berechtigungen werden regelmäßig überprüft",
   "Beim Austritt werden Konten unverzüglich gesperrt",
   "Jeder erhält vorsichtshalber Vollzugriff",
   "Freigaben werden für alle Netze geöffnet"),
  (0, 1, 2, 3),
  "Gruppen und Rollen halten die Vergabe nachvollziehbar, regelmäßige Prüfung verhindert Altlasten, und gesperrte Konten schließen den offensichtlichsten Weg. Vollzugriff für alle hebt jede Schutzwirkung auf.",
  "Which statements about permissions on a file server make sense?",
  ("Rights are granted via groups rather than individually",
   "Rights follow the person's role in the company",
   "Permissions are reviewed on a regular basis",
   "Accounts are disabled immediately when someone leaves",
   "Everyone gets full access just to be safe",
   "Shares are opened up to all networks"),
  "Groups and roles keep assignment traceable, regular review prevents legacy build-up, and disabled accounts close the most obvious route. Full access for everyone cancels out any protection."),

M("ap1-sec-r52",
  "Welche Angaben sollten in einem Verzeichnis von Verarbeitungstätigkeiten stehen?",
  ("Zweck der Verarbeitung",
   "Kategorien betroffener Personen",
   "Kategorien der verarbeiteten Daten",
   "Vorgesehene Löschfristen",
   "Die Marktanteile der Wettbewerber",
   "Die Farbgestaltung der Firmenwebseite"),
  (0, 1, 2, 3),
  "Das Verzeichnis nach Artikel 30 hält fest, warum welche Daten über wen wie lange verarbeitet werden, ergänzt um Empfänger und Schutzmaßnahmen. Marktdaten und Gestaltungsfragen gehören nicht hinein.",
  "Which details should appear in a record of processing activities?",
  ("Purpose of the processing",
   "Categories of data subjects",
   "Categories of data being processed",
   "Intended erasure periods",
   "The market shares of competitors",
   "The colour scheme of the company website"),
  "The record under Article 30 documents why which data about whom is processed for how long, plus recipients and safeguards. Market data and design questions do not belong in it."),

M("ap1-sec-r53",
  "Welche Aussagen über einen Virenscanner sind zutreffend?",
  ("Er erkennt Schadcode anhand bekannter Signaturen",
   "Er nutzt zusätzlich verhaltensbasierte Erkennung",
   "Er benötigt regelmäßige Aktualisierungen",
   "Er bietet keinen vollständigen Schutz vor neuen Angriffen",
   "Er ersetzt das Einspielen von Sicherheitsupdates",
   "Er macht eine Datensicherung entbehrlich"),
  (0, 1, 2, 3),
  "Signaturen und Verhaltensanalyse ergänzen sich, brauchen aber Aktualität und versagen bei ganz neuen Varianten. Patches und Sicherungen bleiben trotzdem Pflicht - der Scanner ist nur eine Schicht von mehreren.",
  "Which statements about a virus scanner are correct?",
  ("It detects malicious code from known signatures",
   "It additionally uses behaviour-based detection",
   "It requires regular updates to stay effective",
   "It offers no complete protection against new attacks",
   "It replaces the installation of security updates",
   "It makes data backups unnecessary"),
  "Signatures and behavioural analysis complement each other but need to stay current and fail against brand new variants. Patches and backups remain mandatory - the scanner is only one layer among several."),

M("ap1-sec-r54",
  "Welche Gründe sprechen für eine Verschlüsselung mobiler Datenträger?",
  ("Verlust und Diebstahl sind bei mobilen Geräten häufig",
   "Ohne Verschlüsselung ist die Platte woanders lesbar",
   "Die DSGVO verlangt angemessene Schutzmaßnahmen",
   "Eine Meldepflicht kann dadurch entfallen",
   "Verschlüsselung beschleunigt den Zugriff auf Dateien",
   "Verschlüsselung verhindert das Löschen von Daten"),
  (0, 1, 2, 3),
  "Mobile Medien gehen leicht verloren, und unverschlüsselt sind sie an jedem anderen Rechner lesbar. Wirksame Verschlüsselung kann sogar die Meldepflicht entfallen lassen. Schneller oder löschsicher wird dadurch nichts.",
  "Which reasons argue for encrypting mobile storage media?",
  ("Loss and theft are common with mobile devices",
   "Without encryption the drive is readable elsewhere",
   "The GDPR requires appropriate protective measures",
   "A notification duty may be waived as a result",
   "Encryption speeds up access to the files",
   "Encryption prevents data from being deleted"),
  "Mobile media are easily lost, and unencrypted they can be read on any other machine. Effective encryption can even remove the notification duty. Nothing becomes faster or deletion-proof as a result."),

M("ap1-sec-r55",
  "Welche Schritte gehören zur Bearbeitung eines Sicherheitsvorfalls?",
  ("Den Vorfall erkennen und einordnen",
   "Die Ausbreitung eindämmen",
   "Die Ursache beseitigen",
   "Den Regelbetrieb wiederherstellen",
   "Den Vorfall aus den Unterlagen entfernen",
   "Die Zuständigkeit dauerhaft offenlassen"),
  (0, 1, 2, 3),
  "Erkennen, Eindämmen, Beseitigen und Wiederherstellen sind die üblichen Phasen, abgeschlossen durch eine Nachbetrachtung. Vertuschen und ungeklärte Zuständigkeiten verhindern genau diese Lerneffekte.",
  "Which steps belong to handling a security incident?",
  ("Detect and classify the incident",
   "Contain the spread",
   "Eradicate the root cause",
   "Restore normal operation",
   "Remove the incident from the records",
   "Leave responsibility permanently unassigned"),
  "Detection, containment, eradication and recovery are the usual phases, closed off by a review. Covering up and unclear responsibilities prevent exactly those lessons."),

M("ap1-sec-r56",
  "Welche Eigenschaften soll eine kryptografische Hashfunktion erfüllen?",
  ("Aus dem Hash lässt sich die Eingabe nicht ableiten",
   "Gleiche Eingabe ergibt stets denselben Hashwert",
   "Kleine Änderungen ändern den Hash stark",
   "Kollisionen sollen praktisch nicht auffindbar sein",
   "Der Hash lässt sich mit einem Schlüssel entschlüsseln",
   "Die Länge des Hashs wächst mit der Eingabegröße"),
  (0, 1, 2, 3),
  "Einwegcharakter, Determinismus, Lawineneffekt und Kollisionsresistenz sind die geforderten Eigenschaften. Ein Hash lässt sich nicht entschlüsseln, und seine Länge ist unabhängig von der Eingabe fest.",
  "Which properties should a cryptographic hash function fulfil?",
  ("The input cannot be derived from the hash",
   "The same input always yields the same hash",
   "Small changes alter the hash drastically",
   "Collisions should be practically unfindable",
   "The hash can be decrypted with a key",
   "The hash length grows with the input size"),
  "One-way behaviour, determinism, the avalanche effect and collision resistance are the required properties. A hash cannot be decrypted, and its length is fixed regardless of the input."),

M("ap1-sec-r57",
  "Welche Risiken entstehen durch veraltete Software im Betrieb?",
  ("Bekannte Schwachstellen bleiben ausnutzbar",
   "Sicherheitsupdates werden nicht mehr bereitgestellt",
   "Nachweispflichten lassen sich schwerer erfüllen",
   "Kompatibilität mit neuen Systemen geht verloren",
   "Der Stromverbrauch der Server steigt deutlich",
   "Die Bildschirmauflösung verringert sich automatisch"),
  (0, 1, 2, 3),
  "Ohne Herstellerunterstützung bleiben Lücken offen, und im Schadensfall wird die Sorgfaltspflicht schwer belegbar. Stromverbrauch und Bildschirmauflösung hängen nicht am Softwarestand.",
  "Which risks arise from outdated software in operation?",
  ("Known vulnerabilities remain exploitable",
   "Security updates are no longer supplied",
   "Compliance obligations get harder to meet",
   "Compatibility with new systems is lost",
   "The power consumption of servers rises sharply",
   "The screen resolution decreases automatically"),
  "Without vendor support the gaps stay open, and in an incident due diligence becomes hard to prove. Power consumption and screen resolution do not depend on the software version."),

M("ap1-sec-r58",
  "Welche Maßnahmen erschweren einen Brute-Force-Angriff auf ein Anmeldeformular?",
  ("Sperren des Kontos nach mehreren Fehlversuchen",
   "Verzögerung zwischen den Anmeldeversuchen",
   "Erzwingen ausreichend langer Passwörter",
   "Ein zusätzlicher zweiter Faktor",
   "Ein Hinweis auf der Seite, es nicht zu versuchen",
   "Verkürzung der erlaubten Passwortlänge"),
  (0, 1, 2, 3),
  "Sperren und Verzögerungen senken die Versuchsrate, Länge und zweiter Faktor vergrößern den Suchraum. Appelle wirken auf Angreifer nicht, und kürzere Passwörter erleichtern den Angriff.",
  "Which measures make a brute force attack on a login form harder?",
  ("Locking the account after several failed attempts",
   "Delay between successive login attempts",
   "Enforcing sufficiently long passwords",
   "An additional second factor",
   "A note on the page asking not to try",
   "Shortening the permitted password length"),
  "Lockouts and delays cut the attempt rate, while length and a second factor enlarge the search space. Appeals do not affect attackers, and shorter passwords make the attack easier."),

M("ap1-sec-r59",
  "Welche Aussagen über ein VPN sind korrekt?",
  ("Es baut einen verschlüsselten Tunnel auf",
   "Es ermöglicht den Zugriff auf interne Ressourcen",
   "Es schützt Daten in fremden Netzen vor Mitlesen",
   "Es authentisiert die Gegenstelle vor dem Aufbau",
   "Es beschleunigt die Internetverbindung spürbar",
   "Es macht einen Virenschutz auf dem Gerät überflüssig"),
  (0, 1, 2, 3),
  "Der Tunnel verschlüsselt und authentisiert und macht interne Dienste erreichbar - besonders wertvoll in fremden WLANs. Schneller wird die Leitung dadurch nicht, und Schadsoftware auf dem Gerät hält das VPN nicht auf.",
  "Which statements about a VPN are correct?",
  ("It establishes an encrypted tunnel",
   "It enables access to internal resources",
   "It protects data in foreign networks from eavesdropping",
   "It authenticates the remote end before connecting",
   "It noticeably speeds up the internet connection",
   "It makes antivirus on the device unnecessary"),
  "The tunnel encrypts and authenticates and makes internal services reachable - especially valuable on foreign Wi-Fi. The line does not get faster, and a VPN does not stop malware on the device."),

M("ap1-sec-r60",
  "Wodurch kann die Verfügbarkeit eines Servers beeinträchtigt werden?",
  ("Ein Ausfall der Stromversorgung",
   "Ein Defekt an einer Festplatte",
   "Eine Überlastung durch massenhafte Anfragen",
   "Ein fehlgeschlagenes Update ohne Rückweg",
   "Eine zu kurze Passwortlänge der Nutzer",
   "Ein veralteter Firmenname im Impressum"),
  (0, 1, 2, 3),
  "Strom, Hardware, Überlast und fehlerhafte Änderungen sind die typischen Verfügbarkeitsrisiken, denen man mit Redundanz und Rückwegen begegnet. Passwortlänge betrifft die Vertraulichkeit, das Impressum gar nichts davon.",
  "What can impair the availability of a server?",
  ("A failure of the power supply",
   "A defect in one of the hard disks",
   "Overload from masses of requests",
   "A failed update with no way back",
   "Too short a password length among users",
   "An outdated company name in the imprint"),
  "Power, hardware, overload and faulty changes are the typical availability risks, countered with redundancy and rollback paths. Password length concerns confidentiality, the imprint none of it."),

M("ap1-sec-r61",
  "Welche Aussagen zum Umgang mit Beschäftigtendaten sind richtig?",
  ("Der Zugriff wird auf die Personalabteilung begrenzt",
   "Die Erhebung bleibt auf das Erforderliche beschränkt",
   "Unterlagen werden nach Fristablauf gelöscht",
   "Der Betriebsrat ist bei Überwachungsfragen zu beteiligen",
   "Die Daten stehen allen Führungskräften offen",
   "Bewerbungen werden dauerhaft zur Auswahl aufbewahrt"),
  (0, 1, 2, 3),
  "Enge Zugriffskreise, Datenminimierung, Löschfristen und Mitbestimmung sind die Leitplanken. Offener Zugriff für alle Führungskräfte und unbefristete Aufbewahrung von Bewerbungen verstoßen dagegen.",
  "Which statements about handling employee data are correct?",
  ("Access is limited to the HR department",
   "Collection stays limited to what is necessary",
   "Records are deleted once retention periods expire",
   "The works council is involved in monitoring questions",
   "The data is open to all managers",
   "Applications are kept indefinitely for future selection"),
  "Narrow access circles, data minimisation, retention periods and codetermination are the guardrails. Open access for all managers and indefinite retention of applications violate them."),

M("ap1-sec-r62",
  "Welche Inhalte gehören in eine Sensibilisierungsschulung für Beschäftigte?",
  ("Erkennen von Phishing-Mails",
   "Sicherer Umgang mit Passwörtern",
   "Meldewege bei einem Verdacht",
   "Umgang mit Daten außerhalb des Büros",
   "Bedienung der Telefonanlage im Detail",
   "Grundlagen der doppelten Buchführung"),
  (0, 1, 2, 3),
  "Schulungen müssen die alltäglichen Entscheidungssituationen abdecken, in denen Beschäftigte selbst zur letzten Schutzschicht werden. Telefonanlage und Buchführung sind fachlich wichtig, aber kein Sicherheitsthema.",
  "Which content belongs in a security awareness training for employees?",
  ("Recognising phishing emails",
   "Safe handling of passwords",
   "Reporting paths when something looks suspicious",
   "Handling data outside the office",
   "Detailed operation of the phone system",
   "Fundamentals of double-entry bookkeeping"),
  "Training must cover the everyday decision situations in which employees themselves become the last layer of protection. Phone systems and bookkeeping matter professionally but are not security topics."),

M("ap1-sec-r63",
  "Welche Aussagen zur Zwei-Faktor-Authentisierung per SMS sind zutreffend?",
  ("Sie ist besser als ein Passwort allein",
   "Sie gilt als schwächer als eine Authenticator-App",
   "SMS können bei einem SIM-Tausch umgeleitet werden",
   "Der Empfang setzt Mobilfunknetz voraus",
   "SMS-Codes sind grundsätzlich unknackbar",
   "Sie ersetzt die Notwendigkeit eines Passworts"),
  (0, 1, 2, 3),
  "Ein zweiter Faktor per SMS erhöht die Hürde spürbar, hat aber bekannte Schwächen wie SIM-Swapping und Netzabhängigkeit. Er ergänzt das Passwort, ersetzt es aber nicht.",
  "Which statements about SMS-based two-factor authentication are correct?",
  ("It is better than a password on its own",
   "It is considered weaker than an authenticator app",
   "SMS can be redirected through a SIM swap",
   "Receiving requires mobile network coverage",
   "SMS codes are fundamentally unbreakable",
   "It removes the need for a password"),
  "A second factor by SMS raises the bar noticeably but has known weaknesses such as SIM swapping and network dependency. It complements the password rather than replacing it."),

M("ap1-sec-r64",
  "Welche Vorgaben gelten für die Aufbewahrung und Löschung von Daten?",
  ("Gesetzliche Aufbewahrungsfristen sind einzuhalten",
   "Nach Fristablauf sind Daten zu löschen",
   "Löschkonzepte legen Fristen je Datenart fest",
   "Auch Sicherungen müssen in das Konzept einbezogen werden",
   "Daten werden sicherheitshalber unbegrenzt aufbewahrt",
   "Löschungen dürfen nicht dokumentiert werden"),
  (0, 1, 2, 3),
  "Aufbewahren und Löschen sind zwei Seiten derselben Pflicht: erst so lange wie nötig, dann konsequent weg - inklusive der Sicherungen. Unbegrenztes Aufbewahren widerspricht der Speicherbegrenzung.",
  "Which requirements apply to retaining and deleting data?",
  ("Statutory retention periods must be observed",
   "Data must be deleted once the period expires",
   "Deletion concepts set periods per data type",
   "Backups must be included in the concept",
   "Data is kept indefinitely just to be safe",
   "Deletions must not be documented"),
  "Retention and deletion are two sides of the same duty: keep only as long as needed, then remove consistently - backups included. Indefinite retention contradicts storage limitation."),

# ------------------------------------------------------------------ text (36)
T("ap1-sec-r65", "Wie viele Stunden hat ein Unternehmen Zeit, eine Datenpanne der Aufsichtsbehörde zu melden?", "72",
  "Artikel 33 DSGVO nennt 72 Stunden ab Kenntnis der Verletzung. Eine spätere Meldung muss begründet werden.",
  "How many hours does a company have to report a data breach to the supervisory authority?", "72",
  "Article 33 GDPR states 72 hours from becoming aware of the breach. A later notification must be justified."),

T("ap1-sec-r66", "Welches Schutzziel ist verletzt, wenn Unbefugte vertrauliche Daten mitlesen?", "Vertraulichkeit",
  "Vertraulichkeit bedeutet, dass nur Befugte Zugriff auf Informationen haben. Verschlüsselung und Berechtigungen sichern sie ab.",
  "Which security objective is violated when unauthorised people read confidential data?", "Confidentiality",
  "Confidentiality means only authorised people have access to information. Encryption and permissions safeguard it."),

T("ap1-sec-r67", "Wie nennt man Schadsoftware, die Daten verschlüsselt und Lösegeld fordert?", "Ransomware",
  "Ransomware verschlüsselt Dateien und erpresst ein Lösegeld. Eine getrennt gelagerte Sicherung ist der wirksamste Schutz.",
  "What is malware that encrypts data and demands a ransom called?", "Ransomware",
  "Ransomware encrypts files and extorts a ransom. A separately stored backup is the most effective protection."),

T("ap1-sec-r68", "Wie viele Kopien verlangt die 3-2-1-Regel insgesamt?", "3",
  "Drei Kopien auf zwei unterschiedlichen Medientypen, davon eine an einem anderen Ort.",
  "How many copies does the 3-2-1 rule require in total?", "3",
  "Three copies on two different media types, one of them at a different location."),

T("ap1-sec-r69", "Mit wessen Schlüssel wird bei asymmetrischer Verschlüsselung eine Nachricht für einen Empfänger verschlüsselt?", "Mit dem öffentlichen Schlüssel des Empfängers",
  "Nur der Empfänger besitzt den passenden privaten Schlüssel und kann die Nachricht damit wieder lesbar machen.",
  "Whose key encrypts a message for a recipient in asymmetric encryption?", "The recipient's public key",
  "Only the recipient holds the matching private key and can therefore make the message readable again."),

T("ap1-sec-r70", "Wie heißt das Prinzip, nach dem jeder nur die nötigsten Rechte erhält?", "Least Privilege",
  "Auf Deutsch das Prinzip der minimalen Rechtevergabe. Es begrenzt den Schaden bei Fehlern und übernommenen Konten.",
  "What is the principle that everyone receives only the most necessary rights called?", "Least privilege",
  "It limits the damage caused by mistakes and compromised accounts."),

T("ap1-sec-r71", "Wie nennt man den Angriff, bei dem sich jemand als vertrauenswürdige Person ausgibt, um an Daten zu kommen?", "Social Engineering",
  "Social Engineering zielt auf den Menschen statt auf die Technik und arbeitet mit Autorität, Hilfsbereitschaft und Zeitdruck.",
  "What is the attack in which someone poses as a trustworthy person to obtain data called?", "Social engineering",
  "Social engineering targets people rather than technology and works with authority, helpfulness and time pressure."),

T("ap1-sec-r72", "Welche Art von Funktion ist eine Hashfunktion, weil sie sich nicht umkehren lässt?", "Einwegfunktion",
  "Aus dem Ergebnis lässt sich die Eingabe praktisch nicht zurückrechnen, weshalb Passwörter als Hash gespeichert werden.",
  "What kind of function is a hash function, given that it cannot be reversed?", "One-way function",
  "The input practically cannot be computed back from the result, which is why passwords are stored as hashes."),

T("ap1-sec-r73", "Wie heißt die Schadsoftware, die sich als nützliches Programm tarnt?", "Trojaner",
  "Der Nutzer startet ihn selbst, weil er nützlich wirkt; im Hintergrund läuft die Schadfunktion mit.",
  "What is malware that disguises itself as a useful program called?", "Trojan",
  "The user starts it themselves because it looks useful; the malicious function runs in the background."),

T("ap1-sec-r74", "Welches Verfahren verlangt neben dem Passwort einen weiteren Nachweis der Identität?", "Zwei-Faktor-Authentisierung",
  "Der zweite Faktor stammt aus einer anderen Kategorie, etwa Besitz oder Biometrie, und entwertet ein gestohlenes Passwort.",
  "Which method requires a further proof of identity in addition to the password?", "Two-factor authentication",
  "The second factor comes from a different category, such as possession or biometrics, devaluing a stolen password."),

T("ap1-sec-r75", "Wie nennt man eine Sicherung, die alle Änderungen seit der letzten Vollsicherung enthält?", "Differenzielle Sicherung",
  "Zum Zurückspielen braucht man die Vollsicherung und genau eine differenzielle Sicherung.",
  "What is a backup containing all changes since the last full backup called?", "Differential backup",
  "To restore, you need the full backup plus exactly one differential backup."),

T("ap1-sec-r76", "Wie nennt man eine Sicherung, die nur Änderungen seit der letzten Sicherung enthält?", "Inkrementelle Sicherung",
  "Sie sichert am schnellsten, verlangt beim Zurückspielen aber die gesamte Kette seit der Vollsicherung.",
  "What is a backup containing only changes since the last backup called?", "Incremental backup",
  "It backs up fastest but requires the entire chain since the full backup when restoring."),

T("ap1-sec-r77", "Welcher Artikel der DSGVO regelt den Vertrag zur Auftragsverarbeitung?", "Artikel 28",
  "Er verpflichtet den Auftragsverarbeiter auf Weisungsbindung, Schutzmaßnahmen und Löschung nach Auftragsende.",
  "Which GDPR article governs the data processing agreement?", "Article 28",
  "It binds the processor to act on instruction, apply safeguards and delete data when the contract ends."),

T("ap1-sec-r78", "Wie nennt man den Angriff, bei dem sich jemand unbemerkt in eine Verbindung einklinkt?", "Man-in-the-Middle",
  "Der Angreifer sitzt zwischen den Partnern und kann mitlesen oder verändern. Zertifikatsprüfung und Verschlüsselung wirken dagegen.",
  "What is the attack in which someone silently interposes in a connection called?", "Man-in-the-middle",
  "The attacker sits between the partners and can read or alter traffic. Certificate checking and encryption counter it."),

T("ap1-sec-r79", "Welches Schutzziel beschreibt, dass ein System nutzbar ist, wenn es gebraucht wird?", "Verfügbarkeit",
  "Redundanz, Wartungskonzepte und eine USV sind die üblichen Mittel, um sie abzusichern.",
  "Which objective describes a system being usable when it is needed?", "Availability",
  "Redundancy, maintenance concepts and a UPS are the usual means of safeguarding it."),

T("ap1-sec-r80", "Wofür steht die Abkürzung DSGVO?", "Datenschutz-Grundverordnung",
  "Sie gilt seit Mai 2018 europaweit einheitlich für die Verarbeitung personenbezogener Daten.",
  "What does the abbreviation GDPR stand for?", "General Data Protection Regulation",
  "It has applied uniformly across Europe since May 2018 for the processing of personal data."),

T("ap1-sec-r81", "Wie nennt man Schadsoftware, die sich selbstständig über Netzwerke verbreitet?", "Wurm",
  "Anders als ein Virus braucht der Wurm keine Wirtsdatei und nutzt Schwachstellen in Netzdiensten.",
  "What is malware that spreads by itself across networks called?", "Worm",
  "Unlike a virus, a worm needs no host file and exploits vulnerabilities in network services."),

T("ap1-sec-r82", "Welches Gerät hält bei einem Stromausfall den Serverbetrieb kurzzeitig aufrecht?", "USV",
  "Die unterbrechungsfreie Stromversorgung überbrückt die Lücke und ermöglicht ein geordnetes Herunterfahren.",
  "Which device keeps servers running briefly during a power failure?", "UPS",
  "The uninterruptible power supply bridges the gap and enables an orderly shutdown."),

T("ap1-sec-r83", "Wie heißt der Angriff, der einen Dienst durch Überlastung unerreichbar macht?", "Denial of Service",
  "Verteilt ausgeführt spricht man von DDoS. Die Daten bleiben unverändert, nur die Verfügbarkeit leidet.",
  "What is the attack that makes a service unreachable through overload called?", "Denial of service",
  "Carried out in a distributed way it is called DDoS. The data stays intact, only availability suffers."),

T("ap1-sec-r84", "Welches Verschlüsselungsverfahren nutzt für Ver- und Entschlüsselung denselben Schlüssel?", "Symmetrische Verschlüsselung",
  "Sie ist schnell, verlangt aber einen sicheren Schlüsselaustausch. AES ist der bekannteste Vertreter.",
  "Which encryption method uses the same key to encrypt and decrypt?", "Symmetric encryption",
  "It is fast but requires secure key exchange. AES is the best-known representative."),

T("ap1-sec-r85", "Welcher Grundsatz verlangt, nur so viele Daten zu erheben wie nötig?", "Datenminimierung",
  "Was nicht erhoben wird, kann auch nicht abfließen oder missbraucht werden - der Grundsatz steht in Artikel 5 DSGVO.",
  "What is the principle of collecting only as much data as necessary called?", "Data minimisation",
  "What is never collected cannot leak or be misused - the principle appears in Article 5 GDPR."),

T("ap1-sec-r86", "Welches Dokument nach Artikel 30 DSGVO listet alle Verarbeitungstätigkeiten eines Unternehmens?", "Verarbeitungsverzeichnis",
  "Es hält Zwecke, Datenkategorien, Empfänger und Löschfristen fest und ist auf Verlangen vorzulegen.",
  "Which document under Article 30 GDPR lists all processing activities of a company?", "Record of processing activities",
  "It documents purposes, data categories, recipients and erasure periods and must be produced on request."),

T("ap1-sec-r87", "Wie heißt die Stelle, die digitale Zertifikate ausstellt und beglaubigt?", "Zertifizierungsstelle",
  "Sie bestätigt mit ihrer Signatur, dass ein öffentlicher Schlüssel wirklich zu der genannten Identität gehört.",
  "What is the body that issues and certifies digital certificates called?", "Certification authority",
  "Its signature confirms that a public key really belongs to the stated identity."),

T("ap1-sec-r88", "Wie nennt man das gezielte Phishing auf eine einzelne, gut recherchierte Person?", "Spear Phishing",
  "Durch persönliche Details wirkt die Nachricht glaubwürdig, was die Erfolgsquote deutlich erhöht.",
  "What is phishing aimed at a single, well-researched individual called?", "Spear phishing",
  "Personal details make the message credible, which raises the success rate considerably."),

T("ap1-sec-r89", "Welche Mindestlänge gilt heute als Untergrenze für ein sicheres Passwort, in Zeichen?", "12",
  "Länge wirkt stärker als Sonderzeichen, weil sie den Suchraum exponentiell vergrößert.",
  "Which minimum length is considered the lower bound for a secure password today, in characters?", "12",
  "Length matters more than special characters because it grows the search space exponentially."),

T("ap1-sec-r90", "Welcher Fachbegriff beschreibt den Blick über die Schulter beim Eintippen eines Passworts?", "Shoulder Surfing",
  "Sichtschutzfolien und eine durchdachte Aufstellung der Bildschirme wirken dagegen.",
  "What is unauthorised watching over the shoulder while a password is typed called?", "Shoulder surfing",
  "Privacy filters and thoughtful screen placement counter it."),

T("ap1-sec-r91", "Welches Bundesamt gibt in Deutschland den IT-Grundschutz heraus?", "BSI",
  "Das Bundesamt für Sicherheit in der Informationstechnik stellt Standards und Bausteine für den Grundschutz bereit.",
  "Which federal office publishes the IT baseline protection standard in Germany?", "BSI",
  "The Federal Office for Information Security provides standards and building blocks for baseline protection."),

T("ap1-sec-r92", "Wie heißt das Verfahren, mit dem ein Absender die Echtheit eines Dokuments nachweist?", "Digitale Signatur",
  "Signiert wird mit dem privaten Schlüssel, geprüft mit dem öffentlichen - das sichert Authentizität und Integrität.",
  "What is the method by which a sender proves a document's authenticity called?", "Digital signature",
  "Signing uses the private key and verification the public one - securing authenticity and integrity."),

T("ap1-sec-r93", "Wie nennt man eine Sicherung, die sämtliche ausgewählten Daten vollständig kopiert?", "Vollsicherung",
  "Sie dauert am längsten, lässt sich dafür aber ohne weitere Sicherungen zurückspielen.",
  "What is a backup that copies all selected data completely called?", "Full backup",
  "It takes longest but can be restored without needing any further backups."),

T("ap1-sec-r94", "Welche Art von Schlüssel darf man gefahrlos veröffentlichen?", "Den öffentlichen Schlüssel",
  "Er dient anderen zum Verschlüsseln und zum Prüfen von Signaturen. Der private Schlüssel bleibt immer geheim.",
  "Which kind of key can be published without risk?", "The public key",
  "Others use it to encrypt and to verify signatures. The private key always stays secret."),

T("ap1-sec-r95", "Welcher Begriff beschreibt das Ansammeln immer weiterer Rechte über die Jahre?", "Rechteanhäufung",
  "Auf Englisch Privilege Creep. Regelmäßige Rechteüberprüfungen bei Rollenwechseln verhindern sie.",
  "What is the state of a user accumulating ever more rights over the years called?", "Privilege creep",
  "Regular permission reviews when roles change prevent it."),

T("ap1-sec-r96", "Welche Maßnahme macht eine gestohlene Notebook-Festplatte für den Dieb unlesbar?", "Festplattenverschlüsselung",
  "Ohne den Schlüssel ist der Inhalt auch beim Ausbau der Platte wertlos - ein Anmeldekennwort allein reicht dafür nicht.",
  "Which measure makes a stolen laptop hard disk unreadable for the thief?", "Full disk encryption",
  "Without the key the content is worthless even if the drive is removed - a login password alone is not enough."),

T("ap1-sec-r97", "Wie nennt man eine bislang unbekannte Schwachstelle, für die es noch keinen Patch gibt?", "Zero-Day",
  "Der Hersteller hatte null Tage Zeit zu reagieren. Solche Lücken sind besonders gefährlich, weil Signaturen fehlen.",
  "What is a previously unknown vulnerability without a patch called?", "Zero-day",
  "The vendor had zero days to react. Such gaps are especially dangerous because signatures are missing."),

T("ap1-sec-r98", "Welches Schutzziel stellt sicher, dass eine Handlung später nicht abgestritten werden kann?", "Verbindlichkeit",
  "Auch Nichtabstreitbarkeit genannt und meist durch digitale Signaturen und Protokolle umgesetzt.",
  "Which objective ensures an action cannot later be denied?", "Non-repudiation",
  "Usually implemented through digital signatures and logging."),

T("ap1-sec-r99", "Wie nennt man das unbefugte Mitgehen durch eine gesicherte Tür hinter einer berechtigten Person?", "Tailgating",
  "Vereinzelungsanlagen und geschultes Personal, das freundlich nachfragt, sind die wirksamsten Gegenmittel.",
  "What is unauthorised following through a secured door behind an authorised person called?", "Tailgating",
  "Turnstiles and trained staff who politely challenge visitors are the most effective countermeasures."),

T("ap1-sec-r100", "Welche Betriebsart sollte ein Administrator für alltägliche Büroarbeit nutzen?", "Ein normales Benutzerkonto",
  "Alles in der Sitzung Gestartete erbt deren Rechte - deshalb gehört das Administratorkonto nur an die Administration.",
  "Which kind of account should an administrator use for everyday office work?", "A normal user account",
  "Everything started in the session inherits its rights - so the administrator account belongs to administration only."),
]

build("ap1-it-sicherheit.json", "IT-Sicherheit & Datenschutz", "IT Security & Data Protection", Q)
