#!/usr/bin/env python3
"""AP2 Serverdienste & Virtualisierung - 100 handgeschriebene Fragen."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from qlib import S, M, T, build

Q = [
# ---------------------------------------------------------------- single (32)
S("ap2-srv-r01",
  "Welcher Hypervisor läuft direkt auf der Hardware ohne darunterliegendes Betriebssystem?",
  ("Ein Typ-1-Hypervisor", "Ein Typ-2-Hypervisor",
   "Ein Container-Laufzeitsystem", "Ein Terminalserverdienst"), 0,
  "Typ 1 setzt unmittelbar auf der Hardware auf und erreicht dadurch bessere Leistung und Isolation. Typ 2 läuft als Anwendung auf einem vorhandenen Betriebssystem und eignet sich eher für Arbeitsplätze.",
  "Which hypervisor runs directly on the hardware without an underlying operating system?",
  ("A type 1 hypervisor", "A type 2 hypervisor",
   "A container runtime", "A terminal server service"),
  "Type 1 sits directly on the hardware and therefore achieves better performance and isolation. Type 2 runs as an application on an existing operating system and suits workstations."),

S("ap2-srv-r02",
  "Ein Server soll gewartet werden, ohne dass die Anwendung ausfällt. Welche Funktion nutzt du?",
  ("Live Migration der virtuellen Maschinen",
   "Einen Snapshot der virtuellen Maschine",
   "Eine Vollsicherung des gesamten Hosts",
   "Eine Erhöhung des zugewiesenen Arbeitsspeichers"), 0,
  "Bei der Live Migration wandert die laufende VM auf einen anderen Host, ohne dass Verbindungen abreißen. Ein Snapshot friert nur einen Zustand ein und ersetzt keine Wartungsstrategie.",
  "A server needs maintenance without the application going down. Which feature do you use?",
  ("Live migration of the virtual machines",
   "A snapshot of the virtual machine",
   "A full backup of the entire host",
   "An increase of the assigned memory"),
  "In live migration the running VM moves to another host without connections dropping. A snapshot only freezes a state and replaces no maintenance strategy."),

S("ap2-srv-r03",
  "Was unterscheidet einen Container von einer virtuellen Maschine?",
  ("Der Container teilt sich den Kernel des Wirtssystems",
   "Der Container bringt ein vollständiges Betriebssystem mit",
   "Der Container benötigt zwingend eigene Hardware",
   "Der Container lässt sich nicht aus einem Abbild starten"), 0,
  "Container virtualisieren nur die Anwendungsumgebung und nutzen den Kernel des Hosts mit. Dadurch starten sie in Sekunden und brauchen deutlich weniger Ressourcen als eine vollständige VM.",
  "What distinguishes a container from a virtual machine?",
  ("The container shares the host system's kernel",
   "The container brings a complete operating system",
   "The container strictly requires its own hardware",
   "The container cannot be started from an image"),
  "Containers virtualise only the application environment and share the host's kernel. That lets them start in seconds and use far fewer resources than a full VM."),

S("ap2-srv-r04",
  "Ein Anbieter stellt virtuelle Server bereit, das Betriebssystem verwaltet der Kunde selbst. Welches Modell ist das?",
  ("IaaS", "PaaS", "SaaS", "On-Premises"), 0,
  "Bei Infrastructure as a Service liefert der Anbieter Rechenleistung, Speicher und Netz, alles darüber liegt beim Kunden. PaaS stellt die Plattform bereit, SaaS die fertige Anwendung.",
  "A provider supplies virtual servers while the customer manages the operating system. Which model is that?",
  ("IaaS", "PaaS", "SaaS", "On-premises"),
  "With infrastructure as a service the provider supplies compute, storage and network, and everything above is the customer's. PaaS provides the platform, SaaS the finished application."),

S("ap2-srv-r05",
  "Welche Aufgabe hat ein Snapshot einer virtuellen Maschine?",
  ("Er friert einen Zustand für eine kurzfristige Rückkehr ein",
   "Er ersetzt die regelmäßige Datensicherung der VM",
   "Er verdoppelt die der Maschine zugewiesene Rechenleistung dauerhaft",
   "Er verteilt die VM automatisch auf mehrere Hosts"), 0,
  "Snapshots sind für kurze Zeiträume gedacht, etwa vor einem Update. Bleiben sie lange bestehen, wachsen die Differenzdateien und bremsen die VM spürbar aus.",
  "What is the purpose of a snapshot of a virtual machine?",
  ("It freezes a state for a short-term return",
   "It replaces the regular backup of the VM",
   "It permanently doubles the compute power assigned to the machine",
   "It automatically spreads the VM across several hosts"),
  "Snapshots are meant for short periods, for example before an update. If they persist, the delta files grow and noticeably slow the VM down."),

S("ap2-srv-r06",
  "Welcher Dienst löst in einer Windows-Domäne Benutzeranmeldungen und Gruppenzugehörigkeiten auf?",
  ("Das Verzeichnisdienst-Verzeichnis der Domäne",
   "Der DHCP-Dienst des Standortservers",
   "Der Druckserverdienst der Abteilung",
   "Der Dateiserverdienst der Fachbereiche"), 0,
  "Der Verzeichnisdienst verwaltet Konten, Gruppen und Richtlinien zentral. DHCP, Druck- und Dateidienste erfüllen ganz andere Aufgaben.",
  "Which service resolves user logins and group memberships in a Windows domain?",
  ("The domain's directory service",
   "The DHCP service of the site server",
   "The print server service of the department",
   "The file server service of the divisions"),
  "The directory service manages accounts, groups and policies centrally. DHCP, print and file services serve entirely different purposes."),

S("ap2-srv-r07",
  "Einstellungen sollen für alle Rechner einer Abteilung zentral vorgegeben werden. Was nutzt du?",
  ("Eine Gruppenrichtlinie auf der passenden Organisationseinheit",
   "Ein Anmeldeskript, das jeder Nutzer selbst starten muss",
   "Eine Notiz mit Anweisungen im Intranet",
   "Eine Änderung direkt an jedem einzelnen Rechner"), 0,
  "Gruppenrichtlinien wirken auf Organisationseinheiten und setzen Einstellungen bei jeder Anmeldung durch. Handarbeit an jedem Gerät skaliert nicht und driftet mit der Zeit auseinander.",
  "Settings must be applied centrally to all computers of a department. What do you use?",
  ("A group policy on the matching organisational unit",
   "A logon script that every user has to start themselves",
   "A note with instructions on the intranet",
   "A change made directly on every single machine"),
  "Group policies apply to organisational units and enforce settings at every login. Manual work on each device does not scale and drifts apart over time."),

S("ap2-srv-r08",
  "Zwei Server übernehmen wechselseitig füreinander bei einem Ausfall. Wie nennt man diesen Verbund?",
  ("Failovercluster", "Loadbalancer", "Terminalserver", "Proxyserver"), 0,
  "Im Failovercluster überwachen sich die Knoten gegenseitig und übernehmen den Dienst bei einem Ausfall. Ein Loadbalancer verteilt Last, garantiert aber allein noch keine Übernahme.",
  "Two servers mutually take over for each other on failure. What is this arrangement called?",
  ("Failover cluster", "Load balancer", "Terminal server", "Proxy server"),
  "In a failover cluster the nodes monitor each other and take over the service on failure. A load balancer spreads load but does not by itself guarantee takeover."),

S("ap2-srv-r09",
  "Ein Host hat 64 GB RAM, die zugewiesenen VMs zusammen 96 GB. Wie heißt dieses Vorgehen?",
  ("Overcommitment der Ressourcen",
   "Live Migration der Maschinen",
   "Thin Provisioning der Datenträger",
   "Clustering der beteiligten Hosts"), 0,
  "Beim Overcommitment wird mehr zugewiesen als physisch vorhanden ist, weil selten alle VMs gleichzeitig alles brauchen. Wird es doch eng, beginnt der Host auszulagern und alles wird langsam.",
  "A host has 64 GB of RAM while the assigned VMs total 96 GB. What is this practice called?",
  ("Overcommitment of resources",
   "Live migration of the machines",
   "Thin provisioning of the disks",
   "Clustering of the hosts involved"),
  "With overcommitment more is assigned than physically exists, because rarely do all VMs need everything at once. If it does get tight, the host starts paging and everything slows down."),

S("ap2-srv-r10",
  "Welcher Dienst sorgt dafür, dass alle Server dieselbe Uhrzeit verwenden?",
  ("NTP", "SNMP", "SMTP", "LDAP"), 0,
  "NTP synchronisiert die Uhren im Netz. Ohne gleiche Zeit lassen sich Protokolle mehrerer Systeme nicht zusammenführen, und Zertifikatsprüfungen schlagen fehl.",
  "Which service ensures all servers use the same time?",
  ("NTP", "SNMP", "SMTP", "LDAP"),
  "NTP synchronises the clocks in a network. Without a common time, logs from several systems cannot be correlated and certificate checks fail."),

S("ap2-srv-r11",
  "Ein Dienst soll bei wachsender Last automatisch zusätzliche Instanzen erhalten. Wie nennt man das?",
  ("Horizontale Skalierung", "Vertikale Skalierung",
   "Statische Provisionierung", "Manuelle Konsolidierung"), 0,
  "Horizontal bedeutet mehr Instanzen nebeneinander, vertikal mehr Ressourcen für dieselbe Instanz. Horizontal skaliert weiter, verlangt aber eine dafür ausgelegte Anwendung.",
  "A service should automatically receive additional instances as load grows. What is this called?",
  ("Horizontal scaling", "Vertical scaling",
   "Static provisioning", "Manual consolidation"),
  "Horizontal means more instances side by side, vertical more resources for the same instance. Horizontal scales further but requires an application designed for it."),

S("ap2-srv-r12",
  "Welche Aussage über ein Container-Image trifft zu?",
  ("Es ist die unveränderliche Vorlage für laufende Container",
   "Es ist der laufende Prozess mit seinen Daten",
   "Es enthält immer einen vollständigen Betriebssystemkern",
   "Es lässt sich nur einmal auf einem Host starten"), 0,
  "Aus einem Image lassen sich beliebig viele Container starten, die alle vom selben unveränderlichen Stand ausgehen. Genau das macht Auslieferungen reproduzierbar.",
  "Which statement about a container image is correct?",
  ("It is the immutable template for running containers",
   "It is the running process together with its data",
   "It always contains a complete operating system kernel",
   "It can be started only once per host"),
  "Any number of containers can be started from one image, all beginning from the same immutable state. That is exactly what makes deployments reproducible."),

S("ap2-srv-r13",
  "Ein einzelner Switch verbindet alle Server ohne Ersatzweg. Wie bezeichnet man diese Stelle?",
  ("Als Single Point of Failure",
   "Als Failoverpartner des Clusters",
   "Als Lastverteiler des Serverraums",
   "Als redundanter Netzknoten"), 0,
  "Ein SPOF ist eine Stelle, deren Ausfall das Gesamtsystem lahmlegt. Beseitigt wird er durch Redundanz auf Geräte-, Leitungs- und Stromebene.",
  "A single switch connects all servers with no alternative path. What is this point called?",
  ("A single point of failure",
   "A failover partner of the cluster",
   "A load distributor of the server room",
   "A redundant network node"),
  "A SPOF is a point whose failure paralyses the whole system. It is removed through redundancy at device, link and power level."),

S("ap2-srv-r14",
  "Welche Aufgabe erfüllt ein Terminalserver?",
  ("Er stellt Anwendungen zentral für viele Sitzungen bereit",
   "Er verteilt IP-Adressen an die angeschlossenen Clients",
   "Er speichert die Sicherungen aller Arbeitsplatzrechner",
   "Er übersetzt Namen in Adressen für das gesamte Netz"), 0,
  "Auf dem Terminalserver laufen die Anwendungen, die Clients übertragen nur Bildschirm und Eingaben. Das vereinfacht Pflege und Lizenzierung erheblich.",
  "What is the purpose of a terminal server?",
  ("It provides applications centrally for many sessions",
   "It distributes IP addresses to the connected clients",
   "It stores the backups of all workstation PCs",
   "It translates names into addresses for the whole network"),
  "The applications run on the terminal server while clients only transfer screen and input. That greatly simplifies maintenance and licensing."),

S("ap2-srv-r15",
  "Ein Webserver ist über den Namen erreichbar, meldet aber ein Zertifikatsproblem. Was prüfst du zuerst?",
  ("Gültigkeit und Namensübereinstimmung des Zertifikats",
   "Die verbleibende Größe der Festplatte des Webservers",
   "Die Anzahl der VLANs auf dem Zugangsswitch",
   "Die Leasedauer des DHCP-Bereichs im Netz"), 0,
  "Fast immer ist entweder das Zertifikat abgelaufen oder der aufgerufene Name steht nicht darin. Speicherplatz, VLANs und DHCP haben mit der Zertifikatsprüfung nichts zu tun.",
  "A web server is reachable by name but reports a certificate problem. What do you check first?",
  ("Validity and name match of the certificate",
   "The remaining disk capacity of the web server",
   "The number of VLANs on the access switch",
   "The lease time of the DHCP scope"),
  "Almost always either the certificate has expired or the requested name is not listed in it. Disk space, VLANs and DHCP have nothing to do with certificate validation."),

S("ap2-srv-r16",
  "Wozu dient eine Vorlage beim Bereitstellen neuer virtueller Maschinen?",
  ("Neue Maschinen entstehen einheitlich und schnell",
   "Bestehende Maschinen erhalten mehr Arbeitsspeicher",
   "Der Host verteilt die Last automatisch neu",
   "Die Sicherung der Maschinen wird überflüssig"), 0,
  "Aus einem geprüften Template entstehen VMs mit identischer Grundkonfiguration. Das spart Zeit und verhindert, dass sich Systeme unbemerkt auseinanderentwickeln.",
  "What is a template used for when provisioning new virtual machines?",
  ("New machines are created uniformly and quickly",
   "Existing machines receive more memory",
   "The host redistributes the load automatically",
   "Backing up the machines becomes unnecessary"),
  "A vetted template produces VMs with identical base configuration. That saves time and prevents systems from silently drifting apart."),

S("ap2-srv-r17",
  "Welche Aussage über Thin Provisioning trifft zu?",
  ("Speicher wird erst bei tatsächlicher Nutzung belegt",
   "Der gesamte Speicher wird sofort reserviert",
   "Die Lesegeschwindigkeit verdoppelt sich dadurch",
   "Die Sicherung der Daten entfällt dadurch"), 0,
  "Thin Provisioning weist virtuell mehr zu, als belegt ist, und spart so Platz. Die Überwachung des tatsächlichen Füllstands wird dadurch aber zur Pflicht.",
  "Which statement about thin provisioning is correct?",
  ("Storage is consumed only when actually used",
   "The entire storage is reserved immediately",
   "Read speed doubles as a result",
   "Backing up the data becomes unnecessary"),
  "Thin provisioning assigns more virtually than is occupied and thereby saves space. Monitoring the actual fill level becomes mandatory as a result."),

S("ap2-srv-r18",
  "Welcher Dienst beantwortet Anfragen nach Benutzerobjekten über ein standardisiertes Protokoll?",
  ("Ein LDAP-Verzeichnisdienst", "Ein SMTP-Mailserver",
   "Ein NTP-Zeitserver", "Ein FTP-Dateiserver"), 0,
  "LDAP ist das Zugriffsprotokoll auf Verzeichnisdienste und liefert Benutzer, Gruppen und Attribute. Die drei anderen Dienste haben mit Verzeichnissen nichts zu tun.",
  "Which service answers queries for user objects via a standardised protocol?",
  ("An LDAP directory service", "An SMTP mail server",
   "An NTP time server", "An FTP file server"),
  "LDAP is the access protocol for directory services and delivers users, groups and attributes. The other three services have nothing to do with directories."),

S("ap2-srv-r19",
  "Warum werden Wartungsfenster vereinbart?",
  ("Um Ausfälle planbar und angekündigt durchzuführen",
   "Um die Anschaffungskosten der Hardware zu senken",
   "Um die Anzahl der Server dauerhaft zu verringern",
   "Um Sicherungen vollständig entbehrlich zu machen"), 0,
  "Ein angekündigtes Fenster in einer lastarmen Zeit begrenzt den Schaden und schafft Erwartungssicherheit. Ungeplante Eingriffe im Tagesbetrieb sind der klassische Weg in den Störfall.",
  "Why are maintenance windows agreed?",
  ("To carry out outages in a planned and announced way",
   "To lower the acquisition costs of the hardware",
   "To permanently reduce the number of servers",
   "To make backups entirely unnecessary"),
  "An announced window during a low-load period limits damage and sets expectations. Unplanned interventions during business hours are the classic route into an incident."),

S("ap2-srv-r20",
  "Ein Dienst benötigt dauerhaft mehr Rechenleistung. Was beschreibt vertikale Skalierung?",
  ("Der bestehenden Instanz werden mehr Ressourcen zugewiesen",
   "Es werden zusätzliche gleichartige Instanzen gestartet",
   "Die Anwendung wird auf mehrere Standorte verteilt",
   "Die Daten werden auf mehrere Datenbanken aufgeteilt"), 0,
  "Vertikal heißt größer statt mehr: mehr CPU oder RAM für dieselbe Maschine. Der Ansatz ist einfach, stößt aber an die Grenzen eines einzelnen Systems.",
  "A service permanently needs more compute power. What does vertical scaling describe?",
  ("The existing instance is given more resources",
   "Additional identical instances are started",
   "The application is spread across several sites",
   "The data is split across several databases"),
  "Vertical means bigger rather than more: more CPU or RAM for the same machine. The approach is simple but hits the limits of a single system."),

S("ap2-srv-r21",
  "Welche Aussage beschreibt Software as a Service zutreffend?",
  ("Der Anbieter betreibt die fertige Anwendung vollständig",
   "Der Kunde verwaltet Betriebssystem und Anwendung selbst",
   "Der Kunde stellt eigene Hardware im Rechenzentrum",
   "Der Anbieter liefert ausschließlich Speicherplatz"), 0,
  "Bei SaaS nutzt der Kunde nur noch die Anwendung, alles darunter verantwortet der Anbieter. Genau deshalb entfällt eigener Betriebsaufwand, aber auch eigene Kontrolle.",
  "Which statement correctly describes software as a service?",
  ("The provider fully operates the finished application",
   "The customer manages operating system and application",
   "The customer supplies own hardware in the data centre",
   "The provider delivers storage space only"),
  "With SaaS the customer only uses the application while the provider is responsible for everything beneath. That is exactly why operational effort disappears - along with control."),

S("ap2-srv-r22",
  "Wie sichert man virtuelle Maschinen sinnvoll?",
  ("Auf Ebene des Hypervisors samt Konfiguration",
   "Ausschließlich durch Snapshots auf demselben Host",
   "Durch Kopieren der laufenden Festplattendateien",
   "Gar nicht, da Virtualisierung schon redundant ist"), 0,
  "Die Sicherung auf Hypervisorebene erfasst die VM konsistent samt Konfiguration. Snapshots auf demselben Host teilen jedes Risiko, und laufende Dateien zu kopieren erzeugt unbrauchbare Abbilder.",
  "How are virtual machines backed up sensibly?",
  ("At hypervisor level including their configuration",
   "Exclusively through snapshots on the same host",
   "By copying the running disk files",
   "Not at all, since virtualisation is already redundant"),
  "Backup at hypervisor level captures the VM consistently including its configuration. Snapshots on the same host share every risk, and copying running files produces unusable images."),

S("ap2-srv-r23",
  "Ein Dienst antwortet nicht mehr, der Server läuft aber. Was prüfst du als Nächstes?",
  ("Ob der Dienst läuft und welchen Fehler er protokolliert",
   "Ob die Netzwerkdose am Arbeitsplatz belegt ist",
   "Ob der Bildschirm des Servers eingeschaltet ist",
   "Ob im Lager noch genügend Patchkabel vorrätig gehalten werden"), 0,
  "Läuft das Betriebssystem, verlagert sich die Suche auf Dienststatus und Protokolle. Dort steht meist unmittelbar, ob eine Abhängigkeit fehlt oder der Speicher vollgelaufen ist.",
  "A service stops responding while the server is running. What do you check next?",
  ("Whether the service runs and what error it logs",
   "Whether the network socket at the desk is in use",
   "Whether the server's monitor is switched on",
   "Whether enough patch cables are still being kept in stock"),
  "If the operating system runs, the search moves to service status and logs. These usually state directly whether a dependency is missing or storage has filled up."),

S("ap2-srv-r24",
  "Welche Aussage über Konfigurationsmanagement mit Skripten trifft zu?",
  ("Der Sollzustand wird beschrieben und wiederholbar hergestellt",
   "Jeder Server wird einzeln von Hand eingerichtet und gepflegt",
   "Änderungen bleiben bewusst undokumentiert",
   "Die Sicherung der Systeme wird dadurch überflüssig"), 0,
  "Beschriebener Sollzustand macht Systeme reproduzierbar und Abweichungen sichtbar. Handarbeit dagegen führt über die Jahre zu Systemen, die niemand mehr nachbauen kann.",
  "Which statement about configuration management with scripts is correct?",
  ("The target state is described and applied repeatably",
   "Every server is set up and maintained individually by hand",
   "Changes deliberately remain undocumented",
   "Backing up the systems becomes unnecessary"),
  "A described target state makes systems reproducible and deviations visible. Manual work by contrast produces systems nobody can rebuild after a few years."),

S("ap2-srv-r25",
  "Welche Aussage über Hochverfügbarkeit ist richtig?",
  ("Sie verringert Ausfallzeiten durch Redundanz",
   "Sie ersetzt vollständig die Datensicherung",
   "Sie verhindert jeden denkbaren Ausfall sicher",
   "Sie beschleunigt die Anwendung im Normalbetrieb"), 0,
  "Hochverfügbarkeit federt Ausfälle einzelner Komponenten ab, schützt aber nicht vor gelöschten Daten oder Ransomware. Dafür braucht es weiterhin Sicherungen.",
  "Which statement about high availability is correct?",
  ("It reduces downtime through redundancy",
   "It completely replaces data backup",
   "It reliably prevents every conceivable outage",
   "It speeds up the application in normal operation"),
  "High availability cushions the failure of individual components but does not protect against deleted data or ransomware. Backups are still needed for that."),

S("ap2-srv-r26",
  "Welche Rolle übernimmt ein Reverse Proxy vor mehreren Anwendungsservern?",
  ("Er nimmt Anfragen an und verteilt sie nach innen",
   "Er verwaltet die Benutzerkonten der Anwendungen",
   "Er sichert die Datenbanken der Anwendungen",
   "Er vergibt die Lizenzen für die Anwendungen"), 0,
  "Als zentraler Eintrittspunkt verteilt er Last, kann TLS terminieren und verbirgt die interne Struktur. Konten, Sicherung und Lizenzen bleiben andernorts.",
  "Which role does a reverse proxy take in front of several application servers?",
  ("It accepts requests and distributes them inward",
   "It manages the user accounts of the applications",
   "It backs up the databases of the applications",
   "It assigns the licences for the applications"),
  "As a central entry point it spreads load, can terminate TLS and hides the internal structure. Accounts, backup and licences stay elsewhere."),

S("ap2-srv-r27",
  "Was beschreibt die Verfügbarkeit von 99,9 Prozent im Jahr ungefähr?",
  ("Rund 9 Stunden Ausfall pro Jahr",
   "Rund 9 Minuten Ausfall pro Jahr",
   "Rund 4 Tage Ausfall pro Jahr",
   "Rund 1 Stunde Ausfall pro Monat"), 0,
  "0,1 Prozent von 8760 Stunden sind etwa 8,8 Stunden. Jede weitere Neun verzehnfacht den Aufwand und senkt die zulässige Ausfallzeit auf ein Zehntel.",
  "What does an availability of 99.9 percent per year mean approximately?",
  ("About 9 hours of downtime per year",
   "About 9 minutes of downtime per year",
   "About 4 days of downtime per year",
   "About 1 hour of downtime per month"),
  "0.1 percent of 8760 hours is roughly 8.8 hours. Each additional nine multiplies the effort tenfold and cuts permitted downtime to a tenth."),

S("ap2-srv-r28",
  "Welche Aussage über Lizenzierung virtualisierter Server ist zutreffend?",
  ("Die Lizenzbedingungen richten sich oft nach den Kernen des Hosts",
   "Virtuelle Maschinen sind grundsätzlich lizenzfrei",
   "Eine Lizenz gilt automatisch für beliebig viele Hosts",
   "Lizenzen sind bei virtualisiertem Betrieb rechtlich ohne Bedeutung"), 0,
  "Viele Hersteller lizenzieren nach physischen Kernen oder Prozessoren des Hosts, unabhängig von der Zahl der VMs. Wer das übersieht, riskiert teure Nachforderungen.",
  "Which statement about licensing virtualised servers is correct?",
  ("Licence terms often depend on the host's cores",
   "Virtual machines are fundamentally licence-free",
   "One licence automatically covers any number of hosts",
   "Licences are legally without significance in virtualised operation"),
  "Many vendors licence by the host's physical cores or processors regardless of the number of VMs. Overlooking that risks expensive back payments."),

S("ap2-srv-r29",
  "Ein Dateiserver meldet ständig zu wenig Speicherplatz. Welche Maßnahme wirkt dauerhaft?",
  ("Kontingente je Bereich einführen und Altdaten auslagern",
   "Den Papierkorb der Nutzer regelmäßig leeren lassen",
   "Die Protokollierung des Servers vollständig abschalten",
   "Die Sicherung des Servers künftig seltener ausführen"), 0,
  "Ohne Begrenzung wächst jeder Dateiserver bis zum Anschlag. Kontingente und ein Konzept für Altdaten wirken dauerhaft, während Aufräumaktionen nur Zeit gewinnen.",
  "A file server constantly reports low disk space. Which measure works permanently?",
  ("Introduce quotas per area and archive old data",
   "Have users empty their recycle bin regularly",
   "Disable the server's logging completely",
   "Run the server's backup less often in future"),
  "Without limits every file server grows until it is full. Quotas and a concept for old data work permanently, while clean-up campaigns only buy time."),

S("ap2-srv-r30",
  "Welche Aussage über eine private Cloud trifft zu?",
  ("Die Ressourcen stehen exklusiv einer Organisation zur Verfügung",
   "Die Ressourcen werden mit beliebigen Kunden geteilt",
   "Sie kann grundsätzlich nicht virtualisiert betrieben werden",
   "Sie befindet sich immer im Rechenzentrum eines Anbieters"), 0,
  "Bei der privaten Cloud nutzt nur eine Organisation die Ressourcen, egal ob im eigenen Haus oder gemietet. Die öffentliche Cloud teilt die Infrastruktur zwischen vielen Kunden.",
  "Which statement about a private cloud is correct?",
  ("The resources are exclusively available to one organisation",
   "The resources are shared with arbitrary customers",
   "It fundamentally cannot be operated virtualised",
   "It is always located in a provider's data centre"),
  "In a private cloud only one organisation uses the resources, whether on premises or rented. The public cloud shares the infrastructure between many customers."),

S("ap2-srv-r31",
  "Welche Aufgabe erfüllt ein Monitoringsystem im Serverbetrieb?",
  ("Es meldet Abweichungen von definierten Schwellwerten",
   "Es installiert Sicherheitsupdates auf allen Servern",
   "Es sichert die Datenbestände auf ein zweites Medium",
   "Es vergibt Berechtigungen an die Benutzerkonten"), 0,
  "Monitoring erkennt volle Datenträger, ausgefallene Dienste und Lastspitzen, bevor Nutzer sie melden. Patchen, Sichern und Berechtigen sind eigenständige Aufgaben.",
  "What is the purpose of a monitoring system in server operations?",
  ("It reports deviations from defined thresholds",
   "It installs security updates on all servers",
   "It backs up the data to a second medium",
   "It assigns permissions to the user accounts"),
  "Monitoring spots full disks, failed services and load peaks before users report them. Patching, backing up and authorising are separate tasks."),

S("ap2-srv-r32",
  "Was geschieht bei der Konsolidierung mehrerer physischer Server?",
  ("Sie werden als virtuelle Maschinen auf weniger Hosts zusammengeführt",
   "Sie werden auf noch mehr einzelne physische Geräte im Rack verteilt",
   "Sie erhalten jeweils zusätzliche eigene Hardware",
   "Sie werden vollständig außer Betrieb genommen"), 0,
  "Konsolidierung nutzt die vorhandene Rechenleistung besser aus und senkt Strom-, Platz- und Wartungsaufwand. Der Preis ist eine höhere Abhängigkeit von den verbliebenen Hosts.",
  "What happens when several physical servers are consolidated?",
  ("They are merged as virtual machines onto fewer hosts",
   "They are spread across even more individual physical devices in the rack",
   "They each receive additional dedicated hardware",
   "They are taken out of service completely"),
  "Consolidation makes better use of available compute power and lowers power, space and maintenance effort. The price is greater dependency on the remaining hosts."),

# -------------------------------------------------------------- multiple (32)
M("ap2-srv-r33",
  "Welche Vorteile bringt die Servervirtualisierung?",
  ("Bessere Auslastung der vorhandenen Hardware",
   "Schnelle Bereitstellung neuer Systeme",
   "Einfachere Wartung durch Live Migration",
   "Geringerer Bedarf an Platz und Strom",
   "Vollständiger Verzicht auf Datensicherung",
   "Wegfall jeder Lizenzpflicht für Betriebssysteme"),
  (0, 1, 2, 3),
  "Auslastung, Tempo bei der Bereitstellung, Wartbarkeit und Betriebskosten sind die klassischen Gewinne. Sicherung und Lizenzen bleiben davon unberührt.",
  "Which advantages does server virtualisation bring?",
  ("Better utilisation of existing hardware",
   "Fast provisioning of new systems",
   "Easier maintenance through live migration",
   "Lower demand for space and power",
   "Complete elimination of data backup",
   "Removal of any licensing obligation for operating systems"),
  "Utilisation, provisioning speed, maintainability and operating costs are the classic gains. Backup and licensing remain unaffected."),

M("ap2-srv-r34",
  "Welche Servicemodelle unterscheidet man beim Cloud Computing?",
  ("Infrastructure as a Service", "Platform as a Service",
   "Software as a Service", "Die abgestufte Verantwortung je Modell",
   "Hardware as a Personal Service", "Network as a Building Service"),
  (0, 1, 2, 3),
  "IaaS, PaaS und SaaS unterscheiden sich darin, wie viel der Anbieter übernimmt und wie viel beim Kunden bleibt. Die beiden letzten Begriffe gibt es nicht.",
  "Which service models are distinguished in cloud computing?",
  ("Infrastructure as a service", "Platform as a service",
   "Software as a service", "The graded responsibility per model",
   "Hardware as a personal service", "Network as a building service"),
  "IaaS, PaaS and SaaS differ in how much the provider takes on and how much stays with the customer. The last two terms do not exist."),

M("ap2-srv-r35",
  "Welche Aussagen über Container sind zutreffend?",
  ("Sie teilen sich den Kernel des Wirtssystems",
   "Sie starten deutlich schneller als virtuelle Maschinen",
   "Sie werden aus unveränderlichen Abbildern erzeugt",
   "Sie brauchen weniger Ressourcen als vollständige VMs",
   "Sie bieten dieselbe Isolation wie eine eigene VM",
   "Sie enthalten stets einen eigenen Betriebssystemkern"),
  (0, 1, 2, 3),
  "Der gemeinsame Kernel ist Stärke und Grenze zugleich: er macht Container schlank und schnell, bietet aber schwächere Isolation als eine echte VM.",
  "Which statements about containers are correct?",
  ("They share the host system's kernel",
   "They start much faster than virtual machines",
   "They are created from immutable images",
   "They need fewer resources than full VMs",
   "They offer the same isolation as a dedicated VM",
   "They always contain their own operating system kernel"),
  "The shared kernel is both strength and limit: it makes containers lean and fast but offers weaker isolation than a real VM."),

M("ap2-srv-r36",
  "Welche Maßnahmen erhöhen die Verfügbarkeit eines Serverdienstes?",
  ("Redundante Hardwarekomponenten",
   "Ein Cluster mit automatischer Übernahme",
   "Eine unterbrechungsfreie Stromversorgung",
   "Überwachung mit Alarmierung",
   "Ein einzelner besonders schneller Server",
   "Der Verzicht auf Wartungsfenster"),
  (0, 1, 2, 3),
  "Redundanz, Übernahme, Stromversorgung und Überwachung wirken zusammen. Ein einzelner starker Server bleibt ein Ausfallpunkt, und ohne Wartung sammeln sich Risiken an.",
  "Which measures increase the availability of a server service?",
  ("Redundant hardware components",
   "A cluster with automatic failover",
   "An uninterruptible power supply",
   "Monitoring with alerting",
   "A single particularly fast server",
   "Doing without maintenance windows"),
  "Redundancy, failover, power supply and monitoring work together. A single powerful server remains a point of failure, and without maintenance risks accumulate."),

M("ap2-srv-r37",
  "Welche Angaben gehören in die Dokumentation eines Servers?",
  ("Zweck und betriebene Dienste", "Zugewiesene Ressourcen und Adressen",
   "Abhängigkeiten zu anderen Systemen", "Ansprechpartner und Wartungsfenster",
   "Die Lieblingsfarbe des Administrators", "Der Kaufpreis des Serverschranks"),
  (0, 1, 2, 3),
  "Zweck, Ressourcen, Abhängigkeiten und Zuständigkeiten entscheiden im Störungsfall über die Reaktionszeit. Abhängigkeiten werden dabei am häufigsten vergessen.",
  "Which details belong in the documentation of a server?",
  ("Purpose and services operated", "Assigned resources and addresses",
   "Dependencies on other systems", "Contacts and maintenance windows",
   "The administrator's favourite colour", "The purchase price of the rack"),
  "Purpose, resources, dependencies and ownership decide response time during an incident. Dependencies are the item most often forgotten."),

M("ap2-srv-r38",
  "Welche Aussagen über Snapshots sind korrekt?",
  ("Sie halten einen Zustand für kurze Zeit fest",
   "Sie eignen sich als Rückweg vor einem Update",
   "Lange bestehende Snapshots bremsen die VM aus",
   "Der belegte Speicher wächst mit der Laufzeit",
   "Sie ersetzen eine ordentliche Datensicherung",
   "Sie liegen sicher auf einem getrennten System"),
  (0, 1, 2, 3),
  "Ein Snapshot ist ein Rückweg für Minuten bis Stunden, keine Sicherung: er liegt auf demselben Speicher und teilt dessen Risiko.",
  "Which statements about snapshots are correct?",
  ("They capture a state for a short time",
   "They serve as a rollback path before an update",
   "Long-lived snapshots slow the VM down",
   "The occupied storage grows over their lifetime",
   "They replace a proper data backup",
   "They reside safely on a separate system"),
  "A snapshot is a rollback path for minutes to hours, not a backup: it sits on the same storage and shares its risk."),

M("ap2-srv-r39",
  "Welche Aufgaben übernimmt ein Verzeichnisdienst im Firmennetz?",
  ("Zentrale Verwaltung von Benutzerkonten",
   "Verwaltung von Gruppen und Berechtigungen",
   "Durchsetzung zentraler Richtlinien",
   "Authentisierung an angebundenen Diensten",
   "Verteilung von IP-Adressen an alle Clients",
   "Sicherung der Fachanwendungsdaten"),
  (0, 1, 2, 3),
  "Konten, Gruppen, Richtlinien und Anmeldung bilden den Kern eines Verzeichnisdienstes. Adressvergabe ist DHCP-Sache, Datensicherung eine eigene Disziplin.",
  "Which tasks does a directory service take on in a company network?",
  ("Central management of user accounts",
   "Management of groups and permissions",
   "Enforcement of central policies",
   "Authentication for connected services",
   "Distribution of IP addresses to all clients",
   "Backup of the business application data"),
  "Accounts, groups, policies and authentication form the core of a directory service. Address assignment is DHCP's job, backup a discipline of its own."),

M("ap2-srv-r40",
  "Welche Faktoren begrenzen die Zahl der VMs auf einem Host?",
  ("Verfügbarer Arbeitsspeicher", "Anzahl und Leistung der CPU-Kerne",
   "Ein- und Ausgabeleistung des Speichersystems", "Netzwerkbandbreite des Hosts",
   "Die Farbe des Servergehäuses", "Die Anzahl der Bildschirme am Host"),
  (0, 1, 2, 3),
  "Speicher, Rechenleistung, Datenträgerdurchsatz und Netzanbindung sind die realen Grenzen. Meist wird zuerst der Arbeitsspeicher knapp.",
  "Which factors limit the number of VMs on a host?",
  ("Available main memory", "Number and performance of CPU cores",
   "I/O performance of the storage system", "Network bandwidth of the host",
   "The colour of the server chassis", "The number of monitors on the host"),
  "Memory, compute power, storage throughput and network attachment are the real limits. Memory usually runs short first."),

M("ap2-srv-r41",
  "Welche Aussagen über Gruppenrichtlinien sind zutreffend?",
  ("Sie setzen Einstellungen zentral durch",
   "Sie wirken auf Organisationseinheiten",
   "Sie werden bei der Anmeldung angewendet",
   "Sie lassen sich für Gruppen gezielt filtern",
   "Sie ersetzen die Vergabe von Dateiberechtigungen",
   "Sie gelten ausschließlich für Serverbetriebssysteme"),
  (0, 1, 2, 3),
  "Richtlinien setzen Konfiguration durch, Berechtigungen bleiben davon getrennt. Angewendet werden sie auf Computer wie auf Benutzer.",
  "Which statements about group policies are correct?",
  ("They enforce settings centrally",
   "They apply to organisational units",
   "They are applied at logon",
   "They can be filtered for specific groups",
   "They replace the assignment of file permissions",
   "They apply exclusively to server operating systems"),
  "Policies enforce configuration while permissions stay separate. They apply to computers as well as users."),

M("ap2-srv-r42",
  "Welche Schritte gehören zur Bereitstellung eines neuen Serverdienstes?",
  ("Anforderungen und Ressourcenbedarf klären",
   "System aus einer geprüften Vorlage erstellen",
   "Dienst konfigurieren und absichern",
   "Überwachung und Sicherung einrichten",
   "Den Dienst ohne Test direkt produktiv nehmen",
   "Die Dokumentation grundsätzlich weglassen"),
  (0, 1, 2, 3),
  "Anforderungen, Vorlage, Absicherung sowie Überwachung und Sicherung machen einen Dienst betriebsreif. Ohne Monitoring merkt niemand den Ausfall, ohne Sicherung ist er nicht wiederherstellbar.",
  "Which steps belong to provisioning a new server service?",
  ("Clarify requirements and resource needs",
   "Create the system from a vetted template",
   "Configure and harden the service",
   "Set up monitoring and backup",
   "Take the service live without any testing",
   "Omit the documentation on principle"),
  "Requirements, template, hardening plus monitoring and backup make a service ready for operation. Without monitoring nobody notices an outage, without backup it cannot be restored."),

M("ap2-srv-r43",
  "Welche Aussagen über ein Failovercluster sind richtig?",
  ("Die Knoten überwachen sich gegenseitig",
   "Bei Ausfall übernimmt ein anderer Knoten den Dienst",
   "Gemeinsamer Speicher ist häufig Voraussetzung",
   "Die Übernahme sollte regelmäßig getestet werden",
   "Ein Cluster schützt vor versehentlich gelöschten Daten",
   "Ein Cluster macht Sicherungen entbehrlich"),
  (0, 1, 2, 3),
  "Ein Cluster fängt Hardware- und Dienstausfälle ab, repliziert aber auch Fehler wie gelöschte Daten sofort auf alle Knoten. Sicherungen bleiben deshalb Pflicht.",
  "Which statements about a failover cluster are correct?",
  ("The nodes monitor each other",
   "On failure another node takes over the service",
   "Shared storage is often a prerequisite",
   "The failover should be tested regularly",
   "A cluster protects against accidentally deleted data",
   "A cluster makes backups dispensable"),
  "A cluster catches hardware and service failures but also replicates mistakes such as deleted data instantly to all nodes. Backups therefore remain mandatory."),

M("ap2-srv-r44",
  "Welche Aussagen über Overcommitment sind zutreffend?",
  ("Es wird mehr zugewiesen als physisch vorhanden ist",
   "Es nutzt aus, dass selten alle VMs gleichzeitig Vollast fahren",
   "Es erfordert sorgfältige Überwachung der Auslastung",
   "Bei Engpässen leidet die Leistung aller Maschinen",
   "Es erhöht die physisch vorhandenen Ressourcen",
   "Es ist bei Arbeitsspeicher völlig risikolos"),
  (0, 1, 2, 3),
  "Overcommitment ist eine Wette auf ungleichzeitige Lastspitzen. Geht sie nicht auf, beginnt der Host auszulagern und alle VMs werden gleichzeitig langsam.",
  "Which statements about overcommitment are correct?",
  ("More is assigned than physically exists",
   "It exploits that VMs rarely peak simultaneously",
   "It requires careful monitoring of utilisation",
   "During shortages all machines suffer in performance",
   "It increases the physically available resources",
   "With memory it is completely risk-free"),
  "Overcommitment is a bet on non-simultaneous load peaks. If it does not pay off, the host starts paging and all VMs slow down at once."),

M("ap2-srv-r45",
  "Welche Aussagen über die Zeitsynchronisation im Serverbetrieb sind korrekt?",
  ("Protokolle mehrerer Systeme werden vergleichbar",
   "Zertifikatsprüfungen setzen korrekte Zeit voraus",
   "Anmeldeverfahren können bei Zeitdrift scheitern",
   "Eine zentrale Zeitquelle ist sinnvoll",
   "Die Uhrzeit spielt für Serverdienste keine Rolle",
   "Jeder Server sollte seine Zeit frei einstellen"),
  (0, 1, 2, 3),
  "Ohne synchrone Uhren lassen sich Vorfälle nicht rekonstruieren, und Verfahren mit Zeitfenstern brechen. Deshalb hängt sich alles an eine gemeinsame Quelle.",
  "Which statements about time synchronisation in server operations are correct?",
  ("Logs from several systems become comparable",
   "Certificate checks require correct time",
   "Authentication can fail on clock drift",
   "A central time source is sensible",
   "The time is irrelevant for server services",
   "Every server should set its time freely"),
  "Without synchronised clocks incidents cannot be reconstructed and time-window based methods break. That is why everything hangs off one common source."),

M("ap2-srv-r46",
  "Welche Aussagen über die Sicherung virtueller Maschinen sind richtig?",
  ("Die Sicherung erfolgt sinnvollerweise auf Hypervisorebene",
   "Die Konfiguration der VM gehört mitgesichert",
   "Anwendungskonsistenz erfordert Abstimmung mit dem Gastsystem",
   "Die Wiederherstellung sollte regelmäßig geprobt werden",
   "Snapshots auf demselben Host genügen als Sicherung",
   "Virtuelle Maschinen sind grundsätzlich selbstsichernd"),
  (0, 1, 2, 3),
  "Erst Hypervisorsicherung plus Konfiguration plus anwendungskonsistente Auslösung ergibt ein wiederherstellbares Ergebnis - überprüft durch Proben.",
  "Which statements about backing up virtual machines are correct?",
  ("Backup is sensibly done at hypervisor level",
   "The VM configuration must be backed up too",
   "Application consistency needs coordination with the guest",
   "Recovery should be rehearsed regularly",
   "Snapshots on the same host suffice as a backup",
   "Virtual machines are inherently self-backing"),
  "Only hypervisor backup plus configuration plus application-consistent triggering yields a restorable result - verified by rehearsals."),

M("ap2-srv-r47",
  "Welche Aussagen über Public und Private Cloud sind zutreffend?",
  ("Die Public Cloud teilt Ressourcen zwischen vielen Kunden",
   "Die Private Cloud steht einer Organisation exklusiv zur Verfügung",
   "Hybride Ansätze kombinieren beide Welten",
   "Datenschutzfragen beeinflussen die Auswahl",
   "Die Public Cloud ist immer die günstigere Lösung",
   "Die Private Cloud kann nicht virtualisiert werden"),
  (0, 1, 2, 3),
  "Die Wahl hängt an Schutzbedarf, Lastprofil und Kosten - eine pauschale Antwort gibt es nicht. Virtualisierung ist in beiden Fällen die Grundlage.",
  "Which statements about public and private cloud are correct?",
  ("The public cloud shares resources between many customers",
   "The private cloud is exclusively available to one organisation",
   "Hybrid approaches combine both worlds",
   "Data protection questions influence the choice",
   "The public cloud is always the cheaper solution",
   "The private cloud cannot be virtualised"),
  "The choice depends on protection needs, load profile and cost - there is no blanket answer. Virtualisation is the basis in both cases."),

M("ap2-srv-r48",
  "Welche Werte sollte ein Monitoring für Server überwachen?",
  ("Auslastung von CPU und Arbeitsspeicher",
   "Freier Speicherplatz auf den Datenträgern",
   "Erreichbarkeit der wichtigen Dienste",
   "Temperatur und Zustand der Hardware",
   "Die Anzahl der Mausklicks der Nutzer",
   "Die Schriftgröße in den Anwendungen"),
  (0, 1, 2, 3),
  "Last, Speicherplatz, Diensterreichbarkeit und Hardwarezustand decken die häufigsten Ausfallursachen ab. Vollgelaufene Datenträger sind dabei der Klassiker.",
  "Which values should monitoring cover for servers?",
  ("Utilisation of CPU and memory",
   "Free space on the storage devices",
   "Reachability of the important services",
   "Temperature and hardware health",
   "The number of mouse clicks by users",
   "The font size in the applications"),
  "Load, disk space, service reachability and hardware health cover the most frequent causes of outages. Full disks are the classic among them."),

M("ap2-srv-r49",
  "Welche Aussagen über Patchmanagement auf Servern sind korrekt?",
  ("Updates werden in einem Wartungsfenster eingespielt",
   "Ein Test vorab senkt das Risiko von Ausfällen",
   "Ein Rückweg für fehlgeschlagene Updates ist eingeplant",
   "Der Patchstand wird dokumentiert",
   "Server werden aus Stabilitätsgründen gar nicht gepatcht",
   "Neustarts lassen sich grundsätzlich immer vermeiden"),
  (0, 1, 2, 3),
  "Fenster, Test, Rückweg und Dokumentation machen Patchen beherrschbar. Ungepatchte Server sind kein Stabilitäts-, sondern ein Sicherheitsproblem.",
  "Which statements about patch management on servers are correct?",
  ("Updates are applied in a maintenance window",
   "Prior testing lowers the risk of outages",
   "A rollback path for failed updates is planned",
   "The patch level is documented",
   "Servers are not patched at all for stability reasons",
   "Reboots can fundamentally always be avoided"),
  "Windows, testing, rollback and documentation make patching manageable. Unpatched servers are not a stability question but a security problem."),

M("ap2-srv-r50",
  "Welche Aussagen über einen Webserver in der DMZ sind zutreffend?",
  ("Er ist aus dem Internet erreichbar",
   "Er ist vom internen Netz durch eine Firewall getrennt",
   "Zugriffe auf interne Systeme werden eng geregelt",
   "Er wird besonders sorgfältig gehärtet und überwacht",
   "Er darf uneingeschränkt auf alle internen Server zugreifen",
   "Er braucht keine Sicherheitsupdates, da er isoliert steht"),
  (0, 1, 2, 3),
  "Der Sinn der DMZ liegt gerade in der engen Regelung des Wegs nach innen. Ein exponierter Server braucht deshalb besonders konsequentes Patchen.",
  "Which statements about a web server in the DMZ are correct?",
  ("It is reachable from the internet",
   "It is separated from the internal network by a firewall",
   "Access to internal systems is tightly regulated",
   "It is hardened and monitored particularly carefully",
   "It may access all internal servers without restriction",
   "It needs no security updates because it stands isolated"),
  "The whole point of a DMZ is tight regulation of the path inward. An exposed server therefore needs especially consistent patching."),

M("ap2-srv-r51",
  "Welche Aussagen über Vorlagen und automatisierte Bereitstellung sind richtig?",
  ("Neue Systeme entstehen einheitlich",
   "Die Bereitstellung wird deutlich schneller",
   "Abweichungen zwischen Systemen werden seltener",
   "Vorlagen müssen selbst gepflegt und gepatcht werden",
   "Einmal erstellte Vorlagen bleiben dauerhaft aktuell",
   "Automatisierung macht Dokumentation überflüssig"),
  (0, 1, 2, 3),
  "Einheitlichkeit und Tempo sind der Gewinn, die Pflege der Vorlagen der Preis. Eine veraltete Vorlage verteilt ihre Lücken auf jedes neue System.",
  "Which statements about templates and automated provisioning are correct?",
  ("New systems are created uniformly",
   "Provisioning becomes considerably faster",
   "Deviations between systems become rarer",
   "Templates themselves must be maintained and patched",
   "Templates once created stay current permanently",
   "Automation makes documentation unnecessary"),
  "Uniformity and speed are the gain, template maintenance the price. An outdated template spreads its gaps to every new system."),

M("ap2-srv-r52",
  "Welche Ursachen können einen langsamen virtualisierten Server erklären?",
  ("Überbuchter Arbeitsspeicher auf dem Host",
   "Zu wenig Ein- und Ausgabeleistung des Speichersystems",
   "Zu viele aktive Snapshots der Maschine",
   "Konkurrenz durch andere VMs auf demselben Host",
   "Ein zu langer Name der virtuellen Maschine",
   "Eine zu hohe Bildschirmauflösung der Konsole"),
  (0, 1, 2, 3),
  "Auf einem geteilten Host wirkt jede Knappheit sofort auf alle Gäste. Alte Snapshots sind dabei eine häufig übersehene Bremse.",
  "Which causes can explain a slow virtualised server?",
  ("Overcommitted memory on the host",
   "Insufficient I/O performance of the storage system",
   "Too many active snapshots of the machine",
   "Competition from other VMs on the same host",
   "Too long a name for the virtual machine",
   "Too high a console screen resolution"),
  "On a shared host every shortage immediately affects all guests. Old snapshots are a frequently overlooked brake among them."),

M("ap2-srv-r53",
  "Welche Aussagen über Verfügbarkeitsklassen sind zutreffend?",
  ("99,9 Prozent entsprechen rund 9 Stunden Ausfall im Jahr",
   "Jede weitere Neun verringert die zulässige Ausfallzeit stark",
   "Höhere Klassen erfordern deutlich mehr Aufwand",
   "Die Zielklasse richtet sich am Geschäftsbedarf aus",
   "100 Prozent Verfügbarkeit ist praktisch erreichbar",
   "Die Klasse sagt nichts über den Aufwand aus"),
  (0, 1, 2, 3),
  "Verfügbarkeit ist eine Kostenfrage: jede Neun kostet ein Vielfaches. Deshalb wird sie am tatsächlichen Bedarf des Geschäfts bemessen, nicht am technisch Machbaren.",
  "Which statements about availability classes are correct?",
  ("99.9 percent equals about 9 hours of downtime per year",
   "Each additional nine sharply reduces permitted downtime",
   "Higher classes require considerably more effort",
   "The target class follows the business need",
   "100 percent availability is practically achievable",
   "The class says nothing about the effort involved"),
  "Availability is a cost question: every nine costs a multiple. That is why it is measured against actual business need, not technical possibility."),

M("ap2-srv-r54",
  "Welche Aussagen über Fernwartung von Servern sind korrekt?",
  ("Der Zugang läuft über ein VPN oder ein Sprungsystem",
   "Eine Mehrfaktor-Anmeldung ist angebracht",
   "Zugriffe werden protokolliert",
   "Ein Zugang unabhängig vom Betriebssystem ist hilfreich",
   "Der Fernwartungsport wird direkt ins Internet gestellt",
   "Ein gemeinsames Konto für alle Administratoren genügt"),
  (0, 1, 2, 3),
  "Getunnelt, stark authentisiert und protokolliert bleibt Fernwartung beherrschbar; ein systemunabhängiger Zugang hilft, wenn das Betriebssystem nicht mehr reagiert. Offene Ports und Sammelkonten sind gefährlich.",
  "Which statements about remote server administration are correct?",
  ("Access runs through a VPN or a jump host",
   "Multi-factor authentication is appropriate",
   "Access is logged",
   "An out-of-band access path is helpful",
   "The remote management port is exposed to the internet",
   "One shared account for all administrators suffices"),
  "Tunnelled, strongly authenticated and logged keeps remote administration manageable; an out-of-band path helps when the OS stops responding. Open ports and shared accounts are dangerous."),

M("ap2-srv-r55",
  "Welche Aussagen über Berechtigungen auf einem Dateiserver sind richtig?",
  ("Rechte werden über Gruppen vergeben",
   "Die Struktur folgt der Organisation",
   "Vergebene Rechte werden regelmäßig überprüft",
   "Vererbung wird bewusst geplant",
   "Jeder Nutzer erhält einzeln zugewiesene Rechte",
   "Vollzugriff für alle vereinfacht die Verwaltung"),
  (0, 1, 2, 3),
  "Gruppenbasierte, an der Organisation orientierte Rechte bleiben nachvollziehbar und pflegbar. Einzelvergabe und Vollzugriff führen binnen Jahren ins Chaos.",
  "Which statements about permissions on a file server are correct?",
  ("Rights are granted via groups",
   "The structure follows the organisation",
   "Granted rights are reviewed regularly",
   "Inheritance is planned deliberately",
   "Every user receives individually assigned rights",
   "Full access for everyone simplifies administration"),
  "Group-based rights aligned with the organisation stay traceable and maintainable. Individual assignment and full access lead into chaos within years."),

M("ap2-srv-r56",
  "Welche Aussagen über Lizenzierung im Serverbetrieb sind zutreffend?",
  ("Lizenzmodelle können sich nach Kernen richten",
   "Auch Zugriffslizenzen für Nutzer können nötig sein",
   "Die Lizenzlage wird dokumentiert",
   "Virtualisierung ändert die Lizenzpflicht nicht",
   "Testsysteme sind grundsätzlich lizenzfrei",
   "Lizenzen gelten unbegrenzt für beliebig viele Systeme"),
  (0, 1, 2, 3),
  "Lizenzen richten sich je nach Hersteller nach Kernen, Prozessoren oder Nutzern - dokumentiert werden muss es in jedem Fall. Auch Testsysteme brauchen in der Regel eine Lizenz.",
  "Which statements about licensing in server operations are correct?",
  ("Licence models can be based on cores",
   "Client access licences for users may also be needed",
   "The licensing situation is documented",
   "Virtualisation does not remove the licensing obligation",
   "Test systems are fundamentally licence-free",
   "Licences apply indefinitely to any number of systems"),
  "Depending on the vendor, licences follow cores, processors or users - and must be documented in any case. Test systems usually need a licence too."),

M("ap2-srv-r57",
  "Welche Aussagen über Orchestrierung von Containern sind korrekt?",
  ("Sie startet und verteilt Container automatisch",
   "Sie ersetzt ausgefallene Container selbstständig",
   "Sie skaliert die Anzahl der Instanzen nach Bedarf",
   "Sie verwaltet Netzwerk und Konfiguration der Container",
   "Sie macht Überwachung vollständig entbehrlich",
   "Sie ist nur für einzelne Container auf einem Host sinnvoll"),
  (0, 1, 2, 3),
  "Orchestrierung lohnt sich gerade bei vielen Containern über mehrere Hosts. Überwachung bleibt nötig - nur die Reaktion darauf wird automatisiert.",
  "Which statements about container orchestration are correct?",
  ("It starts and distributes containers automatically",
   "It replaces failed containers by itself",
   "It scales the number of instances on demand",
   "It manages network and configuration of the containers",
   "It makes monitoring entirely dispensable",
   "It only makes sense for single containers on one host"),
  "Orchestration pays off precisely with many containers across several hosts. Monitoring stays necessary - only the response to it becomes automated."),

M("ap2-srv-r58",
  "Welche Aussagen über den Betrieb eines DNS-Servers im Firmennetz sind richtig?",
  ("Interne Namen werden lokal aufgelöst",
   "Externe Anfragen gehen an Weiterleitungsserver",
   "Die TTL steuert die Zwischenspeicherung",
   "Reverse-Zonen ordnen Adressen Namen zu",
   "Ein DNS-Server vergibt zusätzlich Adressen",
   "Interne Namen gehören ins öffentliche Internet"),
  (0, 1, 2, 3),
  "Interne Auflösung, Weiterleitung, TTL-Steuerung und Reverse-Zonen sind der Alltag. Adressvergabe macht DHCP, und interne Namen bleiben besser intern.",
  "Which statements about operating a DNS server in a company network are correct?",
  ("Internal names are resolved locally",
   "External queries go to forwarders",
   "The TTL controls caching",
   "Reverse zones map addresses to names",
   "A DNS server additionally assigns addresses",
   "Internal names belong on the public internet"),
  "Internal resolution, forwarding, TTL control and reverse zones are the daily business. Address assignment is DHCP's job, and internal names are better kept internal."),

M("ap2-srv-r59",
  "Welche Vorteile bietet ein Terminalserver oder eine Desktopvirtualisierung?",
  ("Anwendungen werden zentral gepflegt",
   "Daten bleiben im Rechenzentrum",
   "Auch schwache Endgeräte genügen",
   "Der Zugriff funktioniert standortunabhängig",
   "Der Ausfall des Servers bleibt folgenlos",
   "Netzwerkqualität spielt keine Rolle mehr"),
  (0, 1, 2, 3),
  "Zentrale Pflege, Datenhaltung im Rechenzentrum und schlanke Endgeräte sind die Gewinne. Der Preis ist die vollständige Abhängigkeit von Server und Netzqualität.",
  "Which advantages does a terminal server or desktop virtualisation offer?",
  ("Applications are maintained centrally",
   "Data stays in the data centre",
   "Even weak end devices suffice",
   "Access works independently of location",
   "A server outage remains without consequence",
   "Network quality no longer matters"),
  "Central maintenance, data kept in the data centre and lean end devices are the gains. The price is complete dependency on server and network quality."),

M("ap2-srv-r60",
  "Welche Angaben gehören in ein Betriebshandbuch für einen Dienst?",
  ("Beschreibung des Dienstes und seiner Aufgabe",
   "Anleitung für Start, Stopp und Neustart",
   "Vorgehen bei bekannten Störungen",
   "Kontakte und Eskalationswege",
   "Die privaten Telefonnummern aller Nutzer",
   "Die Speisekarte der Kantine für die Woche"),
  (0, 1, 2, 3),
  "Ein Betriebshandbuch muss nachts um drei von jemandem lesbar sein, der den Dienst nicht gebaut hat. Genau dafür braucht es Beschreibung, Bedienung, Störungshilfe und Kontakte.",
  "Which details belong in an operations manual for a service?",
  ("Description of the service and its purpose",
   "Instructions for start, stop and restart",
   "Procedure for known faults",
   "Contacts and escalation paths",
   "The private phone numbers of all users",
   "The canteen menu for the week"),
  "An operations manual must be readable at three in the morning by someone who did not build the service. That is exactly why it needs description, operation, fault help and contacts."),

M("ap2-srv-r61",
  "Welche Aussagen über die Konsolidierung physischer Server sind zutreffend?",
  ("Die Auslastung der Hardware steigt",
   "Strom- und Platzbedarf sinken",
   "Die Abhängigkeit von den verbliebenen Hosts steigt",
   "Redundanz der Hosts wird dadurch wichtiger",
   "Die Zahl der zu pflegenden Betriebssysteme sinkt automatisch",
   "Ein Ausfall betrifft danach weniger Systeme"),
  (0, 1, 2, 3),
  "Konsolidierung spart Ressourcen, verdichtet aber das Risiko: ein Hostausfall trifft nun viele Dienste gleichzeitig. Die Zahl der Betriebssysteme bleibt unverändert.",
  "Which statements about consolidating physical servers are correct?",
  ("Hardware utilisation rises",
   "Power and space requirements fall",
   "Dependency on the remaining hosts increases",
   "Host redundancy becomes more important",
   "The number of operating systems to maintain automatically falls",
   "An outage subsequently affects fewer systems"),
  "Consolidation saves resources but concentrates risk: a host failure now hits many services at once. The number of operating systems stays the same."),

M("ap2-srv-r62",
  "Welche Aussagen über Zertifikate für interne Serverdienste sind korrekt?",
  ("Sie ermöglichen verschlüsselte Verbindungen",
   "Ihre Gültigkeit muss überwacht werden",
   "Eine interne CA kann sie ausstellen",
   "Der Name im Zertifikat muss zum Aufruf passen",
   "Abgelaufene Zertifikate stören den Betrieb nicht",
   "Selbstsignierte Zertifikate sind immer unbedenklich"),
  (0, 1, 2, 3),
  "Abgelaufene oder nicht passende Zertifikate legen Dienste zuverlässig lahm, deshalb gehört die Laufzeit ins Monitoring. Selbstsignierte Zertifikate erzwingen Ausnahmen, die Nutzer sich abgewöhnen sollen.",
  "Which statements about certificates for internal server services are correct?",
  ("They enable encrypted connections",
   "Their validity has to be monitored",
   "An internal CA can issue them",
   "The name in the certificate must match the request",
   "Expired certificates do not disturb operation",
   "Self-signed certificates are always harmless"),
  "Expired or mismatched certificates reliably take services down, so expiry belongs in monitoring. Self-signed certificates force exceptions that users should be unlearning."),

M("ap2-srv-r63",
  "Welche Aussagen über Ressourcenzuteilung an virtuelle Maschinen sind richtig?",
  ("Der Bedarf wird vor der Zuteilung ermittelt",
   "Zu große Zuteilung verschwendet Ressourcen",
   "Zu kleine Zuteilung bremst die Anwendung",
   "Die Zuteilung wird im Betrieb nachjustiert",
   "Mehr vCPUs bedeuten immer mehr Leistung",
   "Einmal zugeteilte Werte bleiben dauerhaft passend"),
  (0, 1, 2, 3),
  "Zuteilung ist ein laufender Abgleich zwischen Bedarf und Vorrat. Zu viele vCPUs können die Leistung sogar senken, weil der Host mehr Kerne gleichzeitig freihalten muss.",
  "Which statements about resource allocation to virtual machines are correct?",
  ("The requirement is determined before allocation",
   "Over-allocation wastes resources",
   "Under-allocation slows the application",
   "The allocation is adjusted during operation",
   "More vCPUs always mean more performance",
   "Values once assigned stay appropriate forever"),
  "Allocation is a continuous match between demand and supply. Too many vCPUs can even reduce performance because the host must free up more cores simultaneously."),

M("ap2-srv-r64",
  "Welche Aussagen über den Betrieb eines Mailservers sind zutreffend?",
  ("Der Versand läuft über SMTP",
   "Der Abruf erfolgt über IMAP oder POP3",
   "Verbindungen sollten mit TLS geschützt werden",
   "Absenderprüfung per SPF und DKIM ist üblich",
   "Ein offenes Relay erleichtert den Betrieb",
   "Postfachgrößen müssen nicht begrenzt werden"),
  (0, 1, 2, 3),
  "SMTP für den Versand, IMAP oder POP3 für den Abruf, TLS und Absenderprüfung als Absicherung. Ein offenes Relay macht den Server binnen Stunden zur Spamschleuder.",
  "Which statements about operating a mail server are correct?",
  ("Sending runs over SMTP",
   "Retrieval happens via IMAP or POP3",
   "Connections should be protected with TLS",
   "Sender verification via SPF and DKIM is common",
   "An open relay makes operation easier",
   "Mailbox sizes do not need any limits"),
  "SMTP for sending, IMAP or POP3 for retrieval, TLS and sender verification as safeguards. An open relay turns the server into a spam source within hours."),

# ------------------------------------------------------------------ text (36)
T("ap2-srv-r65", "Welcher Hypervisortyp läuft ohne darunterliegendes Betriebssystem direkt auf der Hardware?", "Typ 1",
  "Er erreicht dadurch bessere Leistung und Isolation als ein Typ-2-Hypervisor.",
  "Which hypervisor type runs directly on hardware without an underlying OS?", "Type 1",
  "It thereby achieves better performance and isolation than a type 2 hypervisor."),

T("ap2-srv-r66", "Wie heißt das Verschieben einer laufenden VM auf einen anderen Host ohne Unterbrechung?", "Live Migration",
  "Sie erlaubt Wartung an einem Host, ohne dass die Anwendung ausfällt.",
  "What is moving a running VM to another host without interruption called?", "Live migration",
  "It allows maintenance on a host without the application going down."),

T("ap2-srv-r67", "Welches Cloud-Modell liefert virtuelle Server, die der Kunde selbst verwaltet?", "IaaS",
  "Der Anbieter stellt Rechenleistung, Speicher und Netz bereit, alles darüber liegt beim Kunden.",
  "Which cloud model delivers virtual servers managed by the customer?", "IaaS",
  "The provider supplies compute, storage and network; everything above is the customer's responsibility."),

T("ap2-srv-r68", "Wie nennt man eine Stelle, deren Ausfall das Gesamtsystem lahmlegt?", "Single Point of Failure",
  "Beseitigt wird sie durch Redundanz auf Geräte-, Leitungs- und Stromebene.",
  "What is a point whose failure paralyses the whole system called?", "Single point of failure",
  "It is removed by redundancy at device, link and power level."),

T("ap2-srv-r69", "Welcher Dienst synchronisiert die Uhrzeit der Server im Netz?", "NTP",
  "Ohne synchrone Zeit lassen sich Protokolle nicht korrelieren und Anmeldeverfahren scheitern.",
  "Which service synchronises the servers' time in a network?", "NTP",
  "Without synchronised time logs cannot be correlated and authentication fails."),

T("ap2-srv-r70", "Wie viele Stunden Ausfall im Jahr erlaubt eine Verfügbarkeit von 99,9 Prozent ungefähr?", "9",
  "0,1 Prozent von 8760 Stunden ergeben rund 8,8 Stunden zulässige Ausfallzeit.",
  "How many hours of annual downtime does 99.9 percent availability allow approximately?", "9",
  "0.1 percent of 8760 hours gives roughly 8.8 hours of permitted downtime."),

T("ap2-srv-r71", "Wie heißt die unveränderliche Vorlage, aus der Container gestartet werden?", "Image",
  "Aus einem Image lassen sich beliebig viele Container mit identischem Ausgangszustand starten.",
  "What is the immutable template containers are started from called?", "Image",
  "Any number of containers with an identical starting state can be launched from one image."),

T("ap2-srv-r72", "Welches Protokoll fragt Benutzerobjekte aus einem Verzeichnisdienst ab?", "LDAP",
  "Es liefert Benutzer, Gruppen und Attribute und ist die Grundlage zentraler Anmeldung.",
  "Which protocol queries user objects from a directory service?", "LDAP",
  "It delivers users, groups and attributes and is the basis of central authentication."),

T("ap2-srv-r73", "Wie nennt man das Zuweisen von mehr Ressourcen, als physisch vorhanden sind?", "Overcommitment",
  "Es funktioniert, solange nicht alle VMs gleichzeitig Vollast fahren.",
  "What is assigning more resources than physically exist called?", "Overcommitment",
  "It works as long as not all VMs run at full load simultaneously."),

T("ap2-srv-r74", "Welches Verfahren belegt Speicher erst bei tatsächlicher Nutzung?", "Thin Provisioning",
  "Es spart Platz, macht aber die Überwachung des echten Füllstands zur Pflicht.",
  "Which method consumes storage only when it is actually used?", "Thin provisioning",
  "It saves space but makes monitoring the real fill level mandatory."),

T("ap2-srv-r75", "Wie heißt das zentrale Werkzeug, das Einstellungen für Organisationseinheiten durchsetzt?", "Gruppenrichtlinie",
  "Sie wird bei der Anmeldung angewendet und lässt sich gezielt für Gruppen filtern.",
  "What is the central tool enforcing settings for organisational units called?", "Group policy",
  "It is applied at logon and can be filtered for specific groups."),

T("ap2-srv-r76", "Wie nennt man das Hinzufügen weiterer gleichartiger Instanzen bei steigender Last?", "Horizontale Skalierung",
  "Sie skaliert weiter als die vertikale Variante, verlangt aber eine dafür ausgelegte Anwendung.",
  "What is adding further identical instances as load rises called?", "Horizontal scaling",
  "It scales further than the vertical variant but requires an application designed for it."),

T("ap2-srv-r77", "Wie heißt ein Serververbund, in dem ein Knoten bei Ausfall den Dienst übernimmt?", "Failovercluster",
  "Die Knoten überwachen sich gegenseitig; die Übernahme sollte regelmäßig getestet werden.",
  "What is a server group where one node takes over the service on failure called?", "Failover cluster",
  "The nodes monitor each other; the failover should be tested regularly."),

T("ap2-srv-r78", "Welches Cloud-Modell stellt eine fertige Anwendung ohne eigenen Betriebsaufwand bereit?", "SaaS",
  "Der Anbieter verantwortet alles unterhalb der Anwendung - Kontrolle gibt der Kunde damit ab.",
  "Which cloud model provides a finished application with no operational effort?", "SaaS",
  "The provider is responsible for everything below the application - the customer gives up control."),

T("ap2-srv-r79", "Wie nennt man das Zusammenführen mehrerer physischer Server auf weniger Hosts?", "Konsolidierung",
  "Sie senkt Strom- und Platzbedarf, erhöht aber die Abhängigkeit von den verbliebenen Hosts.",
  "What is merging several physical servers onto fewer hosts called?", "Consolidation",
  "It lowers power and space needs but increases dependency on the remaining hosts."),

T("ap2-srv-r80", "Welche Momentaufnahme einer VM dient als kurzfristiger Rückweg vor einem Update?", "Snapshot",
  "Lange bestehende Snapshots lassen die Differenzdateien wachsen und bremsen die VM aus.",
  "Which point-in-time copy of a VM serves as a short-term rollback before an update?", "Snapshot",
  "Long-lived snapshots let the delta files grow and slow the VM down."),

T("ap2-srv-r81", "Welches Protokoll versendet E-Mails zwischen Mailservern?", "SMTP",
  "Der Abruf aus dem Postfach erfolgt dagegen über IMAP oder POP3.",
  "Which protocol sends emails between mail servers?", "SMTP",
  "Retrieval from the mailbox by contrast happens via IMAP or POP3."),

T("ap2-srv-r82", "Wie nennt man einen Server, auf dem Anwendungen zentral für viele Sitzungen laufen?", "Terminalserver",
  "Die Clients übertragen nur Bildschirminhalt und Eingaben, was die Pflege stark vereinfacht.",
  "What is a server running applications centrally for many sessions called?", "Terminal server",
  "The clients only transfer screen content and input, which greatly simplifies maintenance."),

T("ap2-srv-r83", "Welche Cloud-Form steht exklusiv einer einzelnen Organisation zur Verfügung?", "Private Cloud",
  "Sie kann im eigenen Rechenzentrum oder gemietet betrieben werden - entscheidend ist die Exklusivität.",
  "Which cloud form is exclusively available to a single organisation?", "Private cloud",
  "It can be run in-house or rented - what matters is the exclusivity."),

T("ap2-srv-r84", "Wie nennt man das geplante Zeitfenster für Wartungsarbeiten mit möglicher Unterbrechung?", "Wartungsfenster",
  "Es wird angekündigt und in eine lastarme Zeit gelegt, um den Schaden zu begrenzen.",
  "What is the planned period for maintenance with possible interruption called?", "Maintenance window",
  "It is announced and placed in a low-load period to limit the impact."),

T("ap2-srv-r85", "Welches System meldet das Überschreiten definierter Schwellwerte im Serverbetrieb?", "Monitoring",
  "Es erkennt volle Datenträger und ausgefallene Dienste, bevor Nutzer sie melden.",
  "Which system reports threshold breaches in server operations?", "Monitoring",
  "It spots full disks and failed services before users report them."),

T("ap2-srv-r86", "Wie heißt das Verfahren, das mehr Ressourcen für dieselbe Instanz bereitstellt?", "Vertikale Skalierung",
  "Sie ist einfach umzusetzen, stößt aber an die Grenzen eines einzelnen Systems.",
  "What is providing more resources to the same instance called?", "Vertical scaling",
  "It is simple to implement but hits the limits of a single system."),

T("ap2-srv-r87", "Welche Cloud-Form kombiniert eigene und fremde Infrastruktur?", "Hybrid Cloud",
  "Sensible Daten bleiben intern, während Lastspitzen nach außen ausgelagert werden.",
  "Which cloud form combines own and external infrastructure?", "Hybrid cloud",
  "Sensitive data stays internal while load peaks are offloaded externally."),

T("ap2-srv-r88", "Auf welcher Ebene sollten virtuelle Maschinen sinnvollerweise gesichert werden?", "Hypervisorebene",
  "So werden Maschine und Konfiguration konsistent erfasst, ohne im Gastsystem arbeiten zu müssen.",
  "At which level should virtual machines sensibly be backed up?", "Hypervisor level",
  "This captures machine and configuration consistently without working inside the guest."),

T("ap2-srv-r89", "Wie viele Neunen hat eine Verfügbarkeit von 99,99 Prozent?", "4",
  "Das entspricht rund 53 Minuten zulässiger Ausfallzeit im Jahr.",
  "How many nines does an availability of 99.99 percent have?", "4",
  "That corresponds to roughly 53 minutes of permitted downtime per year."),

T("ap2-srv-r90", "Welche Software verwaltet viele Container automatisch über mehrere Hosts?", "Orchestrierung",
  "Sie startet, verteilt, ersetzt und skaliert Container nach einem beschriebenen Sollzustand.",
  "Which software manages many containers automatically across several hosts?", "Orchestration",
  "It starts, distributes, replaces and scales containers according to a described target state."),

T("ap2-srv-r91", "Welches Cloud-Modell stellt eine Laufzeitumgebung für eigene Anwendungen bereit?", "PaaS",
  "Der Kunde bringt nur den Anwendungscode mit, um Betriebssystem und Laufzeit kümmert sich der Anbieter.",
  "Which cloud model provides a runtime environment for your own applications?", "PaaS",
  "The customer brings only the application code; the provider handles OS and runtime."),

T("ap2-srv-r92", "Wie heißt die geprüfte Ausgangskonfiguration, aus der neue VMs erstellt werden?", "Vorlage",
  "Auf Englisch Template. Sie muss selbst gepflegt und gepatcht werden, sonst verteilt sie ihre Lücken weiter.",
  "What is the vetted base configuration used to create new VMs called?", "Template",
  "It must itself be maintained and patched, otherwise it spreads its gaps further."),

T("ap2-srv-r93", "Welches Protokoll ruft E-Mails ab und belässt sie dabei auf dem Server?", "IMAP",
  "POP3 holt die Nachrichten dagegen typischerweise ab und entfernt sie vom Server.",
  "Which protocol retrieves emails while leaving them on the server?", "IMAP",
  "POP3 by contrast typically downloads messages and removes them from the server."),

T("ap2-srv-r94", "Wie nennt man einen Zugang zum Server, der unabhängig vom Betriebssystem funktioniert?", "Out-of-Band-Zugang",
  "Er hilft genau dann, wenn das Betriebssystem nicht mehr reagiert und kein Fernzugriff mehr geht.",
  "What is server access that works independently of the operating system called?", "Out-of-band access",
  "It helps exactly when the operating system stops responding and remote access fails."),

T("ap2-srv-r95", "Welche Begrenzung verhindert, dass einzelne Bereiche einen Dateiserver vollschreiben?", "Kontingent",
  "Auf Englisch Quota. Ohne Begrenzung wächst jeder Dateiserver bis zum Anschlag.",
  "Which limit prevents individual areas from filling up a file server?", "Quota",
  "Without limits every file server grows until it is full."),

T("ap2-srv-r96", "Wie viele Kernel teilen sich zehn Container auf einem Host?", "1",
  "Alle nutzen den Kernel des Wirtssystems - genau daher stammt ihr geringer Ressourcenbedarf.",
  "How many kernels do ten containers on one host share?", "1",
  "All use the host system's kernel - which is exactly where their low resource usage comes from."),

T("ap2-srv-r97", "Welcher Dienst verteilt eingehende Anfragen gleichmäßig auf mehrere Server?", "Load Balancer",
  "Er erkennt zusätzlich ausgefallene Backends und nimmt sie aus der Verteilung.",
  "Which service distributes incoming requests evenly across several servers?", "Load balancer",
  "It additionally detects failed backends and removes them from rotation."),

T("ap2-srv-r98", "Welche Eigenschaft eines Backups verlangt Abstimmung mit der Anwendung im Gastsystem?", "Anwendungskonsistenz",
  "Ohne sie kann eine Datenbank im Sicherungsstand mitten in einer Transaktion stehen.",
  "Which backup property requires coordination with the application in the guest?", "Application consistency",
  "Without it a database can sit mid-transaction in the backup state."),

T("ap2-srv-r99", "Wie nennt man die abgestufte Aufteilung der Verantwortung zwischen Cloudanbieter und Kunde?", "Geteilte Verantwortung",
  "Je nach Modell verschiebt sich die Grenze - bei IaaS liegt mehr beim Kunden als bei SaaS.",
  "What is the graded split of responsibility between cloud provider and customer called?", "Shared responsibility",
  "The boundary shifts by model - with IaaS more lies with the customer than with SaaS."),

T("ap2-srv-r100", "Welche Ressource wird auf einem virtualisierten Host meist zuerst knapp?", "Arbeitsspeicher",
  "Anders als Rechenzeit lässt er sich nicht einfach in Scheiben aufteilen, sobald er belegt ist.",
  "Which resource usually runs short first on a virtualised host?", "Main memory",
  "Unlike processing time it cannot simply be time-sliced once it is allocated."),
]

build("ap2-serverdienste-virtualisierung.json", "Serverdienste & Virtualisierung", "Server Services & Virtualisation", Q)
