#!/usr/bin/env python3
"""AP2 IT-Sicherheit & Netzwerksicherheit - 100 handgeschriebene Fragen."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from qlib import S, M, T, build

Q = [
# ---------------------------------------------------------------- single (32)
S("ap2-sec-r01",
  "In einem Eingabefeld führt die Eingabe eines Apostrophs zu einem Datenbankfehler. Worauf deutet das hin?",
  ("Auf eine mögliche SQL-Injection-Schwachstelle",
   "Auf einen zu klein gewählten Arbeitsspeicher",
   "Auf ein abgelaufenes Zertifikat der Webseite",
   "Auf eine fehlende Sicherung der Datenbank"), 0,
  "Wenn Benutzereingaben ungeprüft in eine Abfrage fließen, kann ein Angreifer sie mit Steuerzeichen umschreiben. Wirksam dagegen sind vorbereitete Anweisungen mit Parametern.",
  "In an input field, entering an apostrophe causes a database error. What does that indicate?",
  ("A possible SQL injection vulnerability",
   "Insufficient memory in the server",
   "An expired certificate on the website",
   "A missing backup of the database"),
  "When user input flows unchecked into a query, an attacker can rewrite it using control characters. Prepared statements with parameters are the effective defence."),

S("ap2-sec-r02",
  "Ein Angreifer schleust falsche Zuordnungen von IP zu MAC ins lokale Netz ein. Wie heißt der Angriff?",
  ("ARP-Spoofing", "DNS-Spoofing", "SQL-Injection", "Cross-Site-Scripting"), 0,
  "Beim ARP-Spoofing beantwortet der Angreifer ARP-Anfragen mit seiner eigenen MAC und liest den Verkehr mit. Dynamic ARP Inspection auf den Switches wirkt dagegen.",
  "An attacker injects false IP-to-MAC mappings into the local network. What is this attack called?",
  ("ARP spoofing", "DNS spoofing", "SQL injection", "Cross-site scripting"),
  "In ARP spoofing the attacker answers ARP requests with their own MAC and reads the traffic. Dynamic ARP inspection on the switches counters it."),

S("ap2-sec-r03",
  "Welche Aufgabe hat eine Zertifizierungsstelle in einer PKI?",
  ("Sie bestätigt die Zuordnung von Schlüssel und Identität",
   "Sie erzeugt und verwahrt die privaten Schlüssel aller Nutzer",
   "Sie verschlüsselt den Datenverkehr zwischen zwei Servern",
   "Sie überwacht den Netzwerkverkehr auf Auffälligkeiten"), 0,
  "Die CA signiert Zertifikate und bürgt damit für die Identität hinter einem öffentlichen Schlüssel. Der private Schlüssel bleibt immer beim Inhaber.",
  "What is the task of a certification authority in a PKI?",
  ("It confirms the binding of key and identity",
   "It generates and stores all users' private keys",
   "It encrypts the traffic between two servers",
   "It monitors network traffic for anomalies"),
  "The CA signs certificates and thereby vouches for the identity behind a public key. The private key always stays with its owner."),

S("ap2-sec-r04",
  "Ein System meldet verdächtigen Verkehr, greift aber nicht ein. Um welches System handelt es sich?",
  ("Ein IDS zur reinen Erkennung",
   "Ein IPS mit aktiver Blockierung",
   "Ein VPN-Gateway für Fernzugriffe",
   "Ein Proxy für ausgehende Anfragen"), 0,
  "Das Intrusion Detection System erkennt und alarmiert, während das Intrusion Prevention System zusätzlich eingreift und Verbindungen unterbricht.",
  "A system reports suspicious traffic but does not intervene. Which system is it?",
  ("An IDS for detection only",
   "An IPS with active blocking",
   "A VPN gateway for remote access",
   "A proxy for outgoing requests"),
  "The intrusion detection system detects and alerts, whereas the intrusion prevention system additionally intervenes and cuts connections."),

S("ap2-sec-r05",
  "Nur bekannte Geräte sollen sich am Switchport anmelden dürfen. Welches Verfahren setzt du ein?",
  ("Portbasierte Authentisierung nach 802.1X",
   "Eine längere Leasedauer im DHCP-Server",
   "Eine Portweiterleitung auf dem Router",
   "Eine höhere Priorität im QoS-Regelwerk"), 0,
  "802.1X lässt den Port erst nach erfolgreicher Anmeldung gegen einen RADIUS-Server frei. Damit nützt ein Angreifer die freie Netzwerkdose im Flur nichts.",
  "Only known devices should be allowed to connect to a switch port. Which method do you use?",
  ("Port-based authentication via 802.1X",
   "A longer lease time in the DHCP server",
   "A port forwarding rule on the router",
   "A higher priority in the QoS rule set"),
  "802.1X only opens the port after successful authentication against a RADIUS server. A network socket in the corridor is then useless to an attacker."),

S("ap2-sec-r06",
  "Welchen Zweck hat ein Salt beim Speichern von Passwörtern?",
  ("Gleiche Passwörter erzeugen unterschiedliche Hashwerte",
   "Der Hashwert lässt sich damit wieder entschlüsseln",
   "Das Passwort wird dadurch automatisch verlängert",
   "Die Anmeldung läuft dadurch spürbar schneller ab"), 0,
  "Ein zufälliger Zusatz je Konto verhindert, dass vorberechnete Tabellen funktionieren und dass gleiche Passwörter am gleichen Hash erkennbar sind.",
  "What is the purpose of a salt when storing passwords?",
  ("Identical passwords produce different hash values",
   "The hash value can then be decrypted again",
   "The password is automatically lengthened",
   "The login process becomes noticeably faster"),
  "A random per-account addition prevents precomputed tables from working and stops identical passwords being recognisable by identical hashes."),

S("ap2-sec-r07",
  "Ein Skript aus einer fremden Quelle wird im Browser des Opfers ausgeführt. Wie heißt der Angriff?",
  ("Cross-Site-Scripting", "SQL-Injection", "Port-Scanning", "Brute-Force"), 0,
  "Bei XSS schleust der Angreifer Code in eine Seite ein, den der Browser des Opfers im Vertrauenskontext dieser Seite ausführt. Konsequente Ausgabekodierung verhindert das.",
  "A script from a foreign source is executed in the victim's browser. What is this attack called?",
  ("Cross-site scripting", "SQL injection", "Port scanning", "Brute force"),
  "In XSS the attacker injects code into a page which the victim's browser executes in that page's trust context. Consistent output encoding prevents it."),

S("ap2-sec-r08",
  "Welche Kennzahl beschreibt, wie viel Datenverlust nach einem Ausfall höchstens hinnehmbar ist?",
  ("Recovery Point Objective", "Recovery Time Objective",
   "Mean Time Between Failures", "Service Level Indicator"), 0,
  "Der RPO bestimmt den maximal zulässigen Datenverlust und damit den Sicherungsabstand. Der RTO legt fest, wie lange die Wiederherstellung dauern darf.",
  "Which figure describes the maximum acceptable data loss after an outage?",
  ("Recovery point objective", "Recovery time objective",
   "Mean time between failures", "Service level indicator"),
  "The RPO defines the maximum tolerable data loss and therefore the backup interval. The RTO defines how long recovery may take."),

S("ap2-sec-r09",
  "Ein Webserver soll aus dem Internet erreichbar sein. Wo platzierst du ihn sicher?",
  ("In einer DMZ zwischen zwei Firewallzonen",
   "Direkt im internen Netz mit Portweiterleitung",
   "Im Managementnetz der aktiven Komponenten",
   "Im selben VLAN wie die Arbeitsplatzrechner"), 0,
  "In der DMZ steht der Server hinter einer Firewall zum Internet und einer weiteren zum LAN. Wird er übernommen, ist der Angreifer noch nicht im internen Netz.",
  "A web server must be reachable from the internet. Where do you place it safely?",
  ("In a DMZ between two firewall zones",
   "Directly in the internal network with port forwarding",
   "In the management network of the active components",
   "In the same VLAN as the workstation PCs"),
  "In the DMZ the server sits behind a firewall towards the internet and another towards the LAN. If it is taken over, the attacker is not yet inside the internal network."),

S("ap2-sec-r10",
  "Welches Verfahren stellt sicher, dass ein abgefangener Sitzungsschlüssel spätere Sitzungen nicht kompromittiert?",
  ("Perfect Forward Secrecy", "Symmetrische Verschlüsselung",
   "Zertifikatssperrung über eine CRL", "Portbasierte Zugangskontrolle"), 0,
  "Bei PFS wird für jede Sitzung ein flüchtiger Schlüssel ausgehandelt, der nicht aus dem Langzeitschlüssel ableitbar ist. Ein späterer Diebstahl des privaten Schlüssels entschlüsselt alte Mitschnitte damit nicht.",
  "Which method ensures that an intercepted session key does not compromise later sessions?",
  ("Perfect forward secrecy", "Symmetric encryption",
   "Certificate revocation via a CRL", "Port-based access control"),
  "With PFS an ephemeral key is negotiated for each session that cannot be derived from the long-term key. A later theft of the private key therefore does not decrypt old recordings."),

S("ap2-sec-r11",
  "Ein Angreifer betreibt einen eigenen DHCP-Server im Netz. Welche Gegenmaßnahme greift?",
  ("DHCP Snooping auf den Switches aktivieren",
   "Die Leasedauer im echten Server verlängern",
   "Einen zusätzlichen DNS-Server bereitstellen",
   "Die Sendeleistung der Access Points erhöhen"), 0,
  "DHCP Snooping erlaubt Antworten nur auf ausdrücklich als vertrauenswürdig markierten Ports. Sonst könnte der Angreifer sich als Gateway eintragen und den Verkehr mitlesen.",
  "An attacker runs their own DHCP server on the network. Which countermeasure works?",
  ("Enable DHCP snooping on the switches",
   "Extend the lease time on the real server",
   "Provide an additional DNS server",
   "Increase the access points' transmit power"),
  "DHCP snooping permits replies only on ports explicitly marked as trusted. Otherwise the attacker could register as the gateway and read the traffic."),

S("ap2-sec-r12",
  "Welche Aussage über einen Penetrationstest trifft zu?",
  ("Er prüft Systeme mit vorheriger schriftlicher Beauftragung",
   "Er wird ohne Wissen des Betreibers durchgeführt",
   "Er ersetzt die laufende Schwachstellenverwaltung",
   "Er garantiert dauerhaft ein sicheres System"), 0,
  "Ohne ausdrückliche Beauftragung wäre ein Pentest strafbar. Er liefert eine Momentaufnahme und ersetzt weder Patchmanagement noch dauerhaftes Monitoring.",
  "Which statement about a penetration test is correct?",
  ("It tests systems with prior written authorisation",
   "It is carried out without the operator's knowledge",
   "It replaces ongoing vulnerability management",
   "It permanently guarantees a secure system"),
  "Without explicit authorisation a pentest would be a criminal offence. It provides a snapshot and replaces neither patch management nor continuous monitoring."),

S("ap2-sec-r13",
  "Welcher Eintrag im DNS legt fest, welche Server für eine Domain Mails versenden dürfen?",
  ("SPF", "MX", "CNAME", "AAAA"), 0,
  "Der SPF-Eintrag listet die berechtigten Absendeserver auf und erschwert das Fälschen der Absenderadresse. MX benennt dagegen den empfangenden Mailserver.",
  "Which DNS entry defines which servers may send mail for a domain?",
  ("SPF", "MX", "CNAME", "AAAA"),
  "The SPF record lists the authorised sending servers and makes sender forgery harder. MX by contrast names the receiving mail server."),

S("ap2-sec-r14",
  "Nach welchem Grundsatz arbeitet ein Zero-Trust-Ansatz?",
  ("Jeder Zugriff wird geprüft, unabhängig vom Standort",
   "Geräte im internen Netz gelten grundsätzlich als sicher",
   "Der Zugriff wird allein anhand der IP-Adresse erlaubt",
   "Die Firewall am Netzrand genügt als Schutzmaßnahme"), 0,
  "Zero Trust verzichtet auf die Annahme eines sicheren Innenbereichs: jede Anfrage wird authentisiert und autorisiert. Der klassische Burggraben-Ansatz versagt, sobald jemand drinnen ist.",
  "On which principle does a zero trust approach work?",
  ("Every access is verified regardless of location",
   "Devices on the internal network are inherently trusted",
   "Access is granted based on the IP address alone",
   "The perimeter firewall suffices as protection"),
  "Zero trust abandons the assumption of a safe interior: every request is authenticated and authorised. The classic moat approach fails as soon as someone is inside."),

S("ap2-sec-r15",
  "Ein Dienst ist durch massenhafte Anfragen aus vielen Quellen nicht erreichbar. Wie heißt das?",
  ("Verteilter Denial-of-Service-Angriff",
   "Man-in-the-Middle-Angriff auf die Verbindung",
   "Privilegienerweiterung auf dem Zielsystem",
   "Einschleusen von Schadcode über ein Formular"), 0,
  "Beim DDoS kommt die Last aus vielen verteilten Systemen, oft einem Botnetz. Die Daten bleiben unverändert - allein die Verfügbarkeit leidet.",
  "A service is unreachable due to masses of requests from many sources. What is that called?",
  ("Distributed denial-of-service attack",
   "Man-in-the-middle attack on the connection",
   "Privilege escalation on the target system",
   "Injection of malicious code via a form"),
  "In a DDoS the load comes from many distributed systems, often a botnet. The data stays unchanged - only availability suffers."),

S("ap2-sec-r16",
  "Welche Maßnahme gehört zur Härtung eines Servers?",
  ("Nicht benötigte Dienste und Ports abschalten",
   "Zusätzliche Verwaltungswerkzeuge nachinstallieren",
   "Alle Benutzerkonten mit Administratorrechten ausstatten",
   "Die Protokollierung für mehr Leistung deaktivieren"), 0,
  "Jeder laufende Dienst ist eine potenzielle Angriffsfläche. Minimalinstallation, geschlossene Ports und eingeschränkte Rechte verkleinern sie systematisch.",
  "Which measure belongs to hardening a server?",
  ("Disable services and ports that are not needed",
   "Install additional administration tools",
   "Give all user accounts administrator rights",
   "Disable logging to gain performance"),
  "Every running service is a potential attack surface. Minimal installation, closed ports and restricted rights systematically reduce it."),

S("ap2-sec-r17",
  "Welche Aussage über symmetrische und asymmetrische Verschlüsselung im TLS-Handshake ist richtig?",
  ("Asymmetrisch wird der Sitzungsschlüssel ausgehandelt, symmetrisch verschlüsselt",
   "Der gesamte Datenverkehr wird durchgehend asymmetrisch verschlüsselt",
   "Symmetrisch wird die Identität geprüft, asymmetrisch übertragen",
   "Beide Verfahren werden abwechselnd je Datenpaket eingesetzt"), 0,
  "Asymmetrische Verfahren sind sicher im Schlüsselaustausch, aber langsam. Deshalb dient der Handshake nur der Einigung auf einen symmetrischen Sitzungsschlüssel für die eigentlichen Daten.",
  "Which statement about symmetric and asymmetric encryption in the TLS handshake is correct?",
  ("Asymmetric negotiates the session key, symmetric encrypts the data",
   "The entire traffic is encrypted asymmetrically throughout",
   "Symmetric verifies the identity, asymmetric transports it",
   "Both methods are used alternately per data packet"),
  "Asymmetric methods are secure for key exchange but slow. The handshake therefore only agrees on a symmetric session key for the actual data."),

S("ap2-sec-r18",
  "Wie prüft ein Browser, ob ein Zertifikat vorzeitig für ungültig erklärt wurde?",
  ("Über eine Sperrliste oder eine OCSP-Abfrage",
   "Über einen Vergleich der Dateigröße des Zertifikats",
   "Über die Antwortzeit des angefragten Servers",
   "Über die Anzahl der Zeichen im Domainnamen"), 0,
  "Sperrlisten und OCSP melden zurückgezogene Zertifikate, etwa nach einem Schlüsseldiebstahl. Ohne diese Prüfung bliebe ein kompromittiertes Zertifikat bis zum Ablaufdatum brauchbar.",
  "How does a browser check whether a certificate has been revoked early?",
  ("Via a revocation list or an OCSP query",
   "Via a comparison of the certificate's file size",
   "Via the response time of the queried server",
   "Via the number of characters in the domain name"),
  "Revocation lists and OCSP report withdrawn certificates, for instance after a key theft. Without this check a compromised certificate would stay usable until its expiry date."),

S("ap2-sec-r19",
  "Welche Aufgabe hat ein SIEM-System?",
  ("Es sammelt und korreliert Protokolle aus vielen Quellen",
   "Es verschlüsselt Verbindungen zwischen zwei Standorten",
   "Es verteilt Softwareaktualisierungen an die Clients",
   "Es sichert die Datenbestände auf ein zweites Medium"), 0,
  "Ein SIEM führt Ereignisse aus Firewalls, Servern und Anwendungen zusammen und erkennt Muster, die einzeln unauffällig wären. Genau daraus entstehen belastbare Alarme.",
  "What is the purpose of a SIEM system?",
  ("It collects and correlates logs from many sources",
   "It encrypts connections between two locations",
   "It distributes software updates to the clients",
   "It backs up the data to a second medium"),
  "A SIEM brings together events from firewalls, servers and applications and detects patterns that would be inconspicuous individually. Sound alerts emerge from exactly that."),

S("ap2-sec-r20",
  "Ein Angreifer nutzt ein Konto mit normalen Rechten und erlangt Systemrechte. Wie heißt das?",
  ("Privilegienerweiterung", "Portweiterleitung",
   "Namensauflösung", "Lastverteilung"), 0,
  "Bei der Privilege Escalation nutzt der Angreifer eine Schwachstelle, um über die ihm zugewiesenen Rechte hinauszukommen. Aktuelle Patches und minimale Rechte erschweren das erheblich.",
  "An attacker uses an ordinary account and gains system rights. What is this called?",
  ("Privilege escalation", "Port forwarding",
   "Name resolution", "Load balancing"),
  "In privilege escalation the attacker exploits a vulnerability to go beyond the rights assigned to them. Current patches and least privilege make this considerably harder."),

S("ap2-sec-r21",
  "Welche Angabe beschreibt der CVSS-Wert einer Schwachstelle?",
  ("Ihren Schweregrad auf einer Skala von 0 bis 10",
   "Das Datum ihrer Veröffentlichung durch den Hersteller",
   "Die Anzahl der weltweit betroffenen Systeme",
   "Den Preis für den passenden Sicherheitspatch"), 0,
  "Das Common Vulnerability Scoring System bewertet unter anderem Angriffsvektor, Komplexität und Auswirkung. Der Wert hilft, Patches nach Dringlichkeit zu priorisieren.",
  "What does the CVSS value of a vulnerability describe?",
  ("Its severity on a scale from 0 to 10",
   "The date of its publication by the vendor",
   "The number of affected systems worldwide",
   "The price of the matching security patch"),
  "The common vulnerability scoring system rates attack vector, complexity and impact among others. The value helps prioritise patches by urgency."),

S("ap2-sec-r22",
  "Ein Notebook im VPN soll den Internetverkehr weiter direkt ins Netz senden. Wie heißt diese Konfiguration?",
  ("Split Tunneling", "Full Tunneling", "Port Mirroring", "Load Balancing"), 0,
  "Beim Split Tunneling geht nur der Firmenverkehr durch den Tunnel. Das entlastet das Gateway, umgeht aber die zentralen Schutzmechanismen für den übrigen Verkehr.",
  "A laptop on VPN should keep sending internet traffic directly. What is this configuration called?",
  ("Split tunnelling", "Full tunnelling", "Port mirroring", "Load balancing"),
  "With split tunnelling only company traffic goes through the tunnel. That relieves the gateway but bypasses central protection for the remaining traffic."),

S("ap2-sec-r23",
  "Welches Verfahren authentisiert WLAN-Nutzer einzeln gegen einen zentralen Server?",
  ("WPA2-Enterprise mit RADIUS",
   "WPA2-Personal mit gemeinsamem Schlüssel",
   "Eine Filterung anhand der MAC-Adressen",
   "Eine versteckte Netzwerkkennung im Funknetz"), 0,
  "Im Enterprise-Modus meldet sich jeder Nutzer mit eigenen Zugangsdaten an. Beim gemeinsamen Schlüssel muss beim Ausscheiden eines Mitarbeiters das Passwort überall gewechselt werden.",
  "Which method authenticates WLAN users individually against a central server?",
  ("WPA2-Enterprise with RADIUS",
   "WPA2-Personal with a shared key",
   "Filtering based on MAC addresses",
   "A hidden network name in the radio cell"),
  "In enterprise mode every user logs in with their own credentials. With a shared key the password must be changed everywhere when an employee leaves."),

S("ap2-sec-r24",
  "Welche Aussage über einen Honeypot ist zutreffend?",
  ("Ein absichtlich verwundbares System zum Beobachten von Angriffen",
   "Ein besonders gut gehärteter Server für kritische Daten",
   "Ein Sicherungssystem für ausgelagerte Datenbestände",
   "Ein Verfahren zur Verschlüsselung von Datenträgern"), 0,
  "Der Honeypot lockt Angreifer an und liefert Erkenntnisse über Vorgehen und Werkzeuge. Er muss streng vom Produktivnetz getrennt sein.",
  "Which statement about a honeypot is correct?",
  ("A deliberately vulnerable system for observing attacks",
   "A particularly hardened server for critical data",
   "A backup system for externally stored data",
   "A method for encrypting storage media"),
  "The honeypot attracts attackers and yields insight into their methods and tools. It must be strictly separated from the production network."),

S("ap2-sec-r25",
  "Ein Angreifer manipuliert Antworten der Namensauflösung. Welche Folge hat das?",
  ("Nutzer landen unbemerkt auf einem falschen Server",
   "Die Bandbreite der Leitung sinkt deutlich ab",
   "Die Datenbank verliert ihre Transaktionsprotokolle",
   "Die Zertifikate der Server verlieren ihre Gültigkeit"), 0,
  "Beim DNS-Spoofing zeigt ein korrekt eingegebener Name auf die Adresse des Angreifers. Nur die Zertifikatsprüfung von HTTPS macht die Täuschung sichtbar.",
  "An attacker manipulates name resolution responses. What is the consequence?",
  ("Users unknowingly end up on a false server",
   "The bandwidth of the line drops noticeably",
   "The database loses its transaction logs",
   "The servers' certificates lose their validity"),
  "In DNS spoofing a correctly typed name points to the attacker's address. Only the certificate check in HTTPS makes the deception visible."),

S("ap2-sec-r26",
  "Welche Norm beschreibt die Anforderungen an ein Informationssicherheits-Managementsystem?",
  ("ISO 27001", "ISO 9001", "ISO 14001", "ISO 20000"), 0,
  "ISO 27001 legt fest, wie ein ISMS aufgebaut, betrieben und verbessert wird. ISO 9001 regelt Qualitätsmanagement, 14001 Umweltmanagement und 20000 IT-Service-Management.",
  "Which standard describes the requirements for an information security management system?",
  ("ISO 27001", "ISO 9001", "ISO 14001", "ISO 20000"),
  "ISO 27001 defines how an ISMS is built, operated and improved. ISO 9001 governs quality management, 14001 environmental management and 20000 IT service management."),

S("ap2-sec-r27",
  "Ein Dienstkonto benötigt nur Lesezugriff auf ein Verzeichnis, hat aber Vollzugriff. Was ist zu tun?",
  ("Die Rechte auf das notwendige Maß zurücksetzen",
   "Ein zweites Konto mit Lesezugriff zusätzlich anlegen",
   "Das Konto vorsichtshalber vollständig deaktivieren",
   "Die Protokollierung für dieses Konto abschalten"), 0,
  "Dienstkonten sind ein beliebtes Angriffsziel, weil sie oft überprivilegiert und selten überwacht sind. Rechte auf das Nötige zu reduzieren begrenzt den Schaden bei Missbrauch.",
  "A service account only needs read access to a directory but has full control. What must be done?",
  ("Reduce the rights to the necessary level",
   "Additionally create a second read-only account",
   "Disable the account entirely as a precaution",
   "Turn off logging for this account"),
  "Service accounts are a popular target because they are often over-privileged and rarely monitored. Reducing rights to what is needed limits the damage from misuse."),

S("ap2-sec-r28",
  "Was prüft eine Firewall mit Deep Packet Inspection zusätzlich?",
  ("Den Inhalt der Pakete auf Anwendungsebene",
   "Ausschließlich Quell- und Zieladresse der Pakete",
   "Allein die physische Länge des Netzwerkkabels",
   "Nur die Reihenfolge der eingehenden Pakete"), 0,
  "DPI schaut in die Nutzdaten und erkennt Anwendungen und Schadmuster unabhängig vom verwendeten Port. Klassische Paketfilter sehen nur Kopfdaten.",
  "What does a firewall with deep packet inspection additionally examine?",
  ("The content of packets at application level",
   "Exclusively source and destination addresses",
   "Solely the physical length of the network cable",
   "Only the order of the incoming packets"),
  "DPI looks into the payload and recognises applications and malicious patterns regardless of the port used. Classic packet filters see only header data."),

S("ap2-sec-r29",
  "Nach welchem Prinzip sollte ein Firewallregelwerk aufgebaut sein?",
  ("Alles verbieten und nur Benötigtes ausdrücklich erlauben",
   "Alles erlauben und nur Auffälliges gezielt verbieten",
   "Regeln nach Eingangsdatum der Anträge sortieren",
   "Regeln ausschließlich nach Portnummern gruppieren"), 0,
  "Ein Default-Deny lässt nur bewusst freigegebene Verbindungen zu. Bei Default-Allow bleibt jede vergessene Einschränkung eine offene Tür.",
  "On which principle should a firewall rule set be built?",
  ("Deny everything and explicitly permit only what is needed",
   "Permit everything and selectively deny what looks odd",
   "Sort rules by the date the requests arrived",
   "Group rules exclusively by port numbers"),
  "A default deny only allows deliberately released connections. With default allow every forgotten restriction remains an open door."),

S("ap2-sec-r30",
  "Welches Hashverfahren gilt heute für Prüfsummen als sicher?",
  ("SHA-256", "MD5", "SHA-1", "CRC32"), 0,
  "MD5 und SHA-1 sind wegen praktikabler Kollisionen abgelöst, CRC32 ist eine reine Fehlererkennung ohne kryptografische Eigenschaften.",
  "Which hash method is considered secure for checksums today?",
  ("SHA-256", "MD5", "SHA-1", "CRC32"),
  "MD5 and SHA-1 have been retired due to practical collisions, and CRC32 is pure error detection without cryptographic properties."),

S("ap2-sec-r31",
  "Ein Mitarbeiter meldet einen Verdacht auf Kompromittierung. Was ist der erste Schritt?",
  ("Den Vorfall aufnehmen und das System isolieren",
   "Das System sofort neu aufsetzen und weiterarbeiten",
   "Die Protokolldateien zur Entlastung löschen",
   "Den Vorfall bis zur Klärung für sich behalten"), 0,
  "Isolieren stoppt die Ausbreitung, die Aufnahme sichert Spuren für die spätere Analyse. Ein sofortiges Neuaufsetzen vernichtet genau die Beweise, die man zur Ursachenklärung braucht.",
  "An employee reports a suspected compromise. What is the first step?",
  ("Record the incident and isolate the system",
   "Immediately rebuild the system and carry on",
   "Delete the log files to reduce liability",
   "Keep the incident quiet until it is clarified"),
  "Isolation stops the spread, and recording preserves traces for later analysis. Rebuilding immediately destroys exactly the evidence needed to find the cause."),

S("ap2-sec-r32",
  "Welche Aussage über die Protokollierung sicherheitsrelevanter Ereignisse ist richtig?",
  ("Protokolle gehören zentral und schreibgeschützt abgelegt",
   "Protokolle sollten nur lokal auf dem Gerät verbleiben",
   "Protokolle dürfen jederzeit von jedem geändert werden",
   "Protokolle sind nach einem Tag zwingend zu löschen"), 0,
  "Ein Angreifer räumt als Erstes lokale Spuren auf. Eine zentrale, unveränderbare Ablage bewahrt die Nachvollziehbarkeit und ist Grundlage jeder Auswertung.",
  "Which statement about logging security-relevant events is correct?",
  ("Logs belong in central, write-protected storage",
   "Logs should remain only locally on the device",
   "Logs may be changed by anyone at any time",
   "Logs must be deleted after one day"),
  "An attacker cleans up local traces first. Central, immutable storage preserves traceability and is the basis of any analysis."),

# -------------------------------------------------------------- multiple (32)
M("ap2-sec-r33",
  "Welche Maßnahmen schützen eine Webanwendung vor SQL-Injection?",
  ("Vorbereitete Anweisungen mit Parametern nutzen",
   "Eingaben serverseitig streng validieren",
   "Datenbankrechte der Anwendung minimal halten",
   "Fehlermeldungen ohne technische Details ausgeben",
   "Eingaben nur im Browser per Skript prüfen",
   "Der Anwendung Administratorrechte auf der Datenbank geben"),
  (0, 1, 2, 3),
  "Parametrisierte Abfragen trennen Code von Daten und sind die eigentliche Lösung, flankiert von Validierung, minimalen Rechten und sparsamen Fehlermeldungen. Clientseitige Prüfungen lassen sich umgehen.",
  "Which measures protect a web application against SQL injection?",
  ("Use prepared statements with parameters",
   "Validate input strictly on the server side",
   "Keep the application's database rights minimal",
   "Emit error messages without technical detail",
   "Validate input only in the browser via script",
   "Give the application administrator rights on the database"),
  "Parameterised queries separate code from data and are the actual solution, flanked by validation, minimal rights and sparse error messages. Client-side checks can be bypassed."),

M("ap2-sec-r34",
  "Welche Angriffe zielen auf die Verfügbarkeit eines Systems?",
  ("Denial of Service durch Überlastung",
   "Verteilter Angriff aus einem Botnetz",
   "Verschlüsselung der Daten durch Ransomware",
   "Zerstörung von Konfigurationsdaten",
   "Unbemerktes Mitlesen vertraulicher Daten",
   "Fälschen einer Absenderadresse in einer Mail"),
  (0, 1, 2, 3),
  "Überlast, Botnetzangriffe, Verschlüsselung und Zerstörung machen Systeme unbenutzbar. Mitlesen trifft die Vertraulichkeit, Absenderfälschung die Authentizität.",
  "Which attacks target the availability of a system?",
  ("Denial of service through overload",
   "Distributed attack from a botnet",
   "Encryption of the data by ransomware",
   "Destruction of configuration data",
   "Unnoticed interception of confidential data",
   "Forging a sender address in an email"),
  "Overload, botnet attacks, encryption and destruction render systems unusable. Interception hits confidentiality, sender forgery authenticity."),

M("ap2-sec-r35",
  "Welche Bestandteile gehören zu einer PKI?",
  ("Eine Zertifizierungsstelle", "Eine Registrierungsstelle",
   "Ein Verzeichnis für ausgestellte Zertifikate", "Ein Verfahren zum Sperren von Zertifikaten",
   "Ein zentrales Verzeichnis aller privaten Schlüssel", "Ein Verfahren zum Löschen aller Protokolle"),
  (0, 1, 2, 3),
  "CA, RA, Verzeichnis und Sperrmechanismus bilden die Public-Key-Infrastruktur. Private Schlüssel liegen niemals zentral - genau das wäre der Totalschaden.",
  "Which components belong to a PKI?",
  ("A certification authority", "A registration authority",
   "A directory of issued certificates", "A mechanism for revoking certificates",
   "A central directory of all private keys", "A mechanism for deleting all logs"),
  "CA, RA, directory and revocation form the public key infrastructure. Private keys are never held centrally - that would be exactly the catastrophic case."),

M("ap2-sec-r36",
  "Welche Maßnahmen härten einen Switch gegen Angriffe im Zugangsnetz?",
  ("Port Security mit erlaubten MAC-Adressen",
   "802.1X zur Authentisierung am Port",
   "DHCP Snooping gegen fremde DHCP-Server",
   "Dynamic ARP Inspection gegen ARP-Spoofing",
   "Aktivieren aller nicht genutzten Ports",
   "Verwendung des Standardpassworts für die Verwaltung"),
  (0, 1, 2, 3),
  "Portsicherheit, 802.1X, DHCP Snooping und ARP Inspection schließen die klassischen Lücken im Zugangsnetz. Offene Ports und Standardpasswörter reißen sie wieder auf.",
  "Which measures harden a switch against attacks in the access network?",
  ("Port security with permitted MAC addresses",
   "802.1X for authentication at the port",
   "DHCP snooping against rogue DHCP servers",
   "Dynamic ARP inspection against ARP spoofing",
   "Enabling all unused ports",
   "Using the default password for management"),
  "Port security, 802.1X, DHCP snooping and ARP inspection close the classic gaps in the access network. Open ports and default passwords tear them open again."),

M("ap2-sec-r37",
  "Welche Aussagen über TLS sind korrekt?",
  ("Es verschlüsselt die Verbindung zwischen Client und Server",
   "Es prüft die Identität des Servers über ein Zertifikat",
   "Es sichert die Integrität der übertragenen Daten",
   "Es handelt einen symmetrischen Sitzungsschlüssel aus",
   "Es schützt die Daten auch nach dem Empfang auf der Festplatte",
   "Es macht eine Zugriffskontrolle auf dem Server überflüssig"),
  (0, 1, 2, 3),
  "TLS sichert den Transportweg mit Vertraulichkeit, Authentizität und Integrität. Was auf dem Server passiert, liegt außerhalb seiner Zuständigkeit.",
  "Which statements about TLS are correct?",
  ("It encrypts the connection between client and server",
   "It verifies the server's identity via a certificate",
   "It secures the integrity of the transmitted data",
   "It negotiates a symmetric session key",
   "It protects the data on disk after receipt",
   "It makes access control on the server unnecessary"),
  "TLS secures the transport path with confidentiality, authenticity and integrity. What happens on the server lies outside its remit."),

M("ap2-sec-r38",
  "Welche Schritte gehören zur Behandlung eines Sicherheitsvorfalls?",
  ("Vorfall erkennen und bewerten",
   "Betroffene Systeme isolieren",
   "Spuren für die Analyse sichern",
   "Ursache beseitigen und Betrieb wiederherstellen",
   "Protokolle vorsorglich löschen",
   "Betroffene Systeme sofort neu installieren"),
  (0, 1, 2, 3),
  "Erkennen, Eindämmen, Beweissicherung und Wiederherstellung bilden den Ablauf, abgeschlossen durch die Nachbereitung. Löschen und voreiliges Neuinstallieren vernichten die Spuren.",
  "Which steps belong to handling a security incident?",
  ("Detect and assess the incident",
   "Isolate the affected systems",
   "Preserve evidence for analysis",
   "Eradicate the cause and restore operation",
   "Delete logs as a precaution",
   "Reinstall the affected systems immediately"),
  "Detection, containment, evidence preservation and recovery form the sequence, closed by a review. Deleting and premature reinstalling destroy the traces."),

M("ap2-sec-r39",
  "Welche Merkmale kennzeichnen einen Man-in-the-Middle-Angriff?",
  ("Der Angreifer sitzt zwischen den Kommunikationspartnern",
   "Er kann den Verkehr mitlesen",
   "Er kann Inhalte unbemerkt verändern",
   "Zertifikatsprüfung erschwert den Angriff erheblich",
   "Er benötigt zwingend physischen Zugriff auf den Server",
   "Er lässt sich durch längere Passwörter verhindern"),
  (0, 1, 2, 3),
  "Der Angreifer klinkt sich in die Verbindung ein und kann lesen wie verändern. Eine geprüfte Zertifikatskette macht das sichtbar; Passwortlänge hilft dagegen nicht.",
  "Which characteristics define a man-in-the-middle attack?",
  ("The attacker sits between the communicating parties",
   "They can read the traffic",
   "They can alter content unnoticed",
   "Certificate checking makes the attack much harder",
   "It strictly requires physical access to the server",
   "It can be prevented by longer passwords"),
  "The attacker interposes in the connection and can both read and modify. A verified certificate chain makes this visible; password length does not help."),

M("ap2-sec-r40",
  "Welche Angaben gehören in eine Firewallregel-Dokumentation?",
  ("Zweck und fachliche Begründung der Regel",
   "Quelle, Ziel und freigegebener Dienst",
   "Antragsteller und Freigabedatum",
   "Geplante Überprüfung oder Befristung",
   "Das Passwort des Firewalladministrators",
   "Die Anzahl der Kabel im Serverschrank"),
  (0, 1, 2, 3),
  "Ohne Begründung und Verantwortlichkeit wächst jedes Regelwerk zu einem undurchschaubaren Dickicht. Befristungen erzwingen die regelmäßige Überprüfung.",
  "Which details belong in firewall rule documentation?",
  ("Purpose and business justification of the rule",
   "Source, destination and released service",
   "Requester and approval date",
   "Planned review or expiry",
   "The firewall administrator's password",
   "The number of cables in the server rack"),
  "Without justification and ownership every rule set grows into an unresolvable tangle. Expiry dates enforce regular review."),

M("ap2-sec-r41",
  "Welche Aussagen über Ransomware und ihre Abwehr sind zutreffend?",
  ("Erreichbare Netzlaufwerke werden mitverschlüsselt",
   "Offline gelagerte Sicherungen überstehen den Angriff",
   "Unveränderbare Sicherungen bieten zusätzlichen Schutz",
   "Netzsegmentierung begrenzt die Ausbreitung",
   "Ein Virenscanner allein verhindert jeden Befall",
   "Die Zahlung des Lösegelds garantiert die Entschlüsselung"),
  (0, 1, 2, 3),
  "Ransomware folgt jedem erreichbaren Pfad, deshalb wirken Trennung und Unveränderbarkeit der Sicherungen. Scanner sind eine Schicht von mehreren, und Zahlungen garantieren gar nichts.",
  "Which statements about ransomware and its defence are correct?",
  ("Reachable network drives are encrypted too",
   "Backups stored offline survive the attack",
   "Immutable backups provide additional protection",
   "Network segmentation limits the spread",
   "A virus scanner alone prevents any infection",
   "Paying the ransom guarantees decryption"),
  "Ransomware follows every reachable path, which is why separation and immutability of backups work. Scanners are one layer among several, and payment guarantees nothing."),

M("ap2-sec-r42",
  "Welche Verfahren erhöhen die Sicherheit des E-Mail-Versands einer Domain?",
  ("SPF zur Festlegung berechtigter Absendeserver",
   "DKIM zur Signatur ausgehender Nachrichten",
   "DMARC als Richtlinie für den Umgang mit Verstößen",
   "TLS für die Übertragung zwischen Mailservern",
   "Der Verzicht auf jede Absenderprüfung",
   "Die Veröffentlichung aller Postfachpasswörter"),
  (0, 1, 2, 3),
  "SPF, DKIM und DMARC greifen ineinander und erschweren das Fälschen der Absenderdomain erheblich, TLS schützt den Transportweg. Die letzten beiden Punkte wären grob fahrlässig.",
  "Which methods increase the security of a domain's email sending?",
  ("SPF to define authorised sending servers",
   "DKIM to sign outgoing messages",
   "DMARC as a policy for handling violations",
   "TLS for transport between mail servers",
   "Doing without any sender verification",
   "Publishing all mailbox passwords"),
  "SPF, DKIM and DMARC interlock and make forging the sender domain considerably harder, while TLS protects the transport path. The last two points would be grossly negligent."),

M("ap2-sec-r43",
  "Welche Aussagen über Schwachstellenmanagement sind richtig?",
  ("Systeme werden regelmäßig auf bekannte Lücken geprüft",
   "Der CVSS-Wert hilft bei der Priorisierung",
   "Gefundene Lücken werden nachverfolgt bis zur Behebung",
   "Auch Systeme ohne Internetzugang werden erfasst",
   "Ein einmaliger Scan im Jahr genügt vollständig",
   "Nur Systeme mit öffentlicher IP sind betroffen"),
  (0, 1, 2, 3),
  "Wirksam ist ein laufender Prozess mit Priorisierung und Nachverfolgung über den gesamten Bestand. Interne Systeme geraten spätestens dann ins Visier, wenn ein Angreifer bereits im Netz ist.",
  "Which statements about vulnerability management are correct?",
  ("Systems are checked regularly for known gaps",
   "The CVSS value helps with prioritisation",
   "Findings are tracked through to remediation",
   "Systems without internet access are covered too",
   "A single scan per year is entirely sufficient",
   "Only systems with a public IP are affected"),
  "What works is a continuous process with prioritisation and tracking across the whole estate. Internal systems come into focus at the latest once an attacker is already inside."),

M("ap2-sec-r44",
  "Welche Vorteile bringt die Segmentierung eines Netzes für die Sicherheit?",
  ("Ein Angreifer erreicht nicht sofort alle Systeme",
   "Verkehr zwischen Segmenten lässt sich kontrollieren",
   "Besonders schützenswerte Systeme lassen sich absondern",
   "Die Ausbreitung von Schadsoftware wird gebremst",
   "Die Bandbreite je Segment verdoppelt sich",
   "Virenschutz auf den Endgeräten wird entbehrlich"),
  (0, 1, 2, 3),
  "Segmentierung schafft Kontrollpunkte und begrenzt die seitliche Bewegung im Netz. An Bandbreite und Endgeräteschutz ändert sie nichts.",
  "Which security advantages does network segmentation bring?",
  ("An attacker does not immediately reach all systems",
   "Traffic between segments can be controlled",
   "Particularly sensitive systems can be isolated",
   "The spread of malware is slowed down",
   "The bandwidth per segment doubles",
   "Endpoint antivirus becomes dispensable"),
  "Segmentation creates control points and limits lateral movement. It changes nothing about bandwidth or endpoint protection."),

M("ap2-sec-r45",
  "Welche Aussagen über Zwei-Faktor-Verfahren im Unternehmensumfeld sind korrekt?",
  ("Ein gestohlenes Passwort allein genügt nicht mehr",
   "Hardware-Token gelten als besonders robust",
   "Authenticator-Apps sind sicherer als SMS",
   "Der Schutz von Fernzugängen ist besonders wichtig",
   "Zwei nacheinander eingegebene Passwörter genügen",
   "Der Benutzername zählt als zweiter Faktor"),
  (0, 1, 2, 3),
  "Ein echter zweiter Faktor stammt aus einer anderen Kategorie und ist gerade bei Fernzugängen entscheidend. Zwei Passwörter bleiben beide Wissen, und der Benutzername ist kein Geheimnis.",
  "Which statements about two-factor methods in a corporate setting are correct?",
  ("A stolen password alone is no longer sufficient",
   "Hardware tokens are considered particularly robust",
   "Authenticator apps are safer than SMS",
   "Protecting remote access is especially important",
   "Two passwords entered in sequence suffice",
   "The username counts as a second factor"),
  "A genuine second factor comes from a different category and matters especially for remote access. Two passwords are both knowledge, and the username is not a secret."),

M("ap2-sec-r46",
  "Welche Angaben braucht ein Notfallkonzept für kritische IT-Systeme?",
  ("Zulässige Ausfallzeit je System",
   "Zulässiger Datenverlust je System",
   "Benannte Verantwortliche und Meldewege",
   "Beschriebene Wiederanlaufreihenfolge",
   "Die Anschaffungspreise der Hardware",
   "Die Urlaubswünsche der Fachabteilungen"),
  (0, 1, 2, 3),
  "RTO, RPO, Zuständigkeiten und Wiederanlaufreihenfolge machen den Ernstfall beherrschbar. Kaufmännisches und Organisatorisches gehört in andere Unterlagen.",
  "Which details does an emergency plan for critical IT systems need?",
  ("Permissible downtime per system",
   "Permissible data loss per system",
   "Named responsibilities and reporting paths",
   "A described restart sequence",
   "The purchase prices of the hardware",
   "The holiday preferences of the departments"),
  "RTO, RPO, responsibilities and restart order make an emergency manageable. Commercial and organisational matters belong in other documents."),

M("ap2-sec-r47",
  "Welche Aussagen über Passwortspeicherung sind zutreffend?",
  ("Passwörter werden nur als Hashwert gespeichert",
   "Ein Salt je Konto verhindert vorberechnete Tabellen",
   "Langsame Hashverfahren erschweren das Durchprobieren",
   "Klartextspeicherung ist ein schwerer Mangel",
   "Eine Verschlüsselung ist gleichwertig zum Hashen",
   "Der Salt muss geheim gehalten werden"),
  (0, 1, 2, 3),
  "Hash plus Salt plus bewusst langsames Verfahren ist der Stand der Technik. Verschlüsselung wäre umkehrbar, und der Salt darf offen neben dem Hash stehen.",
  "Which statements about password storage are correct?",
  ("Passwords are stored only as a hash value",
   "A salt per account defeats precomputed tables",
   "Slow hash functions hinder brute forcing",
   "Storing plain text is a severe deficiency",
   "Encryption is equivalent to hashing",
   "The salt has to be kept secret"),
  "Hash plus salt plus a deliberately slow function is the state of the art. Encryption would be reversible, and the salt may sit openly next to the hash."),

M("ap2-sec-r48",
  "Welche Aussagen über ein VPN für Heimarbeitsplätze sind korrekt?",
  ("Der Verkehr wird bis ins Firmennetz verschlüsselt",
   "Die Gegenstelle wird vor dem Aufbau authentisiert",
   "Interne Ressourcen werden erreichbar",
   "Ein zweiter Faktor erhöht die Sicherheit deutlich",
   "Das Endgerät braucht danach keinen Virenschutz",
   "Die Internetleitung wird dadurch schneller"),
  (0, 1, 2, 3),
  "Ein VPN schützt den Transportweg und ermöglicht den Zugriff, gehört aber unbedingt mit starker Anmeldung abgesichert. Ein infiziertes Endgerät bringt den Schadcode direkt mit hinein.",
  "Which statements about a VPN for home workplaces are correct?",
  ("Traffic is encrypted all the way into the company network",
   "The remote end is authenticated before connecting",
   "Internal resources become reachable",
   "A second factor considerably raises security",
   "The device then needs no antivirus protection",
   "The internet line becomes faster"),
  "A VPN protects the transport path and enables access but must be secured with strong authentication. An infected device carries the malicious code straight inside."),

M("ap2-sec-r49",
  "Welche Merkmale hat eine gute Sicherheitsrichtlinie?",
  ("Sie ist verständlich formuliert",
   "Sie benennt Verantwortlichkeiten",
   "Sie wird regelmäßig überprüft",
   "Sie wird von der Leitung getragen",
   "Sie ist bewusst möglichst unbestimmt gehalten",
   "Sie gilt ausdrücklich nicht für Führungskräfte"),
  (0, 1, 2, 3),
  "Verständlichkeit, klare Zuständigkeiten, regelmäßige Pflege und Rückhalt der Leitung entscheiden über die Wirkung. Ausnahmen für einzelne Gruppen untergraben die Glaubwürdigkeit.",
  "Which characteristics does a good security policy have?",
  ("It is formulated understandably",
   "It names responsibilities",
   "It is reviewed regularly",
   "It is backed by management",
   "It is deliberately kept as vague as possible",
   "It explicitly does not apply to managers"),
  "Clarity, clear ownership, regular maintenance and management backing decide its effect. Exceptions for individual groups undermine credibility."),

M("ap2-sec-r50",
  "Welche Angriffsarten richten sich gegen Webanwendungen?",
  ("SQL-Injection über Eingabefelder",
   "Cross-Site-Scripting im Browser des Opfers",
   "Cross-Site-Request-Forgery über fremde Seiten",
   "Ausnutzen unsicherer Sitzungsverwaltung",
   "ARP-Spoofing im lokalen Segment",
   "Physischer Diebstahl eines Notebooks"),
  (0, 1, 2, 3),
  "Injection, XSS, CSRF und Sitzungsprobleme sind die Klassiker auf Anwendungsebene. ARP-Spoofing ist ein Netzangriff und Diebstahl ein physisches Risiko.",
  "Which types of attack target web applications?",
  ("SQL injection via input fields",
   "Cross-site scripting in the victim's browser",
   "Cross-site request forgery via foreign pages",
   "Exploiting insecure session management",
   "ARP spoofing in the local segment",
   "Physical theft of a laptop"),
  "Injection, XSS, CSRF and session problems are the classics at application level. ARP spoofing is a network attack and theft a physical risk."),

M("ap2-sec-r51",
  "Welche Aufgaben erfüllt ein Reverse Proxy im Sicherheitskonzept?",
  ("Er ist zentraler Eintrittspunkt von außen",
   "Er kann TLS zentral terminieren",
   "Er verbirgt die interne Struktur",
   "Er kann Anfragen filtern und begrenzen",
   "Er ersetzt die Absicherung der Anwendung selbst",
   "Er sichert die Datenbank der Anwendung mit"),
  (0, 1, 2, 3),
  "Ein zentraler Eintrittspunkt erlaubt einheitliche Prüfung, Verschlüsselung und Begrenzung. Die Anwendung selbst muss trotzdem sicher gebaut sein.",
  "Which tasks does a reverse proxy perform in a security concept?",
  ("It is the central entry point from outside",
   "It can terminate TLS centrally",
   "It hides the internal structure",
   "It can filter and rate-limit requests",
   "It replaces securing the application itself",
   "It also backs up the application's database"),
  "A central entry point allows uniform inspection, encryption and rate limiting. The application itself must still be built securely."),

M("ap2-sec-r52",
  "Welche Aussagen über Protokolle und Forensik sind richtig?",
  ("Zentrale Ablage schützt vor nachträglicher Änderung",
   "Zeitsynchronisation ist für die Auswertung entscheidend",
   "Aufbewahrungsfristen müssen festgelegt sein",
   "Zugriff auf Protokolle wird eingeschränkt",
   "Protokolle dürfen personenbezogene Daten unbegrenzt speichern",
   "Uhrzeiten der Systeme dürfen beliebig abweichen"),
  (0, 1, 2, 3),
  "Ohne synchrone Uhren lässt sich kein Ablauf über mehrere Systeme rekonstruieren. Fristen und Zugriffsbeschränkung wahren zugleich den Datenschutz.",
  "Which statements about logs and forensics are correct?",
  ("Central storage protects against later modification",
   "Time synchronisation is decisive for analysis",
   "Retention periods have to be defined",
   "Access to logs is restricted",
   "Logs may store personal data indefinitely",
   "System clocks may deviate arbitrarily"),
  "Without synchronised clocks no sequence across several systems can be reconstructed. Retention periods and restricted access simultaneously preserve data protection."),

M("ap2-sec-r53",
  "Welche Aussagen über asymmetrische Verschlüsselung sind zutreffend?",
  ("Es gibt ein Schlüsselpaar aus öffentlich und privat",
   "Verschlüsselt wird mit dem öffentlichen Schlüssel",
   "Signiert wird mit dem privaten Schlüssel",
   "Sie löst das Problem des Schlüsselaustauschs",
   "Sie ist schneller als symmetrische Verfahren",
   "Beide Schlüssel dürfen veröffentlicht werden"),
  (0, 1, 2, 3),
  "Das Schlüsselpaar trennt Verschlüsseln und Entschlüsseln und macht den sicheren Austausch überhaupt erst praktikabel. Der Preis ist deutlich geringere Geschwindigkeit.",
  "Which statements about asymmetric encryption are correct?",
  ("There is a key pair of public and private",
   "Encryption uses the public key",
   "Signing uses the private key",
   "It solves the key exchange problem",
   "It is faster than symmetric methods",
   "Both keys may be published"),
  "The key pair separates encryption from decryption and makes secure exchange practical in the first place. The price is considerably lower speed."),

M("ap2-sec-r54",
  "Welche Maßnahmen begrenzen den Schaden eines übernommenen Benutzerkontos?",
  ("Minimale Rechtevergabe je Konto",
   "Netzsegmentierung zwischen Bereichen",
   "Mehrfaktor-Anmeldung an kritischen Diensten",
   "Überwachung ungewöhnlicher Anmeldemuster",
   "Gemeinsame Konten für ganze Abteilungen",
   "Dauerhafte Administratorrechte für alle Nutzer"),
  (0, 1, 2, 3),
  "Weniger Rechte, kleinere Segmente, starke Anmeldung und Auffälligkeitserkennung begrenzen die Reichweite eines übernommenen Kontos. Sammelkonten und Vollrechte vergrößern sie massiv.",
  "Which measures limit the damage from a compromised user account?",
  ("Minimal rights assignment per account",
   "Network segmentation between areas",
   "Multi-factor login for critical services",
   "Monitoring of unusual login patterns",
   "Shared accounts for entire departments",
   "Permanent administrator rights for all users"),
  "Fewer rights, smaller segments, strong authentication and anomaly detection limit the reach of a compromised account. Shared accounts and full rights massively increase it."),

M("ap2-sec-r55",
  "Welche Aussagen über Patchmanagement sind korrekt?",
  ("Sicherheitsupdates werden priorisiert eingespielt",
   "Ein Testlauf vor dem Ausrollen mindert Risiken",
   "Der Patchstand wird nachvollziehbar dokumentiert",
   "Ein Rückweg für fehlgeschlagene Updates ist eingeplant",
   "Updates werden erst nach einem Vorfall eingespielt",
   "Testsysteme brauchen grundsätzlich keine Patches"),
  (0, 1, 2, 3),
  "Priorisierung, Test, Dokumentation und Rückweg machen Patchen beherrschbar. Zu warten überlässt Angreifern das Zeitfenster, und Testsysteme hängen oft am selben Netz.",
  "Which statements about patch management are correct?",
  ("Security updates are applied with priority",
   "A test run before rollout reduces risk",
   "The patch level is documented traceably",
   "A rollback path for failed updates is planned",
   "Updates are applied only after an incident",
   "Test systems fundamentally need no patches"),
  "Prioritisation, testing, documentation and a rollback path make patching manageable. Waiting hands attackers the window, and test systems often sit on the same network."),

M("ap2-sec-r56",
  "Welche Aussagen über eine Firewall im Unternehmensnetz sind zutreffend?",
  ("Sie trennt Zonen unterschiedlichen Schutzbedarfs",
   "Sie arbeitet nach dem Prinzip Default Deny",
   "Sie protokolliert verworfene Verbindungen",
   "Ihr Regelwerk wird regelmäßig überprüft",
   "Sie erkennt und entfernt Schadsoftware von Clients",
   "Sie macht Endgerätesicherheit überflüssig"),
  (0, 1, 2, 3),
  "Zonentrennung, Default Deny, Protokollierung und Regelpflege sind die Kernaufgaben. Schadcode auf Endgeräten bekämpft man dort, nicht an der Netzgrenze.",
  "Which statements about a firewall in a company network are correct?",
  ("It separates zones with different protection needs",
   "It works on the default deny principle",
   "It logs discarded connections",
   "Its rule set is reviewed regularly",
   "It detects and removes malware from clients",
   "It makes endpoint security unnecessary"),
  "Zone separation, default deny, logging and rule maintenance are the core tasks. Malicious code on endpoints is fought there, not at the network boundary."),

M("ap2-sec-r57",
  "Welche Aussagen über Backups im Sicherheitskontext sind richtig?",
  ("Eine Kopie liegt getrennt vom Produktivnetz",
   "Unveränderbare Sicherungen widerstehen Ransomware",
   "Die Wiederherstellung wird regelmäßig geprobt",
   "Der Zugriff auf Sicherungen ist eingeschränkt",
   "Sicherungen liegen bequem auf demselben Server",
   "Ein Zugang mit Vollrechten für alle vereinfacht die Arbeit"),
  (0, 1, 2, 3),
  "Trennung, Unveränderbarkeit, geprobte Wiederherstellung und enge Zugriffsrechte machen eine Sicherung angriffsfest. Bequemlichkeit an dieser Stelle ist der häufigste Grund für Totalverluste.",
  "Which statements about backups in a security context are correct?",
  ("One copy is kept separate from the production network",
   "Immutable backups resist ransomware",
   "Recovery is rehearsed regularly",
   "Access to backups is restricted",
   "Backups sit conveniently on the same server",
   "One full-rights account for everyone simplifies work"),
  "Separation, immutability, rehearsed recovery and tight access rights make a backup attack-resistant. Convenience here is the most common reason for total losses."),

M("ap2-sec-r58",
  "Welche Angaben beschreibt ein digitales Zertifikat?",
  ("Den öffentlichen Schlüssel des Inhabers",
   "Den Namen des Inhabers", "Den Aussteller des Zertifikats",
   "Den Gültigkeitszeitraum",
   "Den privaten Schlüssel des Inhabers",
   "Das Anmeldepasswort des Inhabers"),
  (0, 1, 2, 3),
  "Ein Zertifikat verknüpft öffentlichen Schlüssel, Identität, Aussteller und Laufzeit in einem signierten Dokument. Geheimnisse stehen niemals darin.",
  "Which details does a digital certificate describe?",
  ("The public key of the holder",
   "The name of the holder", "The issuer of the certificate",
   "The period of validity",
   "The private key of the holder",
   "The login password of the holder"),
  "A certificate links public key, identity, issuer and validity period in one signed document. Secrets never appear in it."),

M("ap2-sec-r59",
  "Welche Aussagen über Port-Scans sind korrekt?",
  ("Sie ermitteln offene Dienste eines Systems",
   "Sie gehen einem gezielten Angriff oft voraus",
   "Sie sind in Protokollen erkennbar",
   "Ohne Beauftragung sind sie rechtlich problematisch",
   "Sie verschlüsseln den Verkehr zum Zielsystem",
   "Sie beheben gefundene Schwachstellen automatisch"),
  (0, 1, 2, 3),
  "Ein Scan ist Aufklärung: er zeigt Angriffsfläche, hinterlässt Spuren und braucht eine Beauftragung. Beheben muss man die Funde anschließend selbst.",
  "Which statements about port scans are correct?",
  ("They determine a system's open services",
   "They often precede a targeted attack",
   "They are visible in logs",
   "Without authorisation they are legally problematic",
   "They encrypt the traffic to the target system",
   "They automatically fix the vulnerabilities found"),
  "A scan is reconnaissance: it reveals attack surface, leaves traces and needs authorisation. Fixing the findings afterwards is your own job."),

M("ap2-sec-r60",
  "Welche Aussagen über die Absicherung von Fernwartungszugängen sind zutreffend?",
  ("Der Zugang läuft über ein VPN statt offen im Internet",
   "Eine Mehrfaktor-Anmeldung ist erforderlich",
   "Zugriffe werden protokolliert und ausgewertet",
   "Zugänge werden nach Ende der Wartung geschlossen",
   "Der Fernwartungsport wird dauerhaft freigegeben",
   "Ein gemeinsames Passwort für alle Dienstleister genügt"),
  (0, 1, 2, 3),
  "Getunnelt, stark authentisiert, protokolliert und zeitlich begrenzt - so bleibt Fernwartung beherrschbar. Dauerhaft offene Ports sind eine der häufigsten Einbruchsursachen.",
  "Which statements about securing remote maintenance access are correct?",
  ("Access runs through a VPN rather than openly on the internet",
   "Multi-factor authentication is required",
   "Access is logged and evaluated",
   "Access is closed once maintenance ends",
   "The remote maintenance port is permanently exposed",
   "One shared password for all providers suffices"),
  "Tunnelled, strongly authenticated, logged and time-limited keeps remote maintenance manageable. Permanently open ports are one of the most common causes of breaches."),

M("ap2-sec-r61",
  "Welche Aussagen über Netzwerkzugangskontrolle sind richtig?",
  ("Geräte werden vor dem Netzzugang geprüft",
   "Nicht konforme Geräte landen in einem Quarantänenetz",
   "802.1X ist ein verbreitetes Verfahren dafür",
   "Ein RADIUS-Server übernimmt die Entscheidung",
   "Jedes Gerät erhält ungeprüft vollen Zugang",
   "Die Prüfung ersetzt jede weitere Absicherung"),
  (0, 1, 2, 3),
  "NAC prüft vor dem Zugang und schiebt auffällige Geräte in ein eingeschränktes Netz. Es ist eine Schicht von mehreren und ersetzt weder Patches noch Segmentierung.",
  "Which statements about network access control are correct?",
  ("Devices are checked before network access",
   "Non-compliant devices land in a quarantine network",
   "802.1X is a widespread method for this",
   "A RADIUS server makes the decision",
   "Every device gets full access unchecked",
   "The check replaces any further protection"),
  "NAC checks before granting access and moves suspicious devices into a restricted network. It is one layer among several and replaces neither patches nor segmentation."),

M("ap2-sec-r62",
  "Welche Aussagen über Social-Engineering-Angriffe auf Administratoren sind korrekt?",
  ("Angreifer geben sich als Kollegen oder Dienstleister aus",
   "Zeitdruck soll die Prüfung der Identität verhindern",
   "Rückruf über bekannte Nummern deckt die Täuschung auf",
   "Festgelegte Freigabeprozesse schützen wirksam",
   "Technische Schutzmaßnahmen allein verhindern sie",
   "Erfahrene Fachkräfte sind grundsätzlich immun"),
  (0, 1, 2, 3),
  "Der Angriff zielt auf den Menschen, deshalb wirken vor allem Prozesse und Rückfragen. Weder Technik noch Erfahrung bieten dagegen vollständigen Schutz.",
  "Which statements about social engineering attacks on administrators are correct?",
  ("Attackers pose as colleagues or service providers",
   "Time pressure is meant to prevent identity checks",
   "Calling back on known numbers exposes the deception",
   "Defined approval processes protect effectively",
   "Technical measures alone prevent them",
   "Experienced professionals are fundamentally immune"),
  "The attack targets people, so processes and verification calls are what help. Neither technology nor experience provides complete protection."),

M("ap2-sec-r63",
  "Welche Aussagen über Verschlüsselung im Ruhezustand sind zutreffend?",
  ("Datenträger werden vollständig verschlüsselt",
   "Bei Diebstahl bleiben die Daten unlesbar",
   "Die Schlüsselverwaltung ist entscheidend",
   "Auch Sicherungen sollten verschlüsselt sein",
   "Sie schützt zusätzlich vor Angriffen im laufenden Betrieb",
   "Ein verlorener Schlüssel lässt sich leicht wiederherstellen"),
  (0, 1, 2, 3),
  "Verschlüsselung im Ruhezustand schützt gegen physischen Zugriff und muss Sicherungen einschließen. Im laufenden, entsperrten Betrieb hilft sie nicht, und ein verlorener Schlüssel bedeutet Datenverlust.",
  "Which statements about encryption at rest are correct?",
  ("Storage media are encrypted in full",
   "In case of theft the data stays unreadable",
   "Key management is decisive",
   "Backups should be encrypted too",
   "It additionally protects against attacks during operation",
   "A lost key can easily be recovered"),
  "Encryption at rest protects against physical access and must include backups. During running, unlocked operation it does not help, and a lost key means data loss."),

M("ap2-sec-r64",
  "Welche Kennzahlen und Vorgaben gehören zu einem Notfallmanagement?",
  ("Die maximal tolerierbare Ausfallzeit",
   "Der maximal tolerierbare Datenverlust",
   "Eine Priorisierung der Geschäftsprozesse",
   "Regelmäßige Übungen des Wiederanlaufs",
   "Die durchschnittliche Tippgeschwindigkeit der Nutzer",
   "Die Anzahl der Bildschirme je Arbeitsplatz"),
  (0, 1, 2, 3),
  "RTO, RPO, Prozesspriorisierung und Übungen bilden das Gerüst. Ohne geprobten Wiederanlauf bleibt jedes Notfallhandbuch Theorie.",
  "Which figures and requirements belong to emergency management?",
  ("The maximum tolerable downtime",
   "The maximum tolerable data loss",
   "A prioritisation of the business processes",
   "Regular rehearsals of the restart",
   "The average typing speed of the users",
   "The number of screens per workstation"),
  "RTO, RPO, process prioritisation and rehearsals form the framework. Without a rehearsed restart every emergency manual stays theory."),

# ------------------------------------------------------------------ text (36)
T("ap2-sec-r65", "Wie heißt der Angriff, bei dem Schadcode über ein Eingabefeld in eine Datenbankabfrage gelangt?", "SQL-Injection",
  "Vorbereitete Anweisungen mit Parametern trennen Code von Daten und verhindern sie zuverlässig.",
  "What is the attack called where malicious code enters a database query through an input field?", "SQL injection",
  "Prepared statements with parameters separate code from data and reliably prevent it."),

T("ap2-sec-r66", "Welche Kennzahl gibt an, wie viel Datenverlust höchstens hinnehmbar ist?", "RPO",
  "Das Recovery Point Objective bestimmt unmittelbar den zulässigen Abstand zwischen zwei Sicherungen.",
  "Which figure states the maximum acceptable data loss?", "RPO",
  "The recovery point objective directly determines the permissible interval between two backups."),

T("ap2-sec-r67", "Welche Kennzahl gibt an, wie lange die Wiederherstellung höchstens dauern darf?", "RTO",
  "Das Recovery Time Objective bemisst sich am Schaden, den ein Stillstand je Stunde verursacht.",
  "Which figure states how long recovery may take at most?", "RTO",
  "The recovery time objective is derived from the damage an hour of downtime causes."),

T("ap2-sec-r68", "Welches Verfahren authentisiert Geräte direkt am Switchport?", "802.1X",
  "Die Entscheidung trifft üblicherweise ein RADIUS-Server; vorher bleibt der Port gesperrt.",
  "Which method authenticates devices directly at the switch port?", "802.1X",
  "The decision is usually made by a RADIUS server; until then the port stays blocked."),

T("ap2-sec-r69", "Wie heißt der zufällige Zusatz, der beim Hashen von Passwörtern je Konto ergänzt wird?", "Salt",
  "Er verhindert vorberechnete Tabellen und macht gleiche Passwörter an ihren Hashes ununterscheidbar.",
  "What is the random per-account addition used when hashing passwords called?", "Salt",
  "It defeats precomputed tables and makes identical passwords indistinguishable by their hashes."),

T("ap2-sec-r70", "Welcher DNS-Eintrag legt die berechtigten Absendeserver einer Domain fest?", "SPF",
  "Zusammen mit DKIM und DMARC erschwert er das Fälschen der Absenderdomain erheblich.",
  "Which DNS record defines the authorised sending servers of a domain?", "SPF",
  "Together with DKIM and DMARC it makes forging the sender domain considerably harder."),

T("ap2-sec-r71", "Welches System erkennt Angriffe und blockiert sie zusätzlich aktiv?", "IPS",
  "Das reine Intrusion Detection System meldet dagegen nur, ohne selbst einzugreifen.",
  "Which system detects attacks and additionally blocks them actively?", "IPS",
  "A pure intrusion detection system by contrast only alerts without intervening."),

T("ap2-sec-r72", "Wie heißt der Angriff, bei dem falsche IP-zu-MAC-Zuordnungen verbreitet werden?", "ARP-Spoofing",
  "Dynamic ARP Inspection auf den Switches prüft die Zuordnungen und verwirft gefälschte Antworten.",
  "What is the attack spreading false IP-to-MAC mappings called?", "ARP spoofing",
  "Dynamic ARP inspection on the switches verifies the mappings and discards forged replies."),

T("ap2-sec-r73", "Welches Hashverfahren gilt für Prüfsummen heute als sicher?", "SHA-256",
  "MD5 und SHA-1 sind wegen praktikabler Kollisionsangriffe nicht mehr geeignet.",
  "Which hash method is considered secure for checksums today?", "SHA-256",
  "MD5 and SHA-1 are no longer suitable because of practical collision attacks."),

T("ap2-sec-r74", "Welche Norm beschreibt Anforderungen an ein Informationssicherheits-Managementsystem?", "ISO 27001",
  "Sie legt fest, wie ein ISMS aufgebaut, betrieben, überprüft und verbessert wird.",
  "Which standard describes requirements for an information security management system?", "ISO 27001",
  "It defines how an ISMS is established, operated, reviewed and improved."),

T("ap2-sec-r75", "Wie heißt das Netzsegment für von außen erreichbare Dienste?", "DMZ",
  "Es liegt zwischen zwei Firewallzonen, damit ein übernommener Dienst nicht direkt ins LAN führt.",
  "What is the network segment for externally reachable services called?", "DMZ",
  "It sits between two firewall zones so a compromised service does not lead straight into the LAN."),

T("ap2-sec-r76", "Welcher Ansatz misstraut grundsätzlich jedem Zugriff, unabhängig vom Standort?", "Zero Trust",
  "Jede Anfrage wird einzeln authentisiert und autorisiert, statt dem internen Netz zu vertrauen.",
  "Which approach fundamentally distrusts every access regardless of location?", "Zero trust",
  "Every request is authenticated and authorised individually instead of trusting the internal network."),

T("ap2-sec-r77", "Auf welcher Skala bewertet CVSS den Schweregrad einer Schwachstelle?", "0 bis 10",
  "Der Wert hilft, begrenzte Patchkapazität auf die dringendsten Lücken zu lenken.",
  "On which scale does CVSS rate the severity of a vulnerability?", "0 to 10",
  "The value helps direct limited patching capacity to the most urgent gaps."),

T("ap2-sec-r78", "Welches Verfahren sorgt dafür, dass alte Mitschnitte auch nach Schlüsseldiebstahl sicher bleiben?", "Perfect Forward Secrecy",
  "Für jede Sitzung wird ein flüchtiger Schlüssel ausgehandelt, der nicht aus dem Langzeitschlüssel ableitbar ist.",
  "Which method keeps old recordings safe even after key theft?", "Perfect forward secrecy",
  "An ephemeral key is negotiated per session that cannot be derived from the long-term key."),

T("ap2-sec-r79", "Wie heißt ein absichtlich verwundbares System zum Beobachten von Angreifern?", "Honeypot",
  "Es muss streng vom Produktivnetz getrennt sein, sonst wird es selbst zum Einfallstor.",
  "What is a deliberately vulnerable system for observing attackers called?", "Honeypot",
  "It must be strictly separated from the production network or it becomes an entry point itself."),

T("ap2-sec-r80", "Welche Firewallgrundregel lässt nur ausdrücklich erlaubten Verkehr durch?", "Default Deny",
  "Alles Nichtgenannte wird verworfen - jede vergessene Regel führt so zu einer Sperre statt zu einer Lücke.",
  "Which basic firewall rule permits only explicitly allowed traffic?", "Default deny",
  "Everything unnamed is discarded - a forgotten rule then causes a block instead of a hole."),

T("ap2-sec-r81", "Welches System sammelt und korreliert Sicherheitsereignisse aus vielen Quellen?", "SIEM",
  "Erst die Korrelation macht Muster sichtbar, die in einer einzelnen Quelle unauffällig bleiben.",
  "Which system collects and correlates security events from many sources?", "SIEM",
  "Only correlation reveals patterns that stay inconspicuous within a single source."),

T("ap2-sec-r82", "Wie nennt man das Erlangen höherer Rechte durch Ausnutzen einer Schwachstelle?", "Privilegienerweiterung",
  "Auf Englisch Privilege Escalation. Aktuelle Patches und minimale Rechte erschweren sie erheblich.",
  "What is gaining higher rights by exploiting a vulnerability called?", "Privilege escalation",
  "Current patches and least privilege make it considerably harder."),

T("ap2-sec-r83", "Welcher Dienst prüft bei WPA2-Enterprise die Zugangsdaten zentral?", "RADIUS",
  "Jeder Nutzer meldet sich mit eigenen Daten an, statt einen gemeinsamen Schlüssel zu teilen.",
  "Which service centrally verifies credentials in WPA2-Enterprise?", "RADIUS",
  "Every user logs in with their own credentials instead of sharing a common key."),

T("ap2-sec-r84", "Wie heißt die VPN-Einstellung, bei der nur Firmenverkehr durch den Tunnel läuft?", "Split Tunneling",
  "Sie entlastet das Gateway, umgeht aber die zentralen Schutzmechanismen für den übrigen Verkehr.",
  "What is the VPN setting where only company traffic goes through the tunnel called?", "Split tunnelling",
  "It relieves the gateway but bypasses central protection for the remaining traffic."),

T("ap2-sec-r85", "Welches Verfahren meldet zurückgezogene Zertifikate in Echtzeit ab?", "OCSP",
  "Die Alternative ist eine Sperrliste, die der Client herunterlädt und lokal auswertet.",
  "Which method reports revoked certificates in real time?", "OCSP",
  "The alternative is a revocation list that the client downloads and evaluates locally."),

T("ap2-sec-r86", "Wie heißt der Angriff, bei dem Skriptcode im Browser des Opfers ausgeführt wird?", "Cross-Site-Scripting",
  "Konsequente Kodierung der Ausgabe verhindert, dass eingeschleuster Code als Code interpretiert wird.",
  "What is the attack executing script code in the victim's browser called?", "Cross-site scripting",
  "Consistent output encoding prevents injected code from being interpreted as code."),

T("ap2-sec-r87", "Welche Switch-Funktion blockiert nicht autorisierte DHCP-Server im Netz?", "DHCP Snooping",
  "Antworten sind nur auf ausdrücklich als vertrauenswürdig markierten Ports erlaubt.",
  "Which switch feature blocks unauthorised DHCP servers on the network?", "DHCP snooping",
  "Replies are permitted only on ports explicitly marked as trusted."),

T("ap2-sec-r88", "Wie viele Faktoren aus unterschiedlichen Kategorien verlangt eine Zwei-Faktor-Anmeldung?", "2",
  "Wissen, Besitz und Biometrie sind die Kategorien - zwei Passwörter zählen deshalb nicht.",
  "How many factors from different categories does two-factor authentication require?", "2",
  "Knowledge, possession and biometrics are the categories - two passwords therefore do not count."),

T("ap2-sec-r89", "Welche Firewalltechnik untersucht zusätzlich den Inhalt der Pakete?", "Deep Packet Inspection",
  "Sie erkennt Anwendungen und Schadmuster unabhängig davon, welchen Port sie benutzen.",
  "Which firewall technique additionally examines the packet content?", "Deep packet inspection",
  "It recognises applications and malicious patterns regardless of which port they use."),

T("ap2-sec-r90", "Wie heißt ein beauftragter, kontrollierter Angriff zur Prüfung der eigenen Systeme?", "Penetrationstest",
  "Ohne schriftliche Beauftragung wäre er strafbar; er liefert eine Momentaufnahme, keine Dauergarantie.",
  "What is an authorised, controlled attack to test one's own systems called?", "Penetration test",
  "Without written authorisation it would be a criminal offence; it gives a snapshot, not a permanent guarantee."),

T("ap2-sec-r91", "Welches Protokoll signiert ausgehende E-Mails kryptografisch?", "DKIM",
  "Der Empfänger prüft die Signatur gegen den im DNS hinterlegten öffentlichen Schlüssel.",
  "Which protocol cryptographically signs outgoing emails?", "DKIM",
  "The recipient verifies the signature against the public key published in DNS."),

T("ap2-sec-r92", "Wie heißt ein Angriff, der eine noch unbekannte Lücke ohne verfügbaren Patch ausnutzt?", "Zero-Day",
  "Signaturen fehlen, deshalb helfen vor allem Segmentierung, Rechtebegrenzung und Verhaltenserkennung.",
  "What is an attack exploiting an unknown gap with no patch available called?", "Zero-day",
  "Signatures are missing, so segmentation, restricted rights and behaviour detection are what help."),

T("ap2-sec-r93", "Welche Richtlinie legt fest, wie Empfänger mit SPF- und DKIM-Verstößen umgehen sollen?", "DMARC",
  "Sie bestimmt zusätzlich, wohin Berichte über abgelehnte Nachrichten geschickt werden.",
  "Which policy defines how recipients should handle SPF and DKIM failures?", "DMARC",
  "It additionally defines where reports about rejected messages are sent."),

T("ap2-sec-r94", "Welche Eigenschaft eines Hashverfahrens sorgt dafür, dass es sich nicht umkehren lässt?", "Einwegfunktion",
  "Aus dem Ergebnis lässt sich die Eingabe praktisch nicht zurückrechnen.",
  "Which property of a hash function makes it irreversible?", "One-way function",
  "The input practically cannot be computed back from the result."),

T("ap2-sec-r95", "Wie heißt ein Angriff aus vielen verteilten Quellen auf die Verfügbarkeit eines Dienstes?", "DDoS",
  "Die Last kommt meist aus einem Botnetz, weshalb einfaches Sperren einzelner Adressen nicht genügt.",
  "What is an attack from many distributed sources against a service's availability called?", "DDoS",
  "The load usually comes from a botnet, so blocking individual addresses is not enough."),

T("ap2-sec-r96", "Welches Verfahren prüft Geräte vor dem Zugang und schiebt auffällige in ein Quarantänenetz?", "NAC",
  "Network Access Control stützt sich meist auf 802.1X und einen RADIUS-Server.",
  "Which method checks devices before access and moves suspicious ones into quarantine?", "NAC",
  "Network access control usually builds on 802.1X and a RADIUS server."),

T("ap2-sec-r97", "Welche Instanz signiert in einer PKI die ausgestellten Zertifikate?", "Zertifizierungsstelle",
  "Ihre Signatur bürgt dafür, dass ein öffentlicher Schlüssel zur genannten Identität gehört.",
  "Which entity signs the issued certificates in a PKI?", "Certification authority",
  "Its signature vouches that a public key belongs to the stated identity."),

T("ap2-sec-r98", "Was ist bei der Auswertung von Protokollen mehrerer Systeme zwingend nötig?", "Zeitsynchronisation",
  "Ohne synchrone Uhren lässt sich kein Ablauf über Systemgrenzen hinweg rekonstruieren.",
  "What is strictly necessary when evaluating logs from several systems?", "Time synchronisation",
  "Without synchronised clocks no sequence across system boundaries can be reconstructed."),

T("ap2-sec-r99", "Welche Sicherungsart lässt sich nachträglich nicht mehr verändern oder löschen?", "Unveränderbare Sicherung",
  "Auf Englisch immutable Backup. Genau daran scheitert Ransomware, die auch Sicherungen verschlüsseln will.",
  "Which kind of backup cannot be altered or deleted afterwards?", "Immutable backup",
  "This is exactly what defeats ransomware that also tries to encrypt backups."),

T("ap2-sec-r100", "Wie heißt der erste Schritt nach dem Verdacht auf eine Kompromittierung?", "System isolieren",
  "Das stoppt die Ausbreitung und erhält gleichzeitig die Spuren für die spätere Analyse.",
  "What is the first step after suspecting a compromise?", "Isolate the system",
  "This stops the spread and simultaneously preserves the traces for later analysis."),
]

build("ap2-it-sicherheit.json", "IT-Sicherheit & Netzwerksicherheit", "IT Security & Network Security", Q)
