#!/usr/bin/env python3
"""AP1 Netzwerktechnik - 100 handgeschriebene Fragen."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from qlib import S, M, T, build

Q = [
# ---------------------------------------------------------------- single (32)
S("ap1-net-r01",
  "Ein Notebook hat die Adresse 169.254.12.7 und kommt nicht ins Netz. Was ist die wahrscheinlichste Ursache?",
  ("Es hat keinen DHCP-Server erreicht und sich selbst adressiert",
   "Es wurde versehentlich in ein falsches VLAN gesteckt",
   "Die Firewall des Notebooks blockiert ausgehende Pakete",
   "Der DNS-Server im Netz beantwortet keine Anfragen mehr"), 0,
  "169.254.0.0/16 ist der APIPA-Bereich: Windows vergibt sich diese Adresse selbst, wenn kein DHCP-Server antwortet. Ein falsches VLAN oder ein toter DNS würde eine reguläre DHCP-Adresse nicht verhindern.",
  "A laptop has the address 169.254.12.7 and cannot reach the network. What is the most likely cause?",
  ("It reached no DHCP server and assigned itself an address",
   "It was accidentally patched into the wrong VLAN",
   "The laptop's own firewall is blocking outgoing packets",
   "The DNS server on the network stopped answering queries"),
  "169.254.0.0/16 is the APIPA range: Windows assigns itself such an address when no DHCP server replies. A wrong VLAN or a dead DNS would not prevent a regular DHCP address."),

S("ap1-net-r02",
  "Ein Kollege kann Webseiten per IP-Adresse aufrufen, aber nicht per Namen. Wo liegt der Fehler?",
  ("Bei der Namensauflösung durch den DNS-Server",
   "Bei der Adressvergabe durch den DHCP-Server",
   "Beim Standardgateway in der IP-Konfiguration",
   "Bei der MAC-Auflösung durch das ARP-Protokoll"), 0,
  "Wenn die IP funktioniert, sind Routing und Gateway offensichtlich in Ordnung - allein die Übersetzung Name zu IP fehlt, und die macht DNS. ARP arbeitet nur innerhalb des lokalen Netzes.",
  "A colleague can open websites by IP address but not by name. Where is the fault?",
  ("In name resolution handled by the DNS server",
   "In address assignment handled by the DHCP server",
   "In the default gateway of the IP configuration",
   "In MAC resolution handled by the ARP protocol"),
  "If the IP works, routing and gateway are clearly fine - only the name-to-IP translation is missing, and that is DNS. ARP only operates inside the local network."),

S("ap1-net-r03",
  "Auf welcher OSI-Schicht trifft ein Switch seine normale Weiterleitungsentscheidung?",
  ("Schicht 2, anhand der Ziel-MAC-Adresse",
   "Schicht 3, anhand der Ziel-IP-Adresse",
   "Schicht 1, anhand der elektrischen Signale",
   "Schicht 4, anhand der Ziel-Portnummer"), 0,
  "Ein klassischer Switch führt eine MAC-Tabelle und leitet Frames anhand der Ziel-MAC weiter - das ist Schicht 2. Erst ein Layer-3-Switch oder Router wertet zusätzlich IP-Adressen aus.",
  "On which OSI layer does a switch make its normal forwarding decision?",
  ("Layer 2, based on the destination MAC address",
   "Layer 3, based on the destination IP address",
   "Layer 1, based on the electrical signals",
   "Layer 4, based on the destination port number"),
  "A classic switch maintains a MAC table and forwards frames by destination MAC - that is layer 2. Only a layer 3 switch or router additionally evaluates IP addresses."),

S("ap1-net-r04",
  "Das Netz 192.168.10.0/24 soll in 4 gleich große Subnetze geteilt werden. Welche Präfixlänge ergibt sich?",
  ("/26", "/25", "/27", "/28"), 0,
  "Für 4 Subnetze braucht man 2 zusätzliche Netzbits, denn 2 hoch 2 = 4. Aus /24 wird damit /26 mit je 62 nutzbaren Hostadressen.",
  "The network 192.168.10.0/24 is to be split into 4 equally sized subnets. Which prefix length results?",
  ("/26", "/25", "/27", "/28"),
  "Four subnets require 2 additional network bits, since 2 to the power of 2 equals 4. So /24 becomes /26 with 62 usable host addresses each."),

S("ap1-net-r05",
  "Zwei PCs im selben Switch erreichen sich nicht: 192.168.1.10/24 und 192.168.2.10/24. Warum?",
  ("Sie liegen trotz gleichem Switch in verschiedenen IP-Netzen",
   "Ein Switch kann grundsätzlich nur 254 Geräte verbinden",
   "Die beiden Adressen kollidieren wegen derselben Endziffer",
   "Ohne aktiviertes ARP können sich Hosts nicht finden"), 0,
  "Bei /24 entscheiden die ersten drei Oktette über die Netzzugehörigkeit - 192.168.1.x und 192.168.2.x sind zwei getrennte Netze. Für die Kommunikation braucht es einen Router, egal wie kurz das Kabel ist.",
  "Two PCs on the same switch cannot reach each other: 192.168.1.10/24 and 192.168.2.10/24. Why?",
  ("Despite the shared switch they sit in different IP networks",
   "A switch can fundamentally only connect 254 devices",
   "The two addresses collide because of the identical last digit",
   "Without ARP enabled, hosts are unable to locate each other"),
  "With /24 the first three octets decide network membership - 192.168.1.x and 192.168.2.x are two separate networks. Communication needs a router, no matter how short the cable is."),

S("ap1-net-r06",
  "Wie lang darf eine Twisted-Pair-Strecke nach Norm höchstens sein?",
  ("100 Meter", "150 Meter", "185 Meter", "250 Meter"), 0,
  "Die strukturierte Verkabelung rechnet mit 90 m Verlegekabel plus 10 m Rangier- und Anschlusskabel. Größere Entfernungen überbrückt man mit Lichtwellenleiter oder einem zwischengeschalteten Switch.",
  "What is the maximum standard length of a twisted-pair link?",
  ("100 metres", "150 metres", "185 metres", "250 metres"),
  "Structured cabling budgets 90 m of installation cable plus 10 m of patch and connection cable. Longer distances are bridged with fibre or an intermediate switch."),

S("ap1-net-r07",
  "In einem Büro mit vielen Nachbar-WLANs ist das 2,4-GHz-Netz sehr langsam. Was hilft am ehesten?",
  ("Die Clients auf das weniger belegte 5-GHz-Band umstellen",
   "Die Sendeleistung des Access Points maximal hochdrehen",
   "Die SSID des Access Points verstecken statt zu senden",
   "Den WLAN-Schlüssel auf ein längeres Passwort ändern"), 0,
  "2,4 GHz bietet nur drei überschneidungsfreie Kanäle und ist deshalb schnell überfüllt. 5 GHz hat deutlich mehr Kanäle. Mehr Sendeleistung verschärft die Störung für alle, versteckte SSIDs und längere Schlüssel ändern am Durchsatz nichts.",
  "In an office with many neighbouring WLANs the 2.4 GHz network is very slow. What helps most?",
  ("Move the clients to the less crowded 5 GHz band",
   "Turn the access point transmit power up to maximum",
   "Hide the access point's SSID instead of broadcasting it",
   "Change the WLAN key to a longer passphrase"),
  "2.4 GHz offers only three non-overlapping channels and fills up quickly. 5 GHz has many more. More transmit power makes interference worse for everyone, and hidden SSIDs or longer keys do not affect throughput."),

S("ap1-net-r08",
  "Über welchen Port läuft eine verschlüsselte HTTPS-Verbindung standardmäßig?",
  ("443", "80", "8080", "993"), 0,
  "HTTPS nutzt standardmäßig TCP 443, unverschlüsseltes HTTP den Port 80. 8080 ist ein häufiger Alternativport für Webdienste, 993 gehört zu IMAPS.",
  "Which port does an encrypted HTTPS connection use by default?",
  ("443", "80", "8080", "993"),
  "HTTPS uses TCP 443 by default, unencrypted HTTP uses port 80. 8080 is a common alternative port for web services, 993 belongs to IMAPS."),

S("ap1-net-r09",
  "Ein Access Point soll an einer Stelle ohne Steckdose montiert werden. Welche Technik löst das?",
  ("Power over Ethernet über das Netzwerkkabel",
   "Ein längeres Patchkabel mit höherer Kategorie",
   "Ein Medienkonverter von Kupfer auf Lichtwellenleiter",
   "Ein zweites VLAN speziell für die Stromversorgung"), 0,
  "PoE speist die Versorgungsspannung in dieselbe Twisted-Pair-Leitung ein, über die auch die Daten laufen. Der Speisepunkt ist ein PoE-fähiger Switch oder ein Injektor.",
  "An access point must be mounted where there is no power socket. Which technology solves this?",
  ("Power over Ethernet through the network cable",
   "A longer patch cable of a higher category",
   "A media converter from copper to fibre optics",
   "A second VLAN dedicated to the power supply"),
  "PoE feeds the supply voltage into the same twisted-pair line that carries the data. The feed point is a PoE-capable switch or an injector."),

S("ap1-net-r10",
  "Eine Verbindung ist auffällig langsam, die Schnittstelle meldet massenhaft Kollisionen. Was prüfst du?",
  ("Ob Duplex und Geschwindigkeit auf beiden Seiten gleich sind",
   "Ob die Subnetzmaske auf beiden Seiten identisch gesetzt ist",
   "Ob der DNS-Server in der Konfiguration erreichbar ist",
   "Ob die MAC-Adresse des Geräts im Netz doppelt vergeben ist"), 0,
  "Steht eine Seite auf Autonegotiation und die andere fest auf Vollduplex, entsteht ein Duplex-Mismatch: eine Seite sendet halbduplex und zählt Kollisionen. Falsche Masken oder DNS-Probleme verursachen Ausfälle, aber keine Kollisionszähler.",
  "A link is noticeably slow and the interface reports masses of collisions. What do you check?",
  ("Whether duplex and speed match on both sides of the link",
   "Whether the subnet mask is set identically on both sides",
   "Whether the DNS server in the configuration is reachable",
   "Whether the device's MAC address is duplicated on the network"),
  "If one side uses autonegotiation and the other is fixed to full duplex, a duplex mismatch results: one side transmits half duplex and counts collisions. Wrong masks or DNS problems cause outages but no collision counters."),

S("ap1-net-r11",
  "Welche der folgenden Adressen stammt aus einem privaten IPv4-Bereich?",
  ("172.16.5.20", "172.32.5.20", "192.169.5.20", "10.256.5.20"), 0,
  "Privat sind 10.0.0.0/8, 172.16.0.0/12 und 192.168.0.0/16. 172.32.x.x liegt knapp außerhalb des 172er-Blocks, 192.169.x.x außerhalb des 192.168er-Blocks, und 256 ist als Oktett gar nicht gültig.",
  "Which of the following addresses comes from a private IPv4 range?",
  ("172.16.5.20", "172.32.5.20", "192.169.5.20", "10.256.5.20"),
  "The private ranges are 10.0.0.0/8, 172.16.0.0/12 and 192.168.0.0/16. 172.32.x.x sits just outside the 172 block, 192.169.x.x outside the 192.168 block, and 256 is not a valid octet at all."),

S("ap1-net-r12",
  "Gäste-WLAN und Büro-Rechner hängen am selben Switch, sollen sich aber nicht sehen. Was setzt du ein?",
  ("Getrennte VLANs für Gäste und Bürogeräte",
   "Feste IP-Adressen statt DHCP für alle Geräte",
   "Ein zweites Passwort auf dem gemeinsamen Access Point",
   "Eine kürzere DHCP-Leasedauer im Gästebereich"), 0,
  "VLANs trennen einen physischen Switch in mehrere logische Netze, die nur über einen Router mit Regelwerk miteinander reden. Feste Adressen oder kurze Leases trennen gar nichts - der Broadcast-Bereich bliebe derselbe.",
  "Guest WLAN and office PCs share one switch but must not see each other. What do you deploy?",
  ("Separate VLANs for guests and office devices",
   "Static IP addresses instead of DHCP for all devices",
   "A second password on the shared access point",
   "A shorter DHCP lease time in the guest area"),
  "VLANs split one physical switch into several logical networks that only talk through a router with a rule set. Static addresses or short leases separate nothing - the broadcast domain would stay the same."),

S("ap1-net-r13",
  "Eine Webseite lädt sehr langsam. Womit findest du heraus, auf welchem Teilstück die Verzögerung entsteht?",
  ("tracert bzw. traceroute zum Zielserver",
   "ipconfig /all auf dem eigenen Rechner",
   "netstat -an auf dem eigenen Rechner",
   "nslookup auf den Namen des Zielservers"), 0,
  "traceroute zeigt jeden Router auf dem Weg samt Antwortzeit - so wird sichtbar, ab welchem Hop die Latenz springt. ipconfig und netstat zeigen nur den lokalen Zustand, nslookup nur die Namensauflösung.",
  "A website loads very slowly. How do you find out on which segment the delay occurs?",
  ("tracert or traceroute to the target server",
   "ipconfig /all on your own computer",
   "netstat -an on your own computer",
   "nslookup on the target server's name"),
  "traceroute shows every router along the path with its response time, revealing at which hop latency jumps. ipconfig and netstat only show local state, nslookup only name resolution."),

S("ap1-net-r14",
  "Wozu dient der Eintrag Standardgateway in der IP-Konfiguration eines Clients?",
  ("Er nennt den Router für Ziele außerhalb des eigenen Netzes",
   "Er nennt den Server, der die IP-Adressen im Netz verteilt",
   "Er nennt den Rechner, der Namen in IP-Adressen übersetzt",
   "Er nennt die Grenze zwischen erlaubtem und verbotenem Verkehr"), 0,
  "Liegt das Ziel laut Subnetzmaske nicht im eigenen Netz, schickt der Client das Paket an das Gateway. Adressvergabe macht DHCP, Namensauflösung DNS, Verkehrsfilterung die Firewall.",
  "What is the default gateway entry in a client's IP configuration for?",
  ("It names the router used for targets outside the local network",
   "It names the server that hands out IP addresses on the network",
   "It names the machine that translates names into IP addresses",
   "It names the boundary between permitted and forbidden traffic"),
  "If the subnet mask says the target is not in the local network, the client sends the packet to the gateway. Address assignment is DHCP, name resolution is DNS, traffic filtering is the firewall."),

S("ap1-net-r15",
  "Ein Switchport flackert dauernd, die Auslastung des Netzes liegt bei 100 Prozent. Was vermutest du zuerst?",
  ("Eine Schleife im Netz, weil zwei Ports verbunden wurden",
   "Einen zu klein gewählten DHCP-Adressbereich im Netz",
   "Einen fehlenden DNS-Eintrag für den betroffenen Server",
   "Eine falsch gesetzte Subnetzmaske auf dem Switchport"), 0,
  "Werden zwei Switchports miteinander verbunden, kreisen Broadcasts endlos und legen das Segment lahm - ein Broadcast-Storm. Genau dagegen schaltet man Spanning Tree ein, das redundante Wege blockiert.",
  "A switch port flickers constantly and network utilisation sits at 100 percent. What do you suspect first?",
  ("A loop in the network because two ports were connected",
   "A DHCP address range that was chosen far too small",
   "A missing DNS record for the affected server",
   "An incorrectly set subnet mask on the switch port"),
  "If two switch ports are connected to each other, broadcasts circle endlessly and paralyse the segment - a broadcast storm. Spanning Tree exists precisely for this and blocks redundant paths."),

S("ap1-net-r16",
  "Welcher DNS-Eintrag ordnet einem Hostnamen eine IPv4-Adresse zu?",
  ("A-Record", "MX-Record", "CNAME-Record", "PTR-Record"), 0,
  "Der A-Record bildet Name auf IPv4 ab, sein IPv6-Gegenstück ist AAAA. MX weist auf den Mailserver, CNAME ist ein Alias, PTR löst umgekehrt IP zu Name auf.",
  "Which DNS record maps a hostname to an IPv4 address?",
  ("A record", "MX record", "CNAME record", "PTR record"),
  "The A record maps a name to IPv4, its IPv6 counterpart is AAAA. MX points to the mail server, CNAME is an alias, PTR resolves IP back to name."),

S("ap1-net-r17",
  "Warum kommen 200 Büro-PCs mit einer einzigen öffentlichen IP-Adresse ins Internet?",
  ("Der Router übersetzt die privaten Adressen per NAT",
   "Der Provider vergibt versteckt 200 weitere Adressen",
   "Die PCs teilen sich die öffentliche Adresse im Zeittakt",
   "Der Switch verteilt die Verbindungen auf mehrere Leitungen"), 0,
  "NAT ersetzt im Router die private Quelladresse durch die öffentliche und merkt sich anhand der Portnummern, welche Antwort zu welchem internen Rechner gehört. Deshalb spricht man genauer von PAT.",
  "Why can 200 office PCs reach the internet through a single public IP address?",
  ("The router translates the private addresses using NAT",
   "The provider secretly hands out 200 further addresses",
   "The PCs share the public address in fixed time slots",
   "The switch spreads the connections across several lines"),
  "NAT replaces the private source address in the router with the public one and uses port numbers to remember which reply belongs to which internal machine. That is why it is more precisely called PAT."),

S("ap1-net-r18",
  "Zwei moderne Switche sollen verbunden werden. Welches Kabel nimmst du?",
  ("Ein normales Patchkabel, Auto-MDI-X dreht die Paare",
   "Zwingend ein Crossover-Kabel, sonst bleibt der Port tot",
   "Ein geschirmtes Kabel, weil Switche stark einstreuen",
   "Ein Konsolenkabel, weil Uplinks seriell gekoppelt werden"), 0,
  "Aktuelle Gigabit-Ports erkennen die Belegung selbst und drehen Sende- und Empfangspaare bei Bedarf um. Crossover-Kabel braucht man nur noch bei sehr alter Hardware ohne Auto-MDI-X.",
  "Two modern switches are to be connected. Which cable do you use?",
  ("A normal patch cable, Auto MDI-X swaps the pairs",
   "Strictly a crossover cable, otherwise the port stays dead",
   "A shielded cable, because switches emit strong interference",
   "A console cable, because uplinks are coupled serially"),
  "Current gigabit ports detect the pinout themselves and swap transmit and receive pairs when needed. Crossover cables are only required with very old hardware lacking Auto MDI-X."),

S("ap1-net-r19",
  "Eine Strecke führt 400 m durch eine Halle mit großen Motoren. Welches Medium wählst du?",
  ("Lichtwellenleiter, weil er unempfindlich gegen Störfelder ist",
   "Cat-7-Kupferkabel, weil die Schirmung Störfelder abhält",
   "WLAN-Richtfunk, weil Funk keine Erdung im Hallenbau braucht",
   "Koaxialkabel, weil es die größte Bandbreite pro Ader bietet"), 0,
  "Glasfaser überträgt Licht statt Strom und ist deshalb völlig immun gegen elektromagnetische Einstreuung - und 400 m sprengen ohnehin die 100-m-Grenze von Kupfer. Motoren stören auch geschirmtes Kupfer und Funk.",
  "A link runs 400 m through a hall with large motors. Which medium do you choose?",
  ("Fibre optics, because it is immune to interference fields",
   "Cat 7 copper cable, because the shielding blocks interference",
   "Wireless directional link, because radio needs no hall earthing",
   "Coaxial cable, because it offers the highest bandwidth per wire"),
  "Fibre transmits light instead of current and is therefore completely immune to electromagnetic interference - and 400 m exceeds the 100 m copper limit anyway. Motors also disturb shielded copper and radio."),

S("ap1-net-r20",
  "Welches WLAN-Sicherheitsverfahren ist heute noch als sicher einzustufen?",
  ("WPA3", "WPA mit TKIP", "WEP mit 128 Bit", "MAC-Adressfilterung"), 0,
  "WPA3 ist der aktuelle Standard, WPA2 mit AES gilt weiterhin als vertretbar. WEP und TKIP sind gebrochen, und ein MAC-Filter lässt sich durch Mitlesen und Fälschen der Adresse trivial umgehen.",
  "Which WLAN security method can still be considered secure today?",
  ("WPA3", "WPA with TKIP", "WEP with 128 bit", "MAC address filtering"),
  "WPA3 is the current standard, WPA2 with AES is still acceptable. WEP and TKIP are broken, and a MAC filter is trivially bypassed by sniffing and spoofing the address."),

S("ap1-net-r21",
  "Ein Netzwerkdrucker soll immer dieselbe Adresse haben, aber zentral verwaltet bleiben. Was richtest du ein?",
  ("Eine DHCP-Reservierung anhand der MAC-Adresse",
   "Eine feste IP direkt am Bedienfeld des Druckers",
   "Einen zusätzlichen DNS-Eintrag für den Drucker",
   "Eine unbegrenzte Leasedauer für den gesamten Bereich"), 0,
  "Die Reservierung bindet eine feste Adresse an die MAC, die Zuweisung bleibt aber im DHCP-Server dokumentiert und änderbar. Eine am Gerät eingetippte Adresse taucht in keiner zentralen Übersicht auf.",
  "A network printer should always keep the same address but stay centrally managed. What do you set up?",
  ("A DHCP reservation based on the MAC address",
   "A static IP entered directly on the printer's panel",
   "An additional DNS record pointing at the printer",
   "An unlimited lease duration for the whole scope"),
  "The reservation binds a fixed address to the MAC while the assignment stays documented and changeable in the DHCP server. An address typed into the device appears in no central overview."),

S("ap1-net-r22",
  "Für eine VoIP-Telefonanlage: welches Transportprotokoll wird für die Sprachdaten genutzt und warum?",
  ("UDP, weil verspätete Pakete wertlos wären",
   "TCP, weil jedes Sprachpaket ankommen muss",
   "ICMP, weil es die geringste Latenz erzeugt",
   "ARP, weil es direkt auf Schicht 2 arbeitet"), 0,
  "Bei Sprache zählt Pünktlichkeit mehr als Vollständigkeit: ein nachgeliefertes Paket käme zu spät für die Wiedergabe. UDP verzichtet daher auf Bestätigungen und Neuversand.",
  "For a VoIP phone system: which transport protocol carries the voice data and why?",
  ("UDP, because late packets would be worthless",
   "TCP, because every voice packet has to arrive",
   "ICMP, because it produces the lowest latency",
   "ARP, because it works directly on layer 2"),
  "For voice, timeliness matters more than completeness: a retransmitted packet would arrive too late to be played. UDP therefore does without acknowledgements and retransmission."),

S("ap1-net-r23",
  "Wie lautet die Broadcast-Adresse des Netzes 192.168.4.0/26?",
  ("192.168.4.63", "192.168.4.64", "192.168.4.127", "192.168.4.255"), 0,
  "Ein /26 fasst 64 Adressen, das erste Subnetz reicht also von .0 bis .63. Die letzte Adresse eines Subnetzes ist immer der Broadcast, hier .63; .64 ist bereits die Netzadresse des nächsten Blocks.",
  "What is the broadcast address of the network 192.168.4.0/26?",
  ("192.168.4.63", "192.168.4.64", "192.168.4.127", "192.168.4.255"),
  "A /26 holds 64 addresses, so the first subnet runs from .0 to .63. The last address of a subnet is always the broadcast, here .63; .64 is already the network address of the next block."),

S("ap1-net-r24",
  "Der Link zu einem Server ist tot, die Link-LED bleibt an beiden Enden dunkel. Was prüfst du zuerst?",
  ("Kabel und Steckverbindung auf der gesamten Strecke",
   "Die Firewallregeln auf dem betroffenen Server",
   "Die DNS-Einträge des Servers auf dem DNS-Server",
   "Die Routingtabelle des zuständigen Standardgateways"), 0,
  "Eine dunkle Link-LED heißt: auf Schicht 1 kommt gar kein Signal an. Firewall, DNS und Routing arbeiten erst auf höheren Schichten und können eine tote LED gar nicht verursachen.",
  "The link to a server is dead and the link LED stays dark at both ends. What do you check first?",
  ("Cabling and connectors along the entire run",
   "The firewall rules on the affected server",
   "The DNS records of the server on the DNS server",
   "The routing table of the responsible default gateway"),
  "A dark link LED means no signal arrives at layer 1 at all. Firewall, DNS and routing only operate on higher layers and cannot cause a dead LED."),

S("ap1-net-r25",
  "Welche Adresse spricht immer den eigenen Rechner an?",
  ("127.0.0.1", "192.168.0.1", "255.255.255.0", "169.254.0.1"), 0,
  "127.0.0.0/8 ist als Loopback reserviert, üblich ist 127.0.0.1. 192.168.0.1 ist eine gewöhnliche private Adresse, 255.255.255.0 eine Subnetzmaske und 169.254.x.x eine APIPA-Adresse.",
  "Which address always addresses the local machine itself?",
  ("127.0.0.1", "192.168.0.1", "255.255.255.0", "169.254.0.1"),
  "127.0.0.0/8 is reserved as loopback, commonly 127.0.0.1. 192.168.0.1 is an ordinary private address, 255.255.255.0 is a subnet mask and 169.254.x.x is an APIPA address."),

S("ap1-net-r26",
  "Ein Port soll mehrere VLANs zu einem zweiten Switch transportieren. Wie konfigurierst du ihn?",
  ("Als Trunk-Port mit Tagging nach 802.1Q",
   "Als Access-Port im höchstnummerierten VLAN",
   "Als gespiegelten Port für die Netzwerkanalyse",
   "Als LACP-Port für die Bündelung der Bandbreite"), 0,
  "Ein Trunk markiert jeden Frame mit seiner VLAN-ID, sodass der Nachbarswitch die Zuordnung kennt. Ein Access-Port führt genau ein VLAN ungetaggt, Portspiegelung und Bandbreitenbündelung lösen ganz andere Aufgaben.",
  "A port must carry several VLANs to a second switch. How do you configure it?",
  ("As a trunk port with 802.1Q tagging",
   "As an access port in the highest numbered VLAN",
   "As a mirrored port for network analysis",
   "As an LACP port for bundling bandwidth"),
  "A trunk tags every frame with its VLAN ID so the neighbouring switch knows the assignment. An access port carries exactly one VLAN untagged; port mirroring and link bundling solve entirely different problems."),

S("ap1-net-r27",
  "Wie viele nutzbare Hostadressen bietet ein /28-Netz?",
  ("14", "16", "12", "30"), 0,
  "Bei /28 bleiben 4 Hostbits, das ergibt 16 Adressen. Netzadresse und Broadcast sind nicht vergebbar, also bleiben 14 nutzbare Hostadressen.",
  "How many usable host addresses does a /28 network provide?",
  ("14", "16", "12", "30"),
  "A /28 leaves 4 host bits, giving 16 addresses. Network address and broadcast cannot be assigned, so 14 usable host addresses remain."),

S("ap1-net-r28",
  "Im Lager bricht das WLAN regelmäßig ab. Der Access Point steht 60 m entfernt hinter Regalen. Was tust du?",
  ("Einen zweiten Access Point im Lager mit Kabel anbinden",
   "Die Verschlüsselung von WPA2 auf WPA3 hochstufen",
   "Die maximale Anzahl der DHCP-Leases deutlich erhöhen",
   "Auf dem Access Point einen kürzeren Netzwerknamen setzen"), 0,
  "Regale dämpfen das Funksignal stark, dagegen hilft nur ein Sender in der Nähe. Verschlüsselung, DHCP-Größe und SSID-Länge haben keinen Einfluss auf die Funkausleuchtung.",
  "In the warehouse the WLAN keeps dropping. The access point is 60 m away behind shelving. What do you do?",
  ("Install a second wired access point inside the warehouse",
   "Upgrade the encryption from WPA2 to WPA3",
   "Raise the maximum number of DHCP leases considerably",
   "Set a shorter network name on the access point"),
  "Shelving heavily attenuates the radio signal, and only a transmitter nearby helps. Encryption, DHCP scope size and SSID length have no influence on radio coverage."),

S("ap1-net-r29",
  "Welche Aussage beschreibt den Unterschied zwischen Hub und Switch zutreffend?",
  ("Der Switch sendet gezielt an einen Port, der Hub an alle",
   "Der Switch arbeitet auf Schicht 1, der Hub auf Schicht 2",
   "Der Hub trennt Kollisionsdomänen, der Switch fasst sie zusammen",
   "Der Hub kann VLANs bilden, der Switch nur Ports spiegeln"), 0,
  "Der Hub ist ein reiner Signalverstärker und schickt jedes Signal an alle Ports, wodurch eine gemeinsame Kollisionsdomäne entsteht. Der Switch lernt MAC-Adressen und gibt jedem Port seine eigene Kollisionsdomäne.",
  "Which statement correctly describes the difference between a hub and a switch?",
  ("The switch sends to one specific port, the hub to all of them",
   "The switch works on layer 1, the hub works on layer 2",
   "The hub separates collision domains, the switch merges them",
   "The hub can create VLANs, the switch can only mirror ports"),
  "A hub is a pure signal repeater and sends every signal to all ports, creating one shared collision domain. A switch learns MAC addresses and gives every port its own collision domain."),

S("ap1-net-r30",
  "Ein neuer PC bekommt keine Adresse, andere Geräte im selben VLAN schon. Was prüfst du zuerst?",
  ("Ob der DHCP-Adressbereich bereits vollständig vergeben ist",
   "Ob der Provider die öffentliche IP-Adresse gewechselt hat",
   "Ob auf dem Zielserver die richtigen Freigaben gesetzt sind",
   "Ob der Router die passende Standardroute eingetragen hat"), 0,
  "Wenn nur das neue Gerät leer ausgeht, spricht das für einen erschöpften Adresspool - die bereits versorgten Geräte halten ihre Leases weiter. Providerwechsel und Serverfreigaben haben mit der lokalen Adressvergabe nichts zu tun.",
  "A new PC gets no address while other devices in the same VLAN do. What do you check first?",
  ("Whether the DHCP address range is already fully handed out",
   "Whether the provider has changed the public IP address",
   "Whether the correct shares are set on the target server",
   "Whether the router has the matching default route entered"),
  "If only the new device goes empty-handed, an exhausted address pool is the likely cause - already served devices keep their leases. Provider changes and server shares have nothing to do with local address assignment."),

S("ap1-net-r31",
  "Welche Angabe beschreibt die Latenz einer Verbindung?",
  ("Die Verzögerung, bis ein Paket beim Ziel eintrifft",
   "Die Datenmenge, die pro Sekunde übertragen wird",
   "Der Anteil der Pakete, der unterwegs verloren geht",
   "Die Schwankung der Laufzeit zwischen zwei Paketen"), 0,
  "Latenz ist die reine Laufzeit, meist in Millisekunden gemessen. Die Datenmenge pro Sekunde ist der Durchsatz, die Laufzeitschwankung der Jitter und der Verlustanteil die Paketverlustrate.",
  "Which description matches the latency of a connection?",
  ("The delay until a packet arrives at its destination",
   "The amount of data transferred per second",
   "The share of packets that get lost along the way",
   "The variation in transit time between two packets"),
  "Latency is the pure transit time, usually measured in milliseconds. Data per second is throughput, variation in transit time is jitter, and the lost share is the packet loss rate."),

S("ap1-net-r32",
  "Ein Rechner soll ein Paket an 8.8.8.8 senden. Wessen MAC-Adresse trägt er als Ziel ein?",
  ("Die des Standardgateways in seinem Netz",
   "Die des Zielservers mit der Adresse 8.8.8.8",
   "Die des DNS-Servers aus seiner Konfiguration",
   "Die Broadcast-MAC, weil das Ziel extern liegt"), 0,
  "Auf Schicht 2 kann nur adressiert werden, wer im selben Segment liegt. Für entfernte Ziele trägt der Host die IP des Ziels, aber die MAC des Gateways ein - der Router setzt die MAC dann Hop für Hop neu.",
  "A computer wants to send a packet to 8.8.8.8. Whose MAC address does it enter as destination?",
  ("That of the default gateway in its own network",
   "That of the target server with the address 8.8.8.8",
   "That of the DNS server from its configuration",
   "The broadcast MAC, because the target is external"),
  "On layer 2 only devices in the same segment can be addressed. For remote targets the host enters the target's IP but the gateway's MAC - the router then rewrites the MAC hop by hop."),

# -------------------------------------------------------------- multiple (32)
M("ap1-net-r33",
  "Welche Angaben braucht ein Client zwingend, um ein Ziel im Internet per Namen zu erreichen?",
  ("Eine eigene IP-Adresse", "Eine passende Subnetzmaske", "Die Adresse des Standardgateways",
   "Die Adresse eines DNS-Servers", "Die MAC-Adresse des Zielservers", "Die Seriennummer der Netzwerkkarte"),
  (0, 1, 2, 3),
  "Adresse und Maske bestimmen das eigene Netz, das Gateway den Weg nach draußen, DNS die Namensauflösung - genau diese vier verteilt auch ein DHCP-Server. Die Ziel-MAC ermittelt der Router selbst, die Seriennummer spielt keine Rolle.",
  "Which entries does a client strictly need to reach an internet target by name?",
  ("Its own IP address", "A matching subnet mask", "The address of the default gateway",
   "The address of a DNS server", "The MAC address of the target server", "The serial number of the network card"),
  "Address and mask define the local network, the gateway the way out, DNS the name resolution - exactly the four a DHCP server hands out. The target MAC is determined by the router itself, the serial number is irrelevant."),

M("ap1-net-r34",
  "Welche Aussagen über IPv6 treffen zu?",
  ("Eine Adresse ist 128 Bit lang", "Die Notation erfolgt hexadezimal", "Broadcasts wurden durch Multicast ersetzt",
   "NAT ist für den Internetzugang zwingend nötig", "Eine Adresse besteht aus 4 Blöcken", "Die Adresse wird stets manuell vergeben"),
  (0, 1, 2),
  "IPv6 nutzt 128 Bit in 8 hexadezimalen Blöcken zu je 16 Bit und kennt statt Broadcast nur noch Multicast. Der riesige Adressraum macht NAT gerade überflüssig, und Adressen kommen meist per SLAAC oder DHCPv6.",
  "Which statements about IPv6 are correct?",
  ("An address is 128 bits long", "Notation is hexadecimal", "Broadcasts were replaced by multicast",
   "NAT is strictly required for internet access", "An address consists of 4 blocks", "Addresses are always assigned manually"),
  "IPv6 uses 128 bits in 8 hexadecimal blocks of 16 bits each and replaces broadcast with multicast. The huge address space makes NAT unnecessary, and addresses usually come via SLAAC or DHCPv6."),

M("ap1-net-r35",
  "Welche Aufgaben erfüllt ein DHCP-Server in einem Firmennetz?",
  ("Er vergibt IP-Adressen aus einem definierten Bereich",
   "Er teilt den Clients die Subnetzmaske mit",
   "Er nennt den Clients Gateway und DNS-Server",
   "Er verwaltet die Leasedauer der Zuweisungen",
   "Er übersetzt Hostnamen in IP-Adressen",
   "Er filtert unerwünschten Verkehr nach Regeln"),
  (0, 1, 2, 3),
  "DHCP liefert das komplette Adresspaket auf Zeit: Adresse, Maske, Gateway und DNS mit befristeter Lease. Namen auflösen ist Sache von DNS, Verkehr filtern Sache der Firewall.",
  "Which tasks does a DHCP server perform in a company network?",
  ("It assigns IP addresses from a defined range",
   "It tells clients their subnet mask",
   "It names the gateway and DNS server to clients",
   "It manages the lease duration of assignments",
   "It translates hostnames into IP addresses",
   "It filters unwanted traffic based on rules"),
  "DHCP delivers the complete address package on a timer: address, mask, gateway and DNS with a limited lease. Resolving names is DNS's job, filtering traffic the firewall's."),

M("ap1-net-r36",
  "Welche Vorteile bringt die Aufteilung eines großen Netzes in Subnetze?",
  ("Broadcasts bleiben auf ihr Teilnetz begrenzt",
   "Der Verkehr lässt sich zwischen Bereichen gezielt filtern",
   "Fehler lassen sich auf einen Bereich eingrenzen",
   "Die Bruttogeschwindigkeit der Kabel steigt an",
   "Die Anzahl nutzbarer Adressen insgesamt steigt",
   "Ein DNS-Server wird dadurch entbehrlich"),
  (0, 1, 2),
  "Kleinere Broadcast-Domänen, gezieltere Filterung und leichtere Fehlersuche sind die klassischen Gründe. Die Leitungsgeschwindigkeit bleibt unverändert, und durch Netz- und Broadcastadressen je Subnetz gehen sogar Adressen verloren.",
  "Which advantages come from splitting a large network into subnets?",
  ("Broadcasts stay confined to their own subnet",
   "Traffic between areas can be filtered deliberately",
   "Faults can be narrowed down to one area",
   "The groß speed of the cabling increases",
   "The total number of usable addresses grows",
   "A DNS server becomes unnecessary"),
  "Smaller broadcast domains, more targeted filtering and easier troubleshooting are the classic reasons. Line speed stays unchanged, and network plus broadcast addresses per subnet actually cost addresses."),

M("ap1-net-r37",
  "Welche Schritte gehören zu einer sinnvollen Fehlersuche nach dem OSI-Modell von unten nach oben?",
  ("Kabel und Link-LED prüfen",
   "IP-Konfiguration des Hosts prüfen",
   "Erreichbarkeit des Gateways per ping testen",
   "Namensauflösung per nslookup testen",
   "Zuerst den Anwendungsserver neu installieren",
   "Zuerst die Netzwerkkarte pauschal austauschen"),
  (0, 1, 2, 3),
  "Von unten nach oben heißt: erst Physik, dann Adressierung, dann Routing, dann Dienste. Neuinstallation und Hardwaretausch auf Verdacht überspringen die Diagnose und kosten unnötig Zeit.",
  "Which steps belong to a sensible bottom-up troubleshooting approach along the OSI model?",
  ("Check the cable and the link LED",
   "Check the host's IP configuration",
   "Test reachability of the gateway with ping",
   "Test name resolution with nslookup",
   "Reinstall the application server first",
   "Replace the network card outright first"),
  "Bottom-up means physics first, then addressing, then routing, then services. Reinstalling or swapping hardware on suspicion skips the diagnosis and wastes time."),

M("ap1-net-r38",
  "Welche Merkmale treffen auf TCP zu?",
  ("Es baut vor der Übertragung eine Verbindung auf",
   "Es bestätigt empfangene Segmente",
   "Es sendet verlorene Segmente erneut",
   "Es stellt die richtige Reihenfolge wieder her",
   "Es verzichtet zugunsten der Geschwindigkeit auf Bestätigungen",
   "Es arbeitet ausschließlich innerhalb eines Subnetzes"),
  (0, 1, 2, 3),
  "TCP ist verbindungsorientiert und zuverlässig: Handshake, Bestätigungen, Neuversand und Sortierung gehören zum Kern. Der Verzicht auf Bestätigungen kennzeichnet UDP, und die Subnetzgrenze ist Sache von Schicht 2.",
  "Which characteristics apply to TCP?",
  ("It establishes a connection before transmitting",
   "It acknowledges received segments",
   "It retransmits lost segments",
   "It restores the correct order of data",
   "It skips acknowledgements in favour of speed",
   "It operates strictly within a single subnet"),
  "TCP is connection-oriented and reliable: handshake, acknowledgements, retransmission and reordering are core features. Skipping acknowledgements characterises UDP, and subnet boundaries are a layer 2 matter."),

M("ap1-net-r39",
  "Welche Bestandteile gehören zu einer strukturierten Gebäudeverkabelung?",
  ("Primärbereich zwischen den Gebäuden",
   "Sekundärbereich zwischen den Etagen",
   "Tertiärbereich innerhalb einer Etage",
   "Patchfeld im Etagenverteiler",
   "Der öffentliche Anschluss des Providers",
   "Die WLAN-Funkzelle im Außenbereich"),
  (0, 1, 2, 3),
  "Die Norm gliedert in Primär, Sekundär und Tertiär, verbunden über Verteiler mit Patchfeldern. Der Providerabschluss liegt vor der Gebäudeverkabelung, Funkzellen sind kein Teil der festen Verkabelung.",
  "Which elements belong to structured building cabling?",
  ("Primary area between buildings",
   "Secondary area between floors",
   "Tertiary area within one floor",
   "Patch panel in the floor distributor",
   "The provider's public connection point",
   "The outdoor WLAN radio cell"),
  "The standard divides cabling into primary, secondary and tertiary areas linked by distributors with patch panels. The provider handover sits before the building cabling, and radio cells are not part of fixed cabling."),

M("ap1-net-r40",
  "Welche Ports sind den genannten Diensten korrekt zugeordnet?",
  ("SSH auf 22", "DNS auf 53", "SMTP auf 25", "RDP auf 3389",
   "FTP auf knapp 8000", "HTTP auf 143"),
  (0, 1, 2, 3),
  "22 SSH, 53 DNS, 25 SMTP und 3389 RDP sind Standardzuordnungen. FTP nutzt 20 und 21, HTTP den Port 80 - 143 gehört zu IMAP.",
  "Which ports are correctly assigned to the listed services?",
  ("SSH on 22", "DNS on 53", "SMTP on 25", "RDP on 3389",
   "FTP on roughly 8000", "HTTP on 143"),
  "22 SSH, 53 DNS, 25 SMTP and 3389 RDP are the standard assignments. FTP uses 20 and 21, HTTP uses port 80 - 143 belongs to IMAP."),

M("ap1-net-r41",
  "Was spricht dafür, im Serverraum Glasfaser statt Kupfer zu verlegen?",
  ("Größere überbrückbare Entfernungen",
   "Unempfindlichkeit gegen elektromagnetische Störungen",
   "Kein Übersprechen zwischen benachbarten Fasern",
   "Höhere erreichbare Übertragungsraten",
   "Deutlich günstigere Steckverbinder und Werkzeuge",
   "Möglichkeit, Endgeräte über die Faser zu speisen"),
  (0, 1, 2, 3),
  "Glasfaser punktet bei Reichweite, Störfestigkeit, Übersprechen und Bandbreite. Konfektionierung und Messtechnik sind allerdings teurer, und eine Stromversorgung wie PoE ist über Licht nicht möglich.",
  "What argues for installing fibre instead of copper in the server room?",
  ("Greater distances that can be bridged",
   "Immunity to electromagnetic interference",
   "No crosstalk between neighbouring fibres",
   "Higher achievable transmission rates",
   "Considerably cheaper connectors and tools",
   "The option to power end devices over the fibre"),
  "Fibre wins on reach, interference immunity, crosstalk and bandwidth. Termination and measurement equipment are more expensive, though, and power delivery like PoE is impossible over light."),

M("ap1-net-r42",
  "Welche Maßnahmen erhöhen die Sicherheit eines Firmen-WLANs tatsächlich?",
  ("WPA3 oder mindestens WPA2 mit AES einsetzen",
   "Ein langes, zufälliges Passwort vergeben",
   "Gäste in ein eigenes, getrenntes Netz legen",
   "WPS per Knopfdruck deaktivieren",
   "Die SSID verstecken statt sie zu senden",
   "Ausschließlich auf einen MAC-Filter setzen"),
  (0, 1, 2, 3),
  "Starke Verschlüsselung, ein gutes Passwort, Netztrennung und abgeschaltetes WPS wirken wirklich. Versteckte SSIDs und MAC-Filter sind mit einfachen Mitteln auslesbar und geben nur ein Gefühl von Sicherheit.",
  "Which measures genuinely increase the security of a company WLAN?",
  ("Use WPA3 or at least WPA2 with AES",
   "Set a long, random passphrase",
   "Put guests into their own separate network",
   "Disable push-button WPS",
   "Hide the SSID instead of broadcasting it",
   "Rely exclusively on a MAC filter"),
  "Strong encryption, a good passphrase, network separation and disabled WPS genuinely help. Hidden SSIDs and MAC filters are readable with simple tools and only create a feeling of security."),

M("ap1-net-r43",
  "Welche Aussagen zur MAC-Adresse sind korrekt?",
  ("Sie ist 48 Bit lang",
   "Sie wird hexadezimal dargestellt",
   "Die erste Hälfte kennzeichnet den Hersteller",
   "Sie wird auf Schicht 2 ausgewertet",
   "Sie wird von einem DHCP-Server vergeben",
   "Sie ändert sich bei jedem Netzwechsel"),
  (0, 1, 2, 3),
  "48 Bit in Hexschreibweise, davon die ersten 24 Bit als Herstellerkennung OUI - ausgewertet wird sie auf der Sicherungsschicht. DHCP vergibt IP-Adressen, nicht MACs, und die MAC bleibt beim Netzwechsel gleich.",
  "Which statements about the MAC address are correct?",
  ("It is 48 bits long",
   "It is written in hexadecimal",
   "The first half identifies the manufacturer",
   "It is evaluated on layer 2",
   "It is assigned by a DHCP server",
   "It changes whenever the network changes"),
  "48 bits in hexadecimal notation, the first 24 of which form the manufacturer OUI - evaluated on the data link layer. DHCP assigns IP addresses, not MACs, and the MAC stays the same across networks."),

M("ap1-net-r44",
  "Welche Werkzeuge liefern bei einem Netzwerkproblem unter Windows nützliche Hinweise?",
  ("ipconfig /all für die eigene Konfiguration",
   "ping für die Erreichbarkeit eines Ziels",
   "tracert für den Weg zum Ziel",
   "nslookup für die Namensauflösung",
   "chkdsk für die Netzwerkeinstellungen",
   "diskpart für die Routingtabelle"),
  (0, 1, 2, 3),
  "ipconfig, ping, tracert und nslookup decken Konfiguration, Erreichbarkeit, Pfad und DNS ab. chkdsk prüft Dateisysteme und diskpart verwaltet Partitionen - beide haben mit dem Netz nichts zu tun.",
  "Which tools give useful hints for a network problem on Windows?",
  ("ipconfig /all for the local configuration",
   "ping for reachability of a target",
   "tracert for the path to the target",
   "nslookup for name resolution",
   "chkdsk for the network settings",
   "diskpart for the routing table"),
  "ipconfig, ping, tracert and nslookup cover configuration, reachability, path and DNS. chkdsk checks file systems and diskpart manages partitions - neither has anything to do with the network."),

M("ap1-net-r45",
  "Welche Aussagen über VLANs sind zutreffend?",
  ("Sie trennen ein physisches Netz logisch auf",
   "Jedes VLAN bildet eine eigene Broadcast-Domäne",
   "Verkehr zwischen VLANs braucht Routing",
   "Ein Trunk transportiert mehrere VLANs getaggt",
   "Ein VLAN erhöht automatisch die Portgeschwindigkeit",
   "VLANs verschlüsseln den Datenverkehr"),
  (0, 1, 2, 3),
  "VLANs schneiden logische Netze aus einer physischen Infrastruktur, jedes mit eigener Broadcast-Domäne; der Übergang läuft über einen Router. Weder Geschwindigkeit noch Verschlüsselung ändern sich dadurch.",
  "Which statements about VLANs are correct?",
  ("They separate a physical network logically",
   "Each VLAN forms its own broadcast domain",
   "Traffic between VLANs requires routing",
   "A trunk carries several VLANs tagged",
   "A VLAN automatically raises port speed",
   "VLANs encrypt the data traffic"),
  "VLANs carve logical networks out of one physical infrastructure, each with its own broadcast domain; crossing between them needs a router. Neither speed nor encryption changes as a result."),

M("ap1-net-r46",
  "Welche Angaben gehören zwingend in die Dokumentation einer Netzwerkverkabelung?",
  ("Verlauf und Länge der einzelnen Strecken",
   "Bezeichnung der Dosen und Patchfeldports",
   "Verwendete Kabelkategorie je Strecke",
   "Ergebnisse der Abnahmemessung",
   "Der Kaufpreis der eingesetzten Endgeräte",
   "Die Namen der Nutzer an jedem Arbeitsplatz"),
  (0, 1, 2, 3),
  "Für spätere Fehlersuche und Erweiterung braucht man Wege, eindeutige Kennzeichnungen, Kabelkategorie und Messprotokolle. Preise und Nutzernamen ändern sich ständig und gehören in andere Verzeichnisse.",
  "Which details must appear in the documentation of a network cabling installation?",
  ("Route and length of the individual runs",
   "Labelling of outlets and patch panel ports",
   "Cable category used on each run",
   "Results of the acceptance measurements",
   "The purchase price of the end devices used",
   "The names of the users at each workstation"),
  "Later troubleshooting and expansion require routes, unambiguous labels, cable category and test reports. Prices and user names change constantly and belong in other records."),

M("ap1-net-r47",
  "Welche Adressen sind in einem /24-Netz nicht an einen Host vergebbar?",
  ("Die Netzadresse mit Hostteil null",
   "Die Broadcast-Adresse mit Hostteil voll gesetzt",
   "Adressen aus dem Loopback-Bereich 127.x.x.x",
   "Adressen mit einem Oktett größer als 255",
   "Die erste vergebbare Adresse des Bereichs",
   "Die Adresse des Standardgateways im Netz"),
  (0, 1, 2, 3),
  "Netz- und Broadcastadresse sind reserviert, Loopback ist für den eigenen Rechner gedacht und Oktette über 255 existieren nicht. Die erste nutzbare Adresse und die Gatewayadresse sind dagegen ganz normale Hostadressen.",
  "Which addresses cannot be assigned to a host in a /24 network?",
  ("The network address with an all-zero host part",
   "The broadcast address with an all-ones host part",
   "Addresses from the loopback range 127.x.x.x",
   "Addresses with an octet greater than 255",
   "The first assignable address of the range",
   "The address of the default gateway"),
  "Network and broadcast addresses are reserved, loopback is meant for the local machine and octets above 255 do not exist. The first usable address and the gateway address are perfectly normal host addresses."),

M("ap1-net-r48",
  "Ein Anwender meldet: kein Netz. Welche Beobachtungen grenzen den Fehler sinnvoll ein?",
  ("Ob nur er oder auch Nachbarn betroffen sind",
   "Ob die Link-LED am Switchport leuchtet",
   "Ob er eine gültige IP-Adresse bezogen hat",
   "Ob das Gateway auf ping antwortet",
   "Ob sein Bildschirm die richtige Auflösung hat",
   "Ob der Drucker im Nachbarraum Toner hat"),
  (0, 1, 2, 3),
  "Reichweite des Problems, Link, Adressbezug und Gateway-Erreichbarkeit engen die Ursache Schicht für Schicht ein. Bildschirmauflösung und Tonerstand haben mit der Netzanbindung nichts zu tun.",
  "A user reports no network. Which observations sensibly narrow down the fault?",
  ("Whether only they or neighbours are affected too",
   "Whether the link LED on the switch port is lit",
   "Whether they obtained a valid IP address",
   "Whether the gateway answers a ping",
   "Whether their screen has the right resolution",
   "Whether the printer next door has toner"),
  "Scope of the problem, link state, address assignment and gateway reachability narrow the cause down layer by layer. Screen resolution and toner level have nothing to do with network connectivity."),

M("ap1-net-r49",
  "Welche Aussagen über das ARP-Protokoll sind richtig?",
  ("Es ermittelt zu einer IPv4-Adresse die passende MAC",
   "Es arbeitet nur innerhalb des lokalen Netzsegments",
   "Die Anfrage geht als Broadcast an alle Geräte",
   "Ergebnisse werden befristet zwischengespeichert",
   "Es übersetzt Hostnamen in IP-Adressen",
   "Es vergibt IP-Adressen an neue Geräte"),
  (0, 1, 2, 3),
  "ARP fragt per Broadcast nach der MAC zu einer IP und legt die Antwort im ARP-Cache ab, gültig nur im eigenen Segment. Namen auflösen macht DNS, Adressen vergeben DHCP.",
  "Which statements about the ARP protocol are correct?",
  ("It finds the matching MAC for an IPv4 address",
   "It works only within the local network segment",
   "The request goes out as a broadcast to all devices",
   "Results are cached for a limited time",
   "It translates hostnames into IP addresses",
   "It assigns IP addresses to new devices"),
  "ARP broadcasts a request for the MAC belonging to an IP and stores the answer in the ARP cache, valid only in its own segment. Resolving names is DNS, assigning addresses is DHCP."),

M("ap1-net-r50",
  "Welche Faktoren begrenzen den tatsächlichen Durchsatz eines WLANs?",
  ("Anzahl der gleichzeitig aktiven Clients",
   "Störungen durch benachbarte Funknetze",
   "Baustoffe und Wände zwischen Sender und Client",
   "Der gemeinsam genutzte Funkkanal",
   "Die Länge des Netzwerknamens SSID",
   "Die Farbe des Gehäuses am Access Point"),
  (0, 1, 2, 3),
  "Funk ist ein geteiltes Medium: mehr Clients, Nachbarnetze, Dämpfung durch Baustoffe und Kanalbelegung drücken den Durchsatz. SSID-Länge und Gehäusefarbe sind ohne jeden Einfluss.",
  "Which factors limit the actual throughput of a WLAN?",
  ("Number of simultaneously active clients",
   "Interference from neighbouring radio networks",
   "Building materials and walls between sender and client",
   "The shared radio channel in use",
   "The length of the network name SSID",
   "The colour of the access point housing"),
  "Radio is a shared medium: more clients, neighbouring networks, attenuation by building materials and channel occupancy all reduce throughput. SSID length and housing colour have no influence whatsoever."),

M("ap1-net-r51",
  "Welche Aufgaben übernimmt ein Router?",
  ("Er verbindet unterschiedliche IP-Netze miteinander",
   "Er trifft Weiterleitungsentscheidungen anhand von IP-Adressen",
   "Er begrenzt die Ausbreitung von Broadcasts",
   "Er führt eine Routingtabelle mit Zielnetzen",
   "Er lernt MAC-Adressen und speichert sie portweise",
   "Er verstärkt Signale, ohne sie auszuwerten"),
  (0, 1, 2, 3),
  "Router arbeiten auf Schicht 3: sie koppeln Netze, entscheiden anhand der Routingtabelle und lassen Broadcasts nicht durch. MAC-Lernen ist Switch-Aufgabe, reines Verstärken die eines Repeaters.",
  "Which tasks does a router perform?",
  ("It connects different IP networks with each other",
   "It makes forwarding decisions based on IP addresses",
   "It limits the spread of broadcasts",
   "It maintains a routing table of destination networks",
   "It learns MAC addresses and stores them per port",
   "It amplifies signals without evaluating them"),
  "Routers work on layer 3: they couple networks, decide via the routing table and do not pass broadcasts. Learning MACs is a switch's job, pure amplification a repeater's."),

M("ap1-net-r52",
  "Welche Schritte sind nötig, damit ein neuer Arbeitsplatz ans Netz kommt?",
  ("Dose und Patchfeldport auflegen und beschriften",
   "Patchkabel vom Patchfeld auf einen Switchport stecken",
   "Den Port dem richtigen VLAN zuordnen",
   "Die Strecke messen und das Ergebnis dokumentieren",
   "Den Switch komplett neu konfigurieren",
   "Allen Nutzern neue Passwörter zuweisen"),
  (0, 1, 2, 3),
  "Auflegen, patchen, VLAN zuordnen und messen sind die Standardschritte einer Neuanbindung. Eine komplette Neukonfiguration des Switches oder ein Passwortwechsel für alle wäre völlig unverhältnismäßig.",
  "Which steps are needed to connect a new workstation to the network?",
  ("Terminate and label the outlet and patch panel port",
   "Patch from the patch panel to a switch port",
   "Assign the port to the correct VLAN",
   "Measure the link and document the result",
   "Reconfigure the switch completely from scratch",
   "Assign new passwords to all users"),
  "Terminating, patching, VLAN assignment and measurement are the standard steps of a new connection. Reconfiguring the whole switch or changing everyone's password would be entirely disproportionate."),

M("ap1-net-r53",
  "Welche Eigenschaften kennzeichnen UDP?",
  ("Es arbeitet ohne vorherigen Verbindungsaufbau",
   "Es bestätigt den Empfang nicht",
   "Es hat weniger Protokoll-Overhead als TCP",
   "Es eignet sich für Echtzeitdaten wie Sprache",
   "Es sichert die Reihenfolge der Pakete zu",
   "Es wiederholt verlorene Pakete automatisch"),
  (0, 1, 2, 3),
  "UDP verschickt Datagramme ohne Handshake, ohne Bestätigung und mit kleinem Header - ideal, wenn Tempo wichtiger als Vollständigkeit ist. Reihenfolge und Neuversand garantiert nur TCP.",
  "Which characteristics define UDP?",
  ("It works without establishing a connection first",
   "It does not acknowledge receipt",
   "It carries less protocol overhead than TCP",
   "It suits real-time data such as voice",
   "It guarantees the order of packets",
   "It automatically repeats lost packets"),
  "UDP sends datagrams without handshake, without acknowledgement and with a small header - ideal when speed matters more than completeness. Ordering and retransmission are guaranteed only by TCP."),

M("ap1-net-r54",
  "Welche Aussagen zur Subnetzmaske 255.255.255.192 sind korrekt?",
  ("Sie entspricht der Präfixlänge /26",
   "Sie lässt 6 Bit für den Hostteil übrig",
   "Sie erlaubt 62 nutzbare Hostadressen",
   "Sie teilt ein /24 in vier gleiche Blöcke",
   "Sie entspricht der Präfixlänge /28",
   "Sie erlaubt 126 nutzbare Hostadressen"),
  (0, 1, 2, 3),
  "192 als letztes Oktett sind 11000000, also 2 zusätzliche Netzbits: /26 mit 6 Hostbits, 64 Adressen und 62 nutzbaren. Damit zerfällt ein /24 in genau vier Blöcke.",
  "Which statements about the subnet mask 255.255.255.192 are correct?",
  ("It corresponds to prefix length /26",
   "It leaves 6 bits for the host part",
   "It allows 62 usable host addresses",
   "It splits a /24 into four equal blocks",
   "It corresponds to prefix length /28",
   "It allows 126 usable host addresses"),
  "192 in the last octet is 11000000, i.e. 2 extra network bits: /26 with 6 host bits, 64 addresses and 62 usable ones. That divides a /24 into exactly four blocks."),

M("ap1-net-r55",
  "Welche Angaben sollte ein Ticket zu einer Netzwerkstörung enthalten?",
  ("Wer betroffen ist und seit wann",
   "Welche Fehlermeldung genau erscheint",
   "Ob das Problem reproduzierbar ist",
   "Was bereits geprüft wurde",
   "Wie hoch das Jahresbudget der Abteilung ist",
   "Welche Farbe das Gehäuse des PCs hat"),
  (0, 1, 2, 3),
  "Betroffene, Zeitpunkt, Wortlaut der Meldung, Reproduzierbarkeit und bereits geprüfte Punkte machen ein Ticket bearbeitbar und verhindern doppelte Arbeit. Budget und Gehäusefarbe helfen bei der Lösung nicht.",
  "Which details should a ticket about a network fault contain?",
  ("Who is affected and since when",
   "Which error message appears exactly",
   "Whether the problem is reproducible",
   "What has already been checked",
   "How large the department's annual budget is",
   "What colour the PC housing has"),
  "Affected users, timing, the exact wording of the message, reproducibility and steps already checked make a ticket workable and prevent duplicated effort. Budget and housing colour do not help solve it."),

M("ap1-net-r56",
  "Welche Aussagen zu Spanning Tree treffen zu?",
  ("Es verhindert Schleifen in vermaschten Switchnetzen",
   "Es blockiert dafür gezielt einzelne Ports",
   "Es wählt eine Root Bridge im Netz",
   "Blockierte Wege werden bei Ausfall aktiviert",
   "Es beschleunigt die Übertragung auf allen Ports",
   "Es ersetzt die Notwendigkeit eines Routers"),
  (0, 1, 2, 3),
  "STP baut aus einem vermaschten Netz einen schleifenfreien Baum: eine Root Bridge wird gewählt, überzählige Wege werden blockiert und im Fehlerfall wieder freigegeben. Mit Geschwindigkeit oder Routing hat es nichts zu tun.",
  "Which statements about Spanning Tree are correct?",
  ("It prevents loops in meshed switch networks",
   "To do so it deliberately blocks individual ports",
   "It elects a root bridge in the network",
   "Blocked paths are activated on failure",
   "It speeds up transmission on all ports",
   "It removes the need for a router"),
  "STP builds a loop-free tree out of a meshed network: a root bridge is elected, surplus paths are blocked and released again on failure. It has nothing to do with speed or routing."),

M("ap1-net-r57",
  "Welche Merkmale hat ein Managed Switch gegenüber einem unmanaged Switch?",
  ("VLANs lassen sich einrichten",
   "Ports lassen sich einzeln konfigurieren",
   "Der Zustand lässt sich per SNMP auslesen",
   "Portspiegelung für Analysen ist möglich",
   "Er benötigt grundsätzlich keinen Strom",
   "Er ersetzt die Firewall am Internetübergang"),
  (0, 1, 2, 3),
  "Konfigurierbarkeit ist der ganze Unterschied: VLANs, Portparameter, Monitoring und Spiegelung. Strom braucht er selbstverständlich, und eine Firewall am Netzübergang ersetzt er nicht.",
  "Which features does a managed switch have over an unmanaged one?",
  ("VLANs can be configured",
   "Ports can be configured individually",
   "Status can be read out via SNMP",
   "Port mirroring for analysis is possible",
   "It fundamentally requires no power supply",
   "It replaces the firewall at the internet edge"),
  "Configurability is the entire difference: VLANs, port parameters, monitoring and mirroring. It obviously still needs power, and it does not replace a firewall at the network edge."),

M("ap1-net-r58",
  "Welche Ursachen können dazu führen, dass ein ping das Ziel nicht erreicht?",
  ("Eine Firewall verwirft ICMP-Pakete",
   "Das Ziel ist ausgeschaltet oder gestartet gerade",
   "Eine Route zum Zielnetz fehlt",
   "Die Ziel-IP wurde falsch eingegeben",
   "Auf dem Ziel ist zu wenig Speicherplatz frei",
   "Der Bildschirmschoner des Ziels ist aktiv"),
  (0, 1, 2, 3),
  "Gefilterte ICMP-Pakete, ein abgeschaltetes Ziel, fehlendes Routing und Tippfehler sind die häufigsten Gründe. Speicherplatz und Bildschirmschoner beeinflussen die Erreichbarkeit im Netz nicht.",
  "Which causes can prevent a ping from reaching its target?",
  ("A firewall discards ICMP packets",
   "The target is switched off or still booting",
   "A route to the target network is missing",
   "The target IP was typed incorrectly",
   "The target has too little free disk space",
   "The target's screen saver is active"),
  "Filtered ICMP packets, a powered-off target, missing routing and typos are the most common reasons. Disk space and screen savers do not affect network reachability."),

M("ap1-net-r59",
  "Welche Aussagen zu Kabelkategorien sind zutreffend?",
  ("Höhere Kategorien erlauben höhere Frequenzen",
   "Cat 5e reicht für Gigabit-Ethernet aus",
   "Die Kategorie muss auch für Dosen und Stecker passen",
   "Die schwächste Komponente bestimmt die Gesamtklasse",
   "Die Kategorie legt die maximale Länge auf 300 m fest",
   "Eine höhere Kategorie erhöht die Anzahl der Adernpaare"),
  (0, 1, 2, 3),
  "Kategorien beschreiben die Übertragungsfrequenz, und die Kette ist nur so gut wie ihr schwächstes Glied - Dose und Stecker zählen mit. Die 100-m-Grenze bleibt bestehen, und vier Adernpaare hat Twisted Pair unabhängig von der Kategorie.",
  "Which statements about cable categories are correct?",
  ("Higher categories allow higher frequencies",
   "Cat 5e is sufficient for gigabit Ethernet",
   "The category must also match outlets and plugs",
   "The weakest component determines the overall class",
   "The category sets the maximum length to 300 m",
   "A higher category increases the number of wire pairs"),
  "Categories describe transmission frequency, and the chain is only as good as its weakest link - outlets and plugs count. The 100 m limit remains, and twisted pair has four wire pairs regardless of category."),

M("ap1-net-r60",
  "Welche Aussagen zur Portnummer in einer TCP-Verbindung sind korrekt?",
  ("Sie identifiziert den Dienst auf dem Zielsystem",
   "Sie ist 16 Bit groß",
   "Ports bis 1023 gelten als well known",
   "Der Client nutzt meist einen zufälligen hohen Port",
   "Sie ersetzt bei fehlender IP die Adressierung",
   "Sie wird vom DNS-Server fest vergeben"),
  (0, 1, 2, 3),
  "Der Port adressiert die Anwendung hinter der IP, ist 16 Bit groß und unterhalb 1024 fest vergeben; Clients nutzen kurzlebige hohe Ports. Ohne IP funktioniert gar nichts, und DNS vergibt keine Ports.",
  "Which statements about the port number in a TCP connection are correct?",
  ("It identifies the service on the target system",
   "It is 16 bits wide",
   "Ports up to 1023 are considered well known",
   "The client usually uses a random high port",
   "It replaces addressing when the IP is missing",
   "It is permanently assigned by the DNS server"),
  "The port addresses the application behind the IP, is 16 bits wide and fixed below 1024; clients use ephemeral high ports. Nothing works without an IP, and DNS does not assign ports."),

M("ap1-net-r61",
  "Ein Kunde will sein Heimnetz sicherer machen. Welche Empfehlungen sind fachlich sinnvoll?",
  ("Das Standardpasswort des Routers ändern",
   "Die Firmware des Routers aktuell halten",
   "Fernzugriff auf die Routeroberfläche abschalten",
   "Ein eigenes Gäste-WLAN einrichten",
   "Den DHCP-Server komplett abschalten",
   "Alle Geräte auf feste öffentliche IPs umstellen"),
  (0, 1, 2, 3),
  "Standardpasswort, Firmwarestand, offener Fernzugriff und fehlende Gästetrennung sind die klassischen Schwachstellen im Heimnetz. DHCP abzuschalten erzeugt nur Handarbeit, und öffentliche Adressen für alle Geräte wären das Gegenteil von sicher.",
  "A customer wants to make their home network safer. Which recommendations are professionally sound?",
  ("Change the router's default password",
   "Keep the router firmware up to date",
   "Switch off remote access to the router interface",
   "Set up a separate guest WLAN",
   "Disable the DHCP server entirely",
   "Move all devices to fixed public IP addresses"),
  "Default passwords, firmware level, exposed remote access and missing guest separation are the classic home network weaknesses. Disabling DHCP only creates manual work, and public addresses for every device would be the opposite of safe."),

M("ap1-net-r62",
  "Welche Aussagen zum OSI-Modell sind richtig?",
  ("Es besteht aus sieben Schichten",
   "Jede Schicht nutzt die Dienste der darunterliegenden",
   "Schicht 3 ist die Vermittlungsschicht",
   "Schicht 4 ist die Transportschicht",
   "Es besteht aus vier Schichten wie TCP/IP",
   "Die oberste Schicht ist die Bitübertragung"),
  (0, 1, 2, 3),
  "Sieben Schichten, jede baut auf der darunter auf; 3 ist Vermittlung, 4 Transport. Vier Schichten hat das TCP/IP-Modell, und die Bitübertragung ist die unterste Schicht, nicht die oberste.",
  "Which statements about the OSI model are correct?",
  ("It consists of seven layers",
   "Each layer uses the services of the one below",
   "Layer 3 is the network layer",
   "Layer 4 is the transport layer",
   "It consists of four layers like TCP/IP",
   "The topmost layer is the physical layer"),
  "Seven layers, each building on the one below; 3 is network, 4 is transport. Four layers belong to the TCP/IP model, and the physical layer is the bottom one, not the top."),

M("ap1-net-r63",
  "Welche Situationen sprechen für eine feste IP-Adresse statt DHCP?",
  ("Ein Server, den andere unter fester Adresse ansprechen",
   "Ein Router als Standardgateway im Netz",
   "Ein Drucker, der in Treibern fest hinterlegt ist",
   "Ein Switch mit Managementzugang",
   "Ein Notebook, das täglich den Standort wechselt",
   "Ein Gastgerät, das einmalig ins WLAN kommt"),
  (0, 1, 2, 3),
  "Infrastruktur und dauerhaft angesprochene Dienste brauchen Verlässlichkeit, deshalb feste Adressen oder Reservierungen. Mobile Geräte und Gäste profitieren dagegen gerade von der automatischen Vergabe.",
  "Which situations argue for a static IP address instead of DHCP?",
  ("A server that others address at a fixed address",
   "A router acting as default gateway",
   "A printer hard-coded into driver configurations",
   "A switch with a management interface",
   "A laptop that changes location every day",
   "A guest device joining the WLAN just once"),
  "Infrastructure and permanently addressed services need reliability, hence static addresses or reservations. Mobile devices and guests benefit precisely from automatic assignment."),

M("ap1-net-r64",
  "Welche Angaben liefert der Befehl ipconfig /all unter Windows?",
  ("Die IP-Adresse der Netzwerkkarte",
   "Die Subnetzmaske der Verbindung",
   "Das eingetragene Standardgateway",
   "Die physische Adresse der Karte",
   "Die freie Kapazität der Festplatte",
   "Die Liste der installierten Programme"),
  (0, 1, 2, 3),
  "ipconfig /all zeigt die vollständige Konfiguration je Adapter samt MAC, DHCP-Server und DNS. Festplattenbelegung und Softwarelisten liefern ganz andere Werkzeuge.",
  "Which information does the command ipconfig /all provide on Windows?",
  ("The IP address of the network adapter",
   "The subnet mask of the connection",
   "The configured default gateway",
   "The physical address of the adapter",
   "The free capacity of the hard disk",
   "The list of installed programs"),
  "ipconfig /all shows the complete per-adapter configuration including MAC, DHCP server and DNS. Disk usage and software inventories come from entirely different tools."),

# ------------------------------------------------------------------ text (36)
T("ap1-net-r65", "Wie viele nutzbare Hostadressen bietet ein /27-Netz?", "30",
  "Bei /27 bleiben 5 Hostbits, also 32 Adressen. Abzüglich Netz- und Broadcastadresse sind 30 nutzbar.",
  "How many usable host addresses does a /27 network provide?", "30",
  "A /27 leaves 5 host bits, i.e. 32 addresses. Minus network and broadcast address, 30 are usable."),

T("ap1-net-r66", "Welcher Präfixlänge entspricht die Maske 255.255.240.0?", "/20",
  "240 im dritten Oktett sind 11110000, also 4 gesetzte Bits. Zusammen mit den 16 Bits davor ergibt das /20.",
  "Which prefix length matches the mask 255.255.240.0?", "/20",
  "240 in the third octet is 11110000, i.e. 4 set bits. Together with the 16 bits before it, that makes /20."),

T("ap1-net-r67", "Auf welchem Port lauscht ein DNS-Server standardmäßig?", "53",
  "Port 53 wird sowohl per UDP für normale Anfragen als auch per TCP für Zonentransfers und große Antworten genutzt.",
  "On which port does a DNS server listen by default?", "53",
  "Port 53 is used both over UDP for regular queries and over TCP for zone transfers and large responses."),

T("ap1-net-r68", "Wie heißt der Adressbereich, den sich Windows ohne DHCP-Antwort selbst vergibt?", "APIPA",
  "APIPA steht für Automatic Private IP Addressing und nutzt 169.254.0.0/16. Kommunikation ist dann nur im lokalen Segment möglich.",
  "What is the address range Windows assigns itself when no DHCP replies called?", "APIPA",
  "APIPA stands for Automatic Private IP Addressing and uses 169.254.0.0/16. Communication is then only possible within the local segment."),

T("ap1-net-r69", "Wie viele Bit umfasst eine IPv4-Adresse?", "32",
  "32 Bit in vier Oktetten zu je 8 Bit. IPv6 nutzt dagegen 128 Bit.",
  "How many bits does an IPv4 address contain?", "32",
  "32 bits in four octets of 8 bits each. IPv6 by contrast uses 128 bits."),

T("ap1-net-r70", "Wie lautet die Netzadresse zu 10.0.5.130 mit der Maske 255.255.255.192?", "10.0.5.128",
  "Bei /26 liegen die Blockgrenzen bei 0, 64, 128 und 192. Die 130 fällt damit in den Block ab 128.",
  "What is the network address for 10.0.5.130 with mask 255.255.255.192?", "10.0.5.128",
  "With /26 the block boundaries are 0, 64, 128 and 192. So .130 falls into the block starting at 128."),

T("ap1-net-r71", "Welches Protokoll löst im lokalen Netz eine IPv4-Adresse zu einer MAC-Adresse auf?", "ARP",
  "Address Resolution Protocol fragt per Broadcast im Segment nach und speichert die Antwort im ARP-Cache.",
  "Which protocol resolves an IPv4 address to a MAC address in the local network?", "ARP",
  "Address Resolution Protocol broadcasts a query in the segment and stores the answer in the ARP cache."),

T("ap1-net-r72", "Wie viele Bit hat eine MAC-Adresse?", "48",
  "48 Bit, notiert als sechs Hexadezimalpaare. Die ersten 24 Bit bilden die Herstellerkennung OUI.",
  "How many bits does a MAC address have?", "48",
  "48 bits, written as six hexadecimal pairs. The first 24 bits form the manufacturer identifier OUI."),

T("ap1-net-r73", "Welcher Befehl zeigt unter Windows den Weg eines Pakets zum Ziel?", "tracert",
  "tracert erhöht schrittweise die TTL und macht so jeden Router auf der Strecke sichtbar. Unter Linux heißt das Werkzeug traceroute.",
  "Which command shows the path of a packet to its target on Windows?", "tracert",
  "tracert increases the TTL step by step and thereby reveals every router along the path. On Linux the tool is called traceroute."),

T("ap1-net-r74", "Wie viele nutzbare Hostadressen hat ein /30-Netz?", "2",
  "4 Adressen minus Netz und Broadcast ergeben genau 2 - deshalb ist /30 die übliche Wahl für Punkt-zu-Punkt-Verbindungen.",
  "How many usable host addresses does a /30 network have?", "2",
  "4 addresses minus network and broadcast leaves exactly 2 - which is why /30 is the usual choice for point-to-point links."),

T("ap1-net-r75", "Welcher Standardport gehört zum Dienst SSH?", "22",
  "SSH nutzt TCP 22 für verschlüsselte Fernwartung und löst damit das unverschlüsselte Telnet auf Port 23 ab.",
  "Which default port belongs to the SSH service?", "22",
  "SSH uses TCP 22 for encrypted remote administration, replacing unencrypted Telnet on port 23."),

T("ap1-net-r76", "Wie viele überschneidungsfreie Kanäle bietet das 2,4-GHz-Band in Europa?", "3",
  "Die Kanäle 1, 6 und 11 überlappen sich nicht. Deshalb wird das Band bei mehreren Access Points schnell eng.",
  "How many non-overlapping channels does the 2.4 GHz band offer in Europe?", "3",
  "Channels 1, 6 and 11 do not overlap. That is why the band gets crowded quickly with several access points."),

T("ap1-net-r77", "Welche Präfixlänge braucht ein Subnetz für mindestens 100 Hosts?", "/25",
  "6 Hostbits ergäben nur 62 nutzbare Adressen, 7 Hostbits dagegen 126 - das entspricht /25.",
  "Which prefix length does a subnet need for at least 100 hosts?", "/25",
  "6 host bits would give only 62 usable addresses, while 7 host bits give 126 - that corresponds to /25."),

T("ap1-net-r78", "Welche Adresse spricht in einem /24-Netz alle Hosts gleichzeitig an, wenn das Netz 192.168.7.0 ist?", "192.168.7.255",
  "Die letzte Adresse eines Subnetzes ist die Broadcast-Adresse und erreicht alle Geräte des Segments.",
  "Which address reaches all hosts at once in the /24 network 192.168.7.0?", "192.168.7.255",
  "The last address of a subnet is the broadcast address and reaches every device in the segment."),

T("ap1-net-r79", "Wofür steht die Abkürzung PoE in der Netzwerktechnik?", "Power over Ethernet",
  "PoE speist Geräte wie Access Points oder IP-Kameras über das Datenkabel und spart damit eine separate Stromleitung.",
  "What does the abbreviation PoE stand for in networking?", "Power over Ethernet",
  "PoE powers devices such as access points or IP cameras over the data cable, saving a separate power line."),

T("ap1-net-r80", "Welchen Dezimalwert hat das Oktett 11000000 einer Subnetzmaske?", "192",
  "128 plus 64 ergibt 192. Dieses Oktett kennzeichnet zwei zusätzliche Netzbits, typisch für /26.",
  "What decimal value does the subnet mask octet 11000000 have?", "192",
  "128 plus 64 equals 192. This octet marks two additional network bits, typical for /26."),

T("ap1-net-r81", "Welches Protokoll nutzt der Befehl ping?", "ICMP",
  "ping verschickt ICMP Echo Requests und wertet die Echo Replies aus. Eine Firewall kann diese Pakete gezielt verwerfen.",
  "Which protocol does the ping command use?", "ICMP",
  "ping sends ICMP echo requests and evaluates the echo replies. A firewall can deliberately discard these packets."),

T("ap1-net-r82", "In wie viele gleich große Subnetze zerfällt ein /24-Netz bei Präfixlänge /27?", "8",
  "Von /24 auf /27 sind es 3 zusätzliche Netzbits, und 2 hoch 3 ergibt 8 Subnetze zu je 30 nutzbaren Adressen.",
  "Into how many equal subnets does a /24 network split at prefix length /27?", "8",
  "From /24 to /27 there are 3 additional network bits, and 2 to the power of 3 gives 8 subnets with 30 usable addresses each."),

T("ap1-net-r83", "Welcher Port wird für unverschlüsseltes HTTP verwendet?", "80",
  "Port 80 ist der Standard für HTTP. Moderne Webserver leiten von dort meist direkt auf HTTPS an Port 443 weiter.",
  "Which port is used for unencrypted HTTP?", "80",
  "Port 80 is the standard for HTTP. Modern web servers usually redirect from there straight to HTTPS on port 443."),

T("ap1-net-r84", "Wie nennt man den Bereich eines Netzes, in dem ein Broadcast alle Geräte erreicht?", "Broadcast-Domäne",
  "Switches leiten Broadcasts weiter und vergrößern damit die Domäne, Router und VLAN-Grenzen begrenzen sie.",
  "What is the area of a network in which a broadcast reaches every device called?", "Broadcast domain",
  "Switches forward broadcasts and thereby enlarge the domain, while routers and VLAN boundaries limit it."),

T("ap1-net-r85", "Wie viele Adressen umfasst ein /29-Netz insgesamt?", "8",
  "3 Hostbits ergeben 2 hoch 3 gleich 8 Adressen, von denen 6 an Hosts vergeben werden können.",
  "How many addresses does a /29 network contain in total?", "8",
  "3 host bits give 2 to the power of 3, i.e. 8 addresses, of which 6 can be assigned to hosts."),

T("ap1-net-r86", "Welches Feld im IP-Header verhindert, dass Pakete endlos kreisen?", "TTL",
  "Time to Live wird an jedem Router um eins verringert; bei null wird das Paket verworfen. Genau das nutzt traceroute aus.",
  "Which field in the IP header prevents packets from circling forever?", "TTL",
  "Time to Live is decremented by one at every router; at zero the packet is discarded. traceroute exploits exactly this."),

T("ap1-net-r87", "Welcher Dienst verteilt in einem Netz automatisch IP-Adressen an Clients?", "DHCP",
  "Der DHCP-Server vergibt Adresse, Maske, Gateway und DNS auf Zeit und spart damit die Konfiguration von Hand.",
  "Which service automatically distributes IP addresses to clients in a network?", "DHCP",
  "The DHCP server hands out address, mask, gateway and DNS on a lease and thereby saves manual configuration."),

T("ap1-net-r88", "Wie lautet die letzte nutzbare Hostadresse im Netz 192.168.1.0/24?", "192.168.1.254",
  "192.168.1.255 ist der Broadcast und damit nicht vergebbar, also endet der nutzbare Bereich bei .254.",
  "What is the last usable host address in the network 192.168.1.0/24?", "192.168.1.254",
  "192.168.1.255 is the broadcast and therefore not assignable, so the usable range ends at .254."),

T("ap1-net-r89", "Welche maximale Länge darf ein Twisted-Pair-Segment nach Norm haben, in Metern?", "100",
  "90 m Verlegekabel plus 10 m Rangierkabel. Daraus ergibt sich die Faustregel von 100 m Gesamtstrecke.",
  "What is the maximum standard length of a twisted-pair segment, in metres?", "100",
  "90 m of installation cable plus 10 m of patch cable. That yields the rule of thumb of a 100 m total run."),

T("ap1-net-r90", "Wie heißt das Verfahren, mit dem ein Router viele private Adressen hinter einer öffentlichen verbirgt?", "NAT",
  "Network Address Translation tauscht die Quelladresse aus; über Portnummern findet die Antwort zurück zum richtigen Host.",
  "What is the method by which a router hides many private addresses behind one public address called?", "NAT",
  "Network Address Translation swaps the source address; port numbers let the reply find its way back to the right host."),

T("ap1-net-r91", "Auf welcher OSI-Schicht arbeitet ein Repeater?", "1",
  "Der Repeater verstärkt nur das Signal, ohne Adressen auszuwerten - das ist reine Bitübertragung.",
  "On which OSI layer does a repeater operate?", "1",
  "A repeater only amplifies the signal without evaluating addresses - that is pure bit transmission."),

T("ap1-net-r92", "Welcher Standardport gehört zum Fernwartungsdienst RDP?", "3389",
  "RDP nutzt TCP 3389. Der Port sollte nie ungeschützt aus dem Internet erreichbar sein, sondern nur über VPN.",
  "Which default port belongs to the remote desktop service RDP?", "3389",
  "RDP uses TCP 3389. The port should never be reachable unprotected from the internet, only through a VPN."),

T("ap1-net-r93", "Wie viele Blöcke hat eine IPv6-Adresse in ausgeschriebener Form?", "8",
  "8 Blöcke zu je 16 Bit ergeben zusammen die 128 Bit einer IPv6-Adresse.",
  "How many blocks does an IPv6 address have when written out in full?", "8",
  "8 blocks of 16 bits each add up to the 128 bits of an IPv6 address."),

T("ap1-net-r94", "Welches Zeichen ersetzt in IPv6 eine zusammenhängende Folge von Nullblöcken?", "::",
  "Der doppelte Doppelpunkt darf in einer Adresse nur ein einziges Mal vorkommen, sonst wäre die Länge nicht mehr eindeutig.",
  "Which notation replaces a contiguous run of zero blocks in IPv6?", "::",
  "The double colon may appear only once in an address, otherwise the length would no longer be unambiguous."),

T("ap1-net-r95", "Wie viele Adernpaare enthält ein übliches Twisted-Pair-Netzwerkkabel?", "4",
  "Vier verdrillte Paare, also acht Adern. Gigabit-Ethernet nutzt alle vier Paare gleichzeitig.",
  "How many wire pairs does a standard twisted-pair network cable contain?", "4",
  "Four twisted pairs, i.e. eight wires. Gigabit Ethernet uses all four pairs simultaneously."),

T("ap1-net-r96", "Welcher DNS-Eintragstyp verweist auf den zuständigen Mailserver einer Domain?", "MX",
  "Der MX-Record nennt Namen und Priorität des Mailservers; mehrere Einträge dienen der Ausfallsicherheit.",
  "Which DNS record type points to the mail server responsible for a domain?", "MX",
  "The MX record names the mail server and its priority; several entries provide failover."),

T("ap1-net-r97", "Wie viele Subnetze entstehen, wenn ein /16-Netz auf /18 aufgeteilt wird?", "4",
  "2 zusätzliche Netzbits ergeben 2 hoch 2 gleich 4 gleich große Subnetze.",
  "How many subnets result from splitting a /16 network into /18?", "4",
  "2 additional network bits give 2 to the power of 2, i.e. 4 equally sized subnets."),

T("ap1-net-r98", "Welches Protokoll überträgt E-Mails vom Client zum Mailserver?", "SMTP",
  "SMTP versendet Nachrichten, während POP3 und IMAP zum Abholen aus dem Postfach dienen.",
  "Which protocol transports emails from the client to the mail server?", "SMTP",
  "SMTP sends messages, while POP3 and IMAP are used to retrieve them from the mailbox."),

T("ap1-net-r99", "Wie nennt man die Schwankung der Paketlaufzeit, die bei VoIP stört?", "Jitter",
  "Gleichmäßige Laufzeiten sind bei Sprache wichtiger als niedrige Werte; ein Jitterbuffer glättet die Schwankung.",
  "What is the variation in packet transit time that disturbs VoIP called?", "Jitter",
  "Even transit times matter more than low ones for voice; a jitter buffer smooths the variation."),

T("ap1-net-r100", "Welche Präfixlänge hat eine Punkt-zu-Punkt-Verbindung üblicherweise, wenn nur zwei Adressen gebraucht werden?", "/30",
  "Ein /30 stellt genau zwei nutzbare Adressen bereit und verschwendet damit den geringsten Adressraum.",
  "Which prefix length does a point-to-point link usually use when only two addresses are needed?", "/30",
  "A /30 provides exactly two usable addresses and therefore wastes the least address space."),
]

build("ap1-netzwerktechnik.json", "Netzwerktechnik", "Network Technology", Q)
