#!/usr/bin/env python3
"""AP1 Hardware & Arbeitsplatz - 100 handgeschriebene Fragen."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from qlib import S, M, T, build

Q = [
# ---------------------------------------------------------------- single (32)
S("ap1-hw-r01",
  "Ein Rechner startet nicht, die Lüfter laufen kurz an und stoppen wieder. Was prüfst du zuerst?",
  ("Die Stromversorgung und den Sitz der Netzteilstecker",
   "Die Treiberversion der eingebauten Grafikkarte",
   "Die Startreihenfolge der Laufwerke im UEFI",
   "Die Freigaben des Benutzerkontos im Netzwerk"), 0,
  "Ein Anlaufen und sofortiges Abschalten deutet auf zu wenig oder gestörte Spannung hin. Treiber, Bootreihenfolge und Benutzerrechte greifen erst, wenn das System überhaupt startet.",
  "A PC does not start, the fans spin up briefly and stop again. What do you check first?",
  ("The power supply and the seating of its connectors",
   "The driver version of the installed graphics card",
   "The boot order of the drives in the UEFI",
   "The network shares of the user account"),
  "Spinning up and immediately shutting down suggests insufficient or faulty voltage. Drivers, boot order and user rights only matter once the system starts at all."),

S("ap1-hw-r02",
  "Ein Sachbearbeiter klagt über lange Ladezeiten beim Öffnen großer Dateien. Der Rechner hat eine HDD. Was hilft am meisten?",
  ("Der Austausch der Festplatte gegen eine SSD",
   "Der Einbau eines zweiten Bildschirms am Platz",
   "Der Tausch der Maus gegen ein kabelloses Modell",
   "Die Erhöhung der Bildwiederholrate des Monitors"), 0,
  "Bei Ladezeiten ist fast immer der Datenträger der Engpass: eine SSD hat keine mechanische Zugriffszeit und liefert ein Vielfaches an Leseoperationen. Ein- und Ausgabegeräte ändern daran nichts.",
  "An office worker complains about long load times when opening large files. The PC has an HDD. What helps most?",
  ("Replacing the hard disk with an SSD",
   "Adding a second monitor at the workplace",
   "Swapping the mouse for a wireless model",
   "Raising the refresh rate of the monitor"),
  "For load times the storage device is almost always the bottleneck: an SSD has no mechanical seek time and delivers many times the read operations. Input and output devices change nothing."),

S("ap1-hw-r03",
  "Wie viele Byte sind ein Kibibyte nach IEC-Norm?",
  ("1024", "1000", "512", "2048"), 0,
  "Das Kibibyte umfasst 2 hoch 10, also 1024 Byte. Das Kilobyte nach SI steht dagegen für genau 1000 Byte - Festplattenhersteller rechnen deshalb anders als Betriebssysteme.",
  "How many bytes are one kibibyte according to the IEC standard?",
  ("1024", "1000", "512", "2048"),
  "A kibibyte is 2 to the power of 10, i.e. 1024 bytes. The SI kilobyte by contrast means exactly 1000 bytes - which is why disk vendors count differently from operating systems."),

S("ap1-hw-r04",
  "Ein Arbeitsplatz soll zwei Monitore per DisplayPort bekommen, die Grafikkarte hat nur einen Anschluss. Was löst das?",
  ("Eine Grafikkarte mit mehreren Bildausgängen einbauen",
   "Einen einfachen Y-Splitter auf das Signal setzen",
   "Den Arbeitsspeicher des Rechners verdoppeln",
   "Einen schnelleren Prozessor in den Sockel setzen"), 0,
  "Ein passiver Splitter spiegelt nur dasselbe Bild und schafft keinen zweiten unabhängigen Ausgang. Speicher und Prozessor haben mit der Anzahl der Bildausgänge nichts zu tun.",
  "A workstation needs two monitors via DisplayPort but the graphics card has only one connector. What solves this?",
  ("Install a graphics card with several video outputs",
   "Put a simple Y splitter on the signal",
   "Double the amount of RAM in the machine",
   "Fit a faster processor into the socket"),
  "A passive splitter only mirrors the same picture and creates no second independent output. Memory and processor have nothing to do with the number of video outputs."),

S("ap1-hw-r05",
  "Wofür steht die Angabe 3200 bei einem DDR4-Speichermodul?",
  ("Die Übertragungsrate in Megatransfers pro Sekunde",
   "Die Kapazität des Moduls in Megabyte",
   "Die Anzahl der elektrischen Kontakte am Modulstecker",
   "Die Betriebsspannung in Millivolt"), 0,
  "Die Zahl beschreibt die effektive Datenrate in MT/s. Die Kapazität steht getrennt in Gigabyte, und die Spannung liegt bei DDR4 üblicherweise bei 1,2 Volt.",
  "What does the figure 3200 on a DDR4 memory module refer to?",
  ("The transfer rate in megatransfers per second",
   "The capacity of the module in megabytes",
   "The number of electrical contacts on the module edge",
   "The operating voltage in millivolts"),
  "The number describes the effective data rate in MT/s. Capacity is stated separately in gigabytes, and DDR4 voltage is usually 1.2 volts."),

S("ap1-hw-r06",
  "Ein Nutzer sitzt täglich acht Stunden am Bildschirm und klagt über Nackenschmerzen. Was ist zuerst zu prüfen?",
  ("Die Höhe des Monitors und der Blickwinkel darauf",
   "Die Farbtemperatur des eingestellten Bildprofils",
   "Die Abtastrate der angeschlossenen Maus",
   "Die Kapazität der eingebauten Festplatte"), 0,
  "Nach der Bildschirmarbeitsverordnung soll die oberste Zeile leicht unterhalb der Augenhöhe liegen, damit der Blick leicht gesenkt ist. Farbprofil, Maus und Festplatte haben keinen Einfluss auf die Haltung.",
  "A user sits at a screen eight hours a day and complains of neck pain. What is checked first?",
  ("The monitor height and the viewing angle onto it",
   "The colour temperature of the display profile",
   "The polling rate of the connected mouse",
   "The capacity of the built-in hard disk"),
  "Workplace regulations say the top line should sit slightly below eye level so the gaze is angled gently downward. Colour profile, mouse and disk have no influence on posture."),

S("ap1-hw-r07",
  "Welcher Anschluss überträgt Bild und Ton digital und ist an Fernsehern am weitesten verbreitet?",
  ("HDMI", "VGA", "DVI-D", "RS-232"), 0,
  "HDMI führt Bild und Ton in einem Kabel. VGA überträgt analog und ohne Ton, DVI-D digital aber ohne Ton, und RS-232 ist eine serielle Datenschnittstelle.",
  "Which connector carries picture and sound digitally and is most widespread on televisions?",
  ("HDMI", "VGA", "DVI-D", "RS-232"),
  "HDMI carries picture and sound in one cable. VGA transmits analogue and without audio, DVI-D digitally but without audio, and RS-232 is a serial data interface."),

S("ap1-hw-r08",
  "Ein neuer PC soll 350 Watt Dauerlast ziehen. Welches Netzteil wählst du sinnvoll?",
  ("Ein 550-Watt-Netzteil mit Reserve für Lastspitzen",
   "Ein 350-Watt-Netzteil exakt passend zur Last",
   "Ein 1200-Watt-Netzteil für maximale Sicherheit",
   "Ein 250-Watt-Netzteil, da selten Volllast anliegt"), 0,
  "Netzteile arbeiten im mittleren Lastbereich am effizientesten, und Lastspitzen brauchen Luft nach oben. Ein exakt passendes Netzteil läuft dauerhaft am Limit, ein deutlich überdimensioniertes verschenkt Wirkungsgrad und Geld.",
  "A new PC will draw 350 watts of continuous load. Which power supply do you sensibly choose?",
  ("A 550 watt unit with headroom for load peaks",
   "A 350 watt unit matching the load exactly",
   "A 1200 watt unit for maximum safety margin",
   "A 250 watt unit, since full load is rare"),
  "Power supplies are most efficient in the middle of their range, and load peaks need headroom. An exactly matched unit runs permanently at its limit, a heavily oversized one wastes efficiency and money."),

S("ap1-hw-r09",
  "Was beschreibt die Angabe IOPS bei einem Datenträger?",
  ("Die Anzahl der Ein- und Ausgabeoperationen pro Sekunde",
   "Die Kapazität des Datenträgers in Gigabyte",
   "Die Umdrehungsgeschwindigkeit der Magnetscheiben",
   "Die garantierte Anzahl der Schreibzyklen bis zum Ausfall"), 0,
  "IOPS zählt die Zugriffe pro Sekunde und ist bei vielen kleinen Anfragen aussagekräftiger als die reine Übertragungsrate. Genau hier liegt der große Vorsprung der SSD gegenüber der Festplatte.",
  "What does the figure IOPS describe for a storage device?",
  ("The number of input and output operations per second",
   "The capacity of the storage device in gigabytes",
   "The rotational speed of the magnetic platters",
   "The guaranteed number of write cycles until failure"),
  "IOPS counts accesses per second and is more meaningful than raw transfer rate when there are many small requests. This is exactly where an SSD hugely outperforms a hard disk."),

S("ap1-hw-r10",
  "Beim Zusammenbau eines PCs greifst du zur Hauptplatine. Welche Vorkehrung ist Pflicht?",
  ("Erdung gegen elektrostatische Entladung sicherstellen",
   "Das Gehäuse vorher gründlich mit Wasser reinigen",
   "Die Hauptplatine vor dem Einbau kurz erwärmen",
   "Alle Kabel mit Klebeband dauerhaft fixieren"), 0,
  "Schon eine für den Menschen unmerkliche Entladung kann Halbleiter schädigen, oft mit Spätausfällen. Antistatikband und Ablage auf leitfähiger Unterlage sind deshalb Standard.",
  "While assembling a PC you reach for the mainboard. Which precaution is mandatory?",
  ("Ensure earthing against electrostatic discharge",
   "Clean the case thoroughly with water beforehand",
   "Warm the mainboard up briefly before installing",
   "Fix all cables permanently with adhesive tape"),
  "Even a discharge imperceptible to a human can damage semiconductors, often causing later failures. An antistatic strap and a conductive work surface are therefore standard."),

S("ap1-hw-r11",
  "In der Buchhaltung fällt viel bedrucktes Papier an, die Auflagen sind hoch. Welcher Drucker passt?",
  ("Ein Laserdrucker wegen niedriger Seitenkosten",
   "Ein Tintenstrahldrucker wegen der Fotoqualität",
   "Ein Nadeldrucker wegen der leisen Arbeitsweise",
   "Ein Thermodrucker wegen der langen Haltbarkeit"), 0,
  "Bei hohen Auflagen entscheidet der Preis pro Seite, und dort liegt der Laserdrucker vorn. Nadeldrucker sind laut, Thermopapier verblasst, und Fotoqualität ist in der Buchhaltung nebensächlich.",
  "Accounting produces a lot of printed paper with high print runs. Which printer fits?",
  ("A laser printer because of low cost per page",
   "An inkjet printer because of photo quality",
   "A dot matrix printer because it works quietly",
   "A thermal printer because of long durability"),
  "With high print runs the cost per page decides, and the laser printer leads there. Dot matrix printers are loud, thermal paper fades, and photo quality is beside the point in accounting."),

S("ap1-hw-r12",
  "Welche Aufgabe hat der Chipsatz auf einer Hauptplatine?",
  ("Er verbindet den Prozessor mit Speicher und Schnittstellen",
   "Er speichert die Daten des Betriebssystems dauerhaft",
   "Er erzeugt die Betriebsspannungen aus dem Stromnetz",
   "Er kühlt den Prozessor durch aktive Belüftung"), 0,
  "Der Chipsatz steuert die Datenwege zwischen CPU, Arbeitsspeicher, PCIe-Steckplätzen und den übrigen Anschlüssen. Er legt damit fest, welche Komponenten die Platine überhaupt aufnehmen kann.",
  "What is the task of the chipset on a mainboard?",
  ("It links the processor to memory and interfaces",
   "It stores the operating system data permanently",
   "It generates operating voltages from mains power",
   "It cools the processor through active ventilation"),
  "The chipset controls the data paths between CPU, memory, PCIe slots and the remaining connectors. It thereby determines which components the board can accept at all."),

S("ap1-hw-r13",
  "Ein Rechner erkennt nach dem Einbau eines zweiten Riegels nur die Hälfte des Arbeitsspeichers. Was liegt nahe?",
  ("Der Riegel sitzt nicht richtig oder ist defekt",
   "Der Monitor ist für die Kapazität zu klein",
   "Die Festplatte hat zu wenig freien Speicherplatz",
   "Das Netzwerkkabel ist an der falschen Dose"), 0,
  "Wird nur ein Teil erkannt, sitzt das Modul meist nicht sauber im Steckplatz oder ist fehlerhaft. Ein Test einzeln und in verschiedenen Bänken grenzt die Ursache schnell ein.",
  "After adding a second memory module, a PC recognises only half the RAM. What is the likely cause?",
  ("The module is not seated properly or is faulty",
   "The monitor is too small for that capacity",
   "The hard disk has too little free space left",
   "The network cable is in the wrong wall outlet"),
  "If only part is detected, the module usually is not seated cleanly in the slot or is defective. Testing it alone and in different banks narrows the cause down quickly."),

S("ap1-hw-r14",
  "Welche Auflösung verbirgt sich hinter der Bezeichnung Full HD?",
  ("1920 x 1080 Bildpunkte", "1280 x 720 Bildpunkte",
   "2560 x 1440 Bildpunkte", "3840 x 2160 Bildpunkte"), 0,
  "Full HD steht für 1920 x 1080. Darunter liegt HD ready mit 1280 x 720, darüber WQHD mit 2560 x 1440 und UHD mit 3840 x 2160.",
  "Which resolution is behind the label Full HD?",
  ("1920 x 1080 pixels", "1280 x 720 pixels",
   "2560 x 1440 pixels", "3840 x 2160 pixels"),
  "Full HD means 1920 x 1080. Below it sits HD ready at 1280 x 720, above it WQHD at 2560 x 1440 and UHD at 3840 x 2160."),

S("ap1-hw-r15",
  "Ein Notebook soll im Außendienst genutzt werden und braucht lange Laufzeit. Welche Komponente ist entscheidend?",
  ("Ein sparsamer Prozessor mit niedriger Verlustleistung",
   "Eine besonders hohe Bildwiederholrate des Displays",
   "Ein möglichst großer und schneller Arbeitsspeicher",
   "Eine dedizierte Grafikkarte mit eigenem Speicher"), 0,
  "Die Verlustleistung des Prozessors bestimmt maßgeblich den Verbrauch. Hohe Bildwiederholraten und dedizierte Grafik ziehen zusätzlich Strom und verkürzen die Laufzeit eher.",
  "A laptop is for field work and needs long battery life. Which component is decisive?",
  ("An economical processor with low power draw",
   "A particularly high display refresh rate",
   "The largest and fastest RAM available",
   "A dedicated graphics card with its own memory"),
  "The processor's power draw largely determines consumption. High refresh rates and dedicated graphics draw extra power and tend to shorten runtime."),

S("ap1-hw-r16",
  "Was unterscheidet UEFI vom klassischen BIOS?",
  ("UEFI unterstützt große Datenträger und startet schneller",
   "UEFI ersetzt den Arbeitsspeicher beim Systemstart",
   "UEFI übernimmt die Aufgaben des Netzteils mit",
   "UEFI speichert die Nutzerdaten des Betriebssystems"), 0,
  "UEFI kann mit GPT-Partitionierung über 2 TB umgehen, bietet eine grafische Oberfläche und mit Secure Boot eine Startprüfung. Speicher, Strom und Nutzerdaten liegen außerhalb seiner Zuständigkeit.",
  "What distinguishes UEFI from the classic BIOS?",
  ("UEFI supports large drives and boots faster",
   "UEFI replaces the main memory during startup",
   "UEFI also takes over the power supply's job",
   "UEFI stores the operating system's user data"),
  "UEFI handles GPT partitioning beyond 2 TB, offers a graphical interface and adds boot verification through Secure Boot. Memory, power and user data lie outside its remit."),

S("ap1-hw-r17",
  "Welcher Formfaktor beschreibt die kleinste der gängigen Hauptplatinengrößen?",
  ("Mini-ITX", "Micro-ATX", "ATX", "E-ATX"), 0,
  "Mini-ITX misst 17 x 17 cm, Micro-ATX 24,4 x 24,4 cm und ATX 30,5 x 24,4 cm. E-ATX ist noch breiter und für Serverboards üblich.",
  "Which form factor describes the smallest of the common mainboard sizes?",
  ("Mini-ITX", "Micro-ATX", "ATX", "E-ATX"),
  "Mini-ITX measures 17 x 17 cm, Micro-ATX 24.4 x 24.4 cm and ATX 30.5 x 24.4 cm. E-ATX is wider still and common on server boards."),

S("ap1-hw-r18",
  "Ein Rechner piept beim Start mehrfach und zeigt kein Bild. Was bedeutet das?",
  ("Ein Signalcode meldet einen Fehler beim Selbsttest",
   "Der Lüfter meldet eine zu niedrige Drehzahl",
   "Das Betriebssystem meldet fehlende Updates",
   "Der Monitor meldet ein zu schwaches Signal"), 0,
  "Beim POST prüft die Firmware die Grundkomponenten und meldet Fehler über Signaltöne, wenn noch kein Bild möglich ist. Die Bedeutung der Codes steht im Handbuch der Hauptplatine.",
  "A PC beeps several times at startup and shows no picture. What does that mean?",
  ("A signal code reports an error in the self test",
   "The fan reports a rotation speed that is too low",
   "The operating system reports missing updates",
   "The monitor reports a signal that is too weak"),
  "During POST the firmware checks the basic components and reports errors through beeps when no picture is possible yet. The meaning of the codes is in the mainboard manual."),

S("ap1-hw-r19",
  "Welche Schnittstelle bindet eine besonders schnelle SSD direkt an die PCIe-Lanes an?",
  ("NVMe über M.2", "SATA über M.2", "USB 3.0", "eSATA"), 0,
  "NVMe nutzt die PCIe-Anbindung und erreicht ein Vielfaches der SATA-Rate von rund 600 MB/s. Auch M.2 gibt es in einer langsameren SATA-Variante, deshalb lohnt der genaue Blick ins Datenblatt.",
  "Which interface attaches a particularly fast SSD directly to the PCIe lanes?",
  ("NVMe over M.2", "SATA over M.2", "USB 3.0", "eSATA"),
  "NVMe uses the PCIe attachment and reaches many times the SATA rate of about 600 MB/s. M.2 also exists in a slower SATA variant, so it pays to read the data sheet closely."),

S("ap1-hw-r20",
  "Eine Abteilung braucht 20 identische Arbeitsplätze mit zentraler Verwaltung. Welche Lösung passt?",
  ("Thin Clients mit Anwendungen auf einem Terminalserver",
   "Einzelne Hochleistungsrechner mit lokaler Software",
   "Notebooks mit jeweils eigener Softwareinstallation",
   "Tablets mit eigenständiger Verwaltung durch die Nutzer"), 0,
  "Thin Clients verlagern Rechenleistung und Software auf den Server, wodurch Updates und Sicherung zentral erfolgen. Einzelinstallationen vervielfachen dagegen den Pflegeaufwand.",
  "A department needs 20 identical workstations with central administration. Which solution fits?",
  ("Thin clients with applications on a terminal server",
   "Individual high-performance PCs with local software",
   "Laptops each with their own software installation",
   "Tablets administered independently by the users"),
  "Thin clients move computing power and software onto the server so that updates and backup happen centrally. Individual installations multiply the maintenance effort instead."),

S("ap1-hw-r21",
  "Was gibt die Angabe 80 Plus Gold bei einem Netzteil an?",
  ("Einen nachgewiesenen Wirkungsgrad über den Lastbereich",
   "Die maximale Leistungsabgabe in Watt",
   "Die Anzahl der verfügbaren Anschlusskabel",
   "Die Länge der gesetzlichen Herstellergarantie in Jahren"), 0,
  "Die Zertifizierung belegt, wie viel der aufgenommenen Leistung tatsächlich an die Komponenten geht. Ein höherer Wirkungsgrad senkt Stromkosten und Abwärme spürbar.",
  "What does the label 80 Plus Gold on a power supply indicate?",
  ("A verified efficiency across the load range",
   "The maximum power output in watts",
   "The number of available connection cables",
   "The length of the statutory manufacturer warranty"),
  "The certification proves how much of the drawn power actually reaches the components. Higher efficiency noticeably reduces electricity costs and waste heat."),

S("ap1-hw-r22",
  "Welche Aussage über Dual-Channel-Betrieb beim Arbeitsspeicher trifft zu?",
  ("Zwei gleiche Module verdoppeln die Speicherbandbreite",
   "Zwei Module verdoppeln die Taktfrequenz des Prozessors",
   "Zwei Module halbieren den Stromverbrauch des Systems",
   "Zwei Module verdoppeln die Kapazität jedes Moduls"), 0,
  "Der Speichercontroller spricht zwei Kanäle parallel an, was die Bandbreite erhöht. Voraussetzung sind passende Module in den richtigen, meist farblich markierten Bänken.",
  "Which statement about dual channel memory operation is correct?",
  ("Two identical modules double the memory bandwidth",
   "Two modules double the processor clock frequency",
   "Two modules halve the system's power consumption",
   "Two modules double the capacity of each module"),
  "The memory controller addresses two channels in parallel, raising bandwidth. This requires matching modules in the correct, usually colour-coded, banks."),

S("ap1-hw-r23",
  "Ein Monitor zeigt ein unscharfes Bild, obwohl das Kabel steckt. Was prüfst du zuerst?",
  ("Ob die eingestellte Auflösung der nativen entspricht",
   "Ob genug freier Speicherplatz auf der Platte ist",
   "Ob der Drucker im Netzwerk erreichbar ist",
   "Ob die Netzwerkkarte im Gerätemanager aktiviert wurde"), 0,
  "Flachbildschirme haben eine feste Pixelmatrix; jede abweichende Auflösung muss interpoliert werden und wirkt unscharf. Speicherplatz, Drucker und Netzwerkkarte sind hier ohne Belang.",
  "A monitor shows a blurry picture although the cable is connected. What do you check first?",
  ("Whether the set resolution matches the native one",
   "Whether there is enough free space on the disk",
   "Whether the printer is reachable on the network",
   "Whether the network adapter is enabled in device manager"),
  "Flat panels have a fixed pixel matrix; any deviating resolution has to be interpolated and looks blurry. Disk space, printer and network adapter are irrelevant here."),

S("ap1-hw-r24",
  "Welche Aufgabe erfüllt die Wärmeleitpaste zwischen Prozessor und Kühler?",
  ("Sie füllt Luftspalte und verbessert den Wärmeübergang",
   "Sie klebt den Kühler dauerhaft auf dem Prozessor fest",
   "Sie isoliert den Prozessor elektrisch vom Kühlkörper",
   "Sie senkt die Leistungsaufnahme des Prozessors"), 0,
  "Beide Oberflächen sind mikroskopisch rau; die eingeschlossene Luft leitet Wärme schlecht. Die Paste verdrängt sie - deshalb schadet zu viel Paste ebenso wie zu wenig.",
  "What is the purpose of thermal paste between processor and cooler?",
  ("It fills air gaps and improves heat transfer",
   "It glues the cooler permanently onto the processor",
   "It insulates the processor electrically from the sink",
   "It lowers the power consumption of the processor"),
  "Both surfaces are microscopically rough and the trapped air conducts heat poorly. The paste displaces it - which is why too much paste is as harmful as too little."),

S("ap1-hw-r25",
  "Ein Arbeitsplatz benötigt drei USB-Geräte, der Rechner hat nur zwei freie Buchsen. Was ist die einfachste Lösung?",
  ("Ein USB-Hub mit eigener Stromversorgung",
   "Der Einbau einer zweiten Grafikkarte",
   "Der Austausch des Netzteils gegen ein stärkeres",
   "Die Umstellung des Monitors auf DisplayPort"), 0,
  "Ein aktiver Hub vervielfacht die Anschlüsse und liefert genug Strom auch für stromhungrige Geräte. Grafikkarte, Netzteil und Bildanschluss lösen das Problem nicht.",
  "A workstation needs three USB devices but the PC has only two free sockets. What is the simplest solution?",
  ("A USB hub with its own power supply",
   "Installing a second graphics card",
   "Swapping the PSU for a stronger one",
   "Switching the monitor to DisplayPort"),
  "An active hub multiplies the ports and supplies enough current even for power-hungry devices. Graphics card, PSU and video connector do not solve the problem."),

S("ap1-hw-r26",
  "Welche Kenngröße eines Prozessors beschreibt, wie viele Aufgaben er echt parallel bearbeiten kann?",
  ("Die Anzahl der Kerne", "Die Taktfrequenz in Gigahertz",
   "Die Größe des Level-3-Caches", "Die Strukturbreite in Nanometern"), 0,
  "Jeder Kern arbeitet einen eigenen Befehlsstrom ab. Takt beschreibt das Tempo pro Kern, Cache die Zwischenspeichergröße und die Strukturbreite den Fertigungsprozess.",
  "Which processor characteristic describes how many tasks it can truly handle in parallel?",
  ("The number of cores", "The clock frequency in gigahertz",
   "The size of the level 3 cache", "The process node in nanometres"),
  "Each core works through its own instruction stream. Clock describes speed per core, cache the buffer size and the process node the manufacturing technology."),

S("ap1-hw-r27",
  "Eine SSD arbeitet nach Monaten spürbar langsamer beim Schreiben. Was ist die übliche Erklärung?",
  ("Belegte Blöcke müssen vor dem Schreiben gelöscht werden",
   "Die Magnetscheiben nutzen sich mechanisch ab",
   "Der Lesekopf muss längere Wege zurücklegen",
   "Die Rotationsgeschwindigkeit nimmt mit der Zeit ab"), 0,
  "Flash lässt sich nur blockweise löschen, deshalb wird eine belegte Zelle vor dem Neubeschreiben freigeräumt. TRIM meldet dem Laufwerk, welche Blöcke frei sind, und mildert den Effekt.",
  "An SSD writes noticeably slower after some months. What is the usual explanation?",
  ("Occupied blocks must be erased before writing",
   "The magnetic platters wear out mechanically",
   "The read head has to travel longer distances",
   "The rotation speed decreases over time"),
  "Flash can only be erased in blocks, so an occupied cell is cleared before being rewritten. TRIM tells the drive which blocks are free and mitigates the effect."),

S("ap1-hw-r28",
  "Nach welcher Regel richtet sich die empfohlene Sitzhöhe am Bildschirmarbeitsplatz?",
  ("Ober- und Unterarm bilden etwa einen rechten Winkel",
   "Die Füße hängen frei ohne Bodenkontakt",
   "Der Bildschirm steht deutlich über Augenhöhe",
   "Die Tastatur liegt auf Schulterhöhe des Nutzers"), 0,
  "Rechte Winkel in Ellenbogen und Knie entlasten Schultern und Rücken, die Füße stehen dabei flach auf. Ein Bildschirm über Augenhöhe erzwingt genau die Nackenhaltung, die Beschwerden macht.",
  "Which rule governs the recommended seat height at a screen workstation?",
  ("Upper and lower arm form roughly a right angle",
   "The feet hang freely without touching the floor",
   "The screen stands clearly above eye level",
   "The keyboard rests at the user's shoulder height"),
  "Right angles at elbow and knee relieve shoulders and back, with the feet flat on the floor. A screen above eye level forces exactly the neck posture that causes complaints."),

S("ap1-hw-r29",
  "Ein Rechner verliert bei jedem Ausschalten Datum und Uhrzeit. Was ist die Ursache?",
  ("Die Pufferbatterie auf der Hauptplatine ist leer",
   "Die Festplatte hat fehlerhafte Sektoren",
   "Der Arbeitsspeicher ist zu klein bemessen",
   "Der Netzwerktreiber ist nicht installiert"), 0,
  "Eine Knopfzelle versorgt die Echtzeituhr und die Firmware-Einstellungen im stromlosen Zustand. Ist sie leer, fällt das System bei jedem Start auf Grundwerte zurück.",
  "A PC loses date and time every time it is switched off. What is the cause?",
  ("The backup battery on the mainboard is empty",
   "The hard disk has defective sectors",
   "The main memory is dimensioned too small",
   "The network driver has not been installed"),
  "A coin cell powers the real-time clock and firmware settings while the machine is unpowered. When it is empty the system falls back to defaults on every start."),

S("ap1-hw-r30",
  "Welche Kennzahl beschreibt die Gesamtkosten eines Geräts über seine Nutzungsdauer?",
  ("Total Cost of Ownership", "Return on Investment",
   "Break-even-Point", "Deckungsbeitrag"), 0,
  "Die TCO addiert Anschaffung, Verbrauchsmaterial, Energie, Wartung und Entsorgung. Gerade bei Druckern liegt der Anschaffungspreis oft weit unter den Folgekosten.",
  "Which figure describes the total cost of a device across its service life?",
  ("Total cost of ownership", "Return on investment",
   "Break-even point", "Contribution margin"),
  "TCO adds purchase, consumables, energy, maintenance and disposal. With printers especially, the purchase price is often far below the follow-on costs."),

S("ap1-hw-r31",
  "Welcher Datenträger eignet sich am besten für die dauerhafte Archivierung ohne Stromzufuhr?",
  ("Ein Bandmedium in klimatisierter Lagerung",
   "Eine SSD im ausgebauten Zustand im Schrank",
   "Ein USB-Stick in der Schreibtischschublade",
   "Eine Speicherkarte im Kartenleser des PCs"), 0,
  "Bänder halten Jahrzehnte und sind auf Langzeitlagerung ausgelegt. Flash-Speicher verliert seine Ladung über die Jahre und ist für stromlose Archivierung die schlechteste Wahl.",
  "Which medium is best suited to permanent archiving without power?",
  ("A tape medium in climate-controlled storage",
   "An SSD removed and kept in a cabinet",
   "A USB stick in the desk drawer",
   "A memory card left in the PC's card reader"),
  "Tapes last decades and are designed for long-term storage. Flash memory loses its charge over the years and is the worst choice for unpowered archiving."),

S("ap1-hw-r32",
  "Ein Nutzer meldet, sein Bildschirm bleibe schwarz, die Betriebsleuchte des PCs leuchtet. Was prüfst du als Erstes?",
  ("Kabel und Eingangsquelle am Monitor",
   "Die Berechtigungen auf dem Dateiserver",
   "Die installierte Version des Office-Pakets",
   "Den Füllstand der Druckerpatronen"), 0,
  "Solange der Rechner läuft, ist die Bildkette der naheliegende Verdacht: falsche Eingangsquelle, loses Kabel oder ein Monitor im Standby. Software und Peripherie sind hier zweitrangig.",
  "A user reports a black screen while the PC's power light is on. What do you check first?",
  ("Cable and input source on the monitor",
   "The permissions on the file server",
   "The installed version of the office suite",
   "The fill level of the printer cartridges"),
  "As long as the machine is running, the display chain is the obvious suspect: wrong input source, a loose cable or a monitor in standby. Software and peripherals come second."),

# -------------------------------------------------------------- multiple (32)
M("ap1-hw-r33",
  "Welche Komponenten gehören zwingend zu einem funktionsfähigen Desktop-PC?",
  ("Hauptplatine", "Prozessor", "Arbeitsspeicher", "Netzteil",
   "Dedizierte Grafikkarte", "Zweiter Bildschirm"),
  (0, 1, 2, 3),
  "Ohne Platine, Prozessor, Speicher und Stromversorgung startet kein System. Eine eigene Grafikkarte ist entbehrlich, wenn der Prozessor eine Grafikeinheit mitbringt, und Monitore sind Peripherie.",
  "Which components are strictly required for a working desktop PC?",
  ("Mainboard", "Processor", "Main memory", "Power supply",
   "Dedicated graphics card", "Second monitor"),
  "Without board, processor, memory and power no system starts. A separate graphics card is dispensable when the processor has an integrated GPU, and monitors are peripherals."),

M("ap1-hw-r34",
  "Welche Vorteile bietet eine SSD gegenüber einer klassischen Festplatte?",
  ("Deutlich kürzere Zugriffszeiten",
   "Höhere Anzahl an Ein- und Ausgabeoperationen",
   "Unempfindlichkeit gegen Erschütterungen",
   "Geräuschloser Betrieb ohne bewegte Teile",
   "Unbegrenzte Anzahl an Schreibzyklen",
   "Günstigerer Preis je Gigabyte"),
  (0, 1, 2, 3),
  "Fehlende Mechanik bringt Tempo, Robustheit und Ruhe. Die Zahl der Schreibzyklen ist allerdings begrenzt, und pro Gigabyte bleibt die Festplatte günstiger.",
  "Which advantages does an SSD offer over a classic hard disk?",
  ("Considerably shorter access times",
   "Higher number of input and output operations",
   "Insensitivity to shock and vibration",
   "Silent operation without moving parts",
   "Unlimited number of write cycles",
   "Cheaper price per gigabyte"),
  "The absence of mechanics brings speed, robustness and silence. The number of write cycles is limited, though, and per gigabyte the hard disk stays cheaper."),

M("ap1-hw-r35",
  "Welche Angaben beschreiben die Leistungsfähigkeit eines Prozessors?",
  ("Anzahl der Kerne", "Taktfrequenz", "Größe des Caches",
   "Unterstützte Befehlssatzerweiterungen", "Farbe des Kühlkörpers", "Gewicht der Verpackung"),
  (0, 1, 2, 3),
  "Kerne, Takt, Cache und Befehlssatzerweiterungen bestimmen zusammen, wie schnell Aufgaben abgearbeitet werden. Äußerlichkeiten wie Kühlerfarbe oder Verpackungsgewicht sagen nichts aus.",
  "Which figures describe the performance of a processor?",
  ("Number of cores", "Clock frequency", "Cache size",
   "Supported instruction set extensions", "Colour of the heat sink", "Weight of the packaging"),
  "Cores, clock, cache and instruction set extensions together determine how fast tasks are processed. Externals such as cooler colour or packaging weight say nothing."),

M("ap1-hw-r36",
  "Welche Anforderungen stellt die Bildschirmarbeitsverordnung an einen Arbeitsplatz?",
  ("Blendfreie Beleuchtung ohne Spiegelungen",
   "Höhenverstellbarer Stuhl mit Rückenlehne",
   "Ausreichend große und flimmerfreie Bildschirme",
   "Regelmäßige Unterbrechung der Bildschirmarbeit",
   "Einheitliche Farbgestaltung aller Möbel",
   "Feste Sitzordnung nach Dienstalter"),
  (0, 1, 2, 3),
  "Die Verordnung zielt auf Beleuchtung, Mobiliar, Anzeigequalität und Pausen - alles Faktoren, die dauerhafte Belastung senken. Möbelfarbe und Sitzordnung sind arbeitsorganisatorische Nebensachen.",
  "Which requirements does the display screen regulation place on a workstation?",
  ("Glare-free lighting without reflections",
   "Height-adjustable chair with backrest",
   "Sufficiently large and flicker-free screens",
   "Regular interruption of screen work",
   "Uniform colour scheme of all furniture",
   "Fixed seating order by seniority"),
  "The regulation targets lighting, furniture, display quality and breaks - all factors that reduce sustained strain. Furniture colour and seating order are organisational side issues."),

M("ap1-hw-r37",
  "Welche Schnittstellen können ein Bildsignal an einen Monitor übertragen?",
  ("HDMI", "DisplayPort", "DVI", "VGA", "SATA", "PS/2"),
  (0, 1, 2, 3),
  "HDMI, DisplayPort und DVI übertragen digital, VGA analog. SATA verbindet Datenträger und PS/2 ältere Tastaturen und Mäuse.",
  "Which interfaces can carry a video signal to a monitor?",
  ("HDMI", "DisplayPort", "DVI", "VGA", "SATA", "PS/2"),
  "HDMI, DisplayPort and DVI transmit digitally, VGA in analogue form. SATA connects storage devices and PS/2 older keyboards and mice."),

M("ap1-hw-r38",
  "Welche Maßnahmen senken den Energieverbrauch an Arbeitsplätzen?",
  ("Energiesparoptionen im Betriebssystem aktivieren",
   "Geräte mit hohem Wirkungsgrad beschaffen",
   "Bildschirme nach kurzer Untätigkeit abschalten",
   "Abschaltbare Steckdosenleisten einsetzen",
   "Alle Rechner dauerhaft durchlaufen lassen",
   "Bildschirmschoner mit bewegter Grafik nutzen"),
  (0, 1, 2, 3),
  "Abschalten und effiziente Geräte wirken direkt, ebenso Leisten gegen Bereitschaftsverluste. Dauerbetrieb und aufwendige Bildschirmschoner erhöhen den Verbrauch sogar.",
  "Which measures reduce energy consumption at workstations?",
  ("Enable power saving options in the operating system",
   "Procure devices with high efficiency ratings",
   "Switch screens off after short inactivity",
   "Use switchable power strips",
   "Let all PCs run permanently around the clock",
   "Use screen savers with animated graphics"),
  "Switching off and efficient devices act directly, as do power strips against standby losses. Continuous operation and elaborate screen savers actually raise consumption."),

M("ap1-hw-r39",
  "Welche Angaben gehören in eine Inventarliste für IT-Geräte?",
  ("Eindeutige Inventarnummer", "Hersteller und Modellbezeichnung",
   "Seriennummer des Geräts", "Standort und zugeordneter Nutzer",
   "Lieblingsfarbe des Nutzers", "Anzahl der Kaffeepausen"),
  (0, 1, 2, 3),
  "Inventarnummer, Typ, Seriennummer sowie Standort und Zuordnung machen ein Gerät auffindbar und zurechenbar - Grundlage für Garantie, Wartung und Ausmusterung. Alles andere ist irrelevant.",
  "Which entries belong in an inventory list for IT equipment?",
  ("Unique inventory number", "Manufacturer and model designation",
   "Serial number of the device", "Location and assigned user",
   "Favourite colour of the user", "Number of coffee breaks"),
  "Inventory number, type, serial number plus location and assignment make a device findable and attributable - the basis for warranty, maintenance and decommissioning. Everything else is irrelevant."),

M("ap1-hw-r40",
  "Welche Aussagen über Arbeitsspeicher sind korrekt?",
  ("Er ist flüchtig und verliert Daten ohne Strom",
   "Er ist deutlich schneller als jeder Massenspeicher",
   "Zu wenig davon führt zum Auslagern auf die Platte",
   "Die Kapazität wird in Gigabyte angegeben",
   "Er speichert das Betriebssystem dauerhaft",
   "Er ersetzt bei Bedarf den Prozessorcache"),
  (0, 1, 2, 3),
  "RAM ist schnell und flüchtig; reicht er nicht, weicht das System auf die deutlich langsamere Auslagerungsdatei aus. Dauerhafte Ablage übernimmt der Massenspeicher, und der Cache sitzt im Prozessor.",
  "Which statements about main memory are correct?",
  ("It is volatile and loses data without power",
   "It is much faster than any mass storage device",
   "Too little of it leads to paging onto the disk",
   "Capacity is stated in gigabytes",
   "It stores the operating system permanently",
   "It replaces the processor cache when needed"),
  "RAM is fast and volatile; when it runs short the system falls back to the far slower page file. Permanent storage is the mass storage device's job, and the cache sits inside the processor."),

M("ap1-hw-r41",
  "Welche Kriterien sprechen bei der Druckerauswahl für ein Lasergerät?",
  ("Hohes Druckaufkommen im Alltag",
   "Niedrige Kosten je gedruckter Seite",
   "Wischfeste Ausdrucke ohne Trocknungszeit",
   "Hohe Druckgeschwindigkeit bei Text",
   "Häufiger Fotodruck in bester Qualität",
   "Sehr seltene Nutzung mit langen Pausen"),
  (0, 1, 2, 3),
  "Laser spielt seine Stärken bei Menge, Tempo und Seitenpreis aus und schmiert nicht. Für Fotos und für sehr seltene Nutzung ist Tinte oft die passendere Wahl.",
  "Which criteria favour a laser device when choosing a printer?",
  ("High everyday printing volume",
   "Low cost per printed page",
   "Smudge-proof output with no drying time",
   "High printing speed for text documents",
   "Frequent photo printing in top quality",
   "Very rare use with long idle periods"),
  "Laser plays to its strengths in volume, speed and cost per page and does not smudge. For photos and very occasional use, inkjet is often the better fit."),

M("ap1-hw-r42",
  "Welche Schritte gehören zur Inbetriebnahme eines neuen Arbeitsplatzrechners?",
  ("Betriebssystem installieren und aktualisieren",
   "Treiber für die verbaute Hardware einspielen",
   "Gerät in die Inventarverwaltung aufnehmen",
   "Benutzerkonto und Berechtigungen einrichten",
   "Das Gehäuse zur Kennzeichnung lackieren",
   "Sämtliche Schnittstellen dauerhaft verkleben"),
  (0, 1, 2, 3),
  "Installation, Treiber, Inventarisierung und Konten sind die Standardschritte, bis ein Gerät produktiv nutzbar ist. Lackieren und Verkleben wären Eingriffe ohne fachlichen Nutzen.",
  "Which steps belong to commissioning a new workstation PC?",
  ("Install and update the operating system",
   "Install drivers for the installed hardware",
   "Record the device in the inventory system",
   "Set up the user account and permissions",
   "Paint the case for identification purposes",
   "Permanently glue all interfaces shut"),
  "Installation, drivers, inventory and accounts are the standard steps until a device is productively usable. Painting and gluing would be interventions with no professional benefit."),

M("ap1-hw-r43",
  "Welche Ursachen können zu Überhitzung eines Rechners führen?",
  ("Verstaubte Kühlkörper und Lüfter",
   "Ausgetrocknete Wärmeleitpaste",
   "Blockierte Lüftungsöffnungen am Gehäuse",
   "Ein defekter oder stehender Lüfter",
   "Eine zu große Festplattenkapazität",
   "Eine zu hohe Bildschirmauflösung"),
  (0, 1, 2, 3),
  "Wärme muss abgeführt werden; Staub, alte Paste, verdeckte Öffnungen und stehende Lüfter verhindern genau das. Speicherkapazität und Bildauflösung erzeugen keine nennenswerte Abwärme.",
  "Which causes can lead to a computer overheating?",
  ("Dusty heat sinks and fans",
   "Dried-out thermal paste",
   "Blocked ventilation openings on the case",
   "A defective or stalled fan",
   "Too large a hard disk capacity",
   "Too high a screen resolution"),
  "Heat has to be carried away; dust, old paste, covered openings and stalled fans prevent exactly that. Storage capacity and screen resolution produce no notable waste heat."),

M("ap1-hw-r44",
  "Welche Aussagen zu USB treffen zu?",
  ("USB überträgt Daten und liefert Strom",
   "Geräte lassen sich im Betrieb anschließen",
   "Ein Hub erweitert die Zahl der Anschlüsse",
   "Neuere Versionen erreichen höhere Datenraten",
   "USB überträgt grundsätzlich kein Bildsignal",
   "Jeder Anschluss braucht einen eigenen Treiber"),
  (0, 1, 2, 3),
  "Strom und Daten in einem Kabel, Hot-Plug-Fähigkeit, Erweiterbarkeit per Hub und wachsende Raten je Version kennzeichnen USB. Über USB-C lässt sich sehr wohl Bild übertragen, und Standardklassen brauchen keine eigenen Treiber.",
  "Which statements about USB are correct?",
  ("USB carries data and supplies power",
   "Devices can be connected during operation",
   "A hub extends the number of ports",
   "Newer versions reach higher data rates",
   "USB fundamentally carries no video signal",
   "Every port needs its own dedicated driver"),
  "Power and data in one cable, hot-plug capability, expansion through hubs and rising rates per version characterise USB. Video can certainly be carried over USB-C, and standard device classes need no dedicated drivers."),

M("ap1-hw-r45",
  "Welche Faktoren bestimmen die Bildqualität eines Monitors?",
  ("Native Auflösung des Panels", "Bildwiederholrate in Hertz",
   "Verwendete Panel-Technik", "Helligkeit und Kontrastverhältnis",
   "Gewicht des Standfußes", "Länge des Netzkabels"),
  (0, 1, 2, 3),
  "Auflösung, Wiederholrate, Panelart und Helligkeit entscheiden über Schärfe, Bewegtbild, Blickwinkel und Ablesbarkeit. Standfuß und Kabellänge betreffen nur die Aufstellung.",
  "Which factors determine the image quality of a monitor?",
  ("Native resolution of the panel", "Refresh rate in hertz",
   "Panel technology used", "Brightness and contrast ratio",
   "Weight of the stand", "Length of the power cable"),
  "Resolution, refresh rate, panel type and brightness decide sharpness, motion handling, viewing angle and readability. Stand and cable length only affect placement."),

M("ap1-hw-r46",
  "Welche Aufgaben erfüllt das UEFI beim Systemstart?",
  ("Es prüft die Hardware im Selbsttest",
   "Es legt die Startreihenfolge der Datenträger fest",
   "Es übergibt die Kontrolle an den Bootloader",
   "Es stellt grundlegende Einstellungen bereit",
   "Es installiert die Anwendungsprogramme",
   "Es verwaltet die Benutzerkonten des Systems"),
  (0, 1, 2, 3),
  "Selbsttest, Startreihenfolge, Übergabe an den Bootloader und Grundeinstellungen sind die Firmwareaufgaben. Anwendungen und Benutzerkonten verwaltet erst das Betriebssystem.",
  "Which tasks does the UEFI perform during system startup?",
  ("It checks the hardware in a self test",
   "It defines the boot order of the drives",
   "It hands control over to the bootloader",
   "It provides basic configuration settings",
   "It installs the application programs",
   "It manages the system's user accounts"),
  "Self test, boot order, handover to the bootloader and basic settings are the firmware's jobs. Applications and user accounts are managed by the operating system."),

M("ap1-hw-r47",
  "Welche Vorkehrungen schützen Bauteile beim Arbeiten am offenen Gehäuse?",
  ("Antistatikarmband mit Erdung tragen",
   "Rechner vorher vom Stromnetz trennen",
   "Bauteile nur am Rand anfassen",
   "Komponenten auf leitfähiger Unterlage ablegen",
   "Bauteile vor dem Einbau anhauchen",
   "Mit feuchtem Tuch über die Platine wischen"),
  (0, 1, 2, 3),
  "Erdung, Spannungsfreiheit, Anfassen am Rand und leitfähige Ablage verhindern elektrostatische Schäden. Feuchtigkeit auf der Platine wäre dagegen unmittelbar schädlich.",
  "Which precautions protect components when working inside an open case?",
  ("Wear an earthed antistatic wrist strap",
   "Disconnect the machine from mains power first",
   "Handle components only by their edges",
   "Place components on a conductive surface",
   "Breathe on components before installing them",
   "Wipe the board with a damp cloth"),
  "Earthing, removing power, edge handling and conductive surfaces prevent electrostatic damage. Moisture on the board would be immediately harmful."),

M("ap1-hw-r48",
  "Welche Angaben braucht man, um die jährlichen Stromkosten eines Geräts zu berechnen?",
  ("Leistungsaufnahme in Watt", "Betriebsstunden pro Tag",
   "Betriebstage pro Jahr", "Strompreis je Kilowattstunde",
   "Kaufpreis des Geräts", "Gewicht des Geräts"),
  (0, 1, 2, 3),
  "Leistung mal Zeit ergibt den Verbrauch in Kilowattstunden, multipliziert mit dem Strompreis die Kosten. Kaufpreis und Gewicht gehen in diese Rechnung nicht ein.",
  "Which figures are needed to calculate the annual electricity cost of a device?",
  ("Power draw in watts", "Operating hours per day",
   "Operating days per year", "Electricity price per kilowatt hour",
   "Purchase price of the device", "Weight of the device"),
  "Power times time gives consumption in kilowatt hours, multiplied by the electricity price it gives the cost. Purchase price and weight do not enter this calculation."),

M("ap1-hw-r49",
  "Welche Aussagen über Notebooks im Vergleich zu Desktop-Rechnern treffen zu?",
  ("Sie sind mobil und arbeiten netzunabhängig",
   "Sie sind bei gleicher Leistung meist teurer",
   "Ihre Komponenten sind schlechter aufrüstbar",
   "Sie erzeugen bei Volllast mehr Geräusch je Leistung",
   "Sie lassen sich leichter selbst reparieren",
   "Sie bieten grundsätzlich mehr Anschlüsse"),
  (0, 1, 2, 3),
  "Mobilität erkauft man mit Preis, kompakter Bauweise und schlechter Aufrüstbarkeit; kleine Lüfter werden zudem schneller laut. Reparatur und Anschlussvielfalt sprechen für den Desktop.",
  "Which statements about laptops compared with desktop PCs are correct?",
  ("They are mobile and run independently of mains power",
   "They usually cost more for the same performance",
   "Their components are harder to upgrade",
   "They are noisier per unit of performance at full load",
   "They are easier to repair yourself",
   "They fundamentally offer more ports"),
  "Mobility is paid for with price, compact construction and poor upgradability; small fans also get loud sooner. Repairability and port variety favour the desktop."),

M("ap1-hw-r50",
  "Welche Merkmale kennzeichnen einen Thin Client?",
  ("Geringe eigene Rechenleistung",
   "Anwendungen laufen auf einem zentralen Server",
   "Niedriger Stromverbrauch im Betrieb",
   "Zentrale Verwaltung und Aktualisierung",
   "Umfangreiche lokale Datenhaltung",
   "Hohe Grafikleistung für lokale Spiele"),
  (0, 1, 2, 3),
  "Der Thin Client ist bewusst schlank: er zeigt an und nimmt Eingaben entgegen, während Rechenlast und Daten zentral liegen. Genau daraus folgen sparsamer Betrieb und einfache Verwaltung.",
  "Which characteristics define a thin client?",
  ("Little processing power of its own",
   "Applications run on a central server",
   "Low power consumption in operation",
   "Central administration and updating",
   "Extensive local data storage",
   "High graphics performance for local gaming"),
  "A thin client is deliberately lean: it displays and accepts input while processing load and data stay central. Economical operation and simple administration follow directly from that."),

M("ap1-hw-r51",
  "Welche Ursachen können einen langsamen Arbeitsplatzrechner erklären?",
  ("Zu wenig Arbeitsspeicher für die genutzte Software",
   "Eine nahezu volle Systempartition",
   "Eine mechanische Festplatte als Systemlaufwerk",
   "Viele automatisch startende Hintergrundprogramme",
   "Ein zu langes Netzwerkkabel am Arbeitsplatz",
   "Eine zu hell eingestellte Bildschirmhelligkeit"),
  (0, 1, 2, 3),
  "Speicherknappheit, volle Systemplatte, langsames Laufwerk und Autostart-Ballast sind die üblichen Verdächtigen. Kabellänge und Helligkeit haben keinen Einfluss auf die Rechenleistung.",
  "Which causes can explain a slow workstation PC?",
  ("Too little RAM for the software in use",
   "A system partition that is nearly full",
   "A mechanical hard disk as the system drive",
   "Many background programs starting automatically",
   "Too long a network cable at the workstation",
   "A screen brightness set too high"),
  "Memory shortage, a full system disk, a slow drive and autostart clutter are the usual suspects. Cable length and brightness have no influence on computing performance."),

M("ap1-hw-r52",
  "Welche Aussagen zur Entsorgung von Altgeräten sind richtig?",
  ("Elektroaltgeräte gehören nicht in den Restmüll",
   "Datenträger sind vorher sicher zu löschen",
   "Rücknahmestellen nehmen Altgeräte an",
   "Batterien werden getrennt entsorgt",
   "Geräte dürfen im Hausmüll entsorgt werden",
   "Festplatten können ungelöscht verkauft werden"),
  (0, 1, 2, 3),
  "Das Elektrogesetz verlangt getrennte Rückgabe, Batterien nochmals gesondert, und Datenschutz verlangt sicheres Löschen vor der Abgabe. Hausmüll und ungelöschte Verkäufe verstoßen gegen beides.",
  "Which statements about disposing of old equipment are correct?",
  ("Electronic waste does not belong in general refuse",
   "Storage media must be securely wiped beforehand",
   "Collection points accept old equipment",
   "Batteries are disposed of separately",
   "Devices may be put into household waste",
   "Hard disks can be sold without being wiped"),
  "Electronics legislation requires separate return, batteries separately again, and data protection requires secure wiping before handover. Household waste and unwiped sales violate both."),

M("ap1-hw-r53",
  "Welche Wechselmedien und Anschlüsse eignen sich zur Datenübertragung zwischen Rechnern?",
  ("USB-Stick", "Externe SSD über USB", "Speicherkarte mit Lesegerät",
   "Netzwerkfreigabe über LAN", "Der Kaltgerätestecker des Netzteils", "Der Lüfteranschluss auf der Platine"),
  (0, 1, 2, 3),
  "Wechselmedien und Netzwerkfreigaben sind die üblichen Wege, wobei die Freigabe bei größeren Mengen und Nachvollziehbarkeit klar im Vorteil ist. Strom- und Lüfteranschlüsse übertragen keine Daten.",
  "Which removable media and connections are suitable for transferring data between computers?",
  ("USB stick", "External SSD over USB", "Memory card with a reader",
   "Network share over LAN", "The power inlet of the PSU", "The fan header on the board"),
  "Removable media and network shares are the usual routes, with the share clearly ahead for larger volumes and traceability. Power and fan connectors carry no data."),

M("ap1-hw-r54",
  "Welche Aussagen über Grafikkarten sind zutreffend?",
  ("Sie besitzen eigenen Grafikspeicher",
   "Sie stecken üblicherweise in einem PCIe-Steckplatz",
   "Sie brauchen bei hoher Leistung eigene Stromstecker",
   "Sie entlasten den Prozessor bei der Bildberechnung",
   "Sie ersetzen den Arbeitsspeicher des Systems",
   "Sie sind für jeden Bürorechner zwingend nötig"),
  (0, 1, 2, 3),
  "Eigener Speicher, PCIe-Anbindung, zusätzliche Stromversorgung und Entlastung der CPU sind typisch. Den Arbeitsspeicher ersetzen sie nicht, und für Büroarbeit reicht meist die integrierte Grafikeinheit.",
  "Which statements about graphics cards are correct?",
  ("They have their own graphics memory",
   "They usually sit in a PCIe slot",
   "High-performance models need dedicated power connectors",
   "They relieve the processor of image computation",
   "They replace the system's main memory",
   "They are strictly necessary for every office PC"),
  "Own memory, PCIe attachment, additional power supply and offloading the CPU are typical. They do not replace main memory, and for office work the integrated GPU usually suffices."),

M("ap1-hw-r55",
  "Welche Punkte gehören in ein Pflichtenheft für die Beschaffung neuer Arbeitsplatzrechner?",
  ("Geforderte Mindestausstattung an Prozessor und Speicher",
   "Notwendige Schnittstellen und Anschlüsse",
   "Gewünschte Garantie- und Reaktionszeiten",
   "Anforderungen an Energieeffizienz",
   "Die Lieblingsmarke des Einkäufers",
   "Die Farbe der Verpackungskartons"),
  (0, 1, 2, 3),
  "Ein Pflichtenheft beschreibt messbare Anforderungen, an denen Angebote vergleichbar werden: Leistung, Anschlüsse, Service und Effizienz. Persönliche Vorlieben und Verpackung gehören nicht dazu.",
  "Which points belong in a specification for procuring new workstation PCs?",
  ("Required minimum processor and memory configuration",
   "Necessary interfaces and connectors",
   "Desired warranty and response times",
   "Requirements for energy efficiency",
   "The purchaser's favourite brand",
   "The colour of the packaging boxes"),
  "A specification describes measurable requirements that make offers comparable: performance, connectors, service and efficiency. Personal preferences and packaging do not belong there."),

M("ap1-hw-r56",
  "Welche Aussagen über Massenspeicher-Schnittstellen sind korrekt?",
  ("SATA erreicht rund 600 Megabyte je Sekunde",
   "NVMe nutzt die PCIe-Anbindung des Systems",
   "M.2 beschreibt eine Bauform, nicht das Protokoll",
   "NVMe erreicht deutlich höhere Datenraten als SATA",
   "SATA ist schneller als jede NVMe-Verbindung",
   "M.2 arbeitet grundsätzlich immer mit NVMe"),
  (0, 1, 2, 3),
  "SATA deckelt bei etwa 600 MB/s, NVMe hängt am PCIe-Bus und liegt weit darüber. M.2 ist nur der Steckplatz und kann beide Protokolle führen - der Blick ins Datenblatt lohnt sich.",
  "Which statements about mass storage interfaces are correct?",
  ("SATA reaches around 600 megabytes per second",
   "NVMe uses the system's PCIe attachment",
   "M.2 describes a form factor, not the protocol",
   "NVMe reaches much higher data rates than SATA",
   "SATA is faster than any NVMe connection",
   "M.2 always works with NVMe by definition"),
  "SATA caps at roughly 600 MB/s while NVMe hangs off the PCIe bus and goes far beyond. M.2 is only the slot and can carry either protocol - reading the data sheet pays off."),

M("ap1-hw-r57",
  "Welche Symptome deuten auf eine defekte Festplatte hin?",
  ("Ungewöhnliche klackernde Geräusche",
   "Häufige Lesefehler beim Öffnen von Dateien",
   "Auffällige SMART-Werte im Auslesetool",
   "Stark verlängerte Startzeiten des Systems",
   "Ein flackerndes Bild auf dem Monitor",
   "Eine nicht funktionierende Tastaturbeleuchtung"),
  (0, 1, 2, 3),
  "Geräusche, Lesefehler, SMART-Warnungen und schleichende Verlangsamung sind klassische Vorboten eines Plattenausfalls - Anlass, sofort zu sichern. Bild und Tastatur zeigen ganz andere Fehler an.",
  "Which symptoms indicate a failing hard disk?",
  ("Unusual clicking noises",
   "Frequent read errors when opening files",
   "Conspicuous SMART values in the reading tool",
   "Greatly extended system startup times",
   "A flickering image on the monitor",
   "Keyboard backlighting that does not work"),
  "Noises, read errors, SMART warnings and creeping slowdown are classic precursors of disk failure - reason to back up immediately. Display and keyboard indicate entirely different faults."),

M("ap1-hw-r58",
  "Welche Eigenschaften hat ECC-Arbeitsspeicher?",
  ("Er erkennt Bitfehler im Speicherinhalt",
   "Er korrigiert Einzelbitfehler selbstständig",
   "Er wird vor allem in Servern eingesetzt",
   "Er braucht Unterstützung durch Board und Prozessor",
   "Er ist schneller als gewöhnlicher Speicher",
   "Er verdoppelt die nutzbare Kapazität"),
  (0, 1, 2, 3),
  "ECC bezahlt Zuverlässigkeit mit etwas Kapazität und Tempo: Fehler werden erkannt und einzelne Bits korrigiert, sofern die Plattform mitspielt. Schneller oder größer wird der Speicher dadurch nicht.",
  "Which properties does ECC memory have?",
  ("It detects bit errors in the stored content",
   "It corrects single-bit errors automatically",
   "It is used primarily in servers",
   "It needs support from board and processor",
   "It is faster than ordinary memory",
   "It doubles the usable capacity"),
  "ECC pays for reliability with a little capacity and speed: errors are detected and single bits corrected, provided the platform supports it. The memory becomes neither faster nor larger."),

M("ap1-hw-r59",
  "Welche Angaben beschreiben einen Monitor in einem Angebot sinnvoll?",
  ("Bildschirmdiagonale in Zoll", "Native Auflösung in Bildpunkten",
   "Anschlüsse für das Bildsignal", "Höhenverstellbarkeit des Standfußes",
   "Anzahl der Schrauben im Gehäuse", "Herkunftsland des Verpackungskartons"),
  (0, 1, 2, 3),
  "Diagonale, Auflösung, Anschlüsse und Ergonomie entscheiden über Eignung am Arbeitsplatz. Konstruktionsdetails und Verpackungsherkunft helfen bei der Auswahl nicht weiter.",
  "Which details sensibly describe a monitor in a quotation?",
  ("Screen diagonal in inches", "Native resolution in pixels",
   "Connectors for the video signal", "Height adjustability of the stand",
   "Number of screws in the housing", "Country of origin of the packaging"),
  "Diagonal, resolution, connectors and ergonomics decide suitability at the workplace. Construction details and packaging origin do not help the selection."),

M("ap1-hw-r60",
  "Welche Aussagen zu Zahlensystemen in der IT sind richtig?",
  ("Das Dualsystem kennt die Ziffern 0 und 1",
   "Das Hexadezimalsystem hat die Basis 16",
   "Vier Bit lassen sich als eine Hexziffer schreiben",
   "Ein Byte umfasst acht Bit",
   "Das Dezimalsystem hat die Basis 8",
   "Ein Bit kann drei Zustände annehmen"),
  (0, 1, 2, 3),
  "Dual und Hexadezimal sind die IT-Klassiker, und die Vier-Bit-Gruppierung macht Hex zur kompakten Schreibweise für Binärwerte. Das Dezimalsystem hat die Basis 10, und ein Bit kennt genau zwei Zustände.",
  "Which statements about number systems in IT are correct?",
  ("The binary system uses the digits 0 and 1",
   "The hexadecimal system has base 16",
   "Four bits can be written as one hex digit",
   "One byte comprises eight bits",
   "The decimal system has base 8",
   "One bit can take three states"),
  "Binary and hexadecimal are the IT classics, and four-bit grouping makes hex a compact notation for binary values. The decimal system has base 10, and a bit knows exactly two states."),

M("ap1-hw-r61",
  "Welche Maßnahmen verlängern die Lebensdauer eines Arbeitsplatzrechners?",
  ("Regelmäßige Reinigung von Staub",
   "Aufstellung mit freien Lüftungsöffnungen",
   "Vermeidung von direkter Sonneneinstrahlung",
   "Schutz vor Spannungsspitzen im Netz",
   "Dauerbetrieb unter Volllast rund um die Uhr",
   "Betrieb bei möglichst hoher Raumtemperatur"),
  (0, 1, 2, 3),
  "Wärme und Staub sind die größten Feinde der Elektronik, Spannungsspitzen der plötzliche. Dauervolllast und Hitze verkürzen die Lebensdauer dagegen messbar.",
  "Which measures extend the service life of a workstation PC?",
  ("Regular removal of dust",
   "Placement with unobstructed ventilation openings",
   "Avoiding direct sunlight on the case",
   "Protection against mains voltage spikes",
   "Continuous full-load operation around the clock",
   "Operation at the highest possible room temperature"),
  "Heat and dust are electronics' biggest enemies, voltage spikes the sudden one. Continuous full load and heat measurably shorten service life instead."),

M("ap1-hw-r62",
  "Welche Aussagen über Ein- und Ausgabegeräte sind korrekt?",
  ("Die Tastatur ist ein reines Eingabegerät",
   "Der Monitor ist ein Ausgabegerät",
   "Ein Touchscreen dient Ein- und Ausgabe zugleich",
   "Ein Multifunktionsdrucker mit Scanner kann beides",
   "Die Maus gibt Bildinformationen aus",
   "Der Lautsprecher nimmt Daten entgegen"),
  (0, 1, 2, 3),
  "Die Zuordnung folgt der Richtung des Datenflusses; Touchscreens und Multifunktionsgeräte vereinen beide Richtungen. Die Maus gibt nichts aus, der Lautsprecher nimmt nichts auf.",
  "Which statements about input and output devices are correct?",
  ("The keyboard is a pure input device",
   "The monitor is an output device",
   "A touchscreen serves input and output at once",
   "A multifunction printer with scanner does both",
   "The mouse outputs image information",
   "The loudspeaker receives data input"),
  "The classification follows the direction of data flow; touchscreens and multifunction devices combine both directions. The mouse outputs nothing and the loudspeaker records nothing."),

M("ap1-hw-r63",
  "Welche Schritte gehören zu einer strukturierten Hardware-Fehlersuche?",
  ("Fehlerbild genau beschreiben lassen",
   "Prüfen, ob der Fehler reproduzierbar ist",
   "Mögliche Ursachen schrittweise ausschließen",
   "Ergebnis und Lösung dokumentieren",
   "Sofort alle Bauteile gleichzeitig tauschen",
   "Den Nutzer für den Fehler verantwortlich machen"),
  (0, 1, 2, 3),
  "Beschreiben, reproduzieren, eingrenzen und dokumentieren führt zuverlässig zur Ursache und hilft beim nächsten Mal. Blindes Tauschen verschleiert die Ursache und kostet Material.",
  "Which steps belong to structured hardware troubleshooting?",
  ("Have the symptom described precisely",
   "Check whether the fault is reproducible",
   "Rule out possible causes step by step",
   "Document the result and the solution",
   "Immediately swap all components at once",
   "Hold the user responsible for the fault"),
  "Describing, reproducing, narrowing down and documenting reliably leads to the cause and helps next time. Blind swapping obscures the cause and wastes parts."),

M("ap1-hw-r64",
  "Welche Aussagen über Kühlung im PC sind zutreffend?",
  ("Luftkühlung nutzt Kühlkörper und Lüfter",
   "Ein guter Luftstrom braucht Zu- und Abluft",
   "Wasserkühlung führt Wärme über ein Medium ab",
   "Staub verschlechtert die Kühlleistung deutlich",
   "Mehr Lüfter bedeuten immer bessere Kühlung",
   "Ein geschlossenes Gehäuse braucht keine Belüftung"),
  (0, 1, 2, 3),
  "Entscheidend ist ein gerichteter Luftstrom von kalt nach warm, nicht die bloße Anzahl der Lüfter - gegeneinander blasende Lüfter bringen wenig. Ohne Belüftung staut sich die Wärme in jedem Gehäuse.",
  "Which statements about cooling in a PC are correct?",
  ("Air cooling uses heat sinks and fans",
   "Good airflow needs both intake and exhaust",
   "Water cooling carries heat away via a medium",
   "Dust noticeably degrades cooling performance",
   "More fans always mean better cooling",
   "A closed case needs no ventilation at all"),
  "What matters is a directed airflow from cool to warm, not the sheer number of fans - fans blowing against each other achieve little. Without ventilation heat builds up in any case."),

# ------------------------------------------------------------------ text (36)
T("ap1-hw-r65", "Wie viele Bit umfasst ein Byte?", "8",
  "Acht Bit ergeben ein Byte und damit 256 mögliche Zustände von 0 bis 255.",
  "How many bits does a byte comprise?", "8",
  "Eight bits make one byte and therefore 256 possible states from 0 to 255."),

T("ap1-hw-r66", "Welchen Dezimalwert hat die Binärzahl 1101?", "13",
  "Die Stellenwerte von rechts sind 1, 2, 4 und 8: also 8 + 4 + 0 + 1 = 13.",
  "What is the decimal value of the binary number 1101?", "13",
  "The place values from the right are 1, 2, 4 and 8: so 8 + 4 + 0 + 1 = 13."),

T("ap1-hw-r67", "Welche Bauform hat eine SSD, die flach direkt auf der Hauptplatine steckt?", "M.2",
  "M.2 spart Kabel und Platz. Ob NVMe oder SATA darüber läuft, verrät erst das Datenblatt.",
  "Which form factor describes an SSD plugging flat directly into the mainboard?", "M.2",
  "M.2 saves cables and space. Whether NVMe or SATA runs over it is only revealed by the data sheet."),

T("ap1-hw-r68", "Welche Auflösung in Bildpunkten steht hinter der Bezeichnung Full HD?", "1920 x 1080",
  "Rund zwei Millionen Bildpunkte. Darüber folgen WQHD mit 2560 x 1440 und UHD mit 3840 x 2160.",
  "Which pixel resolution is behind the label Full HD?", "1920 x 1080",
  "Roughly two million pixels. Above it come WQHD at 2560 x 1440 and UHD at 3840 x 2160."),

T("ap1-hw-r69", "Wie nennt man den Selbsttest, den ein PC unmittelbar nach dem Einschalten durchführt?", "POST",
  "Der Power-On Self-Test prüft die Grundkomponenten und meldet Fehler notfalls über Signaltöne.",
  "What is the self test a PC performs immediately after power-on called?", "POST",
  "The power-on self-test checks the basic components and reports faults through beeps if necessary."),

T("ap1-hw-r70", "Welches Bauteil auf der Hauptplatine hält Uhrzeit und Einstellungen ohne Netzstrom?", "Die Pufferbatterie",
  "Eine Knopfzelle versorgt Echtzeituhr und Firmwarespeicher. Ist sie leer, startet das System mit Grundwerten.",
  "Which component on the mainboard keeps time and settings without mains power?", "The backup battery",
  "A coin cell powers the real-time clock and firmware memory. When empty, the system starts with default values."),

T("ap1-hw-r71", "Wie viele Byte enthält ein Kibibyte?", "1024",
  "2 hoch 10 Byte. Das SI-Kilobyte steht dagegen für glatte 1000 Byte.",
  "How many bytes does a kibibyte contain?", "1024",
  "2 to the power of 10 bytes. The SI kilobyte by contrast means a round 1000 bytes."),

T("ap1-hw-r72", "Welche Paste sorgt für den Wärmeübergang zwischen Prozessor und Kühler?", "Wärmeleitpaste",
  "Sie verdrängt die schlecht leitende Luft in den mikroskopischen Unebenheiten beider Flächen.",
  "Which paste ensures heat transfer between processor and cooler?", "Thermal paste",
  "It displaces the poorly conducting air in the microscopic unevenness of both surfaces."),

T("ap1-hw-r73", "Welche Firmware hat das klassische BIOS auf modernen Rechnern abgelöst?", "UEFI",
  "UEFI beherrscht GPT für Datenträger über 2 TB, startet schneller und bietet Secure Boot.",
  "Which firmware has replaced the classic BIOS on modern computers?", "UEFI",
  "UEFI handles GPT for drives beyond 2 TB, boots faster and offers Secure Boot."),

T("ap1-hw-r74", "Wie heißt der Speicher, der seinen Inhalt beim Ausschalten verliert?", "Arbeitsspeicher",
  "Flüchtiger Speicher, auch RAM genannt. Dauerhafte Ablage übernimmt der Massenspeicher.",
  "What is memory that loses its content when powered off called?", "Main memory",
  "Volatile memory, also called RAM. Permanent storage is handled by mass storage devices."),

T("ap1-hw-r75", "Welche Kennzahl zählt die Zugriffe eines Datenträgers pro Sekunde?", "IOPS",
  "Bei vielen kleinen Zugriffen aussagekräftiger als die reine Übertragungsrate - hier glänzen SSDs.",
  "Which figure counts a storage device's accesses per second?", "IOPS",
  "More meaningful than raw transfer rate when there are many small accesses - where SSDs shine."),

T("ap1-hw-r76", "Wie viele Watt verbraucht ein Gerät mit 100 Watt in 10 Stunden, in Wattstunden?", "1000",
  "Leistung mal Zeit: 100 W mal 10 h ergibt 1000 Wh, also eine Kilowattstunde.",
  "How many watt hours does a 100 watt device consume in 10 hours?", "1000",
  "Power times time: 100 W times 10 h gives 1000 Wh, i.e. one kilowatt hour."),

T("ap1-hw-r77", "Welcher Formfaktor beschreibt eine 17 mal 17 Zentimeter große Hauptplatine?", "Mini-ITX",
  "Die kleinste gängige Bauform, beliebt für kompakte Büro- und Wohnzimmerrechner.",
  "Which form factor describes a mainboard measuring 17 by 17 centimetres?", "Mini-ITX",
  "The smallest common form factor, popular for compact office and living room machines."),

T("ap1-hw-r78", "Wie nennt man den Betrieb zweier gleicher Speichermodule für höhere Bandbreite?", "Dual Channel",
  "Der Speichercontroller nutzt zwei Kanäle parallel. Die Module gehören in die passenden Bänke.",
  "What is running two identical memory modules for higher bandwidth called?", "Dual channel",
  "The memory controller uses two channels in parallel. The modules belong in the matching banks."),

T("ap1-hw-r79", "Welche Technik überträgt Strom und Daten über ein einziges Netzwerkkabel?", "Power over Ethernet",
  "Vor allem für Access Points, IP-Telefone und Kameras an Orten ohne Steckdose.",
  "Which technology carries power and data over a single network cable?", "Power over Ethernet",
  "Mainly for access points, IP phones and cameras in places without a power socket."),

T("ap1-hw-r80", "Wie heißt die Kennzahl für die Gesamtkosten eines Geräts über die Nutzungsdauer?", "TCO",
  "Total Cost of Ownership umfasst Anschaffung, Verbrauch, Energie, Wartung und Entsorgung.",
  "What is the figure for a device's total cost over its service life called?", "TCO",
  "Total cost of ownership covers purchase, consumables, energy, maintenance and disposal."),

T("ap1-hw-r81", "Welchen Dezimalwert hat die Hexadezimalzahl FF?", "255",
  "F entspricht 15: 15 mal 16 plus 15 ergibt 255 - der größte Wert eines Bytes.",
  "What is the decimal value of the hexadecimal number FF?", "255",
  "F equals 15: 15 times 16 plus 15 gives 255 - the largest value of one byte."),

T("ap1-hw-r82", "Wie viele Bit lassen sich durch eine einzige Hexadezimalziffer darstellen?", "4",
  "16 Werte entsprechen genau vier Bit, weshalb Hex eine kompakte Schreibweise für Binärdaten ist.",
  "How many bits can a single hexadecimal digit represent?", "4",
  "16 values correspond to exactly four bits, which makes hex a compact notation for binary data."),

T("ap1-hw-r83", "Welche Schutzmaßnahme verhindert Schäden durch elektrostatische Entladung beim Einbau?", "Antistatikarmband",
  "Es leitet Ladung kontrolliert ab. Ergänzend hilft eine leitfähige Ablage für Bauteile.",
  "Which protective measure prevents electrostatic discharge damage during installation?", "Antistatic wrist strap",
  "It conducts charge away in a controlled way. A conductive mat for components helps in addition."),

T("ap1-hw-r84", "Welches Protokoll meldet den Gesundheitszustand einer Festplatte?", "SMART",
  "Die Selbstüberwachung liefert Werte zu Fehlern, Betriebsstunden und Temperatur - Vorwarnung vor dem Ausfall.",
  "Which protocol reports the health status of a hard disk?", "SMART",
  "The self-monitoring feature supplies values on errors, operating hours and temperature - early warning of failure."),

T("ap1-hw-r85", "Wie viel Prozent Wirkungsgrad muss ein Netzteil mindestens erreichen, um 80 Plus zu heißen?", "80",
  "Daher der Name. Höhere Stufen wie Gold oder Platin verlangen deutlich mehr über den Lastbereich.",
  "What minimum efficiency in percent must a PSU reach to be called 80 Plus?", "80",
  "Hence the name. Higher tiers such as Gold or Platinum demand considerably more across the load range."),

T("ap1-hw-r86", "Wie heißt der Zwischenspeicher direkt im Prozessor?", "Cache",
  "Er puffert häufig gebrauchte Daten in mehreren Stufen und überbrückt die Lücke zum langsameren Arbeitsspeicher.",
  "What is the buffer memory directly inside the processor called?", "Cache",
  "It buffers frequently used data in several levels and bridges the gap to slower main memory."),

T("ap1-hw-r87", "Welcher Anschluss überträgt Bild und Ton digital über ein Kabel und ist an Fernsehern üblich?", "HDMI",
  "Im PC-Bereich ist DisplayPort verbreiteter, weil er höhere Auflösungen und Wiederholraten unterstützt.",
  "Which connector carries picture and sound digitally over one cable and is common on TVs?", "HDMI",
  "In the PC world DisplayPort is more common because it supports higher resolutions and refresh rates."),

T("ap1-hw-r88", "Welcher Befehl der SSD meldet dem Laufwerk freigewordene Blöcke?", "TRIM",
  "Ohne TRIM sammeln sich belegt markierte Blöcke an und das Schreiben wird mit der Zeit langsamer.",
  "Which SSD command informs the drive about freed blocks?", "TRIM",
  "Without TRIM, blocks marked as used accumulate and writing gets slower over time."),

T("ap1-hw-r89", "Wie viel Megabyte pro Sekunde erreicht SATA III maximal, gerundet?", "600",
  "Rund 600 MB/s sind die praktische Obergrenze - NVMe über PCIe liegt um ein Vielfaches darüber.",
  "How many megabytes per second does SATA III reach at most, rounded?", "600",
  "Around 600 MB/s is the practical ceiling - NVMe over PCIe lies many times above it."),

T("ap1-hw-r90", "Wie nennt man einen Rechner ohne eigene Rechenleistung, dessen Anwendungen zentral laufen?", "Thin Client",
  "Er zeigt an und nimmt Eingaben entgegen; Rechenlast und Daten bleiben auf dem Server.",
  "What is a computer without own processing power whose applications run centrally called?", "Thin client",
  "It displays and accepts input; processing load and data stay on the server."),

T("ap1-hw-r91", "Welches Speichermedium eignet sich am besten für die stromlose Langzeitarchivierung?", "Magnetband",
  "Bänder überstehen Jahrzehnte in klimatisierter Lagerung, während Flash-Speicher über Jahre Ladung verliert.",
  "Which storage medium is best suited to unpowered long-term archiving?", "Magnetic tape",
  "Tapes survive decades in climate-controlled storage while flash memory loses charge over the years."),

T("ap1-hw-r92", "Welche Bauteilgruppe verbindet den Prozessor mit Speicher und Schnittstellen der Hauptplatine?", "Chipsatz",
  "Er bestimmt maßgeblich, welche Prozessoren, Speicher und Erweiterungen eine Platine aufnehmen kann.",
  "Which component group links the processor to memory and interfaces on the mainboard?", "Chipset",
  "It largely determines which processors, memory and expansions a board can accept."),

T("ap1-hw-r93", "Wie viele Bildpunkte hat ein Monitor mit 1920 x 1080 insgesamt, gerundet in Millionen?", "2",
  "1920 mal 1080 ergibt 2073600 Bildpunkte, also rund zwei Millionen.",
  "How many pixels does a 1920 x 1080 monitor have in total, rounded in millions?", "2",
  "1920 times 1080 gives 2,073,600 pixels, i.e. roughly two million."),

T("ap1-hw-r94", "Welche Speicherart erkennt und korrigiert Bitfehler selbstständig?", "ECC-Speicher",
  "Error Correcting Code kommt vor allem in Servern zum Einsatz und braucht Unterstützung durch Board und CPU.",
  "Which type of memory detects and corrects bit errors by itself?", "ECC memory",
  "Error correcting code is used mainly in servers and requires support from board and CPU."),

T("ap1-hw-r95", "Wie viele Zustände kann ein einzelnes Bit annehmen?", "2",
  "Genau zwei: 0 oder 1. Aus dieser Zweiwertigkeit ergibt sich die gesamte Digitaltechnik.",
  "How many states can a single bit take?", "2",
  "Exactly two: 0 or 1. All of digital technology follows from this two-valued nature."),

T("ap1-hw-r96", "Welches Verfahren im UEFI prüft beim Start die Signatur des Bootloaders?", "Secure Boot",
  "Nur signierter Startcode wird ausgeführt, was Manipulationen vor dem Systemstart erschwert.",
  "Which UEFI feature verifies the bootloader's signature at startup?", "Secure Boot",
  "Only signed startup code is executed, which makes tampering before system start harder."),

T("ap1-hw-r97", "Welche Steckplatzart nimmt heute Grafikkarten und schnelle SSDs auf?", "PCIe",
  "PCI Express arbeitet mit Lanes; mehr Lanes bedeuten mehr Bandbreite für die Steckkarte.",
  "Which slot type accommodates graphics cards and fast SSDs today?", "PCIe",
  "PCI Express works with lanes; more lanes mean more bandwidth for the card."),

T("ap1-hw-r98", "Wie hoch sollte die oberste Bildschirmzeile im Verhältnis zur Augenhöhe stehen?", "Leicht darunter",
  "Ein leicht gesenkter Blick entlastet die Nackenmuskulatur gegenüber einem erhöhten Bildschirm.",
  "Where should the top line of the screen sit relative to eye level?", "Slightly below",
  "A slightly lowered gaze relieves the neck muscles compared with a raised screen."),

T("ap1-hw-r99", "Welches Bauteil wandelt die Netzspannung in die Betriebsspannungen des PCs um?", "Netzteil",
  "Es liefert im Wesentlichen 12, 5 und 3,3 Volt. Sein Wirkungsgrad zeigt sich in der 80-Plus-Zertifizierung.",
  "Which component converts mains voltage into the PC's operating voltages?", "Power supply",
  "It mainly supplies 12, 5 and 3.3 volts. Its efficiency is shown by the 80 Plus certification."),

T("ap1-hw-r100", "Wie viele nutzbare Werte kann ein Byte darstellen?", "256",
  "2 hoch 8 gleich 256, üblicherweise als Bereich 0 bis 255 gezählt.",
  "How many distinct values can one byte represent?", "256",
  "2 to the power of 8 equals 256, usually counted as the range 0 to 255."),
]

build("ap1-hardware-arbeitsplatz.json", "Hardware & Arbeitsplatz", "Hardware & Workplace", Q)
