#!/usr/bin/env python3
"""AP2 Speicher & Backup - 100 handgeschriebene Fragen."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from qlib import S, M, T, build

Q = [
# ---------------------------------------------------------------- single (32)
S("ap2-sto-r01",
  "Vier Festplatten zu je 2 TB werden als RAID 5 betrieben. Wie groß ist die Nettokapazität?",
  ("6 TB", "8 TB", "4 TB", "2 TB"), 0,
  "RAID 5 opfert die Kapazität genau einer Platte für die Paritätsinformation. Aus 4 mal 2 TB werden damit 3 mal 2 TB nutzbar.",
  "Four hard disks of 2 TB each run as RAID 5. What is the net capacity?",
  ("6 TB", "8 TB", "4 TB", "2 TB"),
  "RAID 5 sacrifices exactly one disk's capacity for parity information. So 4 times 2 TB becomes 3 times 2 TB usable."),

S("ap2-sto-r02",
  "Welches RAID-Level bietet keinerlei Ausfallsicherheit?",
  ("RAID 0", "RAID 1", "RAID 5", "RAID 6"), 0,
  "RAID 0 verteilt die Daten nur auf mehrere Platten und erhöht damit den Durchsatz. Fällt eine Platte aus, ist der gesamte Verbund verloren.",
  "Which RAID level offers no fault tolerance at all?",
  ("RAID 0", "RAID 1", "RAID 5", "RAID 6"),
  "RAID 0 merely spreads the data across several disks and thereby raises throughput. If one disk fails, the whole array is lost."),

S("ap2-sto-r03",
  "Eine Vollsicherung läuft sonntags, danach täglich eine Sicherung aller Änderungen seit Sonntag. Welche Art ist das?",
  ("Differenzielle Sicherung", "Inkrementelle Sicherung",
   "Vollsicherung mit Kompression", "Reine Spiegelung des Bestands"), 0,
  "Die differenzielle Sicherung bezieht sich immer auf die letzte Vollsicherung und wächst deshalb bis zur nächsten an. Zum Zurückspielen genügen Vollsicherung plus die jüngste differenzielle.",
  "A full backup runs on Sunday, then daily a backup of all changes since Sunday. Which type is that?",
  ("Differential backup", "Incremental backup",
   "Full backup with compression", "Plain mirroring of the data"),
  "A differential backup always refers to the last full backup and therefore grows until the next one. To restore you need the full backup plus the most recent differential."),

S("ap2-sto-r04",
  "Welcher Speicheranschluss stellt Blockspeicher über ein normales IP-Netz bereit?",
  ("iSCSI", "NFS", "SMB", "FTP"), 0,
  "iSCSI transportiert SCSI-Kommandos über IP und liefert dem Server ein Blockgerät. NFS und SMB stellen dagegen Dateifreigaben bereit.",
  "Which storage connection provides block storage over an ordinary IP network?",
  ("iSCSI", "NFS", "SMB", "FTP"),
  "iSCSI carries SCSI commands over IP and gives the server a block device. NFS and SMB by contrast provide file shares."),

S("ap2-sto-r05",
  "Sechs Platten zu je 4 TB laufen als RAID 6. Wie viel Kapazität steht netto zur Verfügung?",
  ("16 TB", "20 TB", "24 TB", "12 TB"), 0,
  "RAID 6 legt doppelte Parität ab und verliert damit die Kapazität von zwei Platten. Aus 6 mal 4 TB bleiben 4 mal 4 TB nutzbar.",
  "Six disks of 4 TB each run as RAID 6. How much capacity is available net?",
  ("16 TB", "20 TB", "24 TB", "12 TB"),
  "RAID 6 stores double parity and therefore loses the capacity of two disks. From 6 times 4 TB, 4 times 4 TB remains usable."),

S("ap2-sto-r06",
  "Eine Ransomware hat auch die Sicherungen auf dem Netzlaufwerk verschlüsselt. Was hätte das verhindert?",
  ("Eine Sicherung ohne dauerhafte Netzverbindung",
   "Ein zusätzlicher Virenscanner auf dem Sicherungsserver",
   "Eine höhere Kompressionsstufe der Sicherungsdateien",
   "Eine kürzere Aufbewahrungsdauer der Sicherungen"), 0,
  "Was erreichbar ist, wird mitverschlüsselt. Ein Air Gap oder eine unveränderbare Ablage entzieht die Sicherung dem Zugriff des Angreifers.",
  "Ransomware has also encrypted the backups on the network share. What would have prevented that?",
  ("A backup without a permanent network connection",
   "An additional virus scanner on the backup server",
   "A higher compression level for the backup files",
   "A shorter retention period for the backups"),
  "Whatever is reachable gets encrypted too. An air gap or immutable storage removes the backup from the attacker's reach."),

S("ap2-sto-r07",
  "Welche Aussage über RAID 1 trifft zu?",
  ("Die Daten werden identisch auf zwei Platten geschrieben",
   "Die Daten werden ohne Redundanz auf zwei Platten verteilt",
   "Eine Platte speichert ausschließlich Paritätsinformation",
   "Es werden mindestens vier Platten dafür benötigt"), 0,
  "Die Spiegelung schreibt jeden Block doppelt und übersteht den Ausfall einer Platte. Der Preis ist, dass nur die Hälfte der Rohkapazität nutzbar bleibt.",
  "Which statement about RAID 1 is correct?",
  ("The data is written identically to two disks",
   "The data is spread across two disks without redundancy",
   "One disk stores parity information exclusively",
   "At least four disks are required for it"),
  "Mirroring writes every block twice and survives the failure of one disk. The price is that only half the raw capacity stays usable."),

S("ap2-sto-r08",
  "Wie viele Platten dürfen bei RAID 6 gleichzeitig ausfallen, ohne dass Daten verloren gehen?",
  ("2", "1", "3", "0"), 0,
  "Die doppelte Parität erlaubt den Ausfall zweier Platten. Das ist gerade bei großen Platten wichtig, weil ein Rebuild lange dauert und dabei eine weitere Platte ausfallen kann.",
  "How many disks may fail simultaneously in RAID 6 without data loss?",
  ("2", "1", "3", "0"),
  "The double parity allows two disks to fail. That matters especially with large disks because a rebuild takes long and another disk can fail during it."),

S("ap2-sto-r09",
  "Was beschreibt das Großvater-Vater-Sohn-Prinzip?",
  ("Eine gestaffelte Aufbewahrung täglicher, wöchentlicher und monatlicher Sicherungen",
   "Eine gleichmäßige Verteilung der Sicherung auf drei getrennte Standorte",
   "Eine Aufteilung der Daten auf drei getrennte Speichersysteme im Haus",
   "Eine abgestufte Vergabe von Rechten an drei verschiedene Benutzergruppen"), 0,
  "Das Generationenprinzip hält mehrere Stände unterschiedlicher Tiefe vor. So lässt sich auch ein Fehler zurückholen, der erst nach Wochen auffällt.",
  "What does the grandfather-father-son principle describe?",
  ("A staggered retention of daily, weekly and monthly backups",
   "An even distribution of the backup across three separate sites",
   "A split of the data across three separate in-house storage systems",
   "A graded assignment of rights to three different user groups"),
  "The generation principle keeps several states of different depth. That allows recovering from a fault noticed only weeks later."),

S("ap2-sto-r10",
  "Welche Sicherungsart braucht beim Zurückspielen die gesamte Kette seit der letzten Vollsicherung?",
  ("Die inkrementelle Sicherung", "Die differenzielle Sicherung",
   "Die Vollsicherung selbst", "Die Spiegelung auf ein zweites System"), 0,
  "Inkrementell sichert nur die Änderungen seit der letzten Sicherung gleich welcher Art. Das ist schnell beim Sichern, verlängert aber die Wiederherstellung.",
  "Which backup type needs the entire chain since the last full backup when restoring?",
  ("The incremental backup", "The differential backup",
   "The full backup itself", "Mirroring to a second system"),
  "Incremental backs up only changes since the last backup of any kind. That is fast when backing up but lengthens recovery."),

S("ap2-sto-r11",
  "Welches Speicherkonzept stellt Dateifreigaben über das Netz für mehrere Clients bereit?",
  ("NAS", "DAS", "SAN", "RAID"), 0,
  "Ein NAS liefert Dateien über Protokolle wie SMB oder NFS. DAS hängt direkt am Server, ein SAN liefert Blockspeicher über ein eigenes Netz.",
  "Which storage concept provides file shares over the network for several clients?",
  ("NAS", "DAS", "SAN", "RAID"),
  "A NAS delivers files via protocols such as SMB or NFS. DAS attaches directly to a server, and a SAN delivers block storage over its own network."),

S("ap2-sto-r12",
  "Eine Sicherung soll nachträglich nicht mehr verändert oder gelöscht werden können. Wie nennt man das?",
  ("Unveränderbare Sicherung", "Differenzielle Sicherung",
   "Komprimierte Sicherung", "Verteilte Sicherung"), 0,
  "Unveränderbare Ablagen setzen eine Sperrfrist, innerhalb derer selbst ein Administrator nichts löschen kann. Genau daran scheitert Ransomware, die Sicherungen mitverschlüsseln will.",
  "A backup must not be alterable or deletable afterwards. What is that called?",
  ("Immutable backup", "Differential backup",
   "Compressed backup", "Distributed backup"),
  "Immutable storage sets a retention lock within which not even an administrator can delete anything. This is exactly what defeats ransomware trying to encrypt backups."),

S("ap2-sto-r13",
  "Welche Kennzahl legt fest, wie lange die Wiederherstellung eines Dienstes höchstens dauern darf?",
  ("Recovery Time Objective", "Recovery Point Objective",
   "Total Cost of Ownership", "Mean Time To Repair"), 0,
  "Der RTO bemisst sich am Schaden je Stillstandsstunde und bestimmt, wie aufwendig die Wiederherstellungslösung ausfallen muss. Der RPO regelt dagegen den zulässigen Datenverlust.",
  "Which figure defines how long the recovery of a service may take at most?",
  ("Recovery time objective", "Recovery point objective",
   "Total cost of ownership", "Mean time to repair"),
  "The RTO derives from the damage per hour of downtime and determines how elaborate the recovery solution must be. The RPO governs permissible data loss."),

S("ap2-sto-r14",
  "Welches Verfahren speichert mehrfach vorkommende Datenblöcke nur einmal ab?",
  ("Deduplizierung", "Kompression", "Verschlüsselung", "Fragmentierung"), 0,
  "Deduplizierung erkennt identische Blöcke und verweist auf die vorhandene Kopie. Gerade bei vielen ähnlichen virtuellen Maschinen spart das enorm viel Platz.",
  "Which method stores repeatedly occurring data blocks only once?",
  ("Deduplication", "Compression", "Encryption", "Fragmentation"),
  "Deduplication recognises identical blocks and references the existing copy. Especially with many similar virtual machines this saves an enormous amount of space."),

S("ap2-sto-r15",
  "Zwei Rechenzentren spiegeln Daten mit Bestätigung vor dem Schreibabschluss. Wie heißt das Verfahren?",
  ("Synchrone Replikation", "Asynchrone Replikation",
   "Inkrementelle Sicherung", "Manuelle Archivierung"), 0,
  "Bei synchroner Replikation gilt ein Schreibvorgang erst als abgeschlossen, wenn beide Seiten bestätigt haben - der Datenverlust ist dadurch null. Der Preis ist die Empfindlichkeit gegenüber Entfernung und Latenz.",
  "Two data centres mirror data with acknowledgement before the write completes. What is this method called?",
  ("Synchronous replication", "Asynchronous replication",
   "Incremental backup", "Manual archiving"),
  "With synchronous replication a write counts as complete only once both sides acknowledge - data loss is therefore zero. The price is sensitivity to distance and latency."),

S("ap2-sto-r16",
  "Welches Speichermedium eignet sich am besten für die langfristige Archivierung großer Datenmengen?",
  ("Magnetband", "USB-Stick", "Speicherkarte", "Optisches Laufwerk"), 0,
  "Bänder sind preiswert je Terabyte, halten Jahrzehnte und liegen stromlos außerhalb der Reichweite von Angreifern. Flash-Speicher verliert über die Jahre seine Ladung.",
  "Which storage medium is best suited to long-term archiving of large data volumes?",
  ("Magnetic tape", "USB stick", "Memory card", "Optical drive"),
  "Tapes are cheap per terabyte, last decades and sit unpowered beyond an attacker's reach. Flash memory loses its charge over the years."),

S("ap2-sto-r17",
  "Welche Aussage über RAID 10 trifft zu?",
  ("Es kombiniert Spiegelung mit Aufteilung über mehrere Paare",
   "Es speichert Parität verteilt über alle beteiligten Platten",
   "Es benötigt mindestens drei Platten für den Betrieb",
   "Es bietet dieselbe Nettokapazität wie RAID 5"), 0,
  "RAID 10 spiegelt zuerst Plattenpaare und verteilt darüber die Daten. Das ergibt hohe Leistung und Ausfallsicherheit bei nur 50 Prozent Nettokapazität.",
  "Which statement about RAID 10 is correct?",
  ("It combines mirroring with striping across several pairs",
   "It stores parity distributed across all involved disks",
   "It requires at least three disks to operate",
   "It offers the same net capacity as RAID 5"),
  "RAID 10 first mirrors disk pairs and stripes across them. That yields high performance and fault tolerance at only 50 percent net capacity."),

S("ap2-sto-r18",
  "Wozu dient eine Hot-Spare-Platte in einem RAID-Verbund?",
  ("Sie springt bei einem Ausfall automatisch ein",
   "Sie erhöht im Normalbetrieb den Durchsatz",
   "Sie speichert eine zusätzliche Sicherungskopie",
   "Sie ersetzt die Paritätsinformation des Verbunds"), 0,
  "Die Reserveplatte läuft mit und wird bei einem Ausfall sofort in den Rebuild einbezogen. Das verkürzt die kritische Zeit, in der der Verbund ungeschützt ist.",
  "What is a hot spare disk in a RAID array for?",
  ("It steps in automatically when a disk fails",
   "It increases throughput during normal operation",
   "It stores an additional backup copy",
   "It replaces the array's parity information"),
  "The spare disk runs alongside and is immediately included in the rebuild on failure. That shortens the critical period in which the array is unprotected."),

S("ap2-sto-r19",
  "Die Sicherung läuft seit Jahren fehlerfrei, wurde aber nie zurückgespielt. Wie bewertest du das?",
  ("Ohne Rückspieltest ist die Sicherung ungeprüft",
   "Fehlerfreie Protokolle belegen die Wiederherstellbarkeit",
   "Die Dateigröße der Sicherung ist Beleg genug",
   "Ein Test ist erst nach einem Schadensfall sinnvoll"), 0,
  "Ein grünes Protokoll sagt nur, dass der Schreibvorgang durchlief. Ob die Daten vollständig und lesbar sind und wie lange die Wiederherstellung dauert, zeigt allein der Test.",
  "The backup has run without errors for years but was never restored. How do you judge that?",
  ("Without a restore test the backup is unverified",
   "Error-free logs prove that recovery will work",
   "The size of the backup file is proof enough",
   "A test only makes sense after an incident"),
  "A green log only says the write operation finished. Whether the data is complete and readable, and how long recovery takes, is shown only by the test."),

S("ap2-sto-r20",
  "Welches Netz verbindet Server und Speichersysteme über ein eigenes Hochgeschwindigkeitsnetz?",
  ("SAN", "LAN", "WAN", "WLAN"), 0,
  "Ein Storage Area Network stellt Blockspeicher bereit, klassisch über Fibre Channel. Für den Server sieht der zugewiesene Bereich aus wie eine lokale Platte.",
  "Which network connects servers and storage systems over a dedicated high-speed network?",
  ("SAN", "LAN", "WAN", "WLAN"),
  "A storage area network provides block storage, classically over fibre channel. To the server the assigned area looks like a local disk."),

S("ap2-sto-r21",
  "Eine Datenbank soll ohne Datenverlust wiederherstellbar sein. Welcher RPO ist gefordert?",
  ("Ein RPO von null", "Ein RPO von 24 Stunden",
   "Ein RPO von einer Woche", "Ein RPO ist dafür ohne Bedeutung"), 0,
  "Ein RPO von null verlangt synchrone Replikation oder durchgehende Protokollsicherung. Je näher der Wert an null rückt, desto steiler steigen die Kosten.",
  "A database must be recoverable without data loss. Which RPO is required?",
  ("An RPO of zero", "An RPO of 24 hours",
   "An RPO of one week", "An RPO is irrelevant for this"),
  "An RPO of zero requires synchronous replication or continuous log shipping. The closer the value moves to zero, the steeper the costs rise."),

S("ap2-sto-r22",
  "Welche Aussage über Archivierung im Unterschied zur Sicherung trifft zu?",
  ("Archivierung bewahrt Daten langfristig zur Nachweispflicht auf",
   "Archivierung dient der schnellen Wiederherstellung nach Ausfällen",
   "Archivierung ersetzt die tägliche Datensicherung vollständig",
   "Archivierung wird täglich überschrieben und erneuert"), 0,
  "Die Sicherung schützt vor Verlust und wird laufend überschrieben, das Archiv erfüllt Aufbewahrungspflichten über Jahre. Beides ist nicht gegeneinander austauschbar.",
  "Which statement about archiving as distinct from backup is correct?",
  ("Archiving preserves data long term for compliance purposes",
   "Archiving serves fast recovery after outages",
   "Archiving fully replaces the daily data backup",
   "Archiving is overwritten and renewed every day"),
  "Backup protects against loss and is continuously overwritten, while archiving fulfils retention obligations over years. The two are not interchangeable."),

S("ap2-sto-r23",
  "Ein RAID-5-Verbund meldet den Ausfall einer Platte. Was gilt jetzt?",
  ("Die Daten sind noch verfügbar, aber ungeschützt",
   "Die Daten sind bereits vollständig verloren",
   "Der Verbund arbeitet unverändert geschützt weiter",
   "Der Verbund verdoppelt automatisch seine Kapazität"), 0,
  "RAID 5 rekonstruiert die fehlenden Blöcke aus der Parität und läuft weiter. Bis der Rebuild abgeschlossen ist, führt jedoch ein zweiter Ausfall zum Totalverlust.",
  "A RAID 5 array reports the failure of one disk. What applies now?",
  ("The data is still available but unprotected",
   "The data is already completely lost",
   "The array continues protected without change",
   "The array automatically doubles its capacity"),
  "RAID 5 reconstructs the missing blocks from parity and keeps running. Until the rebuild finishes, however, a second failure causes total loss."),

S("ap2-sto-r24",
  "Welche Angabe beschreibt die Sicherungsfenster in einem Rechenzentrum?",
  ("Den Zeitraum, in dem Sicherungen laufen dürfen",
   "Die Größe der Sicherungsdateien auf dem Band",
   "Die Anzahl der aufbewahrten Sicherungsstände",
   "Den Ort, an dem die Sicherungen gelagert werden"), 0,
  "Das Sicherungsfenster begrenzt die Zeit, in der die Last vertretbar ist - meist nachts. Passt die Datenmenge nicht mehr hinein, braucht es inkrementelle Verfahren oder schnellere Medien.",
  "What does the backup window in a data centre describe?",
  ("The period in which backups are allowed to run",
   "The size of the backup files on the tape",
   "The number of retained backup generations",
   "The place where the backups are stored"),
  "The backup window limits the time in which the load is acceptable, usually at night. If the data volume no longer fits, incremental methods or faster media are needed."),

S("ap2-sto-r25",
  "Warum sollten Sicherungen verschlüsselt werden?",
  ("Weil sie außer Haus geraten und lesbar wären",
   "Weil die Wiederherstellung dadurch schneller läuft",
   "Weil die Sicherung dadurch weniger Platz braucht",
   "Weil das Band dadurch länger haltbar wird"), 0,
  "Eine Sicherung enthält den kompletten Datenbestand an einem transportablen Ort. Ohne Verschlüsselung wäre ein verlorenes Band eine vollständige Datenpanne.",
  "Why should backups be encrypted?",
  ("Because they leave the premises and would be readable",
   "Because recovery then runs noticeably faster",
   "Because the backup then needs less space",
   "Because the tape then lasts considerably longer"),
  "A backup holds the complete dataset in a transportable place. Without encryption a lost tape would be a full-scale data breach."),

S("ap2-sto-r26",
  "Welche Aussage über SMART-Werte einer Festplatte ist richtig?",
  ("Sie liefern Hinweise auf einen bevorstehenden Ausfall",
   "Sie geben die verbleibende freie Kapazität an",
   "Sie beschleunigen den lesenden Zugriff auf die Platte",
   "Sie ersetzen die Sicherung der gespeicherten Daten"), 0,
  "Die Selbstüberwachung meldet wachsende Fehlerzahlen und Temperaturprobleme frühzeitig. Wer sie überwacht, tauscht die Platte vor dem Ausfall statt danach.",
  "Which statement about a hard disk's SMART values is correct?",
  ("They give indications of an impending failure",
   "They state the remaining free capacity",
   "They speed up read access to the disk",
   "They replace the backup of the stored data"),
  "Self-monitoring reports rising error counts and temperature problems early. Whoever watches them replaces the disk before failure rather than after."),

S("ap2-sto-r27",
  "Wie viel Nettokapazität bleibt bei vier Platten zu je 3 TB im RAID 10?",
  ("6 TB", "12 TB", "9 TB", "3 TB"), 0,
  "RAID 10 spiegelt jedes Plattenpaar, es bleibt also die Hälfte der Rohkapazität. Aus 12 TB brutto werden damit 6 TB netto.",
  "How much net capacity remains with four disks of 3 TB each in RAID 10?",
  ("6 TB", "12 TB", "9 TB", "3 TB"),
  "RAID 10 mirrors every disk pair, so half the raw capacity remains. From 12 TB gross that leaves 6 TB net."),

S("ap2-sto-r28",
  "Ein Speichersystem legt oft genutzte Daten auf SSDs und selten genutzte auf Festplatten. Wie heißt das?",
  ("Tiering", "Spiegelung", "Deduplizierung", "Fragmentierung"), 0,
  "Automatisches Tiering verschiebt Daten je nach Zugriffshäufigkeit zwischen schnellen und günstigen Medien. So bleibt der teure Speicher den heißen Daten vorbehalten.",
  "A storage system places frequently used data on SSDs and rarely used data on hard disks. What is this called?",
  ("Tiering", "Mirroring", "Deduplication", "Fragmentation"),
  "Automatic tiering moves data between fast and cheap media according to access frequency. That reserves the expensive storage for hot data."),

S("ap2-sto-r29",
  "Welche Sicherungsart lässt sich am schnellsten zurückspielen?",
  ("Die Vollsicherung", "Die inkrementelle Sicherung",
   "Die differenzielle Sicherung", "Die synthetische Sicherung"), 0,
  "Die Vollsicherung enthält alles an einer Stelle und braucht keine weiteren Bestandteile. Sie dauert dafür beim Sichern am längsten und belegt den meisten Platz.",
  "Which backup type can be restored fastest?",
  ("The full backup", "The incremental backup",
   "The differential backup", "The synthetic backup"),
  "The full backup contains everything in one place and needs no further components. It takes longest to create, though, and occupies the most space."),

S("ap2-sto-r30",
  "Der Speicherbedarf wächst jährlich um 30 Prozent. Was folgt für die Beschaffung?",
  ("Das Wachstum wird in der Kapazitätsplanung berücksichtigt",
   "Es wird genau die heute benötigte Kapazität beschafft",
   "Die Sicherungsintervalle werden dafür verlängert",
   "Die Kompression ersetzt die zusätzliche Kapazität"), 0,
  "Speicher wird für die geplante Nutzungsdauer beschafft, nicht für den heutigen Stand. Ein System, das schon nach einem Jahr voll ist, verursacht ungeplante Kosten und Ausfälle.",
  "Storage demand grows by 30 percent per year. What follows for procurement?",
  ("The growth is factored into capacity planning",
   "Exactly today's required capacity is procured",
   "The backup intervals are extended for it",
   "Compression replaces the additional capacity"),
  "Storage is procured for the planned service life, not for today's level. A system that is full after a year causes unplanned costs and outages."),

S("ap2-sto-r31",
  "Welche Aussage über asynchrone Replikation trifft zu?",
  ("Die Zweitseite hinkt um einen kurzen Zeitraum hinterher",
   "Beide Seiten sind zu jedem Zeitpunkt exakt identisch",
   "Sie funktioniert nur innerhalb desselben Serverraums",
   "Sie schließt jeden denkbaren Datenverlust sicher aus"), 0,
  "Asynchron bestätigt die Primärseite sofort und überträgt danach. Das erlaubt große Entfernungen, nimmt aber einen kleinen möglichen Datenverlust in Kauf.",
  "Which statement about asynchronous replication is correct?",
  ("The secondary side lags by a short period",
   "Both sides are exactly identical at every moment",
   "It only works within the same server room",
   "It reliably rules out any conceivable data loss"),
  "Asynchronous acknowledges immediately on the primary side and transfers afterwards. That allows large distances but accepts a small possible data loss."),

S("ap2-sto-r32",
  "Welche Aussage über den Rebuild eines RAID-Verbunds ist zutreffend?",
  ("Während des Rebuilds ist der Verbund besonders gefährdet",
   "Während des Rebuilds sind die Daten nicht erreichbar",
   "Der Rebuild verdoppelt die Kapazität des Verbunds",
   "Der Rebuild ersetzt eine anschließende Datensicherung"), 0,
  "Der Rebuild liest alle verbliebenen Platten vollständig aus und belastet sie stark - genau dann fällt gern eine zweite aus. Bei großen Platten dauert das viele Stunden.",
  "Which statement about rebuilding a RAID array is correct?",
  ("During the rebuild the array is especially at risk",
   "During the rebuild the data is unreachable",
   "The rebuild doubles the capacity of the array",
   "The rebuild replaces a subsequent data backup"),
  "The rebuild reads all remaining disks in full and stresses them heavily - which is exactly when a second one tends to fail. With large disks this takes many hours."),

# -------------------------------------------------------------- multiple (32)
M("ap2-sto-r33",
  "Welche Aussagen über RAID 5 sind korrekt?",
  ("Es benötigt mindestens drei Festplatten",
   "Die Kapazität einer Platte geht für Parität verloren",
   "Der Ausfall einer Platte wird verkraftet",
   "Der Rebuild belastet die verbliebenen Platten stark",
   "Es verkraftet den Ausfall zweier Platten gleichzeitig",
   "Es bietet die volle Rohkapazität aller Platten"),
  (0, 1, 2, 3),
  "RAID 5 verteilt die Parität über alle Platten und übersteht genau einen Ausfall. Zwei gleichzeitige Ausfälle bedeuten Totalverlust - dafür gibt es RAID 6.",
  "Which statements about RAID 5 are correct?",
  ("It requires at least three hard disks",
   "One disk's capacity is lost to parity",
   "The failure of one disk is tolerated",
   "The rebuild heavily stresses the remaining disks",
   "It tolerates two disks failing simultaneously",
   "It offers the full raw capacity of all disks"),
  "RAID 5 spreads parity across all disks and survives exactly one failure. Two simultaneous failures mean total loss - that is what RAID 6 is for."),

M("ap2-sto-r34",
  "Welche Anforderungen stellt die 3-2-1-Regel an eine Sicherungsstrategie?",
  ("Drei Kopien der Daten insgesamt",
   "Zwei unterschiedliche Medientypen",
   "Eine Kopie an einem anderen Ort",
   "Schutz vor Ausfall eines einzelnen Mediums",
   "Drei Sicherungsläufe an jedem Werktag",
   "Alle Kopien im selben Serverraum"),
  (0, 1, 2, 3),
  "Drei Kopien, zwei Medientypen, eine auswärts - das deckt Einzelfehler, Medienschaden und Standortverlust ab. Alle Kopien am selben Ort teilen jedes Risiko.",
  "Which requirements does the 3-2-1 rule place on a backup strategy?",
  ("Three copies of the data in total",
   "Two different media types",
   "One copy at a different location",
   "Protection against failure of a single medium",
   "Three backup runs on every working day",
   "All copies in the same server room"),
  "Three copies, two media types, one off site - covering single failures, media damage and site loss. All copies in one place share every risk."),

M("ap2-sto-r35",
  "Welche Aussagen über die inkrementelle Sicherung sind zutreffend?",
  ("Sie sichert Änderungen seit der letzten Sicherung",
   "Sie ist beim Sichern besonders schnell",
   "Sie belegt am wenigsten Speicherplatz",
   "Die Wiederherstellung braucht die gesamte Kette",
   "Sie bezieht sich immer auf die letzte Vollsicherung",
   "Sie lässt sich ohne Vollsicherung zurückspielen"),
  (0, 1, 2, 3),
  "Inkrementell ist der sparsamste Weg beim Sichern und der aufwendigste beim Zurückspielen. Der Bezug auf die letzte Vollsicherung kennzeichnet dagegen die differenzielle Sicherung.",
  "Which statements about incremental backup are correct?",
  ("It backs up changes since the last backup",
   "It is particularly fast when backing up",
   "It occupies the least storage space",
   "Recovery needs the entire chain",
   "It always refers to the last full backup",
   "It can be restored without a full backup"),
  "Incremental is the most economical way to back up and the most laborious to restore. Referring to the last full backup characterises the differential backup instead."),

M("ap2-sto-r36",
  "Welche Maßnahmen schützen Sicherungen vor Ransomware?",
  ("Aufbewahrung ohne dauerhafte Netzverbindung",
   "Unveränderbare Ablage mit Sperrfrist",
   "Getrennte Zugangsdaten für das Sicherungssystem",
   "Eine Kopie außerhalb des Produktivstandorts",
   "Ablage auf einem dauerhaft verbundenen Netzlaufwerk",
   "Ein gemeinsames Administratorkonto für alle Systeme"),
  (0, 1, 2, 3),
  "Trennung, Unveränderbarkeit, eigene Zugangsdaten und ein zweiter Ort entziehen die Sicherung dem Zugriff. Ein dauerhaft verbundenes Laufwerk wird schlicht mitverschlüsselt.",
  "Which measures protect backups against ransomware?",
  ("Storage without a permanent network connection",
   "Immutable storage with a retention lock",
   "Separate credentials for the backup system",
   "A copy outside the production site",
   "Storage on a permanently connected network share",
   "One shared administrator account for all systems"),
  "Separation, immutability, dedicated credentials and a second location put the backup beyond reach. A permanently connected share simply gets encrypted too."),

M("ap2-sto-r37",
  "Welche Aussagen über ein SAN sind richtig?",
  ("Es stellt Blockspeicher für Server bereit",
   "Es nutzt häufig Fibre Channel oder iSCSI",
   "Der Server sieht den Bereich wie eine lokale Platte",
   "Es erlaubt zentrale Verwaltung des Speichers",
   "Es liefert Dateifreigaben über SMB an Clients",
   "Es ersetzt die Datensicherung der Server"),
  (0, 1, 2, 3),
  "Ein SAN liefert Blöcke, kein Dateisystem - das legt der Server selbst darauf an. Dateifreigaben sind Sache eines NAS, und Sicherung bleibt eine eigene Aufgabe.",
  "Which statements about a SAN are correct?",
  ("It provides block storage for servers",
   "It often uses fibre channel or iSCSI",
   "The server sees the area like a local disk",
   "It allows central management of storage",
   "It delivers SMB file shares to clients",
   "It replaces the servers' data backup"),
  "A SAN delivers blocks, not a file system - the server creates that itself. File shares are a NAS's job, and backup remains a separate task."),

M("ap2-sto-r38",
  "Welche Aussagen über Deduplizierung sind zutreffend?",
  ("Mehrfach vorkommende Blöcke werden einmal gespeichert",
   "Der Platzbedarf sinkt teils erheblich",
   "Bei ähnlichen virtuellen Maschinen wirkt sie besonders stark",
   "Sie erfordert zusätzliche Rechenleistung",
   "Sie erhöht die Ausfallsicherheit des Speichers",
   "Sie ersetzt die Verschlüsselung der Sicherung"),
  (0, 1, 2, 3),
  "Deduplizierung tauscht Rechenzeit gegen Speicherplatz und wirkt dort am stärksten, wo sich Daten stark ähneln. Mit Ausfallsicherheit und Vertraulichkeit hat sie nichts zu tun.",
  "Which statements about deduplication are correct?",
  ("Blocks occurring repeatedly are stored once",
   "Space requirements drop considerably at times",
   "It works especially well with similar virtual machines",
   "It requires additional processing power",
   "It increases the fault tolerance of the storage",
   "It replaces encryption of the backup"),
  "Deduplication trades processing time for storage space and works best where data is very similar. It has nothing to do with fault tolerance or confidentiality."),

M("ap2-sto-r39",
  "Welche Angaben braucht die Planung eines Sicherungskonzepts?",
  ("Der zulässige Datenverlust je System",
   "Die zulässige Wiederherstellungsdauer je System",
   "Die zu sichernde Datenmenge und ihr Wachstum",
   "Die geforderten Aufbewahrungsfristen",
   "Die Anzahl der Bildschirme im Rechenzentrum",
   "Die Lieblingsfarbe des Sicherungsverantwortlichen"),
  (0, 1, 2, 3),
  "RPO, RTO, Datenmenge und Aufbewahrung bestimmen Verfahren, Medien und Kosten. Ohne diese vier Werte lässt sich kein Konzept begründen.",
  "Which figures does planning a backup concept require?",
  ("The permissible data loss per system",
   "The permissible recovery time per system",
   "The data volume to back up and its growth",
   "The required retention periods",
   "The number of screens in the data centre",
   "The favourite colour of the backup administrator"),
  "RPO, RTO, data volume and retention determine method, media and cost. Without these four values no concept can be justified."),

M("ap2-sto-r40",
  "Welche Aussagen über Magnetbänder als Sicherungsmedium sind korrekt?",
  ("Sie sind je Terabyte vergleichsweise günstig",
   "Sie lassen sich stromlos lange lagern",
   "Sie bieten von Natur aus ein Air Gap",
   "Der wahlfreie Zugriff ist langsam",
   "Sie eignen sich gut als schneller Zwischenspeicher",
   "Sie verlieren nach wenigen Monaten ihre Daten"),
  (0, 1, 2, 3),
  "Bänder punkten bei Preis, Haltbarkeit und der physischen Trennung vom Netz. Ihr sequenzieller Zugriff macht sie für schnelle Einzelrestores allerdings unpraktisch.",
  "Which statements about magnetic tape as a backup medium are correct?",
  ("They are comparatively cheap per terabyte",
   "They can be stored unpowered for a long time",
   "They inherently provide an air gap",
   "Random access is slow",
   "They work well as a fast intermediate cache",
   "They lose their data after a few months"),
  "Tapes score on price, durability and physical separation from the network. Their sequential access makes them impractical for fast individual restores, though."),

M("ap2-sto-r41",
  "Welche Aussagen über RAID 1 sind zutreffend?",
  ("Die Daten liegen identisch auf zwei Platten",
   "Der Ausfall einer Platte wird verkraftet",
   "Die Nettokapazität beträgt die Hälfte der Rohkapazität",
   "Es sind mindestens zwei Platten erforderlich",
   "Die Nettokapazität entspricht der Summe beider Platten",
   "Es ersetzt die Sicherung der gespiegelten Daten"),
  (0, 1, 2, 3),
  "Spiegelung ist einfach und robust, kostet aber die Hälfte der Kapazität. Gelöschte Dateien werden allerdings auf beiden Platten gelöscht - deshalb bleibt die Sicherung nötig.",
  "Which statements about RAID 1 are correct?",
  ("The data lies identically on two disks",
   "The failure of one disk is tolerated",
   "Net capacity is half the raw capacity",
   "At least two disks are required",
   "Net capacity equals the sum of both disks",
   "It replaces the backup of the mirrored data"),
  "Mirroring is simple and robust but costs half the capacity. Deleted files are deleted on both disks, though - which is why backup remains necessary."),

M("ap2-sto-r42",
  "Welche Aussagen über Archivierung sind richtig?",
  ("Sie dient der langfristigen Aufbewahrung",
   "Gesetzliche Fristen bestimmen die Dauer",
   "Die Daten müssen lesbar bleiben",
   "Auch das Leseformat muss langfristig verfügbar sein",
   "Sie ersetzt die laufende Datensicherung",
   "Archivierte Daten dürfen jederzeit verändert werden"),
  (0, 1, 2, 3),
  "Ein Archiv muss über Jahrzehnte les- und nachweisbar bleiben, deshalb zählt neben dem Medium auch das Format. Veränderbarkeit widerspricht dem Nachweiszweck.",
  "Which statements about archiving are correct?",
  ("It serves long-term retention",
   "Statutory periods determine the duration",
   "The data has to stay readable",
   "The reading format must remain available long term",
   "It replaces ongoing data backup",
   "Archived data may be altered at any time"),
  "An archive must stay readable and evidential for decades, so format matters as much as medium. Mutability contradicts the evidential purpose."),

M("ap2-sto-r43",
  "Welche Aussagen über SSDs im Serverbetrieb sind zutreffend?",
  ("Sie liefern deutlich mehr Ein- und Ausgabeoperationen",
   "Sie haben keine mechanische Zugriffszeit",
   "Ihre Schreibzyklen sind begrenzt",
   "Ihr Zustand lässt sich über Kennwerte überwachen",
   "Sie eignen sich am besten zur stromlosen Archivierung",
   "Sie machen ein RAID grundsätzlich überflüssig"),
  (0, 1, 2, 3),
  "SSDs glänzen bei Zugriffen pro Sekunde, altern aber über Schreibzyklen. Für die stromlose Langzeitlagerung sind sie die schlechteste Wahl, und Ausfälle gibt es auch bei ihnen.",
  "Which statements about SSDs in server operation are correct?",
  ("They deliver far more input and output operations",
   "They have no mechanical seek time",
   "Their write cycles are limited",
   "Their health can be monitored via metrics",
   "They are best suited to unpowered archiving",
   "They fundamentally make RAID unnecessary"),
  "SSDs excel at operations per second but age through write cycles. For unpowered long-term storage they are the worst choice, and they fail too."),

M("ap2-sto-r44",
  "Welche Schritte gehören zu einem Wiederherstellungstest?",
  ("Ein definiertes System oder Datenpaket auswählen",
   "Die Wiederherstellung in einer Testumgebung durchführen",
   "Die Vollständigkeit der Daten prüfen",
   "Die benötigte Dauer messen und dokumentieren",
   "Die Wiederherstellung direkt über das Produktivsystem laufen lassen",
   "Auf eine Dokumentation des Ergebnisses verzichten"),
  (0, 1, 2, 3),
  "Der Test prüft Vollständigkeit und Dauer und liefert damit den Nachweis für RTO und RPO. Auf dem Produktivsystem zu testen riskiert genau den Schaden, den man verhindern will.",
  "Which steps belong to a recovery test?",
  ("Select a defined system or data set",
   "Perform the restore in a test environment",
   "Verify the completeness of the data",
   "Measure and document the time required",
   "Run the restore directly over the production system",
   "Skip documenting the result"),
  "The test verifies completeness and duration and thereby evidences RTO and RPO. Testing on production risks exactly the damage you are trying to prevent."),

M("ap2-sto-r45",
  "Welche Aussagen über synchrone und asynchrone Replikation sind korrekt?",
  ("Synchron bestätigt erst nach dem Schreiben auf beiden Seiten",
   "Synchron erreicht einen RPO von null",
   "Asynchron erlaubt größere Entfernungen",
   "Asynchron nimmt einen kleinen Datenverlust in Kauf",
   "Asynchron erreicht ebenfalls einen RPO von null",
   "Synchron ist unempfindlich gegenüber Latenz"),
  (0, 1, 2, 3),
  "Der Unterschied ist ein Handel zwischen Datenverlust und Entfernung: synchron kostet Latenz, asynchron kostet ein kleines Zeitfenster.",
  "Which statements about synchronous and asynchronous replication are correct?",
  ("Synchronous acknowledges only after writing on both sides",
   "Synchronous achieves an RPO of zero",
   "Asynchronous allows greater distances",
   "Asynchronous accepts a small data loss",
   "Asynchronous also achieves an RPO of zero",
   "Synchronous is insensitive to latency"),
  "The difference is a trade between data loss and distance: synchronous costs latency, asynchronous costs a small time window."),

M("ap2-sto-r46",
  "Welche Faktoren beeinflussen die Wahl des Speichersystems?",
  ("Benötigte Kapazität samt Wachstum",
   "Geforderte Ein- und Ausgabeleistung",
   "Anforderungen an die Verfügbarkeit",
   "Vorhandene Anbindung im Rechenzentrum",
   "Die Farbgestaltung der vorderen Gehäusefront",
   "Das Gewicht der mitgelieferten Transportverpackung"),
  (0, 1, 2, 3),
  "Kapazität, Leistung, Verfügbarkeit und Anbindung bestimmen die Auswahl und die Kosten. Äußerlichkeiten spielen keine Rolle.",
  "Which factors influence the choice of a storage system?",
  ("Required capacity including growth",
   "Required input and output performance",
   "Availability requirements",
   "Existing connectivity in the data centre",
   "The colour scheme of the front of the chassis",
   "The weight of the supplied transport packaging"),
  "Capacity, performance, availability and connectivity determine choice and cost. Externals play no role."),

M("ap2-sto-r47",
  "Welche Aussagen über die differenzielle Sicherung sind zutreffend?",
  ("Sie sichert alle Änderungen seit der letzten Vollsicherung",
   "Sie wächst bis zur nächsten Vollsicherung an",
   "Zum Zurückspielen genügen Vollsicherung und die jüngste differenzielle",
   "Sie ist beim Zurückspielen schneller als inkrementell",
   "Sie sichert nur Änderungen seit der letzten Sicherung",
   "Sie bleibt über die gesamte Woche hinweg konstant groß"),
  (0, 1, 2, 3),
  "Differenziell liegt zwischen voll und inkrementell: mehr Platz beim Sichern, dafür nur zwei Bestandteile beim Zurückspielen.",
  "Which statements about differential backup are correct?",
  ("It backs up all changes since the last full backup",
   "It grows until the next full backup",
   "Restoring needs the full backup and the latest differential",
   "It restores faster than incremental",
   "It backs up only changes since the last backup",
   "It stays constant in size across the entire week"),
  "Differential sits between full and incremental: more space when backing up, but only two components when restoring."),

M("ap2-sto-r48",
  "Welche Aussagen über Dateisystem-Snapshots sind richtig?",
  ("Sie halten einen Zustand zu einem Zeitpunkt fest",
   "Sie erlauben schnelle Rückkehr zu diesem Stand",
   "Sie belegen mit der Zeit zusätzlichen Platz",
   "Sie liegen auf demselben Speichersystem",
   "Sie ersetzen eine ausgelagerte Datensicherung",
   "Sie schützen vor dem Ausfall des Speichersystems"),
  (0, 1, 2, 3),
  "Snapshots sind schnell und praktisch, teilen aber das Schicksal des Speichersystems. Gegen dessen Ausfall hilft nur eine Kopie an anderer Stelle.",
  "Which statements about file system snapshots are correct?",
  ("They capture a state at a point in time",
   "They allow fast return to that state",
   "They occupy additional space over time",
   "They reside on the same storage system",
   "They replace an off-site data backup",
   "They protect against failure of the storage system"),
  "Snapshots are fast and practical but share the fate of the storage system. Only a copy elsewhere helps against its failure."),

M("ap2-sto-r49",
  "Welche Aussagen über die Wiederherstellungskennzahlen sind korrekt?",
  ("Der RPO beschreibt den zulässigen Datenverlust",
   "Der RTO beschreibt die zulässige Ausfallzeit",
   "Beide werden je System festgelegt",
   "Beide leiten sich aus dem Geschäftsbedarf ab",
   "Beide beschreiben denselben Sachverhalt",
   "Beide werden von der Hardware vorgegeben"),
  (0, 1, 2, 3),
  "RPO und RTO beantworten zwei verschiedene Fragen: wie viel darf verloren gehen und wie lange darf es dauern. Beide bemessen sich am Schaden für das Geschäft.",
  "Which statements about recovery metrics are correct?",
  ("The RPO describes permissible data loss",
   "The RTO describes permissible downtime",
   "Both are defined per system",
   "Both derive from business needs",
   "Both describe the same thing",
   "Both are dictated by the hardware"),
  "RPO and RTO answer two different questions: how much may be lost and how long may it take. Both are measured by the damage to the business."),

M("ap2-sto-r50",
  "Welche Aussagen über NAS-Systeme sind zutreffend?",
  ("Sie stellen Dateifreigaben im Netz bereit",
   "Sie nutzen Protokolle wie SMB oder NFS",
   "Sie lassen sich zentral verwalten",
   "Sie sind für viele Clients gleichzeitig gedacht",
   "Sie liefern rohen Blockspeicher genau wie ein SAN",
   "Sie brauchen zwingend eine Fibre-Channel-Anbindung"),
  (0, 1, 2, 3),
  "Ein NAS liefert fertige Dateisysteme über das normale Netz, ein SAN dagegen Blöcke über ein eigenes. Fibre Channel gehört zur SAN-Welt.",
  "Which statements about NAS systems are correct?",
  ("They provide file shares on the network",
   "They use protocols such as SMB or NFS",
   "They can be managed centrally",
   "They are intended for many clients at once",
   "They deliver raw block storage exactly like a SAN",
   "They strictly require a fibre channel connection"),
  "A NAS delivers ready file systems over the normal network, while a SAN delivers blocks over its own. Fibre channel belongs to the SAN world."),

M("ap2-sto-r51",
  "Welche Maßnahmen begrenzen die Dauer eines RAID-Rebuilds?",
  ("Kleinere statt sehr großer Einzelplatten",
   "Eine Hot Spare für den sofortigen Start",
   "Ausreichend Leistungsreserve im Verbund",
   "Regelmäßige Überwachung der Plattenzustände",
   "Möglichst viele Platten in einem einzigen Verbund",
   "Verzicht auf jede Überwachung zur Entlastung"),
  (0, 1, 2, 3),
  "Je größer die Platten und je breiter der Verbund, desto länger der Rebuild und desto größer das Risiko eines zweiten Ausfalls. Frühe Warnungen verkürzen die kritische Phase.",
  "Which measures limit the duration of a RAID rebuild?",
  ("Smaller rather than very large individual disks",
   "A hot spare for an immediate start",
   "Sufficient performance headroom in the array",
   "Regular monitoring of disk health",
   "As many disks as possible in a single array",
   "Doing without monitoring to reduce load"),
  "The larger the disks and the wider the array, the longer the rebuild and the greater the risk of a second failure. Early warnings shorten the critical phase."),

M("ap2-sto-r52",
  "Welche Aussagen über die Verschlüsselung von Sicherungen sind richtig?",
  ("Sie schützt ausgelagerte Medien vor Auslesen",
   "Der Schlüssel muss getrennt sicher verwahrt werden",
   "Ein verlorener Schlüssel bedeutet Datenverlust",
   "Sie ist bei Transport außer Haus besonders wichtig",
   "Sie ersetzt eine Zugriffsbeschränkung am Sicherungssystem",
   "Der Schlüssel gehört zusammen mit der Sicherung auf dasselbe Medium"),
  (0, 1, 2, 3),
  "Verschlüsselung ist erst mit durchdachter Schlüsselverwaltung wirksam. Den Schlüssel neben die Sicherung zu legen hebt den Schutz vollständig auf.",
  "Which statements about encrypting backups are correct?",
  ("It protects off-site media from being read",
   "The key must be kept safely and separately",
   "A lost key means data loss",
   "It matters especially for transport off site",
   "It replaces access restrictions on the backup system",
   "The key belongs on the same medium as the backup"),
  "Encryption is only effective with well-considered key management. Putting the key next to the backup cancels the protection entirely."),

M("ap2-sto-r53",
  "Welche Aussagen über RAID 10 sind zutreffend?",
  ("Es kombiniert Spiegelung und Aufteilung",
   "Es bietet hohe Leistung bei Schreibzugriffen",
   "Die Nettokapazität beträgt die Hälfte der Rohkapazität",
   "Es benötigt mindestens vier Platten",
   "Es speichert Paritätsinformationen verteilt",
   "Es bietet dieselbe Nettokapazität wie RAID 5"),
  (0, 1, 2, 3),
  "RAID 10 verzichtet auf Paritätsberechnung und ist deshalb beim Schreiben schnell - erkauft mit dem Verlust der halben Kapazität.",
  "Which statements about RAID 10 are correct?",
  ("It combines mirroring and striping",
   "It offers high performance on writes",
   "Net capacity is half the raw capacity",
   "It requires at least four disks",
   "It stores parity information distributed",
   "It offers the same net capacity as RAID 5"),
  "RAID 10 does without parity calculation and is therefore fast on writes - paid for with the loss of half the capacity."),

M("ap2-sto-r54",
  "Welche Angaben gehören in die Dokumentation einer Sicherungslösung?",
  ("Welche Systeme in welchem Rhythmus gesichert werden",
   "Wo die Sicherungen abgelegt werden",
   "Wie lange die Stände aufbewahrt werden",
   "Wie eine Wiederherstellung abläuft",
   "Die Passwörter des Sicherungssystems",
   "Die Anzahl der Kaffeetassen im Serverraum"),
  (0, 1, 2, 3),
  "Umfang, Ablageort, Aufbewahrung und Wiederherstellungsweg müssen auch für Vertretungen nachvollziehbar sein. Zugangsdaten gehören niemals in eine Dokumentation.",
  "Which details belong in the documentation of a backup solution?",
  ("Which systems are backed up at which frequency",
   "Where the backups are stored",
   "How long the generations are retained",
   "How a recovery is performed",
   "The passwords of the backup system",
   "The number of coffee cups in the server room"),
  "Scope, storage location, retention and the recovery path must be traceable for stand-ins too. Credentials never belong in documentation."),

M("ap2-sto-r55",
  "Was gehört zu einer tragfähigen Kapazitätsplanung von Speicher?",
  ("Das erwartete Wachstum wird einbezogen",
   "Die geplante Nutzungsdauer bestimmt die Reserve",
   "Die Auslastung wird laufend überwacht",
   "Schwellwerte lösen rechtzeitig eine Erweiterung aus",
   "Es wird genau die aktuelle Belegung beschafft",
   "Volle Datenträger sind betrieblich unproblematisch"),
  (0, 1, 2, 3),
  "Speicher wird für die Zukunft beschafft und laufend beobachtet. Ein vollgelaufener Datenträger legt Dienste zuverlässig lahm und gehört zu den häufigsten Ausfallursachen.",
  "Which statements about storage capacity planning are correct?",
  ("Expected growth is factored in",
   "The planned service life determines the reserve",
   "Utilisation is monitored continuously",
   "Thresholds trigger expansion in good time",
   "Exactly the current usage is procured",
   "Full disks are operationally harmless"),
  "Storage is procured for the future and continuously observed. A full disk reliably takes services down and is among the most frequent causes of outages."),

M("ap2-sto-r56",
  "Welche Aussagen über den Unterschied von Sicherung und Hochverfügbarkeit sind richtig?",
  ("Hochverfügbarkeit federt Hardwareausfälle ab",
   "Die Sicherung schützt vor gelöschten oder verschlüsselten Daten",
   "Beide Konzepte ergänzen einander",
   "Ein Cluster repliziert auch Fehler sofort auf alle Knoten",
   "Hochverfügbarkeit macht regelmäßige Sicherungen vollständig entbehrlich",
   "Eine Sicherung ersetzt jede Form von Redundanz im Betrieb"),
  (0, 1, 2, 3),
  "Redundanz hilft gegen Ausfall, Sicherung gegen Fehler und Angriffe. Wer nur eines von beidem hat, ist gegen die jeweils andere Ursache schutzlos.",
  "Which statements about the difference between backup and high availability are correct?",
  ("High availability cushions hardware failures",
   "Backup protects against deleted or encrypted data",
   "The two concepts complement each other",
   "A cluster replicates errors instantly to all nodes",
   "High availability makes regular backups entirely dispensable",
   "A backup replaces any form of redundancy in operation"),
  "Redundancy helps against outages, backup against mistakes and attacks. Having only one of the two leaves you defenceless against the other cause."),

M("ap2-sto-r57",
  "Welche Aussagen über Aufbewahrungsfristen sind zutreffend?",
  ("Gesetzliche Vorgaben bestimmen die Mindestdauer",
   "Nach Ablauf sind Daten zu löschen",
   "Fristen werden je Datenart festgelegt",
   "Auch Sicherungen fallen unter das Löschkonzept",
   "Alle Daten werden vorsichtshalber unbegrenzt aufbewahrt",
   "Löschungen dürfen nicht dokumentiert werden"),
  (0, 1, 2, 3),
  "Aufbewahren und Löschen sind zwei Seiten derselben Pflicht - und die Sicherungen sind der Punkt, an dem Löschkonzepte in der Praxis meist scheitern.",
  "Which statements about retention periods are correct?",
  ("Statutory requirements set the minimum duration",
   "After expiry the data has to be deleted",
   "Periods are defined per data type",
   "Backups fall under the deletion concept too",
   "All data is retained indefinitely as a precaution",
   "Deletions must not be documented"),
  "Retention and deletion are two sides of the same duty - and backups are where deletion concepts usually fail in practice."),

M("ap2-sto-r58",
  "Welche Aussagen über iSCSI sind korrekt?",
  ("Es transportiert SCSI-Kommandos über IP",
   "Es stellt dem Server Blockspeicher bereit",
   "Es nutzt vorhandene Netzwerkinfrastruktur",
   "Ein getrenntes Speichernetz verbessert die Leistung",
   "Es stellt fertige Dateifreigaben bereit",
   "Es benötigt zwingend Fibre-Channel-Hardware"),
  (0, 1, 2, 3),
  "iSCSI ist die günstige Alternative zu Fibre Channel, weil es auf vorhandenem Ethernet läuft. Für ernsthafte Last sollte der Speicherverkehr dennoch ein eigenes Netz bekommen.",
  "Which statements about iSCSI are correct?",
  ("It carries SCSI commands over IP",
   "It provides block storage to the server",
   "It uses existing network infrastructure",
   "A separate storage network improves performance",
   "It provides ready-made file shares",
   "It strictly requires fibre channel hardware"),
  "iSCSI is the affordable alternative to fibre channel because it runs on existing Ethernet. For serious load the storage traffic should still get its own network."),

M("ap2-sto-r59",
  "Welche Ursachen können zu Datenverlust führen?",
  ("Hardwaredefekt eines Datenträgers",
   "Versehentliches Löschen durch Nutzer",
   "Verschlüsselung durch Schadsoftware",
   "Fehlerhafte Änderungen an Anwendungen",
   "Eine zu große Bildschirmauflösung",
   "Eine zu lange Netzwerkkabellänge"),
  (0, 1, 2, 3),
  "Technik, Mensch, Angriff und Fehler sind die vier klassischen Ursachen - gegen jede einzelne hilft nur eine geprüfte Sicherung. Anzeige und Verkabelung spielen keine Rolle.",
  "Which causes can lead to data loss?",
  ("Hardware defect of a storage device",
   "Accidental deletion by users",
   "Encryption by malicious software",
   "Faulty changes to applications",
   "Too high a screen resolution",
   "Too long a network cable"),
  "Technology, people, attacks and mistakes are the four classic causes - and only a verified backup helps against each. Display and cabling play no role."),

M("ap2-sto-r60",
  "Welche Aussagen über Cloud-Sicherungen sind zutreffend?",
  ("Sie schaffen räumliche Trennung vom Standort",
   "Die Datenmenge bestimmt Dauer und Kosten",
   "Verschlüsselung vor der Übertragung ist sinnvoll",
   "Die Wiederherstellungsdauer ist einzuplanen",
   "Die Verantwortung für die Daten geht auf den Anbieter über",
   "Ein Rückspieltest erübrigt sich in der Cloud"),
  (0, 1, 2, 3),
  "Die Cloud liefert den zweiten Standort frei Haus, aber die Leitung begrenzt die Wiederherstellung. Verantwortung und Prüfpflicht bleiben beim Auftraggeber.",
  "Which statements about cloud backups are correct?",
  ("They create physical separation from the site",
   "The data volume determines duration and cost",
   "Encrypting before transfer is sensible",
   "Recovery duration has to be planned for",
   "Responsibility for the data passes to the provider",
   "A restore test is unnecessary in the cloud"),
  "The cloud delivers the second location for free, but the line limits recovery. Responsibility and the duty to verify stay with the customer."),

M("ap2-sto-r61",
  "Welche Aussagen über RAID 0 sind richtig?",
  ("Die Daten werden über mehrere Platten verteilt",
   "Der Durchsatz steigt gegenüber einer Einzelplatte",
   "Die volle Rohkapazität bleibt nutzbar",
   "Der Ausfall einer Platte zerstört den gesamten Verbund",
   "Es bietet Ausfallsicherheit durch verteilte Paritätsdaten",
   "Es eignet sich besonders gut für unersetzliche Datenbestände"),
  (0, 1, 2, 3),
  "RAID 0 tauscht Sicherheit gegen Tempo und Kapazität. Mit jeder zusätzlichen Platte steigt sogar die Wahrscheinlichkeit eines Totalverlusts.",
  "Which statements about RAID 0 are correct?",
  ("The data is striped across several disks",
   "Throughput rises compared with a single disk",
   "The full raw capacity stays usable",
   "The failure of one disk destroys the whole array",
   "It offers fault tolerance through distributed parity data",
   "It suits irreplaceable datasets particularly well"),
  "RAID 0 trades safety for speed and capacity. With every additional disk the probability of total loss actually rises."),

M("ap2-sto-r62",
  "Worauf achtet die Überwachung eines Speichersystems sinnvollerweise?",
  ("Freier Platz wird gegen Schwellwerte geprüft",
   "Zustandswerte der Datenträger werden ausgewertet",
   "Ausfälle im RAID lösen eine Meldung aus",
   "Erfolg und Dauer der Sicherungen werden überwacht",
   "Eine Meldung genügt, wenn niemand sie liest",
   "Überwachung ersetzt die Wiederherstellungstests"),
  (0, 1, 2, 3),
  "Platz, Plattenzustand, RAID-Status und Sicherungsergebnis sind die vier Werte, die zählen - vorausgesetzt, die Meldungen erreichen jemanden, der handelt.",
  "Which statements about monitoring storage systems are correct?",
  ("Free space is checked against thresholds",
   "Health values of the drives are evaluated",
   "RAID failures trigger an alert",
   "Success and duration of backups are monitored",
   "An alert suffices even if nobody reads it",
   "Monitoring replaces recovery testing"),
  "Space, drive health, RAID status and backup outcome are the four values that count - provided the alerts reach someone who acts."),

M("ap2-sto-r63",
  "Welche Aussagen über das Generationenprinzip sind korrekt?",
  ("Mehrere Sicherungsstände werden gestaffelt aufbewahrt",
   "Tägliche, wöchentliche und monatliche Stände greifen ineinander",
   "Auch ältere Fehler lassen sich damit zurückholen",
   "Die Aufbewahrungsdauer wird je Stufe festgelegt",
   "Es genügt, immer nur die letzte Sicherung zu behalten",
   "Alle Stände werden auf demselben Band überschrieben"),
  (0, 1, 2, 3),
  "Nur mehrere Generationen helfen gegen Fehler, die erst spät auffallen. Wer nur den letzten Stand hält, sichert einen bereits beschädigten Zustand.",
  "Which statements about the generation principle are correct?",
  ("Several backup generations are retained in a staggered way",
   "Daily, weekly and monthly generations interlock",
   "Older faults can be recovered from as well",
   "Retention is defined per level",
   "Keeping only the latest backup is sufficient",
   "All generations are overwritten on the same tape"),
  "Only several generations help against faults noticed late. Whoever keeps only the latest state backs up an already damaged one."),

M("ap2-sto-r64",
  "Welche Aussagen über Speicherprotokolle und ihre Einsatzgebiete sind zutreffend?",
  ("SMB und NFS liefern Dateifreigaben",
   "iSCSI und Fibre Channel liefern Blockspeicher",
   "Blockspeicher wird vom Server selbst formatiert",
   "Dateifreigaben bringen ihr Dateisystem bereits mit",
   "SMB liefert Blockspeicher an Datenbankserver",
   "Fibre Channel stellt Dateifreigaben für Clients bereit"),
  (0, 1, 2, 3),
  "Die entscheidende Trennlinie verläuft zwischen Block und Datei: Blockspeicher bekommt sein Dateisystem vom Server, eine Freigabe bringt es mit.",
  "Which statements about storage protocols and their uses are correct?",
  ("SMB and NFS deliver file shares",
   "iSCSI and fibre channel deliver block storage",
   "Block storage is formatted by the server itself",
   "File shares already bring their own file system",
   "SMB delivers block storage to database servers",
   "Fibre channel provides file shares for clients"),
  "The decisive dividing line runs between block and file: block storage gets its file system from the server, a share brings its own."),

# ------------------------------------------------------------------ text (36)
T("ap2-sto-r65", "Wie viel Nettokapazität bieten fünf Platten zu je 2 TB im RAID 5, in TB?", "8",
  "Eine Platte geht für die Parität verloren, es bleiben also 4 mal 2 TB nutzbar.",
  "How much net capacity do five 2 TB disks provide in RAID 5, in TB?", "8",
  "One disk is lost to parity, leaving 4 times 2 TB usable."),

T("ap2-sto-r66", "Wie viele Platten dürfen bei RAID 6 gleichzeitig ausfallen?", "2",
  "Die doppelte Parität schützt auch dann noch, wenn während eines langen Rebuilds eine weitere Platte ausfällt.",
  "How many disks may fail simultaneously in RAID 6?", "2",
  "Double parity still protects when another disk fails during a long rebuild."),

T("ap2-sto-r67", "Wie viele Festplatten benötigt RAID 5 mindestens?", "3",
  "Zwei Platten tragen Daten, die Kapazität einer dritten geht für die verteilte Parität verloren.",
  "How many hard disks does RAID 5 require at minimum?", "3",
  "Two disks carry data while one disk's worth of capacity is lost to distributed parity."),

T("ap2-sto-r68", "Welche Sicherungsart erfasst alle Änderungen seit der letzten Vollsicherung?", "Differenzielle Sicherung",
  "Sie wächst bis zur nächsten Vollsicherung, braucht zum Zurückspielen aber nur zwei Bestandteile.",
  "Which backup type captures all changes since the last full backup?", "Differential backup",
  "It grows until the next full backup but needs only two components to restore."),

T("ap2-sto-r69", "Welche Kennzahl beschreibt den maximal zulässigen Datenverlust?", "RPO",
  "Das Recovery Point Objective bestimmt unmittelbar den nötigen Abstand zwischen zwei Sicherungen.",
  "Which figure describes the maximum permissible data loss?", "RPO",
  "The recovery point objective directly determines the required interval between backups."),

T("ap2-sto-r70", "Wie nennt man eine Sicherung, die physisch vom Netz getrennt aufbewahrt wird?", "Air Gap",
  "Was nicht erreichbar ist, kann auch nicht von Ransomware mitverschlüsselt werden.",
  "What is a backup kept physically disconnected from the network called?", "Air gap",
  "What cannot be reached cannot be encrypted by ransomware either."),

T("ap2-sto-r71", "Welches Verfahren speichert identische Datenblöcke nur ein einziges Mal?", "Deduplizierung",
  "Bei vielen ähnlichen virtuellen Maschinen spart das einen erheblichen Teil des Speicherplatzes.",
  "Which method stores identical data blocks only once?", "Deduplication",
  "With many similar virtual machines this saves a considerable share of the storage space."),

T("ap2-sto-r72", "Wie viel Prozent der Rohkapazität bleiben bei RAID 1 nutzbar?", "50",
  "Jeder Block wird doppelt geschrieben, damit halbiert sich die nutzbare Kapazität.",
  "What percentage of the raw capacity stays usable in RAID 1?", "50",
  "Every block is written twice, which halves the usable capacity."),

T("ap2-sto-r73", "Welches Speicherkonzept liefert Blockspeicher über ein eigenes Hochgeschwindigkeitsnetz?", "SAN",
  "Der Server legt darauf sein eigenes Dateisystem an, anders als bei einer Freigabe.",
  "Which storage concept delivers block storage over a dedicated high-speed network?", "SAN",
  "The server creates its own file system on it, unlike with a share."),

T("ap2-sto-r74", "Welches Protokoll transportiert SCSI-Kommandos über ein IP-Netz?", "iSCSI",
  "Es ist die günstige Alternative zu Fibre Channel, weil es vorhandenes Ethernet nutzt.",
  "Which protocol carries SCSI commands over an IP network?", "iSCSI",
  "It is the affordable alternative to fibre channel because it uses existing Ethernet."),

T("ap2-sto-r75", "Wie nennt man die Reserveplatte, die bei einem Ausfall automatisch einspringt?", "Hot Spare",
  "Sie verkürzt die Zeit, in der der Verbund ohne Redundanz läuft.",
  "What is the spare disk that automatically steps in on failure called?", "Hot spare",
  "It shortens the period in which the array runs without redundancy."),

T("ap2-sto-r76", "Wie viele Kopien verlangt die 3-2-1-Regel insgesamt?", "3",
  "Auf zwei unterschiedlichen Medientypen, davon eine an einem anderen Ort.",
  "How many copies does the 3-2-1 rule require in total?", "3",
  "On two different media types, one of them at a different location."),

T("ap2-sto-r77", "Welche Kennzahl legt fest, wie lange die Wiederherstellung dauern darf?", "RTO",
  "Sie bemisst sich am Schaden je Stunde Stillstand und bestimmt den Aufwand der Lösung.",
  "Which figure defines how long recovery may take?", "RTO",
  "It is measured by the damage per hour of downtime and determines the effort of the solution."),

T("ap2-sto-r78", "Wie nennt man eine Sicherung, die innerhalb einer Sperrfrist nicht löschbar ist?", "Unveränderbare Sicherung",
  "Auf Englisch immutable Backup - selbst ein Administrator kommt während der Frist nicht daran.",
  "What is a backup that cannot be deleted within a retention lock called?", "Immutable backup",
  "Not even an administrator can touch it during the lock period."),

T("ap2-sto-r79", "Wie viele Platten braucht RAID 10 mindestens?", "4",
  "Zwei gespiegelte Paare, über die anschließend die Daten verteilt werden.",
  "How many disks does RAID 10 require at minimum?", "4",
  "Two mirrored pairs across which the data is then striped."),

T("ap2-sto-r80", "Welches Speichermedium eignet sich am besten zur stromlosen Langzeitarchivierung?", "Magnetband",
  "Es hält Jahrzehnte, ist je Terabyte günstig und liegt außerhalb der Reichweite von Angreifern.",
  "Which storage medium is best suited to unpowered long-term archiving?", "Magnetic tape",
  "It lasts decades, is cheap per terabyte and sits beyond the reach of attackers."),

T("ap2-sto-r81", "Welches Verfahren verschiebt selten genutzte Daten automatisch auf günstigere Medien?", "Tiering",
  "So bleibt der teure schnelle Speicher den häufig gelesenen Daten vorbehalten.",
  "Which method automatically moves rarely used data to cheaper media?", "Tiering",
  "That reserves the expensive fast storage for frequently read data."),

T("ap2-sto-r82", "Wie viel Nettokapazität bleibt bei acht Platten zu je 1 TB im RAID 6, in TB?", "6",
  "Zwei Platten gehen für die doppelte Parität verloren, es bleiben also 6 TB nutzbar.",
  "How much net capacity remains with eight 1 TB disks in RAID 6, in TB?", "6",
  "Two disks are lost to double parity, leaving 6 TB usable."),

T("ap2-sto-r83", "Welche Replikationsart bestätigt erst nach dem Schreiben auf beiden Seiten?", "Synchrone Replikation",
  "Sie erreicht einen RPO von null, reagiert dafür empfindlich auf Entfernung und Latenz.",
  "Which replication type acknowledges only after writing on both sides?", "Synchronous replication",
  "It achieves an RPO of zero but reacts sensitively to distance and latency."),

T("ap2-sto-r84", "Wie nennt man den Zeitraum, in dem Sicherungen laufen dürfen?", "Sicherungsfenster",
  "Passt die Datenmenge nicht mehr hinein, braucht es inkrementelle Verfahren oder schnellere Medien.",
  "What is the period in which backups may run called?", "Backup window",
  "If the data volume no longer fits, incremental methods or faster media are needed."),

T("ap2-sto-r85", "Welche Selbstüberwachung meldet den bevorstehenden Ausfall einer Festplatte?", "SMART",
  "Sie liefert Werte zu Fehlerzahlen, Betriebsstunden und Temperatur als Frühwarnung.",
  "Which self-monitoring feature reports an impending hard disk failure?", "SMART",
  "It supplies values on error counts, operating hours and temperature as an early warning."),

T("ap2-sto-r86", "Welches RAID-Level bietet Geschwindigkeit, aber keinerlei Ausfallsicherheit?", "RAID 0",
  "Fällt eine einzige Platte aus, ist der gesamte Verbund verloren.",
  "Which RAID level offers speed but no fault tolerance at all?", "RAID 0",
  "If a single disk fails, the whole array is lost."),

T("ap2-sto-r87", "Wie nennt man das gestaffelte Aufbewahren täglicher, wöchentlicher und monatlicher Stände?", "Generationenprinzip",
  "Auch Großvater-Vater-Sohn genannt. Es holt auch Fehler zurück, die erst nach Wochen auffallen.",
  "What is the staggered retention of daily, weekly and monthly generations called?", "Generation principle",
  "Also called grandfather-father-son. It recovers even faults noticed only weeks later."),

T("ap2-sto-r88", "Welche Sicherungsart kommt beim Zurückspielen ohne weitere Bestandteile aus?", "Vollsicherung",
  "Sie enthält den gesamten Bestand an einer Stelle, dauert dafür beim Sichern am längsten.",
  "Which backup type needs no further components when restoring?", "Full backup",
  "It holds the entire dataset in one place but takes longest to create."),

T("ap2-sto-r89", "Welches Speicherkonzept stellt Dateifreigaben über SMB oder NFS bereit?", "NAS",
  "Anders als ein SAN liefert es fertige Dateisysteme statt roher Blöcke.",
  "Which storage concept provides file shares over SMB or NFS?", "NAS",
  "Unlike a SAN it delivers ready file systems instead of raw blocks."),

T("ap2-sto-r90", "Wie viel Prozent der Rohkapazität bleiben bei RAID 10 nutzbar?", "50",
  "Jedes Plattenpaar wird gespiegelt, damit halbiert sich die nutzbare Kapazität.",
  "What percentage of raw capacity stays usable in RAID 10?", "50",
  "Every disk pair is mirrored, which halves the usable capacity."),

T("ap2-sto-r91", "Welcher Vorgang stellt nach einem Plattentausch die Redundanz im RAID wieder her?", "Rebuild",
  "Er liest alle verbliebenen Platten vollständig aus - genau dann fällt gern eine zweite aus.",
  "Which process restores redundancy in a RAID after a disk replacement?", "Rebuild",
  "It reads all remaining disks in full - which is exactly when a second one tends to fail."),

T("ap2-sto-r92", "Welche Sicherungsart braucht zum Zurückspielen die gesamte Kette seit der Vollsicherung?", "Inkrementelle Sicherung",
  "Sie ist beim Sichern am schnellsten und beim Wiederherstellen am aufwendigsten.",
  "Which backup type needs the whole chain since the full backup to restore?", "Incremental backup",
  "It is fastest to create and most laborious to restore."),

T("ap2-sto-r93", "Was muss regelmäßig getestet werden, damit eine Sicherung als geprüft gilt?", "Die Wiederherstellung",
  "Ein fehlerfreies Protokoll belegt nur den Schreibvorgang, nicht die Lesbarkeit der Daten.",
  "What must be tested regularly for a backup to count as verified?", "The recovery",
  "An error-free log only evidences the write operation, not the readability of the data."),

T("ap2-sto-r94", "Wie nennt man die langfristige Aufbewahrung zur Erfüllung von Nachweispflichten?", "Archivierung",
  "Anders als die Sicherung wird sie nicht überschrieben und muss über Jahre lesbar bleiben.",
  "What is long-term retention to fulfil compliance obligations called?", "Archiving",
  "Unlike a backup it is not overwritten and must stay readable for years."),

T("ap2-sto-r95", "Wie viel Nettokapazität bieten zwei Platten zu je 4 TB im RAID 1, in TB?", "4",
  "Die Spiegelung schreibt alles doppelt, es bleibt also die Kapazität einer Platte.",
  "How much net capacity do two 4 TB disks provide in RAID 1, in TB?", "4",
  "Mirroring writes everything twice, leaving the capacity of one disk."),

T("ap2-sto-r96", "Welche Replikationsart erlaubt große Entfernungen bei kleinem möglichen Datenverlust?", "Asynchrone Replikation",
  "Die Primärseite bestätigt sofort und überträgt danach, weshalb Latenz kaum stört.",
  "Which replication type allows large distances with a small possible data loss?", "Asynchronous replication",
  "The primary side acknowledges immediately and transfers afterwards, so latency barely matters."),

T("ap2-sto-r97", "Welchen RPO verlangt eine Datenbank, die keinen Datenverlust hinnehmen darf?", "0",
  "Ein RPO von null erfordert synchrone Replikation oder durchgehende Protokollsicherung.",
  "Which RPO does a database that must tolerate no data loss require?", "0",
  "An RPO of zero requires synchronous replication or continuous log shipping."),

T("ap2-sto-r98", "Wie viele unterschiedliche Medientypen verlangt die 3-2-1-Regel?", "2",
  "Zwei Typen schützen davor, dass ein systematischer Medienfehler alle Kopien gleichzeitig trifft.",
  "How many different media types does the 3-2-1 rule require?", "2",
  "Two types protect against a systematic media fault hitting all copies at once."),

T("ap2-sto-r99", "Wie nennt man den Zustand eines RAID-Verbunds nach dem Ausfall einer Platte?", "Degraded",
  "Die Daten sind noch verfügbar, aber ungeschützt - ein zweiter Ausfall wäre der Totalverlust.",
  "What is the state of a RAID array after one disk has failed called?", "Degraded",
  "The data is still available but unprotected - a second failure would mean total loss."),

T("ap2-sto-r100", "Welches Speichermedium liefert die meisten Ein- und Ausgabeoperationen pro Sekunde?", "SSD",
  "Ohne mechanische Zugriffszeit erreicht sie ein Vielfaches der Werte einer Festplatte.",
  "Which storage medium delivers the most input and output operations per second?", "SSD",
  "Without mechanical seek time it reaches many times the values of a hard disk."),
]

build("ap2-speicher-backup.json", "Speicher & Backup", "Storage & Backup", Q)
