#!/usr/bin/env python3
"""AP1 Wirtschaft & Projektmanagement - 100 handgeschriebene Fragen."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from qlib import S, M, T, build

Q = [
# ---------------------------------------------------------------- single (32)
S("ap1-wpm-r01",
  "Ein Kunde bestellt zu den Bedingungen eines Angebots. Wann kommt der Kaufvertrag zustande?",
  ("Mit der Annahme des Angebots durch die Bestellung",
   "Erst mit dem Eingang der Ware beim Kunden",
   "Erst mit der Bezahlung der gestellten Rechnung",
   "Erst mit der schriftlichen Auftragsbestätigung"), 0,
  "Ein Vertrag entsteht durch zwei übereinstimmende Willenserklärungen. Bestellt der Kunde unverändert zum Angebot, ist das die Annahme - Lieferung und Zahlung sind bereits Erfüllung des Vertrags.",
  "A customer orders on the terms of an offer. When is the sales contract concluded?",
  ("On acceptance of the offer through the order",
   "Only when the goods arrive at the customer",
   "Only when the issued invoice is paid",
   "Only with the written order confirmation"),
  "A contract arises from two matching declarations of intent. If the customer orders unchanged from the offer, that is acceptance - delivery and payment are already performance of the contract."),

S("ap1-wpm-r02",
  "Eine Rechnung über 5000 Euro bietet 2 Prozent Skonto. Wie hoch ist der Skontobetrag?",
  ("100 Euro", "50 Euro", "200 Euro", "250 Euro"), 0,
  "2 Prozent von 5000 Euro sind 100 Euro. Skonto lohnt sich fast immer, weil der auf das Jahr gerechnete Zinsvorteil deutlich über üblichen Kreditzinsen liegt.",
  "An invoice for 5000 euros offers a 2 percent early payment discount. How large is the discount?",
  ("100 euros", "50 euros", "200 euros", "250 euros"),
  "2 percent of 5000 euros is 100 euros. Such discounts almost always pay off because the annualised benefit clearly exceeds normal credit interest."),

S("ap1-wpm-r03",
  "Welche Rechtsform beschränkt die Haftung der Gesellschafter auf die Einlage?",
  ("Die GmbH", "Die OHG", "Das Einzelunternehmen", "Die Gesellschaft bürgerlichen Rechts"), 0,
  "Bei der GmbH haftet grundsätzlich nur das Gesellschaftsvermögen. Bei OHG, GbR und Einzelunternehmen haften die Beteiligten dagegen auch mit ihrem Privatvermögen.",
  "Which legal form limits the shareholders' liability to their capital contribution?",
  ("The limited liability company", "The general partnership",
   "The sole proprietorship", "The civil law partnership"),
  "With a limited liability company only the company's assets are generally liable. In partnerships and sole proprietorships the participants are also liable with their private assets."),

S("ap1-wpm-r04",
  "Ein Projekt liegt im Zeitplan zurück. Nach dem magischen Dreieck: was folgt daraus zwangsläufig?",
  ("Kosten oder Leistungsumfang müssen angepasst werden",
   "Die Projektleitung muss ausgetauscht werden",
   "Das Projekt gilt automatisch als gescheitert",
   "Die Qualitätssicherung wird ersatzlos gestrichen"), 0,
  "Zeit, Kosten und Leistung hängen zusammen: wer an einer Ecke zieht, verändert die anderen. Mehr Personal kostet mehr, weniger Umfang spart Zeit - Streichen der Qualitätssicherung ist keine dieser Stellschrauben.",
  "A project is behind schedule. According to the project triangle, what follows inevitably?",
  ("Cost or scope has to be adjusted",
   "The project management has to be replaced",
   "The project counts as failed automatically",
   "Quality assurance is dropped without replacement"),
  "Time, cost and scope are connected: pulling one corner changes the others. More staff costs more, less scope saves time - dropping quality assurance is not one of these levers."),

S("ap1-wpm-r05",
  "Wie berechnet sich der Deckungsbeitrag je Stück?",
  ("Verkaufspreis minus variable Stückkosten",
   "Verkaufspreis minus Fixkosten je Periode",
   "Umsatz minus Gewinn der Periode",
   "Selbstkosten minus Materialeinzelkosten"), 0,
  "Der Deckungsbeitrag zeigt, was jedes verkaufte Stück zur Deckung der Fixkosten beisteuert. Erst wenn alle Fixkosten gedeckt sind, entsteht Gewinn.",
  "How is the contribution margin per unit calculated?",
  ("Selling price minus variable unit costs",
   "Selling price minus fixed costs per period",
   "Revenue minus profit of the period",
   "Total cost minus direct material cost"),
  "The contribution margin shows what each unit sold contributes to covering fixed costs. Only once all fixed costs are covered does profit arise."),

S("ap1-wpm-r06",
  "Ein Vorgang im Netzplan hat einen Puffer von null. Was bedeutet das?",
  ("Er liegt auf dem kritischen Pfad",
   "Er kann beliebig nach hinten verschoben werden",
   "Er ist bereits vollständig abgeschlossen",
   "Er verursacht keine Kosten im Projekt"), 0,
  "Ohne Puffer verschiebt jede Verzögerung dieses Vorgangs direkt den Endtermin. Die Kette solcher Vorgänge bildet den kritischen Pfad und braucht besondere Aufmerksamkeit.",
  "An activity in the network plan has zero float. What does that mean?",
  ("It lies on the critical path",
   "It can be postponed arbitrarily",
   "It has already been fully completed",
   "It causes no costs in the project"),
  "Without float, any delay to this activity directly moves the end date. The chain of such activities forms the critical path and needs particular attention."),

S("ap1-wpm-r07",
  "Ein Lieferant liefert trotz Mahnung nicht zum vereinbarten Termin. Welcher Fall liegt vor?",
  ("Lieferverzug", "Zahlungsverzug", "Sachmangel", "Annahmeverzug"), 0,
  "Beim Lieferverzug bleibt die Leistung nach Fälligkeit und Mahnung aus. Der Käufer kann dann Nachfrist setzen, vom Vertrag zurücktreten oder Schadenersatz verlangen.",
  "A supplier fails to deliver by the agreed date despite a reminder. Which case applies?",
  ("Delivery default", "Payment default", "Material defect", "Default of acceptance"),
  "In delivery default the performance is missing after the due date and a reminder. The buyer can then set a grace period, withdraw from the contract or claim damages."),

S("ap1-wpm-r08",
  "Der Listeneinkaufspreis beträgt 1000 Euro, der Lieferant gewährt 10 Prozent Rabatt. Wie hoch ist der Zieleinkaufspreis?",
  ("900 Euro", "1000 Euro", "990 Euro", "1100 Euro"), 0,
  "Vom Listeneinkaufspreis wird zuerst der Rabatt abgezogen: 1000 minus 100 ergibt 900 Euro. Erst danach folgen Skonto und Bezugskosten in der Bezugskalkulation.",
  "The list purchase price is 1000 euros and the supplier grants a 10 percent trade discount. What is the target purchase price?",
  ("900 euros", "1000 euros", "990 euros", "1100 euros"),
  "The trade discount is deducted from the list price first: 1000 minus 100 gives 900 euros. Only then follow early payment discount and inbound costs in the purchase calculation."),

S("ap1-wpm-r09",
  "Welche Kosten fallen unabhängig von der produzierten Menge an?",
  ("Fixkosten", "Variable Kosten", "Einzelkosten", "Grenzkosten"), 0,
  "Miete, Versicherung und Gehälter laufen weiter, auch wenn nichts produziert wird. Variable Kosten wie Material steigen dagegen mit jeder zusätzlichen Einheit.",
  "Which costs arise regardless of the quantity produced?",
  ("Fixed costs", "Variable costs", "Direct costs", "Marginal costs"),
  "Rent, insurance and salaries continue even when nothing is produced. Variable costs such as materials rise with every additional unit."),

S("ap1-wpm-r10",
  "Ein Projekt soll in überschaubare Teilaufgaben zerlegt werden. Welches Werkzeug nutzt du?",
  ("Den Projektstrukturplan", "Den Netzplan mit Pufferzeiten",
   "Das Balkendiagramm nach Gantt", "Die Nutzwertanalyse der Angebote"), 0,
  "Der Projektstrukturplan gliedert das Projekt hierarchisch bis auf Arbeitspakete herunter und ist die Grundlage für Termin- und Kostenplanung. Netzplan und Balkenplan bauen darauf auf.",
  "A project is to be broken down into manageable subtasks. Which tool do you use?",
  ("The work breakdown structure", "The network plan with float times",
   "The Gantt bar chart", "The utility analysis of the offers"),
  "The work breakdown structure divides the project hierarchically down to work packages and is the basis for schedule and cost planning. Network plan and bar chart build on it."),

S("ap1-wpm-r11",
  "Welche Aussage beschreibt einen Meilenstein im Projekt zutreffend?",
  ("Ein Ereignis ohne Dauer, das einen Zwischenstand markiert",
   "Ein besonders langes Arbeitspaket im Projektplan",
   "Ein Puffer, der Verzögerungen im Ablauf ausgleicht",
   "Eine zusätzliche Reserve im Projektbudget"), 0,
  "Meilensteine haben die Dauer null und markieren erreichte Zwischenergebnisse - ideal als Entscheidungspunkt, ob das Projekt so weiterlaufen soll.",
  "Which statement correctly describes a milestone in a project?",
  ("An event with no duration marking an interim state",
   "A particularly long work package in the plan",
   "A buffer compensating delays in the sequence",
   "An additional reserve in the project budget"),
  "Milestones have zero duration and mark achieved interim results - ideal as a decision point on whether the project should continue as planned."),

S("ap1-wpm-r12",
  "Bei welcher Organisationsform erhält ein Mitarbeiter Anweisungen von genau einer Stelle?",
  ("Der Einlinienorganisation", "Der Matrixorganisation",
   "Der Mehrlinienorganisation", "Der Projektorganisation mit Doppelunterstellung"), 0,
  "Die Einlinienorganisation kennt einen eindeutigen Dienstweg und vermeidet Weisungskonflikte, ist dafür aber schwerfällig. Matrix und Mehrlinie erlauben mehrere Vorgesetzte.",
  "In which organisational form does an employee receive instructions from exactly one authority?",
  ("The single-line organisation", "The matrix organisation",
   "The multi-line organisation", "Project organisation with dual reporting"),
  "The single-line organisation has one clear chain of command and avoids conflicting instructions but is cumbersome. Matrix and multi-line forms allow several superiors."),

S("ap1-wpm-r13",
  "Zwei Angebote unterscheiden sich in Preis, Service und Lieferzeit. Womit vergleichst du sie sachgerecht?",
  ("Mit einer Nutzwertanalyse mit gewichteten Kriterien",
   "Ausschließlich anhand des niedrigsten Angebotspreises",
   "Anhand der Reihenfolge des Angebotseingangs",
   "Anhand der Anzahl der Seiten im Angebotsschreiben"), 0,
  "Die Nutzwertanalyse macht weiche Kriterien vergleichbar, indem sie gewichtet und bewertet. Der reine Preisvergleich ignoriert Folgekosten und Servicequalität.",
  "Two offers differ in price, service and delivery time. How do you compare them properly?",
  ("With a utility analysis using weighted criteria",
   "Solely by the lowest quoted price",
   "By the order in which the offers arrived",
   "By the number of pages in the offer letter"),
  "A utility analysis makes soft criteria comparable by weighting and scoring them. A pure price comparison ignores follow-on costs and service quality."),

S("ap1-wpm-r14",
  "Ein neues System kostet 30000 Euro und spart jährlich 10000 Euro. Wie lange dauert die Amortisation?",
  ("3 Jahre", "2 Jahre", "4 Jahre", "5 Jahre"), 0,
  "Investition geteilt durch jährlichen Rückfluss: 30000 durch 10000 ergibt 3 Jahre. Danach wirkt die Einsparung als Gewinn.",
  "A new system costs 30000 euros and saves 10000 euros per year. How long is the payback period?",
  ("3 years", "2 years", "4 years", "5 years"),
  "Investment divided by annual return: 30000 divided by 10000 gives 3 years. After that the saving works as profit."),

S("ap1-wpm-r15",
  "Welche Aufgabe hat ein Lastenheft im Beschaffungsprozess?",
  ("Es beschreibt die Anforderungen des Auftraggebers",
   "Es beschreibt die technische Umsetzung des Anbieters",
   "Es dokumentiert die Abnahme der gelieferten Leistung",
   "Es regelt die Zahlungsbedingungen des Vertrags"), 0,
  "Das Lastenheft nennt das Was und macht Angebote überhaupt vergleichbar. Das Wie beschreibt der Anbieter im Pflichtenheft.",
  "What is the purpose of a requirements specification in procurement?",
  ("It describes the client's requirements",
   "It describes the vendor's technical implementation",
   "It documents acceptance of the delivered service",
   "It governs the payment terms of the contract"),
  "The requirements specification states the what and is what makes offers comparable at all. The how is described by the vendor in the functional specification."),

S("ap1-wpm-r16",
  "Ab welcher Absatzmenge erwirtschaftet ein Unternehmen Gewinn?",
  ("Ab Überschreiten der Gewinnschwelle",
   "Ab dem ersten verkauften Stück",
   "Sobald der Umsatz die variablen Kosten deckt",
   "Sobald der Lagerbestand vollständig geräumt ist"), 0,
  "An der Gewinnschwelle decken die Deckungsbeiträge genau die Fixkosten. Jedes weitere Stück bringt seinen vollen Deckungsbeitrag als Gewinn.",
  "From which sales volume does a company generate profit?",
  ("Once the break-even point is exceeded",
   "From the very first unit sold",
   "As soon as revenue covers the variable costs",
   "As soon as the stock is completely cleared"),
  "At break-even the contribution margins exactly cover the fixed costs. Every further unit brings its full contribution margin as profit."),

S("ap1-wpm-r17",
  "Ein Kunde reklamiert nach vier Wochen einen Mangel an einem gelieferten Server. Was steht ihm zunächst zu?",
  ("Nacherfüllung durch Reparatur oder Ersatzlieferung",
   "Sofortige Rückabwicklung des gesamten Vertrags",
   "Sofortige Auszahlung von Schadenersatz",
   "Eine Verlängerung der Zahlungsfrist um vier Wochen"), 0,
  "Das Gesetz räumt dem Verkäufer zuerst die Nacherfüllung ein. Erst wenn diese fehlschlägt, kommen Minderung, Rücktritt oder Schadenersatz in Betracht.",
  "A customer complains about a defect in a delivered server after four weeks. What is he entitled to first?",
  ("Subsequent performance by repair or replacement",
   "Immediate reversal of the entire contract",
   "Immediate payment of damages",
   "An extension of the payment deadline by four weeks"),
  "The law grants the seller subsequent performance first. Only if that fails do price reduction, withdrawal or damages come into play."),

S("ap1-wpm-r18",
  "Wofür steht die Abkürzung ROI in der Wirtschaftlichkeitsbetrachtung?",
  ("Return on Investment", "Rate of Interest", "Risk of Implementation", "Range of Income"), 0,
  "Der ROI setzt den Gewinn ins Verhältnis zum eingesetzten Kapital und macht Investitionen unterschiedlicher Größe vergleichbar.",
  "What does the abbreviation ROI stand for in profitability analysis?",
  ("Return on investment", "Rate of interest", "Risk of implementation", "Range of income"),
  "The ROI relates profit to the capital employed and makes investments of different sizes comparable."),

S("ap1-wpm-r19",
  "Ein Unternehmen überlegt, die IT-Wartung extern zu vergeben. Wie heißt diese Entscheidung?",
  ("Make-or-Buy-Entscheidung", "Break-even-Analyse",
   "Deckungsbeitragsrechnung", "Nutzwertanalyse der Standorte"), 0,
  "Bei Make or Buy wird verglichen, ob Eigenleistung oder Fremdbezug günstiger und strategisch sinnvoller ist. Neben Kosten zählen Know-how und Abhängigkeit vom Anbieter.",
  "A company considers outsourcing its IT maintenance. What is this decision called?",
  ("Make-or-buy decision", "Break-even analysis",
   "Contribution margin accounting", "Utility analysis of locations"),
  "Make or buy compares whether in-house work or external purchase is cheaper and strategically wiser. Besides cost, know-how and vendor dependency matter."),

S("ap1-wpm-r20",
  "Was regelt ein Service Level Agreement?",
  ("Messbare Zusagen zu Verfügbarkeit und Reaktionszeit",
   "Die Höhe des Grundgehalts der Beschäftigten",
   "Die technische Bauweise der gelieferten Geräte",
   "Die Reihenfolge der Bestellungen im Einkauf"), 0,
  "Ein SLA macht Servicequalität überprüfbar: Verfügbarkeit in Prozent, Reaktions- und Wiederherstellungszeiten, oft mit Vertragsstrafen bei Verfehlung.",
  "What does a service level agreement govern?",
  ("Measurable commitments on availability and response time",
   "The level of the employees' base salary",
   "The technical construction of the delivered devices",
   "The order in which purchase orders are processed"),
  "An SLA makes service quality verifiable: availability in percent, response and recovery times, often with penalties for missing them."),

S("ap1-wpm-r21",
  "Welche Personen oder Gruppen bezeichnet man im Projekt als Stakeholder?",
  ("Alle, die vom Projekt betroffen sind oder es beeinflussen",
   "Ausschließlich die Mitglieder des Projektteams",
   "Ausschließlich die Anteilseigner des Unternehmens",
   "Ausschließlich die Lieferanten der Hardware"), 0,
  "Zu den Stakeholdern zählen Auftraggeber, Nutzer, Betriebsrat, Lieferanten und Betroffene. Wer sie früh einbindet, vermeidet Widerstand im späteren Verlauf.",
  "Which people or groups are called stakeholders in a project?",
  ("Everyone affected by the project or influencing it",
   "Only the members of the project team",
   "Only the shareholders of the company",
   "Only the suppliers of the hardware"),
  "Stakeholders include the client, users, works council, suppliers and those affected. Involving them early avoids resistance later on."),

S("ap1-wpm-r22",
  "Der Lagerbestand erreicht den Meldebestand. Was löst das aus?",
  ("Eine Bestellung, damit die Lieferzeit überbrückt wird",
   "Eine sofortige Inventur des gesamten Lagers",
   "Eine Preissenkung für die betroffene Ware",
   "Eine Aussonderung der verbliebenen Bestände"), 0,
  "Der Meldebestand ist so bemessen, dass der Rest bis zur Lieferung reicht - er berechnet sich aus Tagesverbrauch mal Lieferzeit plus Sicherheitsbestand.",
  "The stock level reaches the reorder point. What does that trigger?",
  ("An order so that the delivery time is bridged",
   "An immediate stocktake of the entire warehouse",
   "A price reduction for the affected goods",
   "A disposal of the remaining stock"),
  "The reorder point is set so that the remainder lasts until delivery - it is calculated from daily consumption times lead time plus safety stock."),

S("ap1-wpm-r23",
  "Ein Projektauftrag nennt weder Budget noch Termin. Was ist die Folge?",
  ("Erfolg und Fortschritt bleiben unüberprüfbar",
   "Das Projekt wird dadurch nachweislich günstiger",
   "Die Motivation im Team steigt messbar an",
   "Die Qualität der Ergebnisse verbessert sich"), 0,
  "Ohne messbare Ziele lässt sich weder steuern noch abnehmen. Deshalb gehören Ziele, Budget, Termin und Verantwortlichkeiten in jeden Projektauftrag.",
  "A project charter states neither budget nor deadline. What is the consequence?",
  ("Success and progress remain unverifiable",
   "The project becomes demonstrably cheaper",
   "Motivation in the team rises measurably",
   "The quality of the results improves"),
  "Without measurable goals there is nothing to steer by and nothing to accept against. That is why goals, budget, deadline and responsibilities belong in every project charter."),

S("ap1-wpm-r24",
  "Was versteht man unter Gemeinkosten?",
  ("Kosten, die sich nicht direkt einem Produkt zurechnen lassen",
   "Kosten, die nur bei Überstunden zusätzlich entstehen",
   "Kosten, die ausschließlich im Vertrieb anfallen",
   "Kosten, die von allen Abteilungen gemeinsam beantragt werden"), 0,
  "Miete, Verwaltung und Energie lassen sich keinem einzelnen Auftrag zuordnen und werden über Zuschlagssätze verteilt. Einzelkosten wie Material gehören dagegen direkt zum Produkt.",
  "What are overhead costs?",
  ("Costs that cannot be assigned directly to a product",
   "Costs that arise additionally only during overtime",
   "Costs that occur exclusively in the sales department",
   "Costs jointly requested by all departments"),
  "Rent, administration and energy cannot be assigned to a single order and are allocated via overhead rates. Direct costs such as materials belong to the product directly."),

S("ap1-wpm-r25",
  "Welches Dokument hält am Projektende die gewonnenen Erkenntnisse fest?",
  ("Der Abschlussbericht mit den Lessons Learned",
   "Der Projektstrukturplan aus der Startphase",
   "Das Lastenheft des ursprünglichen Auftraggebers",
   "Der Netzplan mit den berechneten Pufferzeiten"), 0,
  "Ohne Auswertung wiederholt die Organisation dieselben Fehler im nächsten Projekt. Der Abschlussbericht hält fest, was gut lief und was künftig anders laufen soll.",
  "Which document records the insights gained at the end of a project?",
  ("The closing report with the lessons learned",
   "The work breakdown structure from the start phase",
   "The requirements specification of the original client",
   "The network plan with the calculated float times"),
  "Without a review the organisation repeats the same mistakes in the next project. The closing report records what went well and what should change in future."),

S("ap1-wpm-r26",
  "Ein Anbieter senkt den Preis erst nach Auftragserteilung. Wie heißt der nachträgliche Preisnachlass?",
  ("Bonus", "Rabatt", "Skonto", "Provision"), 0,
  "Der Bonus wird nachträglich gewährt, meist umsatzabhängig zum Jahresende. Rabatt gilt sofort, Skonto belohnt schnelle Zahlung und Provision entlohnt Vermittlung.",
  "A vendor lowers the price only after the order is placed. What is this subsequent reduction called?",
  ("Bonus", "Trade discount", "Cash discount", "Commission"),
  "A bonus is granted retrospectively, usually revenue-dependent at year end. A trade discount applies immediately, cash discount rewards fast payment and commission pays for brokerage."),

S("ap1-wpm-r27",
  "Die Fixkosten betragen 20000 Euro, der Deckungsbeitrag je Stück 50 Euro. Wo liegt die Gewinnschwelle?",
  ("Bei 400 Stück", "Bei 200 Stück", "Bei 500 Stück", "Bei 1000 Stück"), 0,
  "Fixkosten geteilt durch Deckungsbeitrag: 20000 durch 50 ergibt 400 Stück. Ab dem 401. Stück entsteht Gewinn.",
  "Fixed costs are 20000 euros and the contribution margin per unit is 50 euros. Where is the break-even point?",
  ("At 400 units", "At 200 units", "At 500 units", "At 1000 units"),
  "Fixed costs divided by contribution margin: 20000 divided by 50 gives 400 units. From the 401st unit onward profit arises."),

S("ap1-wpm-r28",
  "Warum wird in Projekten eine Risikoanalyse durchgeführt?",
  ("Um Gefahren früh zu erkennen und Gegenmaßnahmen zu planen",
   "Um die Verantwortung auf einzelne Personen abzuwälzen",
   "Um den Projektauftrag nachträglich zu erweitern",
   "Um die Anzahl der Projektbesprechungen zu erhöhen"), 0,
  "Bewertet werden Eintrittswahrscheinlichkeit und Schadenshöhe; daraus entstehen Maßnahmen und Reserven. Früh erkannte Risiken kosten deutlich weniger als eingetretene.",
  "Why is a risk analysis carried out in projects?",
  ("To spot dangers early and plan countermeasures",
   "To shift responsibility onto individual people",
   "To extend the project charter retrospectively",
   "To increase the number of project meetings"),
  "Probability of occurrence and extent of damage are assessed, producing measures and reserves. Risks spotted early cost far less than risks that materialise."),

S("ap1-wpm-r29",
  "Welche Aussage über Leasing im Vergleich zum Kauf trifft zu?",
  ("Die Liquidität wird geschont, dafür steigen die Gesamtkosten",
   "Das Eigentum geht sofort auf den Leasingnehmer über",
   "Die monatliche Belastung entfällt vollständig",
   "Wartung und Reparatur sind immer ausgeschlossen"), 0,
  "Leasing verteilt die Belastung auf Raten und schont das Kapital, kostet über die Laufzeit aber meist mehr als der Kauf. Eigentümer bleibt der Leasinggeber.",
  "Which statement about leasing compared with buying is correct?",
  ("Liquidity is preserved but total costs rise",
   "Ownership passes to the lessee immediately",
   "The monthly burden disappears entirely",
   "Maintenance and repair are always excluded"),
  "Leasing spreads the burden across instalments and preserves capital but usually costs more than buying over the term. The lessor remains the owner."),

S("ap1-wpm-r30",
  "Ein Auftrag wächst im Verlauf immer weiter, ohne dass Budget angepasst wird. Wie heißt dieses Problem?",
  ("Scope Creep", "Break-even", "Deckungsbeitrag", "Meilenstein-Trendanalyse"), 0,
  "Scope Creep beschreibt das schleichende Anwachsen des Leistungsumfangs. Dagegen hilft ein definierter Änderungsprozess, der jede Erweiterung bewertet und freigibt.",
  "An assignment keeps growing during the project without the budget being adjusted. What is this problem called?",
  ("Scope creep", "Break-even", "Contribution margin", "Milestone trend analysis"),
  "Scope creep describes the gradual growth of the scope of work. A defined change process that assesses and approves every extension counters it."),

S("ap1-wpm-r31",
  "Welche Größe gibt an, wie viele Tage ein Vorgang ohne Folgen verschoben werden darf?",
  ("Die Pufferzeit", "Die Vorgangsdauer", "Der frühestmögliche Anfangszeitpunkt", "Der späteste Endzeitpunkt"), 0,
  "Der Puffer ergibt sich aus der Differenz zwischen spätester und frühester Lage eines Vorgangs. Ist er null, liegt der Vorgang auf dem kritischen Pfad.",
  "Which figure states how many days an activity may be postponed without consequences?",
  ("The float time", "The activity duration", "The earliest start date", "The latest finish date"),
  "Float is the difference between the latest and earliest position of an activity. If it is zero, the activity lies on the critical path."),

S("ap1-wpm-r32",
  "Ein Betrieb schult Auszubildende nach einem festgelegten Plan. Wie heißt dieses Dokument?",
  ("Der betriebliche Ausbildungsplan", "Der Tarifvertrag der Branche",
   "Die Betriebsvereinbarung zur Arbeitszeit", "Das Arbeitszeugnis am Ende"), 0,
  "Der betriebliche Ausbildungsplan überträgt den Ausbildungsrahmenplan auf die konkreten Abteilungen und Zeiträume des Betriebs.",
  "A company trains apprentices according to a defined plan. What is this document called?",
  ("The company training plan", "The industry collective agreement",
   "The works agreement on working hours", "The reference letter at the end"),
  "The company training plan transfers the general training framework onto the specific departments and periods of the company."),

# -------------------------------------------------------------- multiple (32)
M("ap1-wpm-r33",
  "Welche Bestandteile gehören in ein vollständiges Angebot?",
  ("Genaue Beschreibung der Leistung", "Preis und Preisbestandteile",
   "Liefer- und Zahlungsbedingungen", "Bindefrist des Angebots",
   "Das Privatvermögen des Anbieters", "Die Urlaubsplanung des Vertriebs"),
  (0, 1, 2, 3),
  "Leistung, Preis, Bedingungen und Bindefrist machen ein Angebot annahmefähig und vergleichbar. Interna des Anbieters gehören nicht hinein.",
  "Which elements belong in a complete offer?",
  ("Precise description of the service", "Price and price components",
   "Delivery and payment terms", "Period of validity of the offer",
   "The vendor's private assets", "The holiday planning of the sales team"),
  "Service, price, terms and validity make an offer acceptable and comparable. The vendor's internal matters do not belong there."),

M("ap1-wpm-r34",
  "Welche Größen bilden das magische Dreieck des Projektmanagements?",
  ("Zeit", "Kosten", "Leistung beziehungsweise Qualität",
   "Ihre gegenseitige Abhängigkeit", "Die Anzahl der Besprechungen", "Die Größe des Besprechungsraums"),
  (0, 1, 2, 3),
  "Zeit, Kosten und Leistung stehen in Wechselwirkung: keine Ecke lässt sich ändern, ohne die anderen zu berühren. Genau diese Abhängigkeit macht das Dreieck aus.",
  "Which factors form the magic triangle of project management?",
  ("Time", "Cost", "Scope or quality",
   "Their mutual dependency", "The number of meetings", "The size of the meeting room"),
  "Time, cost and scope interact: no corner can be changed without touching the others. This dependency is exactly what the triangle expresses."),

M("ap1-wpm-r35",
  "Welche Rechte hat ein Käufer bei einem Sachmangel?",
  ("Nacherfüllung verlangen", "Vom Vertrag zurücktreten",
   "Den Kaufpreis mindern", "Schadenersatz fordern",
   "Die Ware behalten und gar nichts zahlen", "Den Verkäufer zur Namensänderung zwingen"),
  (0, 1, 2, 3),
  "Das Gesetz sieht eine Stufenfolge vor: zuerst Nacherfüllung, danach Rücktritt, Minderung oder Schadenersatz. Ware behalten ohne Zahlung ist keine dieser Möglichkeiten.",
  "Which rights does a buyer have in the case of a material defect?",
  ("Demand subsequent performance", "Withdraw from the contract",
   "Reduce the purchase price", "Claim damages",
   "Keep the goods and pay nothing at all", "Force the seller to change its name"),
  "The law provides a sequence: subsequent performance first, then withdrawal, price reduction or damages. Keeping the goods without paying is none of these options."),

M("ap1-wpm-r36",
  "Welche Angaben braucht man für die Berechnung des Meldebestands?",
  ("Durchschnittlicher Tagesverbrauch", "Wiederbeschaffungszeit in Tagen",
   "Sicherheitsbestand für Störungen", "Die daraus errechnete Bestellgrenze",
   "Die Farbe der Lagerregale", "Die Anzahl der Lagermitarbeiter"),
  (0, 1, 2, 3),
  "Tagesverbrauch mal Wiederbeschaffungszeit plus Sicherheitsbestand ergibt den Meldebestand. Damit reicht der Rest bis zur nächsten Lieferung.",
  "Which figures are needed to calculate the reorder point?",
  ("Average daily consumption", "Replenishment lead time in days",
   "Safety stock for disruptions", "The resulting order threshold",
   "The colour of the warehouse shelves", "The number of warehouse staff"),
  "Daily consumption times lead time plus safety stock gives the reorder point. The remaining stock then lasts until the next delivery."),

M("ap1-wpm-r37",
  "Welche Kostenarten zählen zu den variablen Kosten?",
  ("Material für die gefertigten Stücke", "Fertigungslöhne nach Stückzahl",
   "Energie für laufende Maschinen", "Verpackung je ausgeliefertem Stück",
   "Miete für die Betriebshalle", "Versicherungsprämie des Gebäudes"),
  (0, 1, 2, 3),
  "Variable Kosten steigen mit der Ausbringungsmenge, fixe laufen mengenunabhängig weiter. Miete und Versicherung fallen auch bei Stillstand an.",
  "Which cost types count as variable costs?",
  ("Material for the units produced", "Piece-rate production wages",
   "Energy for running machines", "Packaging per unit shipped",
   "Rent for the production hall", "Insurance premium for the building"),
  "Variable costs rise with output while fixed costs continue regardless of quantity. Rent and insurance apply even during a standstill."),

M("ap1-wpm-r38",
  "Welche Schritte gehören zur Bezugskalkulation eines Einkaufs?",
  ("Rabatt vom Listeneinkaufspreis abziehen", "Skonto vom Zieleinkaufspreis abziehen",
   "Bezugskosten hinzurechnen", "Den Bezugspreis als Ergebnis ermitteln",
   "Den erwarteten Gewinn aufschlagen", "Die Mehrwertsteuer des Kunden abziehen"),
  (0, 1, 2, 3),
  "Die Bezugskalkulation führt vom Listenpreis über Rabatt, Skonto und Bezugskosten zum Bezugspreis. Gewinnaufschlag und Kundensteuer gehören in die Verkaufskalkulation.",
  "Which steps belong to the purchase price calculation?",
  ("Deduct the trade discount from the list price", "Deduct cash discount from the target price",
   "Add the inbound freight and handling costs", "Determine the purchase price as the result",
   "Add the expected profit margin", "Deduct the customer's value added tax"),
  "The purchase calculation runs from list price through trade discount, cash discount and inbound costs to the purchase price. Profit margin and customer tax belong in the sales calculation."),

M("ap1-wpm-r39",
  "Welche Aufgaben hat die Projektleitung?",
  ("Das Projekt planen und steuern", "Den Fortschritt regelmäßig überwachen",
   "Zwischen Auftraggeber und Team vermitteln", "Risiken erkennen und behandeln",
   "Die Gehälter der Teammitglieder festlegen", "Die Bilanz des Unternehmens erstellen"),
  (0, 1, 2, 3),
  "Planen, steuern, kommunizieren und Risiken beherrschen sind der Kern der Projektleitung. Gehalt und Bilanz liegen in der Linienorganisation beziehungsweise im Rechnungswesen.",
  "Which tasks does project management have?",
  ("Plan and steer the project", "Monitor progress regularly",
   "Mediate between client and team", "Identify and handle risks",
   "Set the salaries of the team members", "Prepare the company balance sheet"),
  "Planning, steering, communicating and managing risks form the core of project management. Salaries and the balance sheet belong to line management and accounting."),

M("ap1-wpm-r40",
  "Welche Merkmale kennzeichnen ein Projekt gegenüber der Linienarbeit?",
  ("Es ist zeitlich befristet", "Es verfolgt ein einmaliges Ziel",
   "Es hat begrenzte Ressourcen", "Es ist abteilungsübergreifend organisiert",
   "Es wiederholt sich in gleicher Form täglich", "Es kommt ohne jede Planung aus"),
  (0, 1, 2, 3),
  "Befristung, Einmaligkeit, begrenzte Mittel und interdisziplinäre Zusammensetzung unterscheiden Projekte von Routinearbeit. Wiederholende Tätigkeit ist gerade kein Projekt.",
  "Which characteristics distinguish a project from routine line work?",
  ("It is limited in time", "It pursues a unique goal",
   "It has limited resources", "It is organised across departments",
   "It repeats in identical form every day", "It manages without any planning"),
  "Time limitation, uniqueness, limited means and interdisciplinary composition distinguish projects from routine work. Repetitive activity is precisely not a project."),

M("ap1-wpm-r41",
  "Welche Kriterien fließen in eine Nutzwertanalyse für Lieferanten ein?",
  ("Preis der angebotenen Leistung", "Zugesagte Lieferzeit",
   "Umfang und Qualität des Services", "Erfahrungen aus früheren Aufträgen",
   "Die Schriftart im Angebotsschreiben", "Der Vorname des Vertriebsmitarbeiters"),
  (0, 1, 2, 3),
  "Bewertet werden gewichtete Sachkriterien wie Preis, Termin, Service und Zuverlässigkeit. Rein formale oder persönliche Merkmale haben in einer objektiven Bewertung nichts zu suchen.",
  "Which criteria enter a utility analysis for suppliers?",
  ("Price of the offered service", "Promised delivery time",
   "Scope and quality of the service", "Experience from previous orders",
   "The font used in the offer letter", "The first name of the sales representative"),
  "Weighted factual criteria such as price, deadline, service and reliability are assessed. Purely formal or personal features have no place in an objective evaluation."),

M("ap1-wpm-r42",
  "Welche Angaben gehören in einen Projektauftrag?",
  ("Ziel und Gegenstand des Projekts", "Budget und Termine",
   "Benannte Projektleitung", "Abgrenzung dessen, was nicht dazugehört",
   "Die Lieblingsfarbe des Auftraggebers", "Die Mittagspausenregelung im Team"),
  (0, 1, 2, 3),
  "Ziel, Rahmen, Verantwortung und Abgrenzung machen ein Projekt steuerbar und abnahmefähig. Gerade die Abgrenzung schützt später vor schleichender Ausweitung.",
  "Which items belong in a project charter?",
  ("Goal and subject of the project", "Budget and deadlines",
   "Named project management", "Delimitation of what is out of scope",
   "The client's favourite colour", "The lunch break arrangement in the team"),
  "Goal, framework, responsibility and delimitation make a project steerable and acceptable. The delimitation in particular protects against creeping expansion later."),

M("ap1-wpm-r43",
  "Welche Aussagen über die GmbH sind zutreffend?",
  ("Sie ist eine juristische Person", "Die Haftung ist auf das Gesellschaftsvermögen beschränkt",
   "Sie braucht ein Mindeststammkapital", "Sie wird ins Handelsregister eingetragen",
   "Die Gesellschafter haften stets privat mit", "Sie darf keine Mitarbeiter beschäftigen"),
  (0, 1, 2, 3),
  "Die GmbH ist eine eigene Rechtspersönlichkeit mit beschränkter Haftung, Mindeststammkapital und Registereintrag. Private Haftung greift nur in Ausnahmefällen.",
  "Which statements about the German limited liability company are correct?",
  ("It is a legal person", "Liability is limited to the company's assets",
   "It requires a minimum share capital", "It is entered in the commercial register",
   "The shareholders are always personally liable", "It may not employ any staff"),
  "The company is a legal entity of its own with limited liability, minimum capital and register entry. Personal liability applies only in exceptional cases."),

M("ap1-wpm-r44",
  "Welche Angaben liefert ein Netzplan?",
  ("Die Reihenfolge der Vorgänge", "Frühest- und spätestmögliche Zeitpunkte",
   "Die Pufferzeiten der Vorgänge", "Den kritischen Pfad des Projekts",
   "Die Zufriedenheit der Mitarbeiter", "Die Höhe der Umsatzsteuer"),
  (0, 1, 2, 3),
  "Der Netzplan macht Abhängigkeiten und Zeitreserven sichtbar und zeigt, welche Kette den Endtermin bestimmt. Weiche Faktoren und Steuern gehören nicht dazu.",
  "Which information does a network plan provide?",
  ("The sequence of the activities", "Earliest and latest possible dates",
   "The float times of the activities", "The critical path of the project",
   "The satisfaction of the employees", "The rate of value added tax"),
  "The network plan makes dependencies and time reserves visible and shows which chain determines the end date. Soft factors and taxes are not part of it."),

M("ap1-wpm-r45",
  "Welche Voraussetzungen müssen für Zahlungsverzug eines Kunden vorliegen?",
  ("Eine fällige und durchsetzbare Forderung", "Eine Mahnung nach Fälligkeit",
   "Ausbleiben der Zahlung trotz Mahnung", "Alternativ Ablauf von 30 Tagen nach Rechnungserhalt",
   "Eine schriftliche Zustimmung des Kunden", "Eine Bestätigung durch die Hausbank"),
  (0, 1, 2, 3),
  "Verzug tritt durch Mahnung nach Fälligkeit ein oder automatisch 30 Tage nach Zugang der Rechnung. Zustimmung des Schuldners ist dafür gerade nicht nötig.",
  "Which conditions must be met for a customer to be in payment default?",
  ("A due and enforceable claim", "A reminder after the due date",
   "Non-payment despite the reminder", "Alternatively 30 days after receiving the invoice",
   "A written consent from the customer", "A confirmation from the house bank"),
  "Default arises through a reminder after the due date or automatically 30 days after the invoice is received. The debtor's consent is precisely not required."),

M("ap1-wpm-r46",
  "Welche Vorteile bietet die Matrixorganisation?",
  ("Fachwissen bleibt in den Fachabteilungen gebündelt",
   "Projekte erhalten dennoch eigene Steuerung",
   "Ressourcen lassen sich flexibel zuordnen",
   "Der Austausch zwischen Bereichen nimmt zu",
   "Weisungskonflikte sind vollständig ausgeschlossen",
   "Die Entscheidungswege werden immer kürzer"),
  (0, 1, 2, 3),
  "Die Matrix verbindet Fachtiefe mit Projektsteuerung und fördert den Austausch. Der Preis dafür sind genau die Weisungskonflikte durch doppelte Unterstellung.",
  "Which advantages does the matrix organisation offer?",
  ("Expertise stays concentrated in the specialist departments",
   "Projects still receive their own steering",
   "Resources can be assigned flexibly",
   "Exchange between areas increases",
   "Conflicting instructions are completely ruled out",
   "Decision paths always become shorter"),
  "The matrix combines depth of expertise with project steering and encourages exchange. The price is precisely the conflicting instructions from dual reporting."),

M("ap1-wpm-r47",
  "Welche Angaben braucht man, um die Wirtschaftlichkeit einer Investition zu beurteilen?",
  ("Anschaffungskosten", "Laufende Betriebskosten",
   "Erwartete Einsparungen oder Erträge", "Nutzungsdauer der Investition",
   "Die Anzahl der Parkplätze am Standort", "Das Alter des Geschäftsführers"),
  (0, 1, 2, 3),
  "Erst Anschaffung, Betrieb, Rückfluss und Nutzungsdauer zusammen ergeben ein belastbares Bild. Der reine Kaufpreis führt bei Folgekosten leicht in die Irre.",
  "Which figures are needed to assess the profitability of an investment?",
  ("Acquisition costs", "Ongoing operating costs",
   "Expected savings or returns", "Useful life of the investment",
   "The number of parking spaces on site", "The age of the managing director"),
  "Only acquisition, operation, return and useful life together give a sound picture. The purchase price alone easily misleads when follow-on costs exist."),

M("ap1-wpm-r48",
  "Welche Aussagen zum Skonto sind richtig?",
  ("Es belohnt Zahlung innerhalb einer kurzen Frist",
   "Es wird in Prozent vom Rechnungsbetrag berechnet",
   "Es lohnt sich meist gegenüber einem Kredit",
   "Die Frist steht in den Zahlungsbedingungen",
   "Es wird immer erst am Jahresende gutgeschrieben",
   "Es steht dem Kunden unabhängig vom Zahlungstermin zu"),
  (0, 1, 2, 3),
  "Skonto ist an eine kurze Zahlungsfrist gebunden und deshalb hoch verzinst, wenn man es aufs Jahr rechnet. Wer die Frist verstreichen lässt, verliert den Anspruch.",
  "Which statements about cash discount are correct?",
  ("It rewards payment within a short deadline",
   "It is calculated as a percentage of the invoice total",
   "It usually pays off compared with taking a loan",
   "The deadline appears in the payment terms",
   "It is always credited only at year end",
   "The customer is entitled to it regardless of payment date"),
  "Cash discount is tied to a short payment window and therefore highly beneficial when annualised. Anyone letting the deadline pass loses the entitlement."),

M("ap1-wpm-r49",
  "Welche Aufgaben erfüllt ein Projektstrukturplan?",
  ("Er zerlegt das Projekt in Teilaufgaben", "Er führt bis auf Arbeitspakete herunter",
   "Er schafft die Basis für Aufwandsschätzung", "Er macht Verantwortlichkeiten zuordenbar",
   "Er berechnet automatisch den kritischen Pfad", "Er ersetzt den Projektauftrag vollständig"),
  (0, 1, 2, 3),
  "Der Strukturplan gliedert und macht schätzbar und zuordenbar. Zeitliche Abhängigkeiten und der kritische Pfad entstehen erst im Netzplan.",
  "Which tasks does a work breakdown structure fulfil?",
  ("It divides the project into subtasks", "It breaks down to work packages",
   "It creates the basis for effort estimation", "It makes responsibilities assignable",
   "It automatically calculates the critical path", "It fully replaces the project charter"),
  "The breakdown structure divides and makes work estimable and assignable. Temporal dependencies and the critical path only emerge in the network plan."),

M("ap1-wpm-r50",
  "Welche Faktoren beeinflussen die Wahl der Rechtsform eines Unternehmens?",
  ("Umfang der Haftung", "Höhe des benötigten Kapitals",
   "Gewünschte Mitspracherechte", "Steuerliche Auswirkungen",
   "Die Anzahl der Bürostühle", "Die Marke des Firmenwagens"),
  (0, 1, 2, 3),
  "Haftung, Kapitalbedarf, Mitsprache und Steuern sind die klassischen Entscheidungskriterien, ergänzt um Aufwand für Gründung und Publizität. Ausstattungsfragen spielen keine Rolle.",
  "Which factors influence the choice of a company's legal form?",
  ("Extent of liability", "Amount of capital required",
   "Desired participation rights", "Tax implications",
   "The number of office chairs", "The brand of the company car"),
  "Liability, capital needs, participation and taxes are the classic decision criteria, plus formation effort and disclosure duties. Equipment questions play no role."),

M("ap1-wpm-r51",
  "Welche Aussagen über Fixkosten sind zutreffend?",
  ("Sie fallen unabhängig von der Ausbringungsmenge an",
   "Sie sinken je Stück bei steigender Menge",
   "Miete und Versicherung zählen dazu",
   "Sie müssen durch Deckungsbeiträge gedeckt werden",
   "Sie steigen mit jedem produzierten Stück",
   "Sie entfallen bei einem Produktionsstopp sofort"),
  (0, 1, 2, 3),
  "Fixkosten laufen unabhängig weiter, verteilen sich aber auf mehr Stücke - das ist die Degression. Erst wenn die Deckungsbeiträge sie decken, beginnt der Gewinn.",
  "Which statements about fixed costs are correct?",
  ("They arise regardless of output quantity",
   "They fall per unit as quantity rises",
   "Rent and insurance are among them",
   "They must be covered by contribution margins",
   "They rise with every unit produced",
   "They disappear immediately if production stops"),
  "Fixed costs continue regardless but spread across more units - that is cost degression. Profit begins only once contribution margins cover them."),

M("ap1-wpm-r52",
  "Welche Punkte sollte eine Aufwandsschätzung berücksichtigen?",
  ("Erfahrungswerte aus vergleichbaren Projekten",
   "Einschätzung der Personen, die die Arbeit tun",
   "Reserve für unvorhergesehene Probleme",
   "Abhängigkeiten von Zulieferungen Dritter",
   "Den Wunschtermin des Auftraggebers als Vorgabe",
   "Die aktuelle Wettervorhersage der Region"),
  (0, 1, 2, 3),
  "Gute Schätzungen stützen sich auf Erfahrung, die Sicht der Ausführenden, Puffer und externe Abhängigkeiten. Vom Wunschtermin rückwärts zu rechnen erzeugt keine Schätzung, sondern eine Hoffnung.",
  "Which points should an effort estimate take into account?",
  ("Experience from comparable projects",
   "Assessment by the people doing the work",
   "Reserve for unforeseen problems",
   "Dependencies on third-party deliveries",
   "The client's desired date as a given",
   "The current weather forecast for the region"),
  "Good estimates rest on experience, the view of those doing the work, buffers and external dependencies. Working backwards from a desired date produces a hope, not an estimate."),

M("ap1-wpm-r53",
  "Welche Aussagen über den kritischen Pfad sind richtig?",
  ("Er besteht aus Vorgängen ohne Puffer",
   "Er bestimmt die Gesamtdauer des Projekts",
   "Verzögerungen auf ihm verschieben den Endtermin",
   "Er verdient besondere Aufmerksamkeit in der Steuerung",
   "Er enthält immer die teuersten Vorgänge",
   "Er lässt sich beliebig verkürzen ohne Folgen"),
  (0, 1, 2, 3),
  "Pufferlose Vorgänge bilden die längste Kette und damit die Projektdauer. Ob diese Vorgänge teuer sind, hat damit nichts zu tun.",
  "Which statements about the critical path are correct?",
  ("It consists of activities without float",
   "It determines the overall project duration",
   "Delays on it move the end date",
   "It deserves special attention in steering",
   "It always contains the most expensive activities",
   "It can be shortened arbitrarily without consequences"),
  "Activities without float form the longest chain and thus the project duration. Whether those activities are expensive has nothing to do with it."),

M("ap1-wpm-r54",
  "Welche Aussagen über AGB sind zutreffend?",
  ("Sie sind für eine Vielzahl von Verträgen vorformuliert",
   "Sie müssen wirksam einbezogen werden",
   "Überraschende Klauseln werden nicht Vertragsbestandteil",
   "Unwirksame Klauseln werden durch Gesetz ersetzt",
   "Sie gelten automatisch ohne jeden Hinweis",
   "Sie stehen immer über den gesetzlichen Regelungen"),
  (0, 1, 2, 3),
  "AGB brauchen einen Hinweis und die Möglichkeit zur Kenntnisnahme; überraschende oder unangemessene Klauseln fallen weg. Über dem Gesetz stehen sie nie.",
  "Which statements about standard terms and conditions are correct?",
  ("They are pre-formulated for a multitude of contracts",
   "They must be effectively incorporated",
   "Surprising clauses do not become part of the contract",
   "Invalid clauses are replaced by statutory law",
   "They apply automatically without any notice",
   "They always override statutory provisions"),
  "Standard terms need a notice and an opportunity to read them; surprising or unreasonable clauses fall away. They never override the law."),

M("ap1-wpm-r55",
  "Welche Kennzahlen helfen bei der Beurteilung eines IT-Beschaffungsvorhabens?",
  ("Gesamtkosten über die Nutzungsdauer", "Amortisationsdauer der Investition",
   "Erwartete jährliche Einsparung", "Verfügbarkeitszusagen des Anbieters",
   "Die Anzahl der Seiten im Prospekt", "Das Gründungsjahr des Herstellers"),
  (0, 1, 2, 3),
  "TCO, Amortisation, Einsparung und Servicezusagen machen Angebote wirtschaftlich vergleichbar. Prospektumfang und Firmenalter sagen über die Eignung nichts aus.",
  "Which figures help assess an IT procurement project?",
  ("Total cost over the useful life", "Payback period of the investment",
   "Expected annual saving", "Availability commitments of the vendor",
   "The number of pages in the brochure", "The founding year of the manufacturer"),
  "TCO, payback, savings and service commitments make offers economically comparable. Brochure length and company age say nothing about suitability."),

M("ap1-wpm-r56",
  "Welche Aussagen über Arbeitspakete sind richtig?",
  ("Sie sind die kleinste Einheit des Strukturplans",
   "Sie haben eine benannte verantwortliche Person",
   "Ihr Aufwand lässt sich abschätzen",
   "Ihr Ergebnis ist überprüfbar beschrieben",
   "Sie dauern grundsätzlich genau eine Woche",
   "Sie werden erst nach Projektende definiert"),
  (0, 1, 2, 3),
  "Ein gutes Arbeitspaket ist klein genug zum Schätzen, hat einen Verantwortlichen und ein prüfbares Ergebnis. Eine feste Dauer gibt es nicht, und definiert wird es zu Projektbeginn.",
  "Which statements about work packages are correct?",
  ("They are the smallest unit of the breakdown structure",
   "They have a named responsible person",
   "Their effort can be estimated",
   "Their result is described verifiably",
   "They fundamentally last exactly one week",
   "They are defined only after the project ends"),
  "A good work package is small enough to estimate, has an owner and a verifiable result. There is no fixed duration, and it is defined at project start."),

M("ap1-wpm-r57",
  "Welche Aussagen über Einzel- und Gemeinkosten sind zutreffend?",
  ("Einzelkosten lassen sich direkt zurechnen",
   "Gemeinkosten werden über Zuschlagssätze verteilt",
   "Fertigungsmaterial ist typischerweise Einzelkosten",
   "Verwaltungskosten sind typischerweise Gemeinkosten",
   "Gemeinkosten fallen nur einmal im Jahr an",
   "Einzelkosten lassen sich nicht beziffern"),
  (0, 1, 2, 3),
  "Die Unterscheidung folgt der Zurechenbarkeit auf den Kostenträger. Genau deshalb braucht es Zuschlagssätze, um Gemeinkosten verursachungsgerecht zu verteilen.",
  "Which statements about direct and overhead costs are correct?",
  ("Direct costs can be assigned directly",
   "Overheads are allocated via overhead rates",
   "Production material is typically a direct cost",
   "Administration costs are typically overheads",
   "Overheads arise only once a year",
   "Direct costs cannot be quantified"),
  "The distinction follows assignability to the cost object. That is exactly why overhead rates are needed to allocate overheads according to their cause."),

M("ap1-wpm-r58",
  "Welche Inhalte gehören in eine Projektdokumentation?",
  ("Der Projektauftrag mit Zielen", "Die Planungsunterlagen",
   "Protokolle wesentlicher Entscheidungen", "Der Abschlussbericht",
   "Die privaten Notizen einzelner Beteiligter", "Die Speisekarte der Betriebskantine"),
  (0, 1, 2, 3),
  "Auftrag, Planung, Entscheidungen und Abschluss machen ein Projekt nachvollziehbar und übergabefähig. Private Notizen sind kein verbindlicher Bestandteil.",
  "Which content belongs in project documentation?",
  ("The project charter with its goals", "The planning documents",
   "Minutes of key decisions", "The closing report",
   "Private notes of individual participants", "The menu of the company canteen"),
  "Charter, planning, decisions and closure make a project traceable and handover-ready. Private notes are not a binding component."),

M("ap1-wpm-r59",
  "Welche Aussagen über Angebote und deren Bindung sind korrekt?",
  ("Ein Angebot kann eine Bindefrist enthalten",
   "Nach Ablauf der Frist erlischt die Bindung",
   "Eine abweichende Bestellung gilt als neues Angebot",
   "Freibleibende Angebote binden den Anbieter nicht",
   "Jedes Angebot bindet unbefristet",
   "Ein Angebot kommt erst mit Zahlung zustande"),
  (0, 1, 2, 3),
  "Bindefristen und Freizeichnungsklauseln steuern, wie lange und ob ein Anbieter gebunden ist. Weicht die Bestellung ab, dreht sich das Verhältnis und der Kunde macht das Angebot.",
  "Which statements about offers and their binding effect are correct?",
  ("An offer can contain a period of validity",
   "After the period expires the binding ends",
   "A deviating order counts as a new offer",
   "Non-binding offers do not bind the vendor",
   "Every offer binds indefinitely",
   "An offer only arises upon payment"),
  "Validity periods and non-binding clauses control how long and whether a vendor is bound. If the order deviates, the roles reverse and the customer makes the offer."),

M("ap1-wpm-r60",
  "Welche Vorteile bringt eine frühzeitige Einbindung der Stakeholder?",
  ("Anforderungen werden vollständiger erfasst",
   "Widerstände lassen sich früh erkennen",
   "Die Akzeptanz des Ergebnisses steigt",
   "Spätere teure Änderungen werden seltener",
   "Der Projektumfang schrumpft dadurch automatisch",
   "Die Notwendigkeit von Tests entfällt"),
  (0, 1, 2, 3),
  "Wer früh fragt, erfährt früh von Anforderungen und Vorbehalten - und spart sich teure Korrekturen am Ende. Auf Umfang und Tests hat das keinen automatischen Einfluss.",
  "Which advantages come from involving stakeholders early?",
  ("Requirements are captured more completely",
   "Resistance can be spotted early",
   "Acceptance of the result increases",
   "Expensive late changes become rarer",
   "The project scope automatically shrinks",
   "The need for testing disappears"),
  "Asking early means learning early about requirements and reservations - saving expensive corrections at the end. It has no automatic effect on scope or testing."),

M("ap1-wpm-r61",
  "Welche Aussagen über Outsourcing sind zutreffend?",
  ("Interne Ressourcen werden freigesetzt",
   "Der Anbieter bringt spezialisiertes Wissen mit",
   "Es entsteht Abhängigkeit vom Dienstleister",
   "Vertragliche Regelungen werden wichtiger",
   "Die Verantwortung geht vollständig auf den Anbieter über",
   "Kosten sinken in jedem Fall dauerhaft"),
  (0, 1, 2, 3),
  "Outsourcing tauscht eigene Kapazität gegen Spezialwissen, erzeugt aber Abhängigkeit und verlagert das Gewicht auf den Vertrag. Die Gesamtverantwortung bleibt beim Auftraggeber.",
  "Which statements about outsourcing are correct?",
  ("Internal resources are freed up",
   "The provider brings specialised knowledge",
   "Dependency on the service provider arises",
   "Contractual arrangements become more important",
   "Responsibility passes entirely to the provider",
   "Costs fall permanently in every case"),
  "Outsourcing trades own capacity for specialist knowledge but creates dependency and shifts weight onto the contract. Overall responsibility stays with the client."),

M("ap1-wpm-r62",
  "Welche Aussagen zur Inventur sind richtig?",
  ("Sie erfasst die tatsächlichen Bestände", "Sie dient dem Abgleich mit der Buchführung",
   "Sie deckt Schwund und Fehlbuchungen auf", "Sie ist gesetzlich vorgeschrieben",
   "Sie ersetzt die laufende Lagerbuchhaltung", "Sie erfolgt ausschließlich täglich"),
  (0, 1, 2, 3),
  "Die körperliche Bestandsaufnahme prüft, ob Buchbestand und Wirklichkeit übereinstimmen. Sie ergänzt die laufende Buchhaltung, ersetzt sie aber nicht.",
  "Which statements about stocktaking are correct?",
  ("It records the actual stock levels", "It serves to reconcile with the accounts",
   "It reveals shrinkage and posting errors", "It is required by law",
   "It replaces ongoing inventory bookkeeping", "It takes place exclusively every day"),
  "The physical count checks whether book stock and reality agree. It complements ongoing bookkeeping but does not replace it."),

M("ap1-wpm-r63",
  "Welche Maßnahmen helfen, ein Projekt wieder in den Zeitplan zu bringen?",
  ("Zusätzliche Ressourcen für kritische Vorgänge",
   "Reduzierung des vereinbarten Leistungsumfangs",
   "Parallelisierung geeigneter Arbeitspakete",
   "Neuverhandlung des Endtermins mit dem Auftraggeber",
   "Streichen aller Tests bis zur Auslieferung",
   "Verschweigen der Verzögerung gegenüber dem Kunden"),
  (0, 1, 2, 3),
  "Mehr Mittel, weniger Umfang, mehr Parallelität oder ein neuer Termin sind die ehrlichen Stellschrauben. Tests zu streichen und Verzögerungen zu verschweigen verlagert das Problem nur nach hinten.",
  "Which measures help bring a project back on schedule?",
  ("Additional resources for critical activities",
   "Reduction of the agreed scope",
   "Parallelising suitable work packages",
   "Renegotiating the deadline with the client",
   "Cutting all testing until delivery",
   "Concealing the delay from the customer"),
  "More resources, less scope, more parallelism or a new date are the honest levers. Cutting tests and hiding delays merely postpone the problem."),

M("ap1-wpm-r64",
  "Welche Aussagen über die Handelskalkulation sind korrekt?",
  ("Vom Bezugspreis führt der Weg über Zuschläge zum Verkaufspreis",
   "Der Handlungskostenzuschlag deckt die Gemeinkosten",
   "Der Gewinnzuschlag ergibt den Barverkaufspreis",
   "Kundenskonto und Rabatt werden aufgeschlagen",
   "Die Kalkulation endet beim Listeneinkaufspreis",
   "Die Umsatzsteuer wird vom Verkaufspreis abgezogen"),
  (0, 1, 2, 3),
  "Die Vorwärtskalkulation führt vom Bezugspreis über Handlungskosten und Gewinn zum Bar-, Ziel- und Listenverkaufspreis. Kundenskonto und Rabatt werden dabei aufgeschlagen, nicht abgezogen.",
  "Which statements about trade calculation are correct?",
  ("From the purchase price the path leads via surcharges to the selling price",
   "The handling cost surcharge covers the overheads",
   "The profit surcharge yields the cash selling price",
   "Customer cash discount and trade discount are added on",
   "The calculation ends at the list purchase price",
   "Value added tax is deducted from the selling price"),
  "Forward calculation runs from the purchase price via handling costs and profit to the cash, target and list selling price. Customer discounts are added on, not deducted."),

# ------------------------------------------------------------------ text (36)
T("ap1-wpm-r65", "Wie hoch ist der Skontobetrag bei 3 Prozent auf eine Rechnung über 4000 Euro?", "120",
  "3 Prozent von 4000 Euro sind 120 Euro. Der Zahlbetrag sinkt damit auf 3880 Euro.",
  "How large is the cash discount at 3 percent on an invoice of 4000 euros?", "120",
  "3 percent of 4000 euros is 120 euros. The amount payable drops to 3880 euros."),

T("ap1-wpm-r66", "Fixkosten 30000 Euro, Deckungsbeitrag 60 Euro je Stück: bei welcher Stückzahl liegt die Gewinnschwelle?", "500",
  "30000 geteilt durch 60 ergibt 500 Stück. Ab dem 501. Stück entsteht Gewinn.",
  "Fixed costs 30000 euros, contribution margin 60 euros per unit: at which quantity is break-even?", "500",
  "30000 divided by 60 gives 500 units. From the 501st unit onward profit arises."),

T("ap1-wpm-r67", "Um welche Größe lässt sich ein Vorgang verschieben, ohne den Endtermin zu gefährden?", "Pufferzeit",
  "Ist sie null, liegt der Vorgang auf dem kritischen Pfad und jede Verzögerung trifft den Endtermin.",
  "What is the span by which an activity can be delayed without affecting the end date called?", "Float",
  "If it is zero, the activity lies on the critical path and any delay hits the end date."),

T("ap1-wpm-r68", "Welche drei Größen bilden das magische Dreieck? Nenne die dritte neben Zeit und Kosten.", "Leistung",
  "Auch als Qualität oder Umfang bezeichnet. Alle drei hängen voneinander ab.",
  "Which three factors form the project triangle? Name the third besides time and cost.", "Scope",
  "Also called quality or performance. All three depend on each other."),

T("ap1-wpm-r69", "Wie viele Jahre dauert die Amortisation bei 50000 Euro Investition und 12500 Euro jährlicher Einsparung?", "4",
  "50000 geteilt durch 12500 ergibt 4 Jahre bis zur vollständigen Rückgewinnung.",
  "How many years is the payback period at 50000 euros investment and 12500 euros annual saving?", "4",
  "50000 divided by 12500 gives 4 years until full recovery."),

T("ap1-wpm-r70", "Welches Dokument beschreibt aus Sicht des Auftraggebers die Anforderungen an eine Beschaffung?", "Lastenheft",
  "Es nennt das Was und macht eingehende Angebote überhaupt erst vergleichbar.",
  "Which document describes the client's requirements for a procurement?", "Requirements specification",
  "It states the what and is what makes incoming offers comparable in the first place."),

T("ap1-wpm-r71", "Wie nennt man den nachträglich gewährten, meist umsatzabhängigen Preisnachlass?", "Bonus",
  "Er wird typischerweise zum Jahresende abgerechnet, anders als der sofort wirksame Rabatt.",
  "What is the retrospectively granted, usually revenue-dependent price reduction called?", "Bonus",
  "It is typically settled at year end, unlike the immediately effective trade discount."),

T("ap1-wpm-r72", "Welche Kostenart bleibt bei schwankender Produktionsmenge unverändert?", "Fixkosten",
  "Miete, Versicherung und Gehälter laufen auch bei Stillstand weiter.",
  "Which cost type stays unchanged when production quantity fluctuates?", "Fixed costs",
  "Rent, insurance and salaries continue even during a standstill."),

T("ap1-wpm-r73", "Welche Größe ergibt sich aus Verkaufspreis minus variablen Stückkosten?", "Deckungsbeitrag",
  "Er zeigt, was jedes verkaufte Stück zur Deckung der Fixkosten beiträgt.",
  "Which figure results from selling price minus variable unit costs?", "Contribution margin",
  "It shows what each unit sold contributes to covering the fixed costs."),

T("ap1-wpm-r74", "Nach wie vielen Tagen ab Rechnungszugang tritt Zahlungsverzug auch ohne Mahnung ein?", "30",
  "Bei Verbrauchern setzt das allerdings einen entsprechenden Hinweis auf der Rechnung voraus.",
  "After how many days from receiving an invoice does payment default occur even without a reminder?", "30",
  "For consumers this does require a corresponding notice on the invoice."),

T("ap1-wpm-r75", "Wie nennt man die Kette von Vorgängen ohne Puffer, die die Projektdauer bestimmt?", "Kritischer Pfad",
  "Jede Verzögerung auf ihm verschiebt unmittelbar den Endtermin des gesamten Projekts.",
  "What is the chain of activities without float determining project duration called?", "Critical path",
  "Any delay on it immediately moves the end date of the entire project."),

T("ap1-wpm-r76", "Welche Rechtsform haftet nur mit dem Gesellschaftsvermögen und braucht Mindeststammkapital?", "GmbH",
  "Die Gesellschafter riskieren grundsätzlich nur ihre Einlage, nicht ihr Privatvermögen.",
  "Which legal form is liable only with company assets and needs minimum share capital?", "Limited liability company",
  "The shareholders generally risk only their contribution, not their private assets."),

T("ap1-wpm-r77", "Wie nennt man ein Ereignis ohne Dauer, das einen wichtigen Zwischenstand markiert?", "Meilenstein",
  "Er eignet sich als Entscheidungspunkt, ob und wie das Projekt fortgesetzt wird.",
  "What is an event with no duration marking an important interim state called?", "Milestone",
  "It works well as a decision point on whether and how the project continues."),

T("ap1-wpm-r78", "Wie hoch ist der Zieleinkaufspreis bei 2000 Euro Listenpreis und 15 Prozent Rabatt?", "1700",
  "15 Prozent von 2000 sind 300 Euro, also bleiben 1700 Euro als Zieleinkaufspreis.",
  "What is the target purchase price at a 2000 euro list price and 15 percent trade discount?", "1700",
  "15 percent of 2000 is 300 euros, leaving 1700 euros as the target purchase price."),

T("ap1-wpm-r79", "Welche Entscheidung vergleicht Eigenfertigung mit Fremdbezug?", "Make or Buy",
  "Neben den Kosten zählen Know-how im Haus und die entstehende Abhängigkeit vom Anbieter.",
  "What is the decision between in-house production and external purchase called?", "Make or buy",
  "Besides cost, in-house know-how and the resulting vendor dependency matter."),

T("ap1-wpm-r80", "Wofür steht die Abkürzung SLA im Dienstleistungsvertrag?", "Service Level Agreement",
  "Es legt messbare Zusagen zu Verfügbarkeit, Reaktions- und Wiederherstellungszeiten fest.",
  "What does the abbreviation SLA stand for in a service contract?", "Service level agreement",
  "It defines measurable commitments on availability, response and recovery times."),

T("ap1-wpm-r81", "Wie nennt man das schleichende Anwachsen des Leistungsumfangs im Projekt?", "Scope Creep",
  "Ein definierter Änderungsprozess, der jede Erweiterung bewertet und freigibt, wirkt dagegen.",
  "What is the gradual growth of scope during a project called?", "Scope creep",
  "A defined change process that assesses and approves every extension counters it."),

T("ap1-wpm-r82", "Welcher Lagerkennwert löst eine Nachbestellung aus?", "Meldebestand",
  "Er errechnet sich aus Tagesverbrauch mal Wiederbeschaffungszeit plus Sicherheitsbestand.",
  "Which inventory figure triggers a reorder?", "Reorder point",
  "It is calculated from daily consumption times lead time plus safety stock."),

T("ap1-wpm-r83", "Wie viele Prozent Rabatt entsprechen 250 Euro Nachlass auf 5000 Euro?", "5",
  "250 geteilt durch 5000 ergibt 0,05 und damit 5 Prozent.",
  "How many percent discount do 250 euros off 5000 euros correspond to?", "5",
  "250 divided by 5000 gives 0.05, i.e. 5 percent."),

T("ap1-wpm-r84", "Wie nennt man die Personen und Gruppen, die von einem Projekt betroffen sind?", "Stakeholder",
  "Frühe Einbindung senkt Widerstände und macht Anforderungen vollständiger.",
  "What are the people and groups affected by a project called?", "Stakeholders",
  "Early involvement lowers resistance and makes requirements more complete."),

T("ap1-wpm-r85", "Welches Verfahren gewichtet und bewertet mehrere Kriterien beim Angebotsvergleich?", "Nutzwertanalyse",
  "Sie macht weiche Faktoren wie Service und Zuverlässigkeit rechnerisch vergleichbar.",
  "Which method weights and scores several criteria when comparing offers?", "Utility analysis",
  "It makes soft factors such as service and reliability numerically comparable."),

T("ap1-wpm-r86", "Wie nennt man die kleinste planbare Einheit eines Projektstrukturplans?", "Arbeitspaket",
  "Es hat einen Verantwortlichen, einen schätzbaren Aufwand und ein überprüfbares Ergebnis.",
  "What is the smallest plannable unit of a work breakdown structure called?", "Work package",
  "It has an owner, an estimable effort and a verifiable result."),

T("ap1-wpm-r87", "Wofür steht die Abkürzung ROI?", "Return on Investment",
  "Er setzt den Gewinn ins Verhältnis zum eingesetzten Kapital und macht Investitionen vergleichbar.",
  "What does the abbreviation ROI stand for?", "Return on investment",
  "It relates profit to capital employed and makes investments comparable."),

T("ap1-wpm-r88", "Welche Organisationsform unterstellt Mitarbeiter gleichzeitig einer Fach- und einer Projektleitung?", "Matrixorganisation",
  "Sie verbindet Fachtiefe mit Projektsteuerung, erzeugt aber Weisungskonflikte.",
  "Which organisational form places staff under both a functional and a project manager?", "Matrix organisation",
  "It combines depth of expertise with project steering but creates conflicting instructions."),

T("ap1-wpm-r89", "Welches Verfahren erfasst körperlich die tatsächlichen Bestände im Lager?", "Inventur",
  "Sie gleicht Buchbestand und Wirklichkeit ab und deckt Schwund sowie Fehlbuchungen auf.",
  "What is the physical stock count in a warehouse called?", "Stocktaking",
  "It reconciles book stock with reality and reveals shrinkage and posting errors."),

T("ap1-wpm-r90", "Welche Vertragsverletzung liegt vor, wenn der Verkäufer nach Mahnung nicht liefert?", "Lieferverzug",
  "Der Käufer kann dann Nachfrist setzen, zurücktreten oder Schadenersatz verlangen.",
  "Which breach of contract occurs when the seller fails to deliver after a reminder?", "Delivery default",
  "The buyer can then set a grace period, withdraw or claim damages."),

T("ap1-wpm-r91", "Wie nennt man Kosten, die sich nicht direkt einem einzelnen Produkt zurechnen lassen?", "Gemeinkosten",
  "Sie werden über Zuschlagssätze verteilt, etwa Miete, Verwaltung und Energie.",
  "What are costs that cannot be assigned directly to a single product called?", "Overhead costs",
  "They are allocated via overhead rates, for example rent, administration and energy."),

T("ap1-wpm-r92", "Wie viel Prozent beträgt der Deckungsbeitrag vom Preis, wenn er 40 Euro bei 100 Euro Verkaufspreis ist?", "40",
  "40 geteilt durch 100 ergibt 0,4 und damit eine Deckungsbeitragsquote von 40 Prozent.",
  "What percentage of the price is the contribution margin if it is 40 euros at a 100 euro selling price?", "40",
  "40 divided by 100 gives 0.4, i.e. a contribution margin ratio of 40 percent."),

T("ap1-wpm-r93", "Welches Dokument hält am Projektende fest, was gut und was schlecht lief?", "Abschlussbericht",
  "Die darin gesammelten Lessons Learned verhindern, dass sich Fehler im nächsten Projekt wiederholen.",
  "Which document records at project end what went well and badly?", "Closing report",
  "The lessons learned collected in it prevent mistakes repeating in the next project."),

T("ap1-wpm-r94", "Wie nennt man den Zeitpunkt, ab dem die Erlöse die Gesamtkosten decken?", "Gewinnschwelle",
  "Auch Break-even-Point genannt. Ab hier bringt jedes weitere Stück seinen Deckungsbeitrag als Gewinn.",
  "What is the point at which revenue covers total costs called?", "Break-even point",
  "From here every further unit brings its contribution margin as profit."),

T("ap1-wpm-r95", "Wie viele übereinstimmende Willenserklärungen braucht ein Kaufvertrag?", "2",
  "Angebot und Annahme. Erst beide zusammen lassen den Vertrag entstehen.",
  "How many matching declarations of intent does a sales contract require?", "2",
  "Offer and acceptance. Only both together bring the contract into existence."),

T("ap1-wpm-r96", "Welches Recht steht dem Käufer bei einem Sachmangel als Erstes zu?", "Nacherfüllung",
  "Also Reparatur oder Ersatzlieferung. Erst wenn diese scheitert, folgen Rücktritt, Minderung oder Schadenersatz.",
  "Which right does a buyer have first in the case of a material defect?", "Subsequent performance",
  "That is repair or replacement. Only if it fails do withdrawal, price reduction or damages follow."),

T("ap1-wpm-r97", "Welche grafische Terminplanung nutzt waagerechte Balken auf einer Zeitachse?", "Balkendiagramm",
  "Auch Gantt-Diagramm genannt. Es zeigt Dauer und Überschneidungen anschaulich, aber Abhängigkeiten nur begrenzt.",
  "What is graphical scheduling with horizontal bars on a time axis called?", "Bar chart",
  "Also called a Gantt chart. It shows duration and overlaps clearly but dependencies only to a limited extent."),

T("ap1-wpm-r98", "Wie hoch ist der Zahlbetrag bei 1000 Euro Rechnung und 2 Prozent Skonto?", "980",
  "2 Prozent von 1000 sind 20 Euro Abzug, es bleiben 980 Euro zu zahlen.",
  "What is the amount payable on a 1000 euro invoice with 2 percent cash discount?", "980",
  "2 percent of 1000 is a 20 euro deduction, leaving 980 euros to pay."),

T("ap1-wpm-r99", "Welche Kennzahl beschreibt die Gesamtkosten eines Systems über seine gesamte Nutzungsdauer?", "TCO",
  "Total Cost of Ownership deckt auch Betrieb, Wartung und Entsorgung ab, nicht nur den Kaufpreis.",
  "Which figure describes a system's total cost across its entire service life?", "TCO",
  "Total cost of ownership also covers operation, maintenance and disposal, not just the purchase price."),

T("ap1-wpm-r100", "Wie nennt man das Werkzeug, das ein Projekt hierarchisch in Teilaufgaben zerlegt?", "Projektstrukturplan",
  "Er ist die Grundlage für Aufwandsschätzung, Terminplanung und Zuordnung von Verantwortung.",
  "What is the tool dividing a project hierarchically into subtasks called?", "Work breakdown structure",
  "It is the basis for effort estimation, scheduling and assignment of responsibility."),
]

build("ap1-wirtschaft-projektmanagement.json", "Wirtschaft & Projektmanagement", "Business & Project Management", Q)
