#!/usr/bin/env python3
"""AP2 Datenbanken - 100 handgeschriebene Fragen."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from qlib import S, M, T, build

Q = [
# ---------------------------------------------------------------- single (32)
S("ap2-db-r01",
  "Welche Abfrage liefert alle Kunden aus Berlin, sortiert nach Name?",
  ("SELECT * FROM kunden WHERE ort = 'Berlin' ORDER BY name;",
   "SELECT * FROM kunden ORDER BY ort = 'Berlin' WHERE name;",
   "SELECT * FROM kunden GROUP BY name HAVING ort = 'Berlin';",
   "SELECT * FROM kunden SORT BY name WHERE ort = 'Berlin';"), 0,
  "WHERE filtert Zeilen, ORDER BY sortiert das Ergebnis. GROUP BY mit HAVING ist für Gruppierungen gedacht, und SORT BY existiert in SQL nicht.",
  "Which query returns all customers from Berlin, sorted by name?",
  ("SELECT * FROM kunden WHERE ort = 'Berlin' ORDER BY name;",
   "SELECT * FROM kunden ORDER BY ort = 'Berlin' WHERE name;",
   "SELECT * FROM kunden GROUP BY name HAVING ort = 'Berlin';",
   "SELECT * FROM kunden SORT BY name WHERE ort = 'Berlin';"),
  "WHERE filters rows, ORDER BY sorts the result. GROUP BY with HAVING is meant for grouping, and SORT BY does not exist in SQL."),

S("ap2-db-r02",
  "Ein Bericht soll alle Kunden zeigen, auch die ohne Bestellung. Welcher JOIN passt?",
  ("LEFT JOIN von kunden auf bestellungen",
   "INNER JOIN von kunden auf bestellungen",
   "CROSS JOIN von kunden auf bestellungen",
   "SELF JOIN der Tabelle bestellungen"), 0,
  "Der LEFT JOIN behält alle Zeilen der linken Tabelle und füllt fehlende Treffer mit NULL. Ein INNER JOIN würde genau die Kunden ohne Bestellung herausfiltern.",
  "A report must show all customers, including those without orders. Which join fits?",
  ("LEFT JOIN from kunden onto bestellungen",
   "INNER JOIN from kunden onto bestellungen",
   "CROSS JOIN from kunden onto bestellungen",
   "SELF JOIN of the table bestellungen"),
  "A LEFT JOIN keeps all rows of the left table and fills missing matches with NULL. An INNER JOIN would filter out exactly the customers without orders."),

S("ap2-db-r03",
  "Welche Bedingung filtert erst nach der Gruppierung?",
  ("HAVING", "WHERE", "ORDER BY", "DISTINCT"), 0,
  "WHERE wirkt auf einzelne Zeilen vor der Gruppierung, HAVING auf die gebildeten Gruppen danach. Deshalb dürfen nur in HAVING Aggregatfunktionen stehen.",
  "Which clause filters only after grouping?",
  ("HAVING", "WHERE", "ORDER BY", "DISTINCT"),
  "WHERE acts on individual rows before grouping, HAVING on the resulting groups afterwards. That is why only HAVING may contain aggregate functions."),

S("ap2-db-r04",
  "In einer Tabelle steht die Lieferantenanschrift bei jedem Artikel erneut. Welches Problem entsteht?",
  ("Redundanz mit der Gefahr von Änderungsanomalien",
   "Ein Verstoß gegen die referenzielle Integrität",
   "Ein Verlust der Sortierbarkeit der Tabelle",
   "Eine automatische Sperre der betroffenen Zeilen"), 0,
  "Wird die Anschrift geändert, muss das an jeder Stelle geschehen - sonst widersprechen sich die Daten. Genau solche Anomalien beseitigt die Normalisierung durch Auslagern in eine eigene Tabelle.",
  "In one table the supplier address is repeated for every article. Which problem arises?",
  ("Redundancy with the risk of update anomalies",
   "A violation of referential integrity",
   "A loss of the table's sortability",
   "An automatic lock on the affected rows"),
  "If the address changes, it must be changed everywhere - otherwise the data contradicts itself. Normalisation removes exactly such anomalies by moving data into its own table."),

S("ap2-db-r05",
  "Welche Eigenschaft muss ein Primärschlüssel erfüllen?",
  ("Er ist eindeutig und niemals NULL",
   "Er ist immer eine fortlaufende Zahl",
   "Er darf sich bei Bedarf wiederholen",
   "Er besteht aus höchstens einem Zeichen"), 0,
  "Eindeutigkeit und Nichtleere machen jeden Datensatz zweifelsfrei ansprechbar. Ob dahinter eine Zahl oder ein zusammengesetzter Schlüssel steht, ist frei wählbar.",
  "Which property must a primary key fulfil?",
  ("It is unique and never NULL",
   "It is always a consecutive number",
   "It may repeat itself when needed",
   "It consists of at most one character"),
  "Uniqueness and non-nullness make every record unambiguously addressable. Whether it is a number or a composite key behind it is free to choose."),

S("ap2-db-r06",
  "Eine Tabelle enthält ein Feld mit mehreren Telefonnummern in einer Zelle. Gegen welche Normalform verstößt das?",
  ("Gegen die erste Normalform", "Gegen die zweite Normalform",
   "Gegen die dritte Normalform", "Gegen keine, das ist zulässig"), 0,
  "Die erste Normalform verlangt atomare Werte - eine Zelle enthält genau einen Wert. Mehrere Nummern gehören in eine eigene Tabelle mit Fremdschlüssel.",
  "A table has one field holding several phone numbers in a single cell. Which normal form does that violate?",
  ("The first normal form", "The second normal form",
   "The third normal form", "None, that is permitted"),
  "The first normal form requires atomic values - one cell holds exactly one value. Several numbers belong in their own table with a foreign key."),

S("ap2-db-r07",
  "Welcher Befehl ändert die Struktur einer bestehenden Tabelle?",
  ("ALTER TABLE", "UPDATE", "INSERT INTO", "SELECT INTO"), 0,
  "ALTER TABLE gehört zur DDL und ändert Spalten oder Bedingungen. UPDATE und INSERT gehören zur DML und ändern nur Daten.",
  "Which statement changes the structure of an existing table?",
  ("ALTER TABLE", "UPDATE", "INSERT INTO", "SELECT INTO"),
  "ALTER TABLE belongs to DDL and changes columns or constraints. UPDATE and INSERT belong to DML and change only data."),

S("ap2-db-r08",
  "Eine Überweisung bucht ab und schreibt gut. Welche ACID-Eigenschaft garantiert, dass beides oder nichts passiert?",
  ("Atomarität", "Konsistenz", "Isolation", "Dauerhaftigkeit"), 0,
  "Atomarität macht die Transaktion unteilbar: bei einem Fehler wird alles zurückgerollt. Konsistenz sichert die Regeln, Isolation die Trennung paralleler Transaktionen.",
  "A transfer debits and credits. Which ACID property guarantees that both or neither happens?",
  ("Atomicity", "Consistency", "Isolation", "Durability"),
  "Atomicity makes the transaction indivisible: on an error everything is rolled back. Consistency preserves the rules, isolation the separation of parallel transactions."),

S("ap2-db-r09",
  "Eine Abfrage auf einer großen Tabelle dauert sehr lange. Was hilft bei häufig gefilterten Spalten?",
  ("Ein Index auf der gefilterten Spalte",
   "Ein zusätzlicher Primärschlüssel je Zeile",
   "Ein DISTINCT vor der WHERE-Bedingung",
   "Eine Umbenennung der betroffenen Spalte"), 0,
  "Ein Index erlaubt gezieltes Nachschlagen statt eines vollständigen Tabellendurchlaufs. Der Preis sind zusätzlicher Speicher und langsamere Schreibvorgänge.",
  "A query on a large table takes very long. What helps for frequently filtered columns?",
  ("An index on the filtered column",
   "An additional primary key per row",
   "A DISTINCT before the WHERE clause",
   "Renaming the affected column"),
  "An index allows targeted lookup instead of a full table scan. The price is extra storage and slower write operations."),

S("ap2-db-r10",
  "Welcher Befehl macht die Änderungen einer Transaktion dauerhaft?",
  ("COMMIT", "ROLLBACK", "SAVEPOINT", "GRANT"), 0,
  "COMMIT schreibt die Transaktion endgültig fest, ROLLBACK verwirft sie. SAVEPOINT setzt nur einen Zwischenpunkt, GRANT vergibt Rechte.",
  "Which statement makes the changes of a transaction permanent?",
  ("COMMIT", "ROLLBACK", "SAVEPOINT", "GRANT"),
  "COMMIT writes the transaction permanently, ROLLBACK discards it. SAVEPOINT only sets an intermediate marker, GRANT assigns privileges."),

S("ap2-db-r11",
  "Ein Kunde soll nicht gelöscht werden können, solange Bestellungen zu ihm existieren. Was sichert das?",
  ("Die referenzielle Integrität über den Fremdschlüssel",
   "Ein zusätzlicher Index auf der Bestelltabelle",
   "Ein DISTINCT beim Auslesen der Bestellungen",
   "Eine Sortierung der Bestellungen nach Datum"), 0,
  "Der Fremdschlüssel verweist auf den Primärschlüssel und verhindert verwaiste Datensätze. Mit ON DELETE CASCADE ließe sich alternativ mitlöschen.",
  "A customer must not be deletable while orders exist for them. What ensures that?",
  ("Referential integrity via the foreign key",
   "An additional index on the orders table",
   "A DISTINCT when reading the orders",
   "Sorting the orders by their date"),
  "The foreign key references the primary key and prevents orphaned records. With ON DELETE CASCADE the dependent rows could alternatively be deleted too."),

S("ap2-db-r12",
  "Welche Funktion liefert die Anzahl der Zeilen eines Ergebnisses?",
  ("COUNT()", "SUM()", "AVG()", "MAX()"), 0,
  "COUNT zählt Zeilen, SUM summiert Werte, AVG bildet den Durchschnitt und MAX liefert den größten Wert.",
  "Which function returns the number of rows in a result?",
  ("COUNT()", "SUM()", "AVG()", "MAX()"),
  "COUNT counts rows, SUM adds values, AVG forms the average and MAX returns the largest value."),

S("ap2-db-r13",
  "Wie wird eine n:m-Beziehung im relationalen Modell umgesetzt?",
  ("Über eine zusätzliche Zwischentabelle",
   "Über einen zusammengesetzten Primärschlüssel in beiden Tabellen",
   "Über ein Mehrfachfeld in einer der Tabellen",
   "Über einen Index auf beiden beteiligten Tabellen"), 0,
  "Die Zwischentabelle nimmt die Fremdschlüssel beider Seiten auf und zerlegt so die n:m- in zwei 1:n-Beziehungen. Mehrfachfelder verstoßen gegen die erste Normalform.",
  "How is an n:m relationship implemented in the relational model?",
  ("Through an additional junction table",
   "Through a composite primary key in both tables",
   "Through a multi-value field in one of the tables",
   "Through an index on both participating tables"),
  "The junction table holds the foreign keys of both sides and thereby splits the n:m into two 1:n relationships. Multi-value fields violate the first normal form."),

S("ap2-db-r14",
  "Welche Aussage über eine View trifft zu?",
  ("Sie ist eine gespeicherte Abfrage ohne eigene Daten",
   "Sie kopiert die Daten in eine zweite Tabelle",
   "Sie ersetzt den Primärschlüssel der Basistabelle",
   "Sie beschleunigt Schreibvorgänge auf der Tabelle"), 0,
  "Eine View liefert bei jedem Zugriff das aktuelle Ergebnis ihrer Abfrage. Sie vereinfacht komplexe Joins und kann Spalten gezielt ausblenden.",
  "Which statement about a view is correct?",
  ("It is a stored query without data of its own",
   "It copies the data into a second table",
   "It replaces the primary key of the base table",
   "It speeds up write operations on the table"),
  "A view delivers the current result of its query on every access. It simplifies complex joins and can deliberately hide columns."),

S("ap2-db-r15",
  "Welcher Vergleich findet alle Namen, die mit Mei beginnen?",
  ("WHERE name LIKE 'Mei%'", "WHERE name = 'Mei'",
   "WHERE name BETWEEN 'Mei'", "WHERE name IN ('Mei')"), 0,
  "LIKE mit dem Platzhalter Prozent sucht nach Mustern. Das Gleichheitszeichen verlangt exakte Übereinstimmung, BETWEEN braucht zwei Grenzen.",
  "Which comparison finds all names starting with Mei?",
  ("WHERE name LIKE 'Mei%'", "WHERE name = 'Mei'",
   "WHERE name BETWEEN 'Mei'", "WHERE name IN ('Mei')"),
  "LIKE with the percent wildcard searches for patterns. The equals sign demands an exact match, and BETWEEN needs two bounds."),

S("ap2-db-r16",
  "Warum liefert die Bedingung WHERE rabatt = NULL keine Zeilen?",
  ("NULL lässt sich nicht mit dem Gleichheitszeichen prüfen",
   "NULL ist in Bedingungen grundsätzlich verboten",
   "NULL wird beim Vergleich automatisch zu null",
   "NULL steht immer am Ende der Sortierung"), 0,
  "NULL bedeutet unbekannt, und ein Vergleich mit Unbekanntem ergibt weder wahr noch falsch. Richtig ist deshalb IS NULL beziehungsweise IS NOT NULL.",
  "Why does the condition WHERE rabatt = NULL return no rows?",
  ("NULL cannot be tested with the equals sign",
   "NULL is fundamentally forbidden in conditions",
   "NULL is automatically converted to zero",
   "NULL always appears last in the sort order"),
  "NULL means unknown, and a comparison with the unknown yields neither true nor false. The correct form is therefore IS NULL or IS NOT NULL."),

S("ap2-db-r17",
  "Ein UPDATE ohne WHERE wurde ausgeführt und die Transaktion läuft noch. Was rettet die Daten?",
  ("Ein ROLLBACK der offenen Transaktion",
   "Ein sofortiges COMMIT der Änderungen",
   "Ein zusätzlicher Index auf der Tabelle",
   "Ein DROP der betroffenen Tabelle"), 0,
  "Solange nicht bestätigt wurde, macht ROLLBACK alle Änderungen der Transaktion rückgängig. Ein COMMIT würde den Fehler dagegen festschreiben.",
  "An UPDATE without WHERE was executed and the transaction is still open. What saves the data?",
  ("A ROLLBACK of the open transaction",
   "An immediate COMMIT of the changes",
   "An additional index on the table",
   "A DROP of the affected table"),
  "As long as nothing has been confirmed, ROLLBACK undoes all changes of the transaction. A COMMIT would make the mistake permanent instead."),

S("ap2-db-r18",
  "Welche Kardinalität beschreibt die Beziehung zwischen Kunde und seinen Bestellungen?",
  ("1:n", "1:1", "n:m", "0:0"), 0,
  "Ein Kunde kann viele Bestellungen haben, jede Bestellung gehört aber zu genau einem Kunden. Das ist der Standardfall einer 1:n-Beziehung.",
  "Which cardinality describes the relationship between a customer and their orders?",
  ("1:n", "1:1", "n:m", "0:0"),
  "One customer can have many orders, but each order belongs to exactly one customer. That is the standard case of a 1:n relationship."),

S("ap2-db-r19",
  "Welcher Befehl entzieht einem Benutzer ein zuvor erteiltes Recht?",
  ("REVOKE", "GRANT", "DELETE", "ROLLBACK"), 0,
  "GRANT vergibt Rechte, REVOKE nimmt sie zurück - beide gehören zur DCL. DELETE entfernt Daten, ROLLBACK verwirft eine Transaktion.",
  "Which statement withdraws a previously granted privilege from a user?",
  ("REVOKE", "GRANT", "DELETE", "ROLLBACK"),
  "GRANT assigns privileges, REVOKE takes them back - both belong to DCL. DELETE removes data, ROLLBACK discards a transaction."),

S("ap2-db-r20",
  "Zwei Transaktionen warten gegenseitig auf gesperrte Zeilen. Wie nennt man diese Situation?",
  ("Deadlock", "Rollback", "Commit", "Trigger"), 0,
  "Beim Deadlock blockieren sich Transaktionen wechselseitig und keine kommt weiter. Das Datenbanksystem erkennt das und rollt eine der beteiligten Transaktionen zurück.",
  "Two transactions wait for each other's locked rows. What is this situation called?",
  ("Deadlock", "Rollback", "Commit", "Trigger"),
  "In a deadlock transactions block each other mutually and none proceeds. The database system detects this and rolls one of the involved transactions back."),

S("ap2-db-r21",
  "Welcher Datentyp eignet sich für einen Geldbetrag mit exakt zwei Nachkommastellen?",
  ("DECIMAL", "FLOAT", "INTEGER", "VARCHAR"), 0,
  "DECIMAL rechnet exakt mit fester Stellenzahl. FLOAT rundet binär und erzeugt bei Geldbeträgen Centabweichungen, VARCHAR verhindert jedes Rechnen.",
  "Which data type suits a monetary amount with exactly two decimal places?",
  ("DECIMAL", "FLOAT", "INTEGER", "VARCHAR"),
  "DECIMAL computes exactly with a fixed number of digits. FLOAT rounds in binary and produces cent deviations for money, VARCHAR prevents any arithmetic."),

S("ap2-db-r22",
  "Welcher Befehl entfernt eine Tabelle samt Struktur aus der Datenbank?",
  ("DROP TABLE", "DELETE FROM", "TRUNCATE TABLE", "ALTER TABLE"), 0,
  "DROP entfernt die Tabelle vollständig. DELETE und TRUNCATE löschen nur Zeilen und lassen die Struktur bestehen.",
  "Which statement removes a table including its structure from the database?",
  ("DROP TABLE", "DELETE FROM", "TRUNCATE TABLE", "ALTER TABLE"),
  "DROP removes the table entirely. DELETE and TRUNCATE only remove rows and leave the structure in place."),

S("ap2-db-r23",
  "Eine Tabelle in der zweiten Normalform hat eine Spalte, die von einer Nichtschlüsselspalte abhängt. Was folgt?",
  ("Sie verletzt die dritte Normalform",
   "Sie verletzt die erste Normalform",
   "Sie ist bereits vollständig normalisiert",
   "Sie benötigt einen zusätzlichen Index"), 0,
  "Die dritte Normalform verlangt, dass Nichtschlüsselattribute nur vom Schlüssel abhängen. Transitive Abhängigkeiten wandern in eine eigene Tabelle.",
  "A table in second normal form has a column depending on a non-key column. What follows?",
  ("It violates the third normal form",
   "It violates the first normal form",
   "It is already fully normalised",
   "It requires an additional index"),
  "The third normal form requires non-key attributes to depend only on the key. Transitive dependencies move into their own table."),

S("ap2-db-r24",
  "Welche Abfrage liefert den Umsatz je Kunde?",
  ("SELECT kunde, SUM(betrag) FROM umsatz GROUP BY kunde;",
   "SELECT kunde, SUM(betrag) FROM umsatz ORDER BY kunde;",
   "SELECT kunde, SUM(betrag) FROM umsatz WHERE kunde;",
   "SELECT DISTINCT kunde, betrag FROM umsatz;"), 0,
  "Aggregatfunktionen brauchen GROUP BY für alle nicht aggregierten Spalten. ORDER BY sortiert nur, DISTINCT entfernt Dubletten ohne zu summieren.",
  "Which query returns the revenue per customer?",
  ("SELECT kunde, SUM(betrag) FROM umsatz GROUP BY kunde;",
   "SELECT kunde, SUM(betrag) FROM umsatz ORDER BY kunde;",
   "SELECT kunde, SUM(betrag) FROM umsatz WHERE kunde;",
   "SELECT DISTINCT kunde, betrag FROM umsatz;"),
  "Aggregate functions need GROUP BY for every non-aggregated column. ORDER BY only sorts, DISTINCT removes duplicates without summing."),

S("ap2-db-r25",
  "Wofür sorgt die Isolation in den ACID-Eigenschaften?",
  ("Parallele Transaktionen beeinflussen sich nicht gegenseitig",
   "Bestätigte Änderungen überstehen einen Systemabsturz",
   "Eine Transaktion wird ganz oder gar nicht ausgeführt",
   "Alle Integritätsregeln bleiben nach der Buchung erhalten"), 0,
  "Isolation verhindert, dass eine Transaktion Zwischenstände einer anderen sieht. Die drei anderen Beschreibungen gehören zu Dauerhaftigkeit, Atomarität und Konsistenz.",
  "What does isolation ensure among the ACID properties?",
  ("Parallel transactions do not influence each other",
   "Committed changes survive a system crash",
   "A transaction runs completely or not at all",
   "All integrity rules hold after the booking"),
  "Isolation prevents one transaction from seeing another's intermediate state. The three other descriptions belong to durability, atomicity and consistency."),

S("ap2-db-r26",
  "Welches System speichert Daten als Dokumente statt in Tabellen?",
  ("MongoDB", "PostgreSQL", "MariaDB", "Microsoft SQL Server"), 0,
  "MongoDB ist eine Dokumentendatenbank ohne festes Schema. Die drei anderen sind relationale Systeme mit Tabellen und SQL.",
  "Which system stores data as documents instead of tables?",
  ("MongoDB", "PostgreSQL", "MariaDB", "Microsoft SQL Server"),
  "MongoDB is a document database without a fixed schema. The other three are relational systems with tables and SQL."),

S("ap2-db-r27",
  "Ein Feld soll beim Einfügen automatisch das aktuelle Datum erhalten. Was setzt du?",
  ("Einen DEFAULT-Wert auf der Spalte",
   "Einen zusätzlichen Index auf der Spalte",
   "Eine UNIQUE-Bedingung auf der Spalte",
   "Einen Fremdschlüssel auf eine Datumstabelle"), 0,
  "DEFAULT greift, wenn beim INSERT kein Wert angegeben wird. Index und UNIQUE regeln Zugriff und Eindeutigkeit, nicht die Vorbelegung.",
  "A field should automatically receive the current date on insert. What do you set?",
  ("A DEFAULT value on the column",
   "An additional index on the column",
   "A UNIQUE constraint on the column",
   "A foreign key to a date table"),
  "DEFAULT applies when no value is given on INSERT. Index and UNIQUE govern access and uniqueness, not the initial value."),

S("ap2-db-r28",
  "Was bewirkt ON DELETE CASCADE bei einem Fremdschlüssel?",
  ("Abhängige Datensätze werden mitgelöscht",
   "Das Löschen des Hauptsatzes wird verhindert",
   "Der Fremdschlüssel wird auf NULL gesetzt",
   "Die Tabelle wird bei jedem Löschen gesperrt"), 0,
  "CASCADE räumt abhängige Zeilen automatisch mit weg. Die Alternative RESTRICT verhindert das Löschen, SET NULL leert den Verweis.",
  "What does ON DELETE CASCADE do on a foreign key?",
  ("Dependent records are deleted along with it",
   "Deleting the parent record is prevented",
   "The foreign key is set to NULL",
   "The table is locked on every delete"),
  "CASCADE automatically clears dependent rows too. The alternative RESTRICT prevents the deletion, SET NULL empties the reference."),

S("ap2-db-r29",
  "Wie viele Zeilen liefert ein CROSS JOIN zweier Tabellen mit 10 und 20 Zeilen?",
  ("200", "30", "20", "10"), 0,
  "Der CROSS JOIN bildet das kartesische Produkt: jede Zeile wird mit jeder kombiniert, also 10 mal 20. Meist ist so ein Ergebnis ein vergessenes JOIN-Kriterium.",
  "How many rows does a CROSS JOIN of two tables with 10 and 20 rows return?",
  ("200", "30", "20", "10"),
  "A CROSS JOIN forms the cartesian product: every row combined with every other, i.e. 10 times 20. Usually such a result means a forgotten join condition."),

S("ap2-db-r30",
  "Welche Sicherung erlaubt die Wiederherstellung auf einen beliebigen Zeitpunkt?",
  ("Vollsicherung zusammen mit den Transaktionsprotokollen",
   "Eine reine Vollsicherung ohne weitere Dateien",
   "Ein Export der Tabellenstruktur ohne Daten",
   "Eine Kopie der Konfigurationsdateien des Servers"), 0,
  "Erst die Protokolle erlauben das Nachfahren aller Änderungen bis kurz vor den Schadenszeitpunkt. Ohne sie landet man beim Stand der letzten Vollsicherung.",
  "Which backup allows recovery to an arbitrary point in time?",
  ("Full backup together with the transaction logs",
   "A plain full backup without further files",
   "An export of the table structure without data",
   "A copy of the server's configuration files"),
  "Only the logs allow replaying all changes up to shortly before the incident. Without them you land at the state of the last full backup."),

S("ap2-db-r31",
  "Welche Klausel entfernt doppelte Zeilen aus dem Ergebnis?",
  ("DISTINCT", "GROUP BY", "HAVING", "UNION ALL"), 0,
  "DISTINCT filtert identische Ergebniszeilen heraus. GROUP BY fasst für Aggregate zusammen, und UNION ALL behält Dubletten ausdrücklich.",
  "Which clause removes duplicate rows from the result?",
  ("DISTINCT", "GROUP BY", "HAVING", "UNION ALL"),
  "DISTINCT filters out identical result rows. GROUP BY consolidates for aggregates, and UNION ALL deliberately keeps duplicates."),

S("ap2-db-r32",
  "Ein Auszubildender soll Daten lesen, aber nichts ändern dürfen. Was vergibst du?",
  ("Nur das SELECT-Recht auf die Tabellen",
   "Alle Rechte mit Ausnahme von DROP",
   "Das Recht, eigene Tabellen anzulegen",
   "Administratorrechte auf der Datenbank"), 0,
  "Rechte werden nach dem Prinzip der minimalen Vergabe erteilt. Lesen ohne Schreibrecht deckt den Bedarf ab, ohne Änderungsrisiko zu schaffen.",
  "An apprentice should read data but not be able to change anything. What do you grant?",
  ("Only the SELECT privilege on the tables",
   "All privileges except for DROP",
   "The privilege to create own tables",
   "Administrator privileges on the database"),
  "Privileges are granted following the principle of least privilege. Read without write covers the need without creating any risk of modification."),

# -------------------------------------------------------------- multiple (32)
M("ap2-db-r33",
  "Welche Befehle gehören zur DML?",
  ("INSERT", "UPDATE", "DELETE", "SELECT",
   "CREATE TABLE", "DROP TABLE"),
  (0, 1, 2, 3),
  "Die Data Manipulation Language arbeitet mit den Daten selbst. CREATE und DROP verändern die Struktur und zählen zur DDL.",
  "Which statements belong to DML?",
  ("INSERT", "UPDATE", "DELETE", "SELECT",
   "CREATE TABLE", "DROP TABLE"),
  "The data manipulation language works with the data itself. CREATE and DROP change the structure and belong to DDL."),

M("ap2-db-r34",
  "Welche Eigenschaften beschreiben die ACID-Regeln?",
  ("Atomarität einer Transaktion", "Konsistenz der Daten danach",
   "Isolation paralleler Transaktionen", "Dauerhaftigkeit bestätigter Änderungen",
   "Automatische Indizierung aller Spalten", "Anonymisierung personenbezogener Daten"),
  (0, 1, 2, 3),
  "ACID steht für Atomicity, Consistency, Isolation und Durability - vier Zusagen, die eine Transaktion verlässlich machen. Indizes und Datenschutz sind eigene Themen.",
  "Which properties describe the ACID rules?",
  ("Atomicity of a transaction", "Consistency of the data afterwards",
   "Isolation of parallel transactions", "Durability of committed changes",
   "Automatic indexing of all columns", "Anonymisation of personal data"),
  "ACID stands for atomicity, consistency, isolation and durability - four guarantees that make a transaction reliable. Indexes and data protection are separate topics."),

M("ap2-db-r35",
  "Welche Aussagen über Fremdschlüssel sind korrekt?",
  ("Er verweist auf den Primärschlüssel einer anderen Tabelle",
   "Er sichert die referenzielle Integrität",
   "Er verhindert verwaiste Datensätze",
   "Er kann mehrfach in der Tabelle vorkommen",
   "Er muss innerhalb seiner Tabelle eindeutig sein",
   "Er ersetzt den Primärschlüssel der eigenen Tabelle"),
  (0, 1, 2, 3),
  "Der Fremdschlüssel bildet die Beziehung ab und darf sich wiederholen - viele Bestellungen gehören zu einem Kunden. Eindeutigkeit fordert nur der Primärschlüssel.",
  "Which statements about foreign keys are correct?",
  ("It references the primary key of another table",
   "It secures referential integrity",
   "It prevents orphaned records",
   "It may appear multiple times in the table",
   "It must be unique within its own table",
   "It replaces the primary key of its own table"),
  "The foreign key models the relationship and may repeat - many orders belong to one customer. Only the primary key demands uniqueness."),

M("ap2-db-r36",
  "Welche Aussagen über Indizes sind zutreffend?",
  ("Sie beschleunigen das Suchen in großen Tabellen",
   "Sie belegen zusätzlichen Speicherplatz",
   "Sie verlangsamen Einfüge- und Änderungsvorgänge",
   "Sie lohnen sich besonders auf häufig gefilterten Spalten",
   "Sie beschleunigen jede denkbare Abfrage",
   "Sie ersetzen den Primärschlüssel einer Tabelle"),
  (0, 1, 2, 3),
  "Ein Index ist ein Handel: schnelleres Lesen gegen Speicher und langsameres Schreiben. Wahllos gesetzte Indizes bringen deshalb mehr Nachteile als Nutzen.",
  "Which statements about indexes are correct?",
  ("They speed up searching in large tables",
   "They occupy additional storage space",
   "They slow down inserts and updates",
   "They pay off especially on frequently filtered columns",
   "They speed up every conceivable query",
   "They replace the primary key of a table"),
  "An index is a trade: faster reads for storage and slower writes. Indexes set indiscriminately therefore cause more harm than good."),

M("ap2-db-r37",
  "Welche Anforderungen stellt die erste Normalform?",
  ("Alle Attributwerte sind atomar",
   "Jede Zelle enthält genau einen Wert",
   "Wiederholungsgruppen werden ausgelagert",
   "Die Tabelle besitzt einen Primärschlüssel",
   "Alle Nichtschlüsselattribute hängen vom Gesamtschlüssel ab",
   "Es gibt keine transitiven Abhängigkeiten mehr"),
  (0, 1, 2, 3),
  "Die erste Normalform verlangt Atomarität und identifizierbare Zeilen. Volle Abhängigkeit vom Schlüssel fordert die zweite, Transitivfreiheit die dritte Normalform.",
  "Which requirements does the first normal form impose?",
  ("All attribute values are atomic",
   "Each cell contains exactly one value",
   "Repeating groups are moved out",
   "The table has a primary key",
   "All non-key attributes depend on the whole key",
   "There are no transitive dependencies left"),
  "The first normal form requires atomicity and identifiable rows. Full dependency on the key is the second normal form, freedom from transitivity the third."),

M("ap2-db-r38",
  "Welche JOIN-Arten kennt SQL?",
  ("INNER JOIN", "LEFT OUTER JOIN", "RIGHT OUTER JOIN", "FULL OUTER JOIN",
   "UPPER JOIN", "GROUP JOIN"),
  (0, 1, 2, 3),
  "Inner und die drei Outer-Varianten decken die üblichen Fälle ab, ergänzt um CROSS JOIN. UPPER und GROUP JOIN gibt es nicht.",
  "Which join types does SQL know?",
  ("INNER JOIN", "LEFT OUTER JOIN", "RIGHT OUTER JOIN", "FULL OUTER JOIN",
   "UPPER JOIN", "GROUP JOIN"),
  "Inner and the three outer variants cover the usual cases, plus CROSS JOIN. UPPER and GROUP JOIN do not exist."),

M("ap2-db-r39",
  "Welche Angaben gehören in ein ER-Modell?",
  ("Entitätstypen mit ihren Attributen",
   "Beziehungen zwischen den Entitätstypen",
   "Kardinalitäten der Beziehungen",
   "Kennzeichnung der Schlüsselattribute",
   "Die Namen der Datenbankbenutzer",
   "Der Speicherort der Datenbankdateien"),
  (0, 1, 2, 3),
  "Das ER-Modell beschreibt die fachliche Struktur: Entitäten, Attribute, Beziehungen und Kardinalitäten. Benutzer und Ablageorte sind Betriebsdetails.",
  "Which items belong in an ER model?",
  ("Entity types with their attributes",
   "Relationships between the entity types",
   "Cardinalities of the relationships",
   "Marking of the key attributes",
   "The names of the database users",
   "The storage location of the database files"),
  "The ER model describes the business structure: entities, attributes, relationships and cardinalities. Users and storage locations are operational details."),

M("ap2-db-r40",
  "Welche Aggregatfunktionen kennt SQL?",
  ("COUNT", "SUM", "AVG", "MAX",
   "SORT", "FILTER"),
  (0, 1, 2, 3),
  "COUNT, SUM, AVG, MIN und MAX fassen mehrere Zeilen zu einem Wert zusammen. SORT und FILTER sind keine SQL-Funktionen - dafür stehen ORDER BY und WHERE.",
  "Which aggregate functions does SQL know?",
  ("COUNT", "SUM", "AVG", "MAX",
   "SORT", "FILTER"),
  "COUNT, SUM, AVG, MIN and MAX condense several rows into one value. SORT and FILTER are not SQL functions - ORDER BY and WHERE serve those purposes."),

M("ap2-db-r41",
  "Welche Vorteile bringt die Normalisierung einer Datenbank?",
  ("Redundanz wird verringert",
   "Änderungsanomalien werden vermieden",
   "Die Datenkonsistenz steigt",
   "Der Speicherbedarf sinkt tendenziell",
   "Jede Abfrage wird dadurch schneller",
   "Die Anzahl der Tabellen sinkt"),
  (0, 1, 2, 3),
  "Weniger Redundanz bedeutet weniger Widersprüche und weniger Speicher. Der Preis sind mehr Tabellen und damit mehr Joins, die Abfragen eher verlangsamen.",
  "Which advantages come from normalising a database?",
  ("Redundancy is reduced",
   "Update anomalies are avoided",
   "Data consistency increases",
   "Storage requirements tend to fall",
   "Every query becomes faster as a result",
   "The number of tables decreases"),
  "Less redundancy means fewer contradictions and less storage. The price is more tables and therefore more joins, which tend to slow queries down."),

M("ap2-db-r42",
  "Welche Constraints lassen sich auf einer Spalte definieren?",
  ("NOT NULL gegen leere Werte", "UNIQUE gegen Doppelungen",
   "CHECK für eine Wertebedingung", "DEFAULT für einen Vorgabewert",
   "SORTED für automatische Sortierung", "FASTER für schnelleren Zugriff"),
  (0, 1, 2, 3),
  "NOT NULL, UNIQUE, CHECK und DEFAULT sichern Datenqualität schon beim Schreiben. SORTED und FASTER existieren nicht.",
  "Which constraints can be defined on a column?",
  ("NOT NULL against empty values", "UNIQUE against duplicates",
   "CHECK for a value condition", "DEFAULT for a preset value",
   "SORTED for automatic sorting", "FASTER for quicker access"),
  "NOT NULL, UNIQUE, CHECK and DEFAULT secure data quality at write time. SORTED and FASTER do not exist."),

M("ap2-db-r43",
  "Welche Aussagen über Transaktionen sind richtig?",
  ("Sie fassen mehrere Anweisungen zu einer Einheit zusammen",
   "COMMIT schreibt sie endgültig fest",
   "ROLLBACK verwirft alle Änderungen",
   "Sie sichern die Konsistenz bei Fehlern",
   "Sie beschleunigen die Ausführung der Anweisungen",
   "Sie ersetzen die Datensicherung der Datenbank"),
  (0, 1, 2, 3),
  "Transaktionen bündeln Anweisungen und machen sie gemeinsam gültig oder ungültig. Auf Geschwindigkeit wirken sie nicht, und eine Sicherung ersetzen sie erst recht nicht.",
  "Which statements about transactions are correct?",
  ("They group several statements into one unit",
   "COMMIT makes them permanent",
   "ROLLBACK discards all changes",
   "They preserve consistency when errors occur",
   "They speed up execution of the statements",
   "They replace the database backup"),
  "Transactions bundle statements and make them jointly valid or invalid. They do not affect speed, and they certainly do not replace a backup."),

M("ap2-db-r44",
  "Welche Systeme sind relationale Datenbankmanagementsysteme?",
  ("MySQL", "PostgreSQL", "MariaDB", "Microsoft SQL Server",
   "Redis", "MongoDB"),
  (0, 1, 2, 3),
  "Die ersten vier speichern in Tabellen und sprechen SQL. Redis ist ein Key-Value-Store und MongoDB eine Dokumentendatenbank.",
  "Which systems are relational database management systems?",
  ("MySQL", "PostgreSQL", "MariaDB", "Microsoft SQL Server",
   "Redis", "MongoDB"),
  "The first four store data in tables and speak SQL. Redis is a key-value store and MongoDB a document database."),

M("ap2-db-r45",
  "Welche Maßnahmen schützen eine Datenbank vor Datenverlust?",
  ("Regelmäßige Vollsicherungen", "Sicherung der Transaktionsprotokolle",
   "Getrennte Aufbewahrung der Sicherungen", "Regelmäßige Rückspieltests",
   "Ein zusätzlicher Index auf jeder Tabelle", "Der Verzicht auf Fremdschlüssel"),
  (0, 1, 2, 3),
  "Sicherungen, Protokolle, räumliche Trennung und geprüfte Wiederherstellung sind das Fundament. Indizes und Schlüssel betreffen Leistung und Integrität, nicht den Verlustschutz.",
  "Which measures protect a database against data loss?",
  ("Regular full backups", "Backup of the transaction logs",
   "Separate storage of the backups", "Regular restore tests",
   "An additional index on every table", "Doing without foreign keys"),
  "Backups, logs, physical separation and verified restores are the foundation. Indexes and keys concern performance and integrity, not loss protection."),

M("ap2-db-r46",
  "Welche Aussagen über NULL in SQL sind zutreffend?",
  ("NULL bedeutet unbekannt, nicht null",
   "Ein Vergleich mit dem Gleichheitszeichen schlägt fehl",
   "Geprüft wird mit IS NULL",
   "Aggregatfunktionen überspringen NULL-Werte meist",
   "NULL entspricht der Zahl null",
   "NULL entspricht einer leeren Zeichenkette"),
  (0, 1, 2, 3),
  "NULL steht für einen fehlenden Wert und ist weder null noch Leerstring. Deshalb braucht es IS NULL statt eines Gleichheitsvergleichs.",
  "Which statements about NULL in SQL are correct?",
  ("NULL means unknown, not zero",
   "A comparison with the equals sign fails",
   "It is tested with IS NULL",
   "Aggregate functions usually skip NULL values",
   "NULL equals the number zero",
   "NULL equals an empty string"),
  "NULL stands for a missing value and is neither zero nor an empty string. That is why IS NULL is needed instead of an equality comparison."),

M("ap2-db-r47",
  "Welche Aussagen über Views sind korrekt?",
  ("Sie speichern eine Abfrage unter einem Namen",
   "Sie liefern beim Zugriff aktuelle Daten",
   "Sie vereinfachen komplexe Abfragen",
   "Sie können Spalten gezielt ausblenden",
   "Sie halten eine eigene Kopie der Daten",
   "Sie machen Indizes grundsätzlich überflüssig"),
  (0, 1, 2, 3),
  "Eine View ist im Kern eine benannte Abfrage - deshalb sieht sie immer die aktuellen Daten und eignet sich zur gezielten Einschränkung des Zugriffs. Eigene Daten hält sie nicht.",
  "Which statements about views are correct?",
  ("They store a query under a name",
   "They deliver current data on access",
   "They simplify complex queries",
   "They can deliberately hide columns",
   "They keep their own copy of the data",
   "They fundamentally make indexes unnecessary"),
  "A view is essentially a named query - which is why it always sees current data and suits restricting access. It holds no data of its own."),

M("ap2-db-r48",
  "Welche Schritte gehören zum Entwurf einer relationalen Datenbank?",
  ("Anforderungen und Datenobjekte erheben",
   "Ein ER-Modell mit Beziehungen erstellen",
   "Das Modell in Tabellen überführen",
   "Die Tabellen normalisieren",
   "Zuerst willkürlich Indizes anlegen",
   "Erst nach dem Betrieb die Schlüssel festlegen"),
  (0, 1, 2, 3),
  "Analyse, Modellierung, Überführung und Normalisierung ergeben ein tragfähiges Schema. Indizes kommen erst danach, wenn das Abfrageverhalten bekannt ist.",
  "Which steps belong to designing a relational database?",
  ("Gather requirements and data objects",
   "Create an ER model with relationships",
   "Transfer the model into tables",
   "Normalise the tables",
   "Create arbitrary indexes first",
   "Define keys only after going live"),
  "Analysis, modelling, transfer and normalisation produce a sound schema. Indexes come afterwards, once query behaviour is known."),

M("ap2-db-r49",
  "Welche Aussagen zur Auflösung einer n:m-Beziehung sind richtig?",
  ("Es entsteht eine zusätzliche Zwischentabelle",
   "Sie enthält die Fremdschlüssel beider Seiten",
   "Aus einer n:m werden zwei 1:n-Beziehungen",
   "Die Zwischentabelle kann eigene Attribute haben",
   "Eine der Ursprungstabellen entfällt dabei",
   "Die Beziehung lässt sich ohne Zwischentabelle abbilden"),
  (0, 1, 2, 3),
  "Die Zwischentabelle trägt beide Fremdschlüssel und oft eigene Angaben wie Menge oder Datum. Beide Ursprungstabellen bleiben erhalten.",
  "Which statements about resolving an n:m relationship are correct?",
  ("An additional junction table is created",
   "It holds the foreign keys of both sides",
   "One n:m becomes two 1:n relationships",
   "The junction table can have own attributes",
   "One of the original tables disappears",
   "The relationship can be modelled without a junction table"),
  "The junction table carries both foreign keys and often its own details such as quantity or date. Both original tables remain."),

M("ap2-db-r50",
  "Welche Aussagen über die Reihenfolge einer SELECT-Anweisung sind korrekt?",
  ("FROM bestimmt die Datenquelle",
   "WHERE filtert einzelne Zeilen",
   "GROUP BY fasst Zeilen zu Gruppen zusammen",
   "HAVING filtert die gebildeten Gruppen",
   "ORDER BY wirkt vor der Gruppierung",
   "WHERE darf Aggregatfunktionen enthalten"),
  (0, 1, 2, 3),
  "Die logische Reihenfolge lautet FROM, WHERE, GROUP BY, HAVING und zuletzt ORDER BY. Aggregate stehen deshalb in HAVING, nicht in WHERE.",
  "Which statements about the order of a SELECT statement are correct?",
  ("FROM determines the data source",
   "WHERE filters individual rows",
   "GROUP BY consolidates rows into groups",
   "HAVING filters the resulting groups",
   "ORDER BY acts before the grouping",
   "WHERE may contain aggregate functions"),
  "The logical order is FROM, WHERE, GROUP BY, HAVING and finally ORDER BY. Aggregates therefore belong in HAVING, not in WHERE."),

M("ap2-db-r51",
  "Welche Gründe sprechen für eine NoSQL-Datenbank?",
  ("Sehr große, schnell wachsende Datenmengen",
   "Flexible Struktur ohne festes Schema",
   "Horizontale Verteilung auf viele Knoten",
   "Speicherung schwach strukturierter Daten",
   "Strenge Einhaltung aller ACID-Zusagen",
   "Komplexe Joins über viele Tabellen"),
  (0, 1, 2, 3),
  "NoSQL punktet bei Menge, Flexibilität und Verteilung. Wer starke Transaktionszusagen und komplexe Joins braucht, ist mit einem relationalen System besser bedient.",
  "Which reasons argue for a NoSQL database?",
  ("Very large, rapidly growing data volumes",
   "Flexible structure without a fixed schema",
   "Horizontal distribution across many nodes",
   "Storage of weakly structured data",
   "Strict adherence to all ACID guarantees",
   "Complex joins across many tables"),
  "NoSQL scores on volume, flexibility and distribution. Anyone needing strong transactional guarantees and complex joins is better served by a relational system."),

M("ap2-db-r52",
  "Welche Aussagen über Schlüsselarten sind zutreffend?",
  ("Ein Kandidatenschlüssel identifiziert eindeutig",
   "Der Primärschlüssel wird aus den Kandidaten gewählt",
   "Ein zusammengesetzter Schlüssel umfasst mehrere Spalten",
   "Ein Fremdschlüssel verweist auf eine andere Tabelle",
   "Eine Tabelle darf mehrere Primärschlüssel haben",
   "Ein Primärschlüssel darf NULL-Werte enthalten"),
  (0, 1, 2, 3),
  "Aus den Kandidatenschlüsseln wird genau einer zum Primärschlüssel bestimmt, notfalls über mehrere Spalten. Mehrere Primärschlüssel oder NULL sind ausgeschlossen.",
  "Which statements about key types are correct?",
  ("A candidate key identifies uniquely",
   "The primary key is chosen from the candidates",
   "A composite key spans several columns",
   "A foreign key references another table",
   "A table may have several primary keys",
   "A primary key may contain NULL values"),
  "Exactly one of the candidate keys becomes the primary key, if necessary spanning several columns. Several primary keys or NULL are ruled out."),

M("ap2-db-r53",
  "Welche Aussagen über die zweite Normalform sind richtig?",
  ("Die erste Normalform ist Voraussetzung",
   "Nichtschlüsselattribute hängen vom gesamten Schlüssel ab",
   "Teilabhängigkeiten werden aufgelöst",
   "Sie ist besonders bei zusammengesetzten Schlüsseln relevant",
   "Sie verlangt den Verzicht auf Fremdschlüssel",
   "Sie beseitigt transitive Abhängigkeiten"),
  (0, 1, 2, 3),
  "Die zweite Normalform beseitigt Abhängigkeiten von nur einem Teil des Schlüssels und ist deshalb nur bei zusammengesetzten Schlüsseln ein Thema. Transitivität behandelt erst die dritte.",
  "Which statements about the second normal form are correct?",
  ("The first normal form is a prerequisite",
   "Non-key attributes depend on the whole key",
   "Partial dependencies are resolved",
   "It matters especially with composite keys",
   "It requires doing without foreign keys",
   "It removes transitive dependencies"),
  "The second normal form removes dependencies on only part of the key and therefore only matters with composite keys. Transitivity is handled by the third."),

M("ap2-db-r54",
  "Welche Maßnahmen erhöhen die Sicherheit einer Datenbank?",
  ("Rechte nach dem Prinzip der minimalen Vergabe",
   "Eigene Konten statt gemeinsam genutzter Zugänge",
   "Verschlüsselte Verbindungen zum Datenbankserver",
   "Regelmäßige Aktualisierung des Datenbanksystems",
   "Ein gemeinsames Administratorkonto für alle",
   "Direkter Zugriff auf die Datenbank aus dem Internet"),
  (0, 1, 2, 3),
  "Minimale Rechte, personenbezogene Konten, verschlüsselte Verbindungen und Patches sind die Grundlagen. Sammelkonten und offene Erreichbarkeit sind das Gegenteil davon.",
  "Which measures increase the security of a database?",
  ("Privileges following the least privilege principle",
   "Individual accounts instead of shared logins",
   "Encrypted connections to the database server",
   "Regular updates of the database system",
   "One shared administrator account for everyone",
   "Direct access to the database from the internet"),
  "Least privilege, individual accounts, encrypted connections and patches are the basics. Shared accounts and open exposure are the opposite."),

M("ap2-db-r55",
  "Welche Aussagen über den INNER JOIN sind korrekt?",
  ("Er liefert nur Zeilen mit Treffern in beiden Tabellen",
   "Zeilen ohne Partner entfallen im Ergebnis",
   "Die Verknüpfungsbedingung steht in der ON-Klausel",
   "Er ist der am häufigsten genutzte JOIN-Typ",
   "Er ergänzt fehlende Partner mit NULL",
   "Er liefert immer das kartesische Produkt"),
  (0, 1, 2, 3),
  "Der INNER JOIN behält nur Paare, die die Bedingung erfüllen. NULL-Auffüllung leisten die OUTER-Varianten, das kartesische Produkt der CROSS JOIN.",
  "Which statements about the INNER JOIN are correct?",
  ("It returns only rows with matches in both tables",
   "Rows without a partner drop out of the result",
   "The join condition sits in the ON clause",
   "It is the most frequently used join type",
   "It fills missing partners with NULL",
   "It always returns the cartesian product"),
  "The INNER JOIN keeps only pairs satisfying the condition. NULL padding is done by the outer variants, the cartesian product by the CROSS JOIN."),

M("ap2-db-r56",
  "Welche Angaben braucht eine CREATE-TABLE-Anweisung mindestens?",
  ("Den Namen der Tabelle", "Die Namen der Spalten",
   "Die Datentypen der Spalten", "Sinnvollerweise einen Primärschlüssel",
   "Die Anzahl der später erwarteten Zeilen", "Den Namen des zuständigen Entwicklers"),
  (0, 1, 2, 3),
  "Tabellenname, Spalten und Datentypen sind zwingend, ein Primärschlüssel ist praktisch immer sinnvoll. Zeilenzahl und Zuständigkeit gehören nicht in die Definition.",
  "Which details does a CREATE TABLE statement need at minimum?",
  ("The name of the table", "The names of the columns",
   "The data types of the columns", "Sensibly a primary key",
   "The number of rows expected later", "The name of the responsible developer"),
  "Table name, columns and data types are mandatory, and a primary key is practically always sensible. Row counts and ownership do not belong in the definition."),

M("ap2-db-r57",
  "Welche Ursachen können eine langsame Datenbankabfrage erklären?",
  ("Fehlende Indizes auf gefilterten Spalten",
   "Ein vergessenes JOIN-Kriterium",
   "Sehr große Ergebnismengen ohne Einschränkung",
   "Ungünstig formulierte Unterabfragen",
   "Ein zu kurzer Tabellenname", "Eine zu helle Bildschirmeinstellung"),
  (0, 1, 2, 3),
  "Fehlende Indizes, vergessene Verknüpfungen, riesige Ergebnismengen und schlecht gebaute Unterabfragen sind die üblichen Verdächtigen. Namen und Anzeige spielen keine Rolle.",
  "Which causes can explain a slow database query?",
  ("Missing indexes on filtered columns",
   "A forgotten join condition",
   "Very large result sets without restriction",
   "Poorly formulated subqueries",
   "Too short a table name", "Too bright a screen setting"),
  "Missing indexes, forgotten joins, huge result sets and badly built subqueries are the usual suspects. Names and display play no role."),

M("ap2-db-r58",
  "Welche Befehle gehören zur DDL?",
  ("CREATE TABLE", "ALTER TABLE", "DROP TABLE", "CREATE INDEX",
   "SELECT", "COMMIT"),
  (0, 1, 2, 3),
  "Die Data Definition Language beschreibt die Struktur der Datenbank. SELECT gehört zur DML und COMMIT zur Transaktionssteuerung.",
  "Which statements belong to DDL?",
  ("CREATE TABLE", "ALTER TABLE", "DROP TABLE", "CREATE INDEX",
   "SELECT", "COMMIT"),
  "The data definition language describes the structure of the database. SELECT belongs to DML and COMMIT to transaction control."),

M("ap2-db-r59",
  "Welche Aussagen über Datentypen in SQL sind zutreffend?",
  ("VARCHAR speichert Text variabler Länge",
   "INTEGER speichert Ganzzahlen",
   "DECIMAL rechnet mit fester Nachkommastellenzahl",
   "DATE speichert ein Kalenderdatum",
   "FLOAT eignet sich am besten für Geldbeträge",
   "VARCHAR eignet sich am besten für Rechenoperationen"),
  (0, 1, 2, 3),
  "Der passende Typ sichert Speicherplatz und Rechengenauigkeit. Für Geld ist DECIMAL Pflicht, weil FLOAT binär rundet, und mit Text lässt sich nicht rechnen.",
  "Which statements about SQL data types are correct?",
  ("VARCHAR stores text of variable length",
   "INTEGER stores whole numbers",
   "DECIMAL computes with a fixed number of decimals",
   "DATE stores a calendar date",
   "FLOAT is best suited to monetary amounts",
   "VARCHAR is best suited to arithmetic operations"),
  "The right type secures storage and computational accuracy. For money DECIMAL is mandatory because FLOAT rounds in binary, and text cannot be used for arithmetic."),

M("ap2-db-r60",
  "Welche Aussagen über die dritte Normalform sind korrekt?",
  ("Die zweite Normalform ist Voraussetzung",
   "Transitive Abhängigkeiten werden beseitigt",
   "Nichtschlüsselattribute hängen nur vom Schlüssel ab",
   "Betroffene Attribute wandern in eine eigene Tabelle",
   "Sie erlaubt wieder Wiederholungsgruppen",
   "Sie verlangt den Verzicht auf Primärschlüssel"),
  (0, 1, 2, 3),
  "Hängt ein Attribut über ein anderes Nichtschlüsselattribut vom Schlüssel ab, wird es ausgelagert. Wiederholungsgruppen und fehlende Schlüssel widersprechen den vorherigen Normalformen.",
  "Which statements about the third normal form are correct?",
  ("The second normal form is a prerequisite",
   "Transitive dependencies are eliminated",
   "Non-key attributes depend only on the key",
   "Affected attributes move into their own table",
   "It permits repeating groups again",
   "It requires doing without primary keys"),
  "If an attribute depends on the key via another non-key attribute, it is moved out. Repeating groups and missing keys contradict the earlier normal forms."),

M("ap2-db-r61",
  "Welche Aussagen über Sperren in Datenbanken sind richtig?",
  ("Sie verhindern widersprüchliche gleichzeitige Änderungen",
   "Lesesperren und Schreibsperren werden unterschieden",
   "Zu lange gehaltene Sperren bremsen andere Transaktionen",
   "Gegenseitiges Warten kann zu einem Deadlock führen",
   "Sperren beschleunigen die Ausführung von Abfragen",
   "Sperren ersetzen die Rechteverwaltung der Datenbank"),
  (0, 1, 2, 3),
  "Sperren sichern die Isolation, kosten aber Parallelität - deshalb sollen Transaktionen kurz sein. Mit Rechteverwaltung haben sie nichts zu tun.",
  "Which statements about database locks are correct?",
  ("They prevent contradictory simultaneous changes",
   "Read locks and write locks are distinguished",
   "Locks held too long slow other transactions",
   "Mutual waiting can lead to a deadlock",
   "Locks speed up the execution of queries",
   "Locks replace the database privilege system"),
  "Locks secure isolation but cost concurrency - which is why transactions should be short. They have nothing to do with privilege management."),

M("ap2-db-r62",
  "Welche Aussagen über Datensicherung von Datenbanken sind zutreffend?",
  ("Eine Vollsicherung erfasst den gesamten Bestand",
   "Transaktionsprotokolle erlauben zeitpunktgenaue Wiederherstellung",
   "Die Wiederherstellung sollte geprüft werden",
   "Sicherungen gehören an einen getrennten Ort",
   "Ein Export der Struktur allein genügt als Sicherung",
   "Sicherungen im laufenden Betrieb sind grundsätzlich unmöglich"),
  (0, 1, 2, 3),
  "Voll plus Protokolle, getrennt gelagert und regelmäßig getestet ergibt ein belastbares Konzept. Die Struktur allein enthält keine Daten, und Online-Sicherungen sind längst Standard.",
  "Which statements about database backups are correct?",
  ("A full backup captures the entire dataset",
   "Transaction logs allow point-in-time recovery",
   "The restore should be verified",
   "Backups belong at a separate location",
   "Exporting the structure alone suffices as a backup",
   "Backups during operation are fundamentally impossible"),
  "Full plus logs, stored separately and tested regularly gives a sound concept. The structure alone contains no data, and online backups have long been standard."),

M("ap2-db-r63",
  "Welche Aussagen über Aggregatfunktionen und GROUP BY sind korrekt?",
  ("Aggregate fassen mehrere Zeilen zu einem Wert zusammen",
   "GROUP BY bildet die Gruppen für die Aggregation",
   "Nicht aggregierte Spalten gehören in die GROUP-BY-Klausel",
   "HAVING filtert anhand der Aggregatergebnisse",
   "Aggregate lassen sich in WHERE verwenden",
   "GROUP BY sortiert das Ergebnis automatisch aufsteigend"),
  (0, 1, 2, 3),
  "Aggregat und GROUP BY gehören zusammen, gefiltert wird danach mit HAVING. In WHERE stehen Aggregate nicht, und für eine Sortierung braucht es ORDER BY.",
  "Which statements about aggregate functions and GROUP BY are correct?",
  ("Aggregates condense several rows into one value",
   "GROUP BY forms the groups for aggregation",
   "Non-aggregated columns belong in the GROUP BY clause",
   "HAVING filters based on the aggregate results",
   "Aggregates can be used in WHERE",
   "GROUP BY automatically sorts the result ascending"),
  "Aggregate and GROUP BY belong together, with HAVING filtering afterwards. Aggregates do not belong in WHERE, and sorting requires ORDER BY."),

M("ap2-db-r64",
  "Welche Angaben gehören in die Dokumentation eines Datenbankschemas?",
  ("Tabellen mit ihren Spalten und Datentypen",
   "Schlüssel und Beziehungen zwischen Tabellen",
   "Bedeutung fachlich unklarer Spalten",
   "Bekannte Einschränkungen und Besonderheiten",
   "Die Passwörter der Datenbankbenutzer",
   "Die Uhrzeit der letzten Kaffeepause"),
  (0, 1, 2, 3),
  "Struktur, Beziehungen, fachliche Bedeutung und Besonderheiten machen ein Schema für andere nutzbar. Zugangsdaten gehören niemals in eine Dokumentation.",
  "Which details belong in the documentation of a database schema?",
  ("Tables with their columns and data types",
   "Keys and relationships between tables",
   "Meaning of columns that are unclear in business terms",
   "Known limitations and peculiarities",
   "The passwords of the database users",
   "The time of the last coffee break"),
  "Structure, relationships, business meaning and peculiarities make a schema usable by others. Credentials never belong in documentation."),

# ------------------------------------------------------------------ text (36)
T("ap2-db-r65", "Welcher JOIN liefert nur Datensätze mit Treffern in beiden Tabellen?", "INNER JOIN",
  "Zeilen ohne passenden Partner fallen dabei aus dem Ergebnis heraus.",
  "Which join returns only records with matches in both tables?", "INNER JOIN",
  "Rows without a matching partner drop out of the result."),

T("ap2-db-r66", "Welche SQL-Funktion zählt die Zeilen eines Abfrageergebnisses?", "COUNT",
  "COUNT(*) zählt alle Zeilen, COUNT(spalte) überspringt NULL-Werte in dieser Spalte.",
  "Which SQL function counts the rows of a query result?", "COUNT",
  "COUNT(*) counts all rows, COUNT(column) skips NULL values in that column."),

T("ap2-db-r67", "Welche Normalform verlangt atomare Werte in jeder Zelle?", "1NF",
  "Mehrere Werte in einer Zelle, etwa mehrere Telefonnummern, verstoßen dagegen.",
  "Which normal form requires atomic values in every cell?", "1NF",
  "Several values in one cell, such as multiple phone numbers, violate it."),

T("ap2-db-r68", "Welcher Befehl macht Änderungen einer Transaktion dauerhaft?", "COMMIT",
  "Erst danach sind sie für andere Transaktionen sichtbar und überstehen einen Absturz.",
  "Which statement makes a transaction's changes permanent?", "COMMIT",
  "Only afterwards are they visible to other transactions and survive a crash."),

T("ap2-db-r69", "Wie prüft man in SQL korrekt auf einen fehlenden Wert?", "IS NULL",
  "Ein Vergleich mit dem Gleichheitszeichen scheitert, weil NULL unbekannt bedeutet.",
  "How do you correctly test for a missing value in SQL?", "IS NULL",
  "A comparison with the equals sign fails because NULL means unknown."),

T("ap2-db-r70", "Wofür steht das A in den ACID-Eigenschaften?", "Atomarität",
  "Eine Transaktion wird ganz oder gar nicht ausgeführt - im Fehlerfall folgt der Rollback.",
  "What does the A in the ACID properties stand for?", "Atomicity",
  "A transaction runs completely or not at all - on error a rollback follows."),

T("ap2-db-r71", "Welches Datenbankobjekt speichert eine Abfrage unter einem Namen?", "View",
  "Sie hält keine eigenen Daten und liefert bei jedem Zugriff den aktuellen Stand.",
  "Which database object stores a query under a name?", "View",
  "It holds no data of its own and delivers the current state on every access."),

T("ap2-db-r72", "Wie viele Zeilen liefert ein CROSS JOIN von 5 mal 6 Zeilen?", "30",
  "Das kartesische Produkt kombiniert jede Zeile mit jeder: 5 mal 6 ergibt 30.",
  "How many rows does a CROSS JOIN of 5 by 6 rows return?", "30",
  "The cartesian product combines every row with every other: 5 times 6 gives 30."),

T("ap2-db-r73", "Welcher Schlüssel verweist auf den Primärschlüssel einer anderen Tabelle?", "Fremdschlüssel",
  "Er bildet die Beziehung ab und sichert zusammen mit der Datenbank die referenzielle Integrität.",
  "Which key references the primary key of another table?", "Foreign key",
  "It models the relationship and, together with the database, secures referential integrity."),

T("ap2-db-r74", "Welche Klausel filtert erst nach der Gruppierung?", "HAVING",
  "WHERE wirkt vorher auf einzelne Zeilen; nur HAVING darf Aggregatfunktionen enthalten.",
  "Which clause filters only after grouping?", "HAVING",
  "WHERE acts beforehand on individual rows; only HAVING may contain aggregate functions."),

T("ap2-db-r75", "Welcher Datentyp eignet sich für Geldbeträge mit exakter Nachkommastelle?", "DECIMAL",
  "FLOAT rundet binär und erzeugt bei Geldbeträgen Abweichungen im Centbereich.",
  "Which data type suits monetary amounts with exact decimals?", "DECIMAL",
  "FLOAT rounds in binary and produces cent-level deviations for monetary values."),

T("ap2-db-r76", "Wie wird eine n:m-Beziehung im relationalen Modell aufgelöst?", "Zwischentabelle",
  "Sie nimmt die Fremdschlüssel beider Seiten auf und macht daraus zwei 1:n-Beziehungen.",
  "How is an n:m relationship resolved in the relational model?", "Junction table",
  "It holds the foreign keys of both sides and turns them into two 1:n relationships."),

T("ap2-db-r77", "Welcher Befehl entzieht einem Benutzer ein Recht?", "REVOKE",
  "Das Gegenstück ist GRANT; beide gehören zur Data Control Language.",
  "Which statement withdraws a privilege from a user?", "REVOKE",
  "Its counterpart is GRANT; both belong to the data control language."),

T("ap2-db-r78", "Wie nennt man das gegenseitige Blockieren zweier Transaktionen?", "Deadlock",
  "Das Datenbanksystem erkennt die Situation und rollt eine der beteiligten Transaktionen zurück.",
  "What is two transactions blocking each other called?", "Deadlock",
  "The database system detects the situation and rolls one of the involved transactions back."),

T("ap2-db-r79", "Welche Normalform beseitigt transitive Abhängigkeiten?", "3NF",
  "Hängt ein Attribut über ein anderes Nichtschlüsselattribut vom Schlüssel ab, wird es ausgelagert.",
  "Which normal form eliminates transitive dependencies?", "3NF",
  "If an attribute depends on the key via another non-key attribute, it is moved out."),

T("ap2-db-r80", "Welcher Platzhalter steht in LIKE für beliebig viele Zeichen?", "%",
  "Der Unterstrich steht dagegen für genau ein einzelnes Zeichen.",
  "Which wildcard stands for any number of characters in LIKE?", "%",
  "The underscore by contrast stands for exactly one single character."),

T("ap2-db-r81", "Welcher Befehl entfernt eine Tabelle samt Struktur?", "DROP TABLE",
  "DELETE und TRUNCATE entfernen dagegen nur die Zeilen und lassen die Tabelle bestehen.",
  "Which statement removes a table including its structure?", "DROP TABLE",
  "DELETE and TRUNCATE by contrast remove only the rows and leave the table in place."),

T("ap2-db-r82", "Welche Kardinalität hat die Beziehung zwischen Bestellung und Kunde?", "n:1",
  "Viele Bestellungen gehören zu einem Kunden; aus Sicht des Kunden ist es eine 1:n-Beziehung.",
  "Which cardinality does the relationship between order and customer have?", "n:1",
  "Many orders belong to one customer; from the customer's side it is a 1:n relationship."),

T("ap2-db-r83", "Welches Datenbankobjekt beschleunigt die Suche auf einer Spalte?", "Index",
  "Er kostet Speicher und verlangsamt Schreibvorgänge, beschleunigt aber gezielte Zugriffe erheblich.",
  "Which database object speeds up searching on a column?", "Index",
  "It costs storage and slows writes but considerably speeds up targeted access."),

T("ap2-db-r84", "Welcher Befehl verwirft alle Änderungen einer offenen Transaktion?", "ROLLBACK",
  "Er rettet auch ein versehentliches UPDATE ohne WHERE, solange noch nicht bestätigt wurde.",
  "Which statement discards all changes of an open transaction?", "ROLLBACK",
  "It even rescues an accidental UPDATE without WHERE, as long as nothing was committed."),

T("ap2-db-r85", "Wofür steht das D in ACID?", "Dauerhaftigkeit",
  "Bestätigte Änderungen überstehen auch einen Systemabsturz, weil sie protokolliert wurden.",
  "What does the D in ACID stand for?", "Durability",
  "Committed changes survive even a system crash because they were logged."),

T("ap2-db-r86", "Welche Klausel entfernt doppelte Zeilen aus einem Ergebnis?", "DISTINCT",
  "UNION entfernt Dubletten ebenfalls, UNION ALL behält sie dagegen ausdrücklich.",
  "Which clause removes duplicate rows from a result?", "DISTINCT",
  "UNION also removes duplicates, while UNION ALL deliberately keeps them."),

T("ap2-db-r87", "Welche Dateien erlauben zusammen mit einer Vollsicherung die zeitpunktgenaue Wiederherstellung?", "Transaktionsprotokolle",
  "Sie erlauben das Nachfahren aller Änderungen bis kurz vor den Schadenszeitpunkt.",
  "Which files, together with a full backup, allow point-in-time recovery?", "Transaction logs",
  "They allow replaying all changes up to shortly before the incident."),

T("ap2-db-r88", "Welche Bedingung verhindert leere Werte in einer Spalte?", "NOT NULL",
  "Sie sichert schon beim Schreiben zu, dass ein Wert vorhanden ist.",
  "Which constraint prevents empty values in a column?", "NOT NULL",
  "It guarantees at write time that a value is present."),

T("ap2-db-r89", "Welcher JOIN behält alle Zeilen der linken Tabelle?", "LEFT JOIN",
  "Fehlende Partner der rechten Seite werden im Ergebnis mit NULL aufgefüllt.",
  "Which join keeps all rows of the left table?", "LEFT JOIN",
  "Missing partners on the right side are filled with NULL in the result."),

T("ap2-db-r90", "Welche Sprachfamilie in SQL umfasst GRANT und REVOKE?", "DCL",
  "Die Data Control Language regelt Rechte an Datenbankobjekten.",
  "Which SQL language family comprises GRANT and REVOKE?", "DCL",
  "The data control language governs privileges on database objects."),

T("ap2-db-r91", "Welche Funktion liefert den Durchschnitt einer Zahlenspalte?", "AVG",
  "NULL-Werte werden dabei übersprungen und fließen nicht in den Mittelwert ein.",
  "Which function returns the average of a numeric column?", "AVG",
  "NULL values are skipped and do not enter the average."),

T("ap2-db-r92", "Welche Datenbankart speichert Daten als Schlüssel-Wert-Paare im Arbeitsspeicher?", "Key-Value-Store",
  "Redis ist der bekannteste Vertreter und wird oft als schneller Zwischenspeicher eingesetzt.",
  "Which kind of database stores data as key-value pairs in memory?", "Key-value store",
  "Redis is the best-known representative and is often used as a fast cache."),

T("ap2-db-r93", "Welche Option löscht abhängige Datensätze beim Entfernen des Hauptsatzes mit?", "ON DELETE CASCADE",
  "Die Alternative RESTRICT verhindert das Löschen, solange abhängige Zeilen existieren.",
  "Which option deletes dependent records along with the parent record?", "ON DELETE CASCADE",
  "The alternative RESTRICT prevents deletion while dependent rows exist."),

T("ap2-db-r94", "Welches Modell stellt Entitäten, Attribute und Beziehungen grafisch dar?", "ER-Modell",
  "Es beschreibt die fachliche Struktur, bevor daraus konkrete Tabellen abgeleitet werden.",
  "Which model shows entities, attributes and relationships graphically?", "ER model",
  "It describes the business structure before concrete tables are derived from it."),

T("ap2-db-r95", "Welche Klausel gibt die Sortierreihenfolge eines Ergebnisses vor?", "ORDER BY",
  "Ohne sie ist die Reihenfolge der Zeilen im Ergebnis nicht zugesichert.",
  "Which clause defines the sort order of a result?", "ORDER BY",
  "Without it the order of rows in the result is not guaranteed."),

T("ap2-db-r96", "Wie viele Primärschlüssel darf eine Tabelle haben?", "1",
  "Er kann allerdings aus mehreren Spalten zusammengesetzt sein.",
  "How many primary keys may a table have?", "1",
  "It can, however, be composed of several columns."),

T("ap2-db-r97", "Welche Bedingung erlaubt genau einen Wert je Spalte in der ganzen Tabelle?", "UNIQUE",
  "Anders als der Primärschlüssel darf eine UNIQUE-Spalte je nach System NULL enthalten.",
  "Which constraint permits each value only once per column across the table?", "UNIQUE",
  "Unlike the primary key, a UNIQUE column may contain NULL depending on the system."),

T("ap2-db-r98", "Welche Anweisung ändert vorhandene Datensätze einer Tabelle?", "UPDATE",
  "Ohne WHERE trifft sie alle Zeilen - ein klassischer und teurer Fehler.",
  "Which statement changes existing records in a table?", "UPDATE",
  "Without WHERE it hits every row - a classic and expensive mistake."),

T("ap2-db-r99", "Wie nennt man Widersprüche, die durch mehrfach gespeicherte gleiche Daten entstehen?", "Anomalien",
  "Einfüge-, Änderungs- und Löschanomalien sind der Hauptgrund für die Normalisierung.",
  "What are contradictions caused by the same data stored multiple times called?", "Anomalies",
  "Insert, update and delete anomalies are the main reason for normalisation."),

T("ap2-db-r100", "Welche SQL-Anweisung liest Daten aus einer Tabelle?", "SELECT",
  "Sie ist die mit Abstand häufigste Anweisung und Grundlage jeder Auswertung.",
  "Which SQL statement reads data from a table?", "SELECT",
  "It is by far the most frequent statement and the basis of every evaluation."),
]

build("ap2-datenbanken.json", "Datenbanken", "Databases", Q)
