#!/usr/bin/env python3
"""AP2 Netzwerke & Subnetting - 100 handgeschriebene Fragen."""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from qlib import S, M, T, build

Q = [
# ---------------------------------------------------------------- single (32)
S("ap2-net-r01",
  "Eine Filiale braucht 60 Hostadressen. Welches Subnetz vergibst du sparsam?",
  ("Ein /26 mit 62 nutzbaren Adressen",
   "Ein /25 mit 126 nutzbaren Adressen",
   "Ein /27 mit 30 nutzbaren Adressen",
   "Ein /24 mit 254 nutzbaren Adressen"), 0,
  "Ein /26 bietet 62 nutzbare Adressen und passt damit knapp über den Bedarf. Ein /27 wäre zu klein, größere Netze verschwenden Adressraum.",
  "A branch office needs 60 host addresses. Which subnet do you assign economically?",
  ("A /26 with 62 usable addresses",
   "A /25 with 126 usable addresses",
   "A /27 with 30 usable addresses",
   "A /24 with 254 usable addresses"),
  "A /26 offers 62 usable addresses and therefore sits just above the requirement. A /27 would be too small, larger networks waste address space."),

S("ap2-net-r02",
  "Vier Netze 10.1.0.0/24 bis 10.1.3.0/24 sollen zu einer Route zusammengefasst werden. Wie lautet sie?",
  ("10.1.0.0/22", "10.1.0.0/23", "10.1.0.0/21", "10.1.0.0/24"), 0,
  "Vier aufeinanderfolgende /24-Netze brauchen 2 Bits weniger Präfix, also /22. Diese Zusammenfassung verkleinert die Routingtabelle spürbar.",
  "Four networks 10.1.0.0/24 to 10.1.3.0/24 are to be summarised into one route. What is it?",
  ("10.1.0.0/22", "10.1.0.0/23", "10.1.0.0/21", "10.1.0.0/24"),
  "Four consecutive /24 networks need 2 fewer prefix bits, i.e. /22. This summarisation noticeably shrinks the routing table."),

S("ap2-net-r03",
  "Welchen Vorteil bietet VLSM gegenüber einer einheitlichen Maskenlänge?",
  ("Jedes Teilnetz erhält genau die Größe, die es braucht",
   "Alle Teilnetze werden automatisch gleich groß angelegt",
   "Die Anzahl der möglichen Router im Netz steigt",
   "Broadcast-Stürme werden dadurch technisch verhindert"), 0,
  "Mit variablen Masken bekommt eine Punkt-zu-Punkt-Strecke ein /30 und ein Bürosegment ein /24. Bei fester Maske müsste überall die größte Maske gelten, was Adressraum verschwendet.",
  "What advantage does VLSM offer over a uniform mask length?",
  ("Each subnet gets exactly the size it needs",
   "All subnets are automatically created equal in size",
   "The number of possible routers in the network rises",
   "Broadcast storms are technically prevented by it"),
  "With variable masks a point-to-point link gets a /30 and an office segment a /24. With a fixed mask the largest mask would apply everywhere, wasting address space."),

S("ap2-net-r04",
  "Ein Client hat die IPv6-Adresse fe80::1. Wofür ist diese Adresse gedacht?",
  ("Nur für die Kommunikation im lokalen Link",
   "Für die weltweite Erreichbarkeit im Internet",
   "Für die Adressierung von Multicast-Gruppen",
   "Für die Rückschleife auf den eigenen Rechner"), 0,
  "fe80::/10 kennzeichnet Link-Local-Adressen, die jede IPv6-Schnittstelle automatisch bildet. Router leiten sie nicht weiter; global routbar ist 2000::/3.",
  "A client has the IPv6 address fe80::1. What is this address intended for?",
  ("Only for communication on the local link",
   "For worldwide reachability on the internet",
   "For addressing multicast groups",
   "For loopback to the local machine"),
  "fe80::/10 marks link-local addresses that every IPv6 interface forms automatically. Routers do not forward them; globally routable is 2000::/3."),

S("ap2-net-r05",
  "Zu welchem Subnetz gehört die Adresse 172.16.35.200 bei der Maske 255.255.248.0?",
  ("172.16.32.0", "172.16.35.0", "172.16.24.0", "172.16.40.0"), 0,
  "248 im dritten Oktett ergibt /21 mit Blockgröße 8: die Grenzen liegen bei 0, 8, 16, 24, 32, 40. Die 35 fällt in den Block ab 32.",
  "Which subnet does the address 172.16.35.200 belong to with mask 255.255.248.0?",
  ("172.16.32.0", "172.16.35.0", "172.16.24.0", "172.16.40.0"),
  "248 in the third octet gives /21 with a block size of 8: boundaries are at 0, 8, 16, 24, 32, 40. So 35 falls into the block starting at 32."),

S("ap2-net-r06",
  "Ein Client im VLAN 20 erhält keine Adresse, der DHCP-Server steht im VLAN 10. Was fehlt?",
  ("Ein DHCP-Relay auf dem Router-Interface im VLAN 20",
   "Ein zweiter DHCP-Bereich im selben Adressbereich",
   "Eine statische Route vom Client zum DHCP-Server",
   "Eine Freigabe des Ports 80 auf der Firewall"), 0,
  "DHCP-Anfragen sind Broadcasts und überschreiten keine Routergrenze. Das Relay nimmt sie entgegen und leitet sie gerichtet an den Server weiter, ergänzt um die Netzinformation.",
  "A client in VLAN 20 gets no address while the DHCP server sits in VLAN 10. What is missing?",
  ("A DHCP relay on the router interface in VLAN 20",
   "A second DHCP scope in the same address range",
   "A static route from the client to the DHCP server",
   "A firewall rule permitting port 80"),
  "DHCP requests are broadcasts and do not cross a router boundary. The relay accepts them and forwards them unicast to the server, adding the network information."),

S("ap2-net-r07",
  "Wie viele nutzbare Hostadressen bietet ein /29-Netz?",
  ("6", "8", "14", "4"), 0,
  "3 Hostbits ergeben 8 Adressen, abzüglich Netz- und Broadcastadresse bleiben 6. Ideal für kleine Servergruppen oder Managementnetze.",
  "How many usable host addresses does a /29 network provide?",
  ("6", "8", "14", "4"),
  "3 host bits give 8 addresses; minus network and broadcast, 6 remain. Ideal for small server groups or management networks."),

S("ap2-net-r08",
  "Welches Routingprotokoll wählt seine Wege anhand der Bandbreite berechneter Kosten?",
  ("OSPF", "RIP", "ARP", "ICMP"), 0,
  "OSPF ist ein Link-State-Protokoll und berechnet Kosten aus der Bandbreite. RIP zählt nur Hops und begrenzt bei 15, ARP und ICMP sind gar keine Routingprotokolle.",
  "Which routing protocol selects paths based on costs derived from bandwidth?",
  ("OSPF", "RIP", "ARP", "ICMP"),
  "OSPF is a link-state protocol and derives cost from bandwidth. RIP only counts hops and caps at 15; ARP and ICMP are not routing protocols at all."),

S("ap2-net-r09",
  "Zwei Standorte sollen dauerhaft verschlüsselt gekoppelt werden. Welche Lösung passt?",
  ("Ein Site-to-Site-VPN zwischen den Routern",
   "Ein Client-to-Site-VPN auf jedem Arbeitsplatz",
   "Eine Portweiterleitung auf beiden Routern",
   "Ein gemeinsamer Proxy für beide Standorte"), 0,
  "Beim Site-to-Site-VPN bauen die Gateways den Tunnel auf, für die Clients bleibt es unsichtbar. Einzelne Clientverbindungen wären bei ganzen Standorten unpraktikabel.",
  "Two sites are to be permanently coupled with encryption. Which solution fits?",
  ("A site-to-site VPN between the routers",
   "A client-to-site VPN on every workstation",
   "A port forwarding rule on both routers",
   "A shared proxy for both locations"),
  "In a site-to-site VPN the gateways build the tunnel and it stays invisible to the clients. Individual client connections would be impractical for whole sites."),

S("ap2-net-r10",
  "Ein Trunk überträgt VLAN 10 und 20, aber VLAN 20 kommt nicht an. Was prüfst du zuerst?",
  ("Ob VLAN 20 auf dem Trunk beidseitig erlaubt ist",
   "Ob der DNS-Server im VLAN 20 antwortet",
   "Ob das Patchkabel die richtige Kategorie hat",
   "Ob die Clients genug Arbeitsspeicher haben"), 0,
  "Auf Trunks wird üblicherweise eine Liste erlaubter VLANs gepflegt; fehlt eines auf einer Seite, verschwinden dessen Frames stillschweigend. Kabel und Clients sind hier unverdächtig.",
  "A trunk carries VLAN 10 and 20, but VLAN 20 does not arrive. What do you check first?",
  ("Whether VLAN 20 is allowed on the trunk at both ends",
   "Whether the DNS server in VLAN 20 responds",
   "Whether the patch cable has the right category",
   "Whether the clients have enough memory"),
  "Trunks usually carry an allowed VLAN list; if one is missing at either end, its frames disappear silently. Cabling and clients are not suspects here."),

S("ap2-net-r11",
  "Welche Aufgabe hat VRRP in einem Netz?",
  ("Es stellt ein redundantes virtuelles Standardgateway bereit",
   "Es verteilt Anfragen gleichmäßig auf mehrere Webserver",
   "Es verschlüsselt den Verkehr zwischen zwei Standorten",
   "Es weist Clients automatisch IP-Adressen zu"), 0,
  "Mehrere Router teilen sich eine virtuelle IP und MAC; fällt der aktive aus, übernimmt ein anderer, ohne dass Clients etwas ändern müssen. Lastverteilung und Verschlüsselung sind andere Aufgaben.",
  "What is the purpose of VRRP in a network?",
  ("It provides a redundant virtual default gateway",
   "It distributes requests evenly across several web servers",
   "It encrypts traffic between two sites",
   "It automatically assigns IP addresses to clients"),
  "Several routers share a virtual IP and MAC; if the active one fails another takes over without clients changing anything. Load balancing and encryption are different jobs."),

S("ap2-net-r12",
  "Wie lautet die letzte nutzbare Hostadresse im Netz 192.168.8.64/27?",
  ("192.168.8.94", "192.168.8.95", "192.168.8.126", "192.168.8.93"), 0,
  "Ein /27 umfasst 32 Adressen, der Block reicht also von .64 bis .95. Die .95 ist Broadcast, damit endet der nutzbare Bereich bei .94.",
  "What is the last usable host address in the network 192.168.8.64/27?",
  ("192.168.8.94", "192.168.8.95", "192.168.8.126", "192.168.8.93"),
  "A /27 covers 32 addresses, so the block runs from .64 to .95. The .95 is the broadcast, ending the usable range at .94."),

S("ap2-net-r13",
  "Ein Dienst im internen Netz soll aus dem Internet erreichbar sein. Was richtest du am Router ein?",
  ("Eine Portweiterleitung auf die interne Adresse",
   "Eine zusätzliche Standardroute ins Internet",
   "Einen zweiten DHCP-Bereich für externe Gäste",
   "Eine Erhöhung der Leasedauer im internen Netz"), 0,
  "Beim Destination NAT übersetzt der Router eingehende Verbindungen auf einem Port zur internen Adresse. Sicherer ist es allerdings, den Dienst in eine DMZ zu stellen.",
  "A service on the internal network must be reachable from the internet. What do you configure on the router?",
  ("A port forwarding rule to the internal address",
   "An additional default route towards the internet",
   "A second DHCP scope for external guests",
   "An increase of the lease time internally"),
  "With destination NAT the router translates incoming connections on a port to the internal address. It is safer, though, to place the service in a DMZ."),

S("ap2-net-r14",
  "Welche Angabe kennzeichnet eine IPv6-Unique-Local-Adresse?",
  ("Sie beginnt mit fc00::/7", "Sie beginnt mit fe80::/10",
   "Sie beginnt mit 2000::/3", "Sie beginnt mit ff00::/8"), 0,
  "ULA entspricht den privaten Adressen aus IPv4 und ist nicht im Internet routbar. fe80 ist Link-Local, 2000::/3 global unicast und ff00::/8 Multicast.",
  "Which prefix identifies an IPv6 unique local address?",
  ("It starts with fc00::/7", "It starts with fe80::/10",
   "It starts with 2000::/3", "It starts with ff00::/8"),
  "ULA corresponds to IPv4 private addresses and is not routable on the internet. fe80 is link-local, 2000::/3 global unicast and ff00::/8 multicast."),

S("ap2-net-r15",
  "In wie viele /27-Subnetze lässt sich ein /24-Netz zerlegen?",
  ("8", "4", "16", "32"), 0,
  "Von /24 auf /27 sind es 3 zusätzliche Netzbits, und 2 hoch 3 ergibt 8 Subnetze mit je 30 nutzbaren Adressen.",
  "Into how many /27 subnets can a /24 network be divided?",
  ("8", "4", "16", "32"),
  "From /24 to /27 there are 3 additional network bits, and 2 to the power of 3 gives 8 subnets with 30 usable addresses each."),

S("ap2-net-r16",
  "Eine Anwendung reagiert träge, obwohl die Bandbreite frei ist. Welcher Wert ist zu prüfen?",
  ("Die Laufzeit und deren Schwankung",
   "Die Kapazität der Festplatte im Server",
   "Die Anzahl der VLANs auf dem Switch",
   "Die Länge des Netzwerknamens im WLAN"), 0,
  "Bei interaktiven Anwendungen begrenzt die Umlaufzeit die gefühlte Geschwindigkeit, nicht die Bandbreite. Hohe Latenz und Jitter fallen bei vielen kleinen Anfragen besonders auf.",
  "An application feels sluggish although bandwidth is free. Which value must be checked?",
  ("The transit time and its variation",
   "The disk capacity in the server",
   "The number of VLANs on the switch",
   "The length of the WLAN network name"),
  "For interactive applications the round trip time limits perceived speed, not bandwidth. High latency and jitter show up especially with many small requests."),

S("ap2-net-r17",
  "Wie viele Adressen umfasst ein IPv6-Standardpräfix für ein Endkundennetz nach Empfehlung?",
  ("Ein /64 je Subnetz", "Ein /24 je Subnetz",
   "Ein /128 je Subnetz", "Ein /32 je Subnetz"), 0,
  "IPv6 sieht /64 je Subnetz vor, weil SLAAC den Interface-Identifier aus 64 Bit bildet. /128 bezeichnet eine einzelne Adresse, /32 ist typisch für Provider.",
  "Which IPv6 prefix length is recommended per end-customer subnet?",
  ("A /64 per subnet", "A /24 per subnet",
   "A /128 per subnet", "A /32 per subnet"),
  "IPv6 provides /64 per subnet because SLAAC forms the interface identifier from 64 bits. /128 denotes a single address, /32 is typical for providers."),

S("ap2-net-r18",
  "Welche Aussage beschreibt eine DMZ zutreffend?",
  ("Ein eigenes Netz für von außen erreichbare Dienste",
   "Ein VLAN ausschließlich für die Netzwerkverwaltung",
   "Ein Bereich ohne jede Firewallregel für Gäste",
   "Ein Adressbereich für Punkt-zu-Punkt-Verbindungen"), 0,
  "Die DMZ liegt zwischen Internet und internem Netz. Wird ein Dienst dort kompromittiert, steht der Angreifer noch immer vor einer Firewall zum LAN.",
  "Which statement correctly describes a DMZ?",
  ("A separate network for externally reachable services",
   "A VLAN exclusively for network management",
   "An area without any firewall rules for guests",
   "An address range for point-to-point links"),
  "The DMZ sits between the internet and the internal network. If a service there is compromised, the attacker still faces a firewall towards the LAN."),

S("ap2-net-r19",
  "Ein Paket ist größer als die MTU der Strecke und darf nicht fragmentiert werden. Was passiert?",
  ("Der Router verwirft es und meldet dies per ICMP",
   "Der Router zerlegt es trotzdem in kleinere Teile",
   "Der Router speichert es bis zur nächsten Anfrage",
   "Der Router leitet es unverändert weiter"), 0,
  "Bei gesetztem Don't-Fragment-Bit meldet der Router Fragmentation Needed zurück. Wird dieses ICMP unterwegs geblockt, entsteht das typische Bild einer hängenden Verbindung.",
  "A packet exceeds the path MTU and must not be fragmented. What happens?",
  ("The router discards it and signals this via ICMP",
   "The router splits it into smaller parts anyway",
   "The router stores it until the next request",
   "The router forwards it unchanged"),
  "With the don't fragment bit set the router returns fragmentation needed. If that ICMP is blocked along the way, the typical picture of a hanging connection appears."),

S("ap2-net-r20",
  "Welche Adresse ist innerhalb von 10.0.4.0/22 eine gültige Hostadresse?",
  ("10.0.5.17", "10.0.8.17", "10.0.3.17", "10.0.4.0"), 0,
  "Ein /22 ab 10.0.4.0 reicht bis 10.0.7.255. 10.0.5.17 liegt darin, 10.0.3.17 und 10.0.8.17 außerhalb, und 10.0.4.0 ist die Netzadresse.",
  "Which address is a valid host address within 10.0.4.0/22?",
  ("10.0.5.17", "10.0.8.17", "10.0.3.17", "10.0.4.0"),
  "A /22 starting at 10.0.4.0 reaches to 10.0.7.255. 10.0.5.17 lies inside, 10.0.3.17 and 10.0.8.17 outside, and 10.0.4.0 is the network address."),

S("ap2-net-r21",
  "Was bewirkt Link Aggregation nach LACP zwischen zwei Switches?",
  ("Mehrere Leitungen wirken als ein logischer Kanal",
   "Eine Leitung wird für Wartungszwecke abgeschaltet",
   "Der Verkehr wird auf verschiedene VLANs verteilt",
   "Broadcasts werden zwischen Switches unterdrückt"), 0,
  "Die gebündelten Leitungen erhöhen Bandbreite und Ausfallsicherheit, und Spanning Tree sieht nur noch einen Pfad. Einzelne Verbindungen werden dabei nicht schneller als eine Leitung.",
  "What does link aggregation via LACP between two switches achieve?",
  ("Several links act as one logical channel",
   "One link is disabled for maintenance purposes",
   "Traffic is distributed across different VLANs",
   "Broadcasts are suppressed between the switches"),
  "The bundled links raise bandwidth and resilience, and Spanning Tree sees only one path. Individual connections do not become faster than a single link, though."),

S("ap2-net-r22",
  "Welche Aufgabe erfüllt QoS in einem Netz mit Sprachtelefonie?",
  ("Es bevorzugt Sprachpakete gegenüber anderem Verkehr",
   "Es verschlüsselt Sprachverbindungen automatisch",
   "Es erhöht die physische Bandbreite der Leitung",
   "Es weist Telefonen feste IP-Adressen zu"), 0,
  "QoS priorisiert anhand von Markierungen wie DSCP und sorgt dafür, dass Sprache auch bei Last vorrangig durchkommt. Mehr Bandbreite entsteht dadurch nicht.",
  "What is the purpose of QoS in a network carrying voice telephony?",
  ("It prioritises voice packets over other traffic",
   "It automatically encrypts voice connections",
   "It increases the physical bandwidth of the line",
   "It assigns fixed IP addresses to phones"),
  "QoS prioritises based on markings such as DSCP so that voice gets through even under load. It does not create additional bandwidth."),

S("ap2-net-r23",
  "Ein Switch meldet dauernd MAC-Flapping zwischen zwei Ports. Worauf deutet das hin?",
  ("Auf eine Schleife im Netz zwischen diesen Ports",
   "Auf einen zu klein gewählten DHCP-Bereich",
   "Auf einen abgelaufenen DNS-Eintrag im Netz",
   "Auf eine falsch gesetzte Uhrzeit im Switch"), 0,
  "Taucht dieselbe MAC abwechselnd an zwei Ports auf, erreichen Frames den Switch auf zwei Wegen - das kennzeichnet eine Schleife. Spanning Tree soll genau das verhindern.",
  "A switch constantly reports MAC flapping between two ports. What does that indicate?",
  ("A loop in the network between those ports",
   "A DHCP range that was chosen too small",
   "An expired DNS record in the network",
   "An incorrectly set clock in the switch"),
  "If the same MAC appears alternately on two ports, frames reach the switch by two paths - the hallmark of a loop. Spanning Tree exists to prevent exactly that."),

S("ap2-net-r24",
  "Welche Subnetzmaske gehört zur Präfixlänge /19?",
  ("255.255.224.0", "255.255.240.0", "255.255.192.0", "255.255.248.0"), 0,
  "/19 setzt im dritten Oktett drei Bits: 128 + 64 + 32 ergibt 224. Die Blockgröße beträgt damit 32 im dritten Oktett.",
  "Which subnet mask belongs to prefix length /19?",
  ("255.255.224.0", "255.255.240.0", "255.255.192.0", "255.255.248.0"),
  "A /19 sets three bits in the third octet: 128 + 64 + 32 gives 224. The block size is therefore 32 in the third octet."),

S("ap2-net-r25",
  "Wie unterscheidet sich der Tunnelmodus vom Transportmodus bei IPsec?",
  ("Der Tunnelmodus verschlüsselt auch den originalen IP-Header",
   "Der Transportmodus verschlüsselt zusätzlich die MAC-Adressen",
   "Der Tunnelmodus arbeitet ausschließlich ohne Verschlüsselung",
   "Der Transportmodus funktioniert nur zwischen zwei Routern"), 0,
  "Im Tunnelmodus wird das gesamte Originalpaket eingepackt und mit neuem Header versehen - deshalb ist er für Site-to-Site-VPNs die Wahl. Der Transportmodus schützt nur die Nutzdaten.",
  "How does IPsec tunnel mode differ from transport mode?",
  ("Tunnel mode also encrypts the original IP header",
   "Transport mode additionally encrypts the MAC addresses",
   "Tunnel mode works exclusively without encryption",
   "Transport mode only works between two routers"),
  "In tunnel mode the entire original packet is wrapped and given a new header - which is why it is the choice for site-to-site VPNs. Transport mode protects only the payload."),

S("ap2-net-r26",
  "Ein Netz 192.168.100.0/24 soll ein Subnetz für genau zwei Router-Interfaces bekommen. Welches Präfix?",
  ("/30", "/29", "/31", "/28"), 0,
  "Ein /30 stellt genau zwei nutzbare Adressen bereit und ist der Standard für Punkt-zu-Punkt-Strecken. /31 ist nur in speziellen Fällen zulässig.",
  "Network 192.168.100.0/24 needs a subnet for exactly two router interfaces. Which prefix?",
  ("/30", "/29", "/31", "/28"),
  "A /30 provides exactly two usable addresses and is the standard for point-to-point links. A /31 is permitted only in special cases."),

S("ap2-net-r27",
  "Welche Aussage über NAT und IPv6 trifft zu?",
  ("Der große Adressraum macht NAT weitgehend überflüssig",
   "IPv6 verlangt NAT zwingend für jeden Internetzugang",
   "NAT ist in IPv6 technisch überhaupt nicht möglich",
   "IPv6 nutzt NAT zur Verschlüsselung der Verbindung"), 0,
  "In IPv6 bekommt jedes Gerät eine global eindeutige Adresse, Adressknappheit entfällt. Für Sicherheit sorgt die Firewall, nicht NAT.",
  "Which statement about NAT and IPv6 is correct?",
  ("The large address space makes NAT largely unnecessary",
   "IPv6 strictly requires NAT for any internet access",
   "NAT is technically impossible in IPv6 altogether",
   "IPv6 uses NAT to encrypt the connection"),
  "In IPv6 every device gets a globally unique address, so address scarcity disappears. Security comes from the firewall, not from NAT."),

S("ap2-net-r28",
  "Eine Firewall trifft Entscheidungen anhand des Verbindungszustands. Wie nennt man das?",
  ("Stateful Packet Inspection", "Static Packet Filtering",
   "Source Address Translation", "Simple Routing Decision"), 0,
  "Eine zustandsbehaftete Firewall merkt sich aufgebaute Verbindungen und lässt zugehörige Antwortpakete automatisch zu. Ein reiner Paketfilter müsste dafür starre Gegenregeln haben.",
  "A firewall makes decisions based on connection state. What is that called?",
  ("Stateful packet inspection", "Static packet filtering",
   "Source address translation", "Simple routing decision"),
  "A stateful firewall remembers established connections and automatically permits the matching reply packets. A pure packet filter would need rigid counter-rules for that."),

S("ap2-net-r29",
  "Welcher Wert entscheidet, welche Route bei mehreren Quellen bevorzugt wird?",
  ("Die administrative Distanz", "Die Anzahl der VLANs",
   "Die Größe des Adressbereichs", "Die Leasedauer im DHCP"), 0,
  "Kennt ein Router dasselbe Ziel über mehrere Protokolle, gewinnt die Quelle mit der niedrigsten administrativen Distanz. Bei gleicher Quelle entscheidet danach die Metrik.",
  "Which value decides which route is preferred when several sources exist?",
  ("The administrative distance", "The number of VLANs",
   "The size of the address range", "The DHCP lease time"),
  "If a router knows the same destination through several protocols, the source with the lowest administrative distance wins. Within the same source the metric then decides."),

S("ap2-net-r30",
  "Ein Netzwerk soll zentral überwacht werden. Welches Protokoll fragt Geräte nach Zustandswerten ab?",
  ("SNMP", "SMTP", "SFTP", "NTP"), 0,
  "SNMP liest Zustandsgrößen über eine MIB aus und kann per Trap auch selbst melden. SMTP verschickt Mails, SFTP überträgt Dateien und NTP synchronisiert die Uhrzeit.",
  "A network is to be monitored centrally. Which protocol queries devices for status values?",
  ("SNMP", "SMTP", "SFTP", "NTP"),
  "SNMP reads status values via a MIB and can also report on its own using traps. SMTP sends mail, SFTP transfers files and NTP synchronises time."),

S("ap2-net-r31",
  "Wie viele /30-Netze passen in ein einzelnes /24-Netz?",
  ("64", "32", "128", "16"), 0,
  "Von /24 auf /30 sind es 6 zusätzliche Netzbits, und 2 hoch 6 ergibt 64 Punkt-zu-Punkt-Netze.",
  "How many /30 networks fit into a single /24 network?",
  ("64", "32", "128", "16"),
  "From /24 to /30 there are 6 additional network bits, and 2 to the power of 6 gives 64 point-to-point networks."),

S("ap2-net-r32",
  "Welche Aufgabe hat ein Reverse Proxy vor mehreren Webservern?",
  ("Er nimmt Anfragen entgegen und verteilt sie nach innen",
   "Er filtert ausgehende Anfragen der internen Clients",
   "Er vergibt Adressen an die dahinterliegenden Server",
   "Er ersetzt die Namensauflösung durch den DNS-Server"), 0,
  "Der Reverse Proxy ist der zentrale Eintrittspunkt von außen: er verteilt Last, terminiert TLS und verbirgt die interne Struktur. Der klassische Proxy arbeitet in die Gegenrichtung.",
  "What is the purpose of a reverse proxy in front of several web servers?",
  ("It accepts requests and distributes them inward",
   "It filters outgoing requests from internal clients",
   "It assigns addresses to the servers behind it",
   "It replaces name resolution by the DNS server"),
  "The reverse proxy is the central entry point from outside: it spreads load, terminates TLS and hides the internal structure. A classic proxy works in the opposite direction."),

# -------------------------------------------------------------- multiple (32)
M("ap2-net-r33",
  "Welche Aussagen über VLSM und Subnetting sind korrekt?",
  ("Teilnetze dürfen unterschiedliche Maskenlängen haben",
   "Punkt-zu-Punkt-Strecken erhalten typischerweise ein /30",
   "Sparsame Vergabe erhält Adressraum für später",
   "Die Zusammenfassung von Routen verkleinert Tabellen",
   "Alle Teilnetze müssen dieselbe Größe besitzen",
   "Jedes Subnetz gewinnt zwei zusätzliche Hostadressen"),
  (0, 1, 2, 3),
  "VLSM passt die Maske an den Bedarf an, spart Adressen und erlaubt saubere Zusammenfassung. Jedes zusätzliche Subnetz kostet dagegen Netz- und Broadcastadresse.",
  "Which statements about VLSM and subnetting are correct?",
  ("Subnets may have different mask lengths",
   "Point-to-point links typically get a /30",
   "Economical assignment preserves address space for later",
   "Route summarisation shrinks routing tables",
   "All subnets must have the same size",
   "Each subnet gains two additional host addresses"),
  "VLSM matches the mask to the need, saves addresses and allows clean summarisation. Each additional subnet by contrast costs a network and a broadcast address."),

M("ap2-net-r34",
  "Welche IPv6-Adresstypen gibt es?",
  ("Global Unicast", "Link Local", "Unique Local", "Multicast",
   "Broadcast", "Reverse Unicast"),
  (0, 1, 2, 3),
  "IPv6 kennt Unicast in globaler, link-lokaler und eindeutig-lokaler Ausprägung sowie Multicast und Anycast. Broadcast wurde bewusst durch Multicast ersetzt.",
  "Which IPv6 address types exist?",
  ("Global unicast", "Link local", "Unique local", "Multicast",
   "Broadcast", "Reverse unicast"),
  "IPv6 knows unicast in global, link-local and unique-local form plus multicast and anycast. Broadcast was deliberately replaced by multicast."),

M("ap2-net-r35",
  "Welche Angaben braucht ein Router, um eine statische Route einzutragen?",
  ("Das Zielnetz", "Die Netzmaske beziehungsweise das Präfix",
   "Den nächsten Hop oder das Ausgangsinterface", "Optional eine Metrik zur Gewichtung",
   "Die MAC-Adresse des Zielhosts", "Die Seriennummer des Zielservers"),
  (0, 1, 2, 3),
  "Zielnetz, Präfix und nächster Hop sind das Minimum, die Metrik steuert die Bevorzugung bei mehreren Wegen. MAC-Adressen ermittelt der Router bei Bedarf selbst.",
  "Which details does a router need to add a static route?",
  ("The destination network", "The netmask or prefix",
   "The next hop or outgoing interface", "Optionally a metric for weighting",
   "The MAC address of the target host", "The serial number of the target server"),
  "Destination, prefix and next hop are the minimum; the metric controls preference between several paths. The router determines MAC addresses itself when needed."),

M("ap2-net-r36",
  "Welche Vorteile bringt die Segmentierung eines Netzes in VLANs?",
  ("Broadcast-Domänen werden kleiner",
   "Verkehr zwischen Bereichen lässt sich filtern",
   "Gäste und Produktion bleiben getrennt",
   "Fehler wirken sich nur im betroffenen Segment aus",
   "Die Portgeschwindigkeit der Switches steigt",
   "Der Verkehr wird dadurch automatisch verschlüsselt"),
  (0, 1, 2, 3),
  "Kleinere Broadcast-Domänen, gezielte Filterung, Trennung und begrenzte Fehlerauswirkung sind die eigentlichen Gewinne. Geschwindigkeit und Verschlüsselung ändern sich nicht.",
  "Which advantages come from segmenting a network into VLANs?",
  ("Broadcast domains become smaller",
   "Traffic between areas can be filtered",
   "Guests and production stay separated",
   "Faults only affect the segment concerned",
   "The port speed of the switches rises",
   "Traffic becomes automatically encrypted"),
  "Smaller broadcast domains, targeted filtering, separation and limited fault impact are the real gains. Speed and encryption do not change."),

M("ap2-net-r37",
  "Welche Aussagen über OSPF treffen zu?",
  ("Es ist ein Link-State-Protokoll",
   "Es berechnet Kosten aus der Bandbreite",
   "Es kennt eine Aufteilung in Areas",
   "Es konvergiert schneller als RIP",
   "Es begrenzt die Netzgröße auf 15 Hops",
   "Es überträgt Routen ausschließlich unverschlüsselt"),
  (0, 1, 2, 3),
  "OSPF baut eine vollständige Topologiedatenbank auf, rechnet mit Bandbreitenkosten und skaliert über Areas. Die 15-Hop-Grenze ist eine RIP-Eigenschaft, und OSPF kennt Authentifizierung.",
  "Which statements about OSPF are correct?",
  ("It is a link-state protocol",
   "It derives cost from bandwidth",
   "It supports division into areas",
   "It converges faster than RIP",
   "It limits network size to 15 hops",
   "It transmits routes exclusively unencrypted"),
  "OSPF builds a complete topology database, computes bandwidth-based cost and scales through areas. The 15-hop limit is a RIP property, and OSPF supports authentication."),

M("ap2-net-r38",
  "Welche Schritte gehören zur Planung eines Subnetzkonzepts?",
  ("Bedarf je Standort und Abteilung erheben",
   "Passende Präfixlängen je Segment festlegen",
   "Adressbereiche überschneidungsfrei vergeben",
   "Reserve für künftiges Wachstum einplanen",
   "Alle Segmente pauschal als /24 anlegen",
   "Adressen erst nach dem Aufbau dokumentieren"),
  (0, 1, 2, 3),
  "Bedarf, passende Größen, Überschneidungsfreiheit und Reserve führen zu einem tragfähigen Plan. Pauschale /24 verschwenden Adressen, und nachträgliche Dokumentation ist erfahrungsgemäß lückenhaft.",
  "Which steps belong to planning a subnet scheme?",
  ("Survey the demand per site and department",
   "Define suitable prefix lengths per segment",
   "Assign address ranges without overlap",
   "Plan reserve for future growth",
   "Create all segments as /24 across the board",
   "Document addresses only after the rollout"),
  "Demand, suitable sizes, freedom from overlap and reserve lead to a viable plan. Blanket /24s waste addresses, and documentation written afterwards is notoriously incomplete."),

M("ap2-net-r39",
  "Welche Merkmale kennzeichnen ein Site-to-Site-VPN?",
  ("Die Gateways bauen den Tunnel auf",
   "Für die Clients bleibt es transparent",
   "Es verbindet ganze Netze miteinander",
   "Es läuft dauerhaft und nicht bedarfsweise",
   "Jeder Client benötigt eine eigene VPN-Software",
   "Es ersetzt die Firewall an beiden Standorten"),
  (0, 1, 2, 3),
  "Beim Site-to-Site-VPN übernehmen die Gateways die Arbeit, die Clients merken nichts davon. Eine eigene Clientsoftware wäre beim Client-to-Site-VPN nötig.",
  "Which characteristics define a site-to-site VPN?",
  ("The gateways establish the tunnel",
   "It stays transparent for the clients",
   "It connects entire networks with each other",
   "It runs permanently rather than on demand",
   "Every client needs its own VPN software",
   "It replaces the firewall at both locations"),
  "In a site-to-site VPN the gateways do the work and the clients notice nothing. Dedicated client software would be needed for a client-to-site VPN."),

M("ap2-net-r40",
  "Welche Ursachen können hohe Latenz in einem Netz erklären?",
  ("Überlastete Leitungen mit Warteschlangen",
   "Viele Zwischenstationen auf dem Weg",
   "Große physische Entfernung zum Ziel",
   "Überlastete Router mit hoher Rechenlast",
   "Eine zu große Festplatte im Zielserver",
   "Ein zu langer Netzwerkname des WLANs"),
  (0, 1, 2, 3),
  "Warteschlangen, Hops, Entfernung und Gerätelast summieren sich zur Umlaufzeit. Speichergröße und Netzname haben darauf keinerlei Einfluss.",
  "Which causes can explain high latency in a network?",
  ("Congested links with queueing",
   "Many intermediate hops on the path",
   "Large physical distance to the target",
   "Overloaded routers under high processing load",
   "Too large a hard disk in the target server",
   "Too long a WLAN network name"),
  "Queueing, hops, distance and device load add up to the round trip time. Storage size and network name have no influence whatsoever."),

M("ap2-net-r41",
  "Welche Aussagen über DHCP in geswitchten Netzen sind richtig?",
  ("DHCP-Anfragen sind zunächst Broadcasts",
   "Ein Relay leitet sie über Netzgrenzen weiter",
   "Reservierungen binden Adressen an MAC-Adressen",
   "Optionen können Gateway und DNS mitgeben",
   "Broadcasts passieren Router ohne weitere Hilfe",
   "Ein DHCP-Server kann nur ein Subnetz bedienen"),
  (0, 1, 2, 3),
  "Der Broadcast bleibt im Segment, deshalb braucht es das Relay. Über Optionen und Reservierungen kann ein einzelner Server viele Subnetze sauber versorgen.",
  "Which statements about DHCP in switched networks are correct?",
  ("DHCP requests are broadcasts at first",
   "A relay forwards them across network boundaries",
   "Reservations bind addresses to MAC addresses",
   "Options can supply gateway and DNS",
   "Broadcasts cross routers without further help",
   "A DHCP server can only serve one subnet"),
  "The broadcast stays in the segment, which is why a relay is needed. Through options and reservations a single server can cleanly serve many subnets."),

M("ap2-net-r42",
  "Welche Maßnahmen erhöhen die Ausfallsicherheit eines Netzes?",
  ("Redundante Leitungen zwischen Verteilern",
   "Ein zweites Gateway per VRRP",
   "Gebündelte Leitungen per LACP",
   "Redundante Netzteile in zentralen Geräten",
   "Ein einzelner zentraler Switch für alles",
   "Verzicht auf Spanning Tree zur Vereinfachung"),
  (0, 1, 2, 3),
  "Redundanz auf Leitungs-, Gateway- und Stromebene beseitigt einzelne Ausfallpunkte. Ein zentraler Switch wäre genau so ein Punkt, und ohne Spanning Tree führen redundante Wege zur Schleife.",
  "Which measures increase the resilience of a network?",
  ("Redundant links between distributors",
   "A second gateway via VRRP",
   "Bundled links via LACP",
   "Redundant power supplies in central devices",
   "A single central switch for everything",
   "Dropping Spanning Tree for simplicity"),
  "Redundancy at link, gateway and power level removes single points of failure. A single central switch would be exactly such a point, and without Spanning Tree redundant paths create loops."),

M("ap2-net-r43",
  "Welche Aussagen über die Adresse 2001:db8::/32 sind zutreffend?",
  ("Sie liegt im globalen Unicast-Bereich",
   "Sie ist für Dokumentation reserviert",
   "Sie darf in Beispielen frei verwendet werden",
   "Ihre Notation nutzt die verkürzte Schreibweise",
   "Sie ist eine Link-Local-Adresse",
   "Sie kennzeichnet eine Multicast-Gruppe"),
  (0, 1, 2, 3),
  "2001:db8::/32 stammt aus 2000::/3 und ist ausdrücklich für Beispiele und Dokumentation reserviert. Link-Local wäre fe80, Multicast ff00.",
  "Which statements about the address 2001:db8::/32 are correct?",
  ("It lies in the global unicast range",
   "It is reserved for documentation",
   "It may be used freely in examples",
   "Its notation uses the shortened form",
   "It is a link-local address",
   "It denotes a multicast group"),
  "2001:db8::/32 comes from 2000::/3 and is expressly reserved for examples and documentation. Link-local would be fe80, multicast ff00."),

M("ap2-net-r44",
  "Welche Informationen liefert ein Trace zum Zielsystem?",
  ("Die Router auf dem Weg zum Ziel",
   "Die Antwortzeit je Zwischenstation",
   "Die Anzahl der Hops bis zum Ziel",
   "Den Punkt, ab dem die Verzögerung springt",
   "Die Auslastung der Festplatten der Router",
   "Die Passwörter der beteiligten Geräte"),
  (0, 1, 2, 3),
  "Ein Trace macht den Pfad und die Zeitverteilung sichtbar und zeigt, wo die Verzögerung entsteht. Interna der Geräte liefert er selbstverständlich nicht.",
  "Which information does a trace to a target system provide?",
  ("The routers along the path to the target",
   "The response time per intermediate hop",
   "The number of hops to the destination",
   "The point at which latency jumps",
   "The disk utilisation of the routers",
   "The passwords of the devices involved"),
  "A trace reveals the path and the distribution of time and shows where the delay arises. It obviously does not provide device internals."),

M("ap2-net-r45",
  "Welche Aussagen über NAT und PAT sind korrekt?",
  ("NAT übersetzt Adressen an der Netzgrenze",
   "PAT unterscheidet Verbindungen über Portnummern",
   "Viele interne Hosts teilen eine öffentliche Adresse",
   "Eingehende Verbindungen brauchen eine Weiterleitung",
   "NAT verschlüsselt den übersetzten Verkehr",
   "PAT vergibt zusätzlich DNS-Namen an Clients"),
  (0, 1, 2, 3),
  "NAT tauscht Adressen, PAT ergänzt Ports zur Unterscheidung - so teilen sich viele Hosts eine öffentliche Adresse. Eingehend braucht es eine ausdrückliche Regel. Verschlüsselung und DNS gehören nicht dazu.",
  "Which statements about NAT and PAT are correct?",
  ("NAT translates addresses at the network boundary",
   "PAT distinguishes connections via port numbers",
   "Many internal hosts share one public address",
   "Inbound connections need a forwarding rule",
   "NAT encrypts the translated traffic",
   "PAT additionally assigns DNS names to clients"),
  "NAT swaps addresses, PAT adds ports to tell connections apart - letting many hosts share one public address. Inbound traffic needs an explicit rule. Encryption and DNS are not part of it."),

M("ap2-net-r46",
  "Welche Angaben gehören in eine Netzdokumentation?",
  ("Adressplan mit vergebenen Subnetzen",
   "VLAN-Übersicht mit Verwendungszweck",
   "Verkabelungsplan mit Portbelegung",
   "Konfigurationsstände der aktiven Komponenten",
   "Die Urlaubsplanung der Administratoren",
   "Die Preisliste des Netzwerklieferanten"),
  (0, 1, 2, 3),
  "Adressen, VLANs, Verkabelung und Konfigurationsstände sind das, was im Störungsfall zählt. Organisatorisches und Kaufmännisches gehört in andere Ablagen.",
  "Which details belong in network documentation?",
  ("Address plan with assigned subnets",
   "VLAN overview with intended purpose",
   "Cabling plan with port assignments",
   "Configuration states of the active components",
   "The holiday planning of the administrators",
   "The price list of the network supplier"),
  "Addresses, VLANs, cabling and configuration states are what counts during an incident. Organisational and commercial matters belong in other records."),

M("ap2-net-r47",
  "Welche Aussagen über Spanning Tree in modernen Netzen sind richtig?",
  ("Es verhindert Schleifen in redundanten Topologien",
   "RSTP konvergiert deutlich schneller als klassisches STP",
   "Eine Root Bridge wird über Prioritäten gewählt",
   "Blockierte Ports übernehmen bei einem Ausfall",
   "Es erhöht die Bandbreite aller beteiligten Ports",
   "Es macht Link Aggregation grundsätzlich überflüssig"),
  (0, 1, 2, 3),
  "STP und sein schnellerer Nachfolger RSTP halten die Topologie schleifenfrei und aktivieren Reservewege im Fehlerfall. Bandbreite entsteht dadurch nicht - dafür ist Link Aggregation da.",
  "Which statements about Spanning Tree in modern networks are correct?",
  ("It prevents loops in redundant topologies",
   "RSTP converges much faster than classic STP",
   "A root bridge is elected via priorities",
   "Blocked ports take over on a failure",
   "It increases the bandwidth of all involved ports",
   "It fundamentally makes link aggregation unnecessary"),
  "STP and its faster successor RSTP keep the topology loop-free and activate standby paths on failure. It creates no bandwidth - that is what link aggregation is for."),

M("ap2-net-r48",
  "Welche Aussagen zur Fehlersuche bei fehlender Erreichbarkeit sind sinnvoll?",
  ("Zuerst die eigene IP-Konfiguration prüfen",
   "Das Standardgateway per ping testen",
   "Die Namensauflösung getrennt prüfen",
   "Den Pfad zum Ziel per Trace verfolgen",
   "Sofort alle Switches neu starten",
   "Die Firewall vollständig deaktivieren"),
  (0, 1, 2, 3),
  "Schrittweises Vorgehen von der eigenen Konfiguration über Gateway und DNS bis zum Pfad grenzt die Ursache ein. Neustarts auf Verdacht und abgeschaltete Firewalls schaffen neue Probleme.",
  "Which approaches to troubleshooting a reachability problem make sense?",
  ("Check your own IP configuration first",
   "Test the default gateway with ping",
   "Check name resolution separately",
   "Follow the path to the target with a trace",
   "Immediately restart all switches",
   "Disable the firewall completely"),
  "Working step by step from your own configuration through gateway and DNS to the path narrows the cause down. Restarts on suspicion and disabled firewalls create new problems."),

M("ap2-net-r49",
  "Welche Merkmale hat ein Layer-3-Switch?",
  ("Er leitet zwischen VLANs weiter",
   "Er trifft Entscheidungen anhand von IP-Adressen",
   "Er führt eine Routingtabelle",
   "Er arbeitet zusätzlich als klassischer Switch",
   "Er ersetzt vollständig die Internet-Firewall",
   "Er arbeitet ausschließlich auf Schicht 1"),
  (0, 1, 2, 3),
  "Der Layer-3-Switch vereint schnelles Switching mit Routingfunktionen und übernimmt typischerweise das Routing zwischen VLANs. Eine Firewall am Internetübergang ersetzt er nicht.",
  "Which characteristics does a layer 3 switch have?",
  ("It forwards between VLANs",
   "It makes decisions based on IP addresses",
   "It maintains a routing table",
   "It additionally works as a classic switch",
   "It fully replaces the internet firewall",
   "It works exclusively on layer 1"),
  "A layer 3 switch combines fast switching with routing functions and typically handles inter-VLAN routing. It does not replace a firewall at the internet edge."),

M("ap2-net-r50",
  "Welche Aussagen über SLAAC in IPv6 sind zutreffend?",
  ("Clients bilden ihre Adresse selbst",
   "Router Advertisements liefern das Präfix",
   "Ein DHCP-Server ist dafür nicht zwingend nötig",
   "Das Präfix ist dabei typischerweise ein /64",
   "Die Adresse wird von einem Server fest vergeben",
   "SLAAC funktioniert ausschließlich mit IPv4"),
  (0, 1, 2, 3),
  "Bei SLAAC verteilt der Router nur das Präfix, den Rest bildet der Client selbst - deshalb reicht ein /64 und es braucht keinen DHCP-Server. Mit IPv4 hat das Verfahren nichts zu tun.",
  "Which statements about SLAAC in IPv6 are correct?",
  ("Clients form their address themselves",
   "Router advertisements supply the prefix",
   "A DHCP server is not strictly required",
   "The prefix is typically a /64",
   "The address is fixed by a server",
   "SLAAC works exclusively with IPv4"),
  "With SLAAC the router only advertises the prefix and the client forms the rest - hence a /64 suffices and no DHCP server is needed. It has nothing to do with IPv4."),

M("ap2-net-r51",
  "Welche Angaben beschreiben eine Firewallregel vollständig?",
  ("Quelladresse oder Quellnetz", "Zieladresse oder Zielnetz",
   "Protokoll und Zielport", "Aktion erlauben oder verwerfen",
   "Die Farbe des Netzwerkkabels", "Der Name des Antragstellers"),
  (0, 1, 2, 3),
  "Quelle, Ziel, Dienst und Aktion sind das Minimum jeder Regel; ergänzend werden Richtung und Protokollierung gesetzt. Organisatorische Angaben gehören in die Dokumentation, nicht in die Regel.",
  "Which details describe a firewall rule completely?",
  ("Source address or source network", "Destination address or network",
   "Protocol and destination port", "Action permit or deny",
   "The colour of the network cable", "The name of the requester"),
  "Source, destination, service and action are the minimum of any rule; direction and logging are added. Organisational details belong in documentation, not in the rule."),

M("ap2-net-r52",
  "Welche Gründe sprechen für ein eigenes Managementnetz für aktive Komponenten?",
  ("Verwaltungszugriff bleibt vom Nutzverkehr getrennt",
   "Ein Ausfall im Produktivnetz blockiert nicht den Zugriff",
   "Angriffe aus dem Nutzernetz erreichen es nicht direkt",
   "Zugriffe lassen sich enger einschränken",
   "Die Bandbreite im Produktivnetz verdoppelt sich",
   "Aktive Komponenten brauchen dann keine Passwörter"),
  (0, 1, 2, 3),
  "Trennung schützt den Zugriffsweg genau dann, wenn man ihn am dringendsten braucht - im Störungsfall. An Bandbreite und Zugangsschutz ändert das nichts.",
  "Which reasons argue for a dedicated management network for active components?",
  ("Administrative access stays separate from user traffic",
   "An outage in the production network does not block access",
   "Attacks from the user network do not reach it directly",
   "Access can be restricted more tightly",
   "Bandwidth in the production network doubles",
   "Active components then need no passwords"),
  "Separation protects the access path exactly when it is needed most - during an incident. It changes nothing about bandwidth or access protection."),

M("ap2-net-r53",
  "Welche Aussagen zur Routenzusammenfassung sind richtig?",
  ("Mehrere benachbarte Netze werden zu einem Eintrag",
   "Die Präfixlänge wird dabei verkürzt",
   "Die Routingtabelle wird dadurch kleiner",
   "Die Netze müssen zusammenhängend sein",
   "Beliebige Netze lassen sich zusammenfassen",
   "Die Zusammenfassung erhöht die Bandbreite"),
  (0, 1, 2, 3),
  "Zusammenfassen funktioniert nur bei zusammenhängenden Blöcken auf einer Bitgrenze und verkürzt das Präfix. Sie entlastet die Tabelle, nicht die Leitung.",
  "Which statements about route summarisation are correct?",
  ("Several adjacent networks become one entry",
   "The prefix length is shortened in the process",
   "The routing table becomes smaller",
   "The networks must be contiguous",
   "Arbitrary networks can be summarised",
   "Summarisation increases bandwidth"),
  "Summarisation only works for contiguous blocks on a bit boundary and shortens the prefix. It relieves the table, not the link."),

M("ap2-net-r54",
  "Welche Aussagen über 802.1Q sind zutreffend?",
  ("Es fügt Frames eine VLAN-Kennung hinzu",
   "Die Kennung ist 12 Bit lang",
   "Damit sind bis zu 4094 nutzbare VLANs möglich",
   "Trunks transportieren mehrere VLANs getaggt",
   "Access-Ports übertragen grundsätzlich getaggt",
   "Die Kennung ersetzt die MAC-Adresse im Frame"),
  (0, 1, 2, 3),
  "Der 802.1Q-Tag trägt eine 12-Bit-VLAN-ID, wodurch 4094 VLANs nutzbar bleiben. Access-Ports arbeiten ungetaggt, und die MAC-Adressen bleiben unangetastet.",
  "Which statements about 802.1Q are correct?",
  ("It adds a VLAN identifier to frames",
   "The identifier is 12 bits long",
   "This allows up to 4094 usable VLANs",
   "Trunks carry several VLANs tagged",
   "Access ports fundamentally transmit tagged",
   "The identifier replaces the MAC address in the frame"),
  "The 802.1Q tag carries a 12-bit VLAN ID, leaving 4094 usable VLANs. Access ports work untagged, and MAC addresses stay untouched."),

M("ap2-net-r55",
  "Welche Maßnahmen begrenzen die Angriffsfläche eines Switches?",
  ("Nicht genutzte Ports administrativ abschalten",
   "Zugriff auf die Verwaltung einschränken",
   "Aktuelle Firmware einspielen",
   "Portsicherheit für erlaubte MAC-Adressen aktivieren",
   "Alle Ports pauschal ins Management-VLAN legen",
   "Standardpasswörter aus Bequemlichkeit belassen"),
  (0, 1, 2, 3),
  "Abgeschaltete Ports, eingeschränkter Verwaltungszugriff, Patches und Portsicherheit verkleinern die Angriffsfläche wirksam. Die letzten beiden Punkte vergrößern sie erheblich.",
  "Which measures reduce the attack surface of a switch?",
  ("Administratively disable unused ports",
   "Restrict access to the management interface",
   "Install current firmware",
   "Enable port security for permitted MAC addresses",
   "Put all ports into the management VLAN wholesale",
   "Leave default passwords in place for convenience"),
  "Disabled ports, restricted management access, patches and port security effectively shrink the attack surface. The last two points enlarge it considerably."),

M("ap2-net-r56",
  "Welche Aussagen über die MTU sind korrekt?",
  ("Sie begrenzt die maximale Nutzlast eines Frames",
   "Ethernet nutzt üblicherweise 1500 Byte",
   "Eine zu große MTU führt zu Fragmentierung",
   "Tunnel verringern die nutzbare MTU",
   "Eine höhere MTU erhöht immer den Durchsatz",
   "Die MTU wird vom DNS-Server vorgegeben"),
  (0, 1, 2, 3),
  "1500 Byte sind der Ethernet-Standard, Tunnel-Header knabbern davon ab und erzwingen Fragmentierung oder Path-MTU-Discovery. Größere Werte helfen nur, wenn die gesamte Strecke mitspielt.",
  "Which statements about the MTU are correct?",
  ("It limits the maximum payload of a frame",
   "Ethernet typically uses 1500 bytes",
   "Too large an MTU leads to fragmentation",
   "Tunnels reduce the usable MTU",
   "A higher MTU always increases throughput",
   "The MTU is dictated by the DNS server"),
  "1500 bytes is the Ethernet standard; tunnel headers eat into it and force fragmentation or path MTU discovery. Larger values only help if the entire path supports them."),

M("ap2-net-r57",
  "Welche Aufgaben übernimmt ein Load Balancer?",
  ("Er verteilt Anfragen auf mehrere Server",
   "Er erkennt ausgefallene Backends",
   "Er nimmt einzelne Server aus der Verteilung",
   "Er ermöglicht Wartung ohne Ausfall nach außen",
   "Er erhöht die Rechenleistung der Backends",
   "Er ersetzt die Datensicherung der Server"),
  (0, 1, 2, 3),
  "Verteilung, Zustandsprüfung und gezieltes Herausnehmen einzelner Server erlauben Wartung im laufenden Betrieb. Rechenleistung und Sicherung bleiben Sache der Server.",
  "Which tasks does a load balancer perform?",
  ("It distributes requests across several servers",
   "It detects failed backends",
   "It removes individual servers from rotation",
   "It enables maintenance without outward downtime",
   "It increases the processing power of the backends",
   "It replaces the servers' data backup"),
  "Distribution, health checking and deliberately removing individual servers allow maintenance during operation. Processing power and backup remain the servers' concern."),

M("ap2-net-r58",
  "Welche Angaben braucht man, um ein Subnetz vollständig zu beschreiben?",
  ("Die Netzadresse", "Die Präfixlänge oder Maske",
   "Die Broadcast-Adresse", "Den nutzbaren Hostbereich",
   "Die Anzahl der Switches im Segment", "Den Hersteller der Netzwerkkarten"),
  (0, 1, 2, 3),
  "Netzadresse, Präfix, Broadcast und Hostbereich beschreiben ein Subnetz vollständig und rechnerisch überprüfbar. Gerätedetails gehören in die Inventarliste.",
  "Which details are needed to describe a subnet completely?",
  ("The network address", "The prefix length or mask",
   "The broadcast address", "The usable host range",
   "The number of switches in the segment", "The manufacturer of the network cards"),
  "Network address, prefix, broadcast and host range describe a subnet completely and verifiably. Device details belong in the inventory."),

M("ap2-net-r59",
  "Welche Aussagen über WLAN in größeren Umgebungen sind richtig?",
  ("Ein Controller verwaltet mehrere Access Points zentral",
   "Benachbarte Zellen sollten verschiedene Kanäle nutzen",
   "Roaming erlaubt den Wechsel ohne Verbindungsabbruch",
   "Eine Ausleuchtungsmessung hilft bei der Planung",
   "Mehr Sendeleistung löst Überlappungsprobleme",
   "Alle Access Points sollten denselben Kanal nutzen"),
  (0, 1, 2, 3),
  "Zentrale Steuerung, Kanalplanung, Roaming und Messung sind das Handwerkszeug. Gleiche Kanäle und mehr Leistung verschärfen die gegenseitige Störung.",
  "Which statements about WLAN in larger environments are correct?",
  ("A controller manages several access points centrally",
   "Neighbouring cells should use different channels",
   "Roaming allows switching without dropping the connection",
   "A site survey helps with planning",
   "More transmit power solves overlap problems",
   "All access points should use the same channel"),
  "Central control, channel planning, roaming and measurement are the tools of the trade. Identical channels and more power worsen mutual interference."),

M("ap2-net-r60",
  "Welche Aussagen zu DNS in Firmennetzen sind zutreffend?",
  ("Forward-Zonen lösen Namen zu Adressen auf",
   "Reverse-Zonen lösen Adressen zu Namen auf",
   "Die TTL steuert die Gültigkeit im Cache",
   "Interne und externe Sichten können sich unterscheiden",
   "DNS vergibt zusätzlich die IP-Adressen der Clients",
   "Ein DNS-Eintrag gilt grundsätzlich unbegrenzt"),
  (0, 1, 2, 3),
  "Forward und Reverse decken beide Richtungen ab, die TTL steuert das Zwischenspeichern, und Split-DNS trennt interne von externen Antworten. Adressvergabe ist Sache von DHCP.",
  "Which statements about DNS in company networks are correct?",
  ("Forward zones resolve names to addresses",
   "Reverse zones resolve addresses to names",
   "The TTL controls validity in the cache",
   "Internal and external views can differ",
   "DNS additionally assigns clients their IP addresses",
   "A DNS record is fundamentally valid indefinitely"),
  "Forward and reverse cover both directions, the TTL controls caching, and split DNS separates internal from external answers. Address assignment is DHCP's job."),

M("ap2-net-r61",
  "Welche Schritte gehören zur Inbetriebnahme eines neuen Standortnetzes?",
  ("Adressbereich aus dem Gesamtplan zuteilen",
   "VLANs und deren Zweck festlegen",
   "Routing zum Hauptstandort einrichten",
   "Konfiguration und Adressen dokumentieren",
   "Adressen frei nach Verfügbarkeit vergeben",
   "Dokumentation erst bei der ersten Störung anlegen"),
  (0, 1, 2, 3),
  "Planvolle Zuteilung, VLAN-Konzept, Routing und Dokumentation machen den Standort betreibbar und erweiterbar. Freihändige Vergabe erzeugt genau die Überschneidungen, die später Ärger machen.",
  "Which steps belong to commissioning a new site network?",
  ("Allocate an address range from the overall plan",
   "Define VLANs and their purpose",
   "Set up routing to the main site",
   "Document configuration and addresses",
   "Assign addresses freely as available",
   "Create documentation only at the first incident"),
  "Planned allocation, a VLAN concept, routing and documentation make the site operable and extensible. Ad-hoc assignment creates exactly the overlaps that cause trouble later."),

M("ap2-net-r62",
  "Welche Aussagen über IPsec sind korrekt?",
  ("Es sichert Vertraulichkeit der Nutzdaten",
   "Es prüft die Integrität der Pakete",
   "Es authentisiert die Gegenstelle",
   "Es kennt Tunnel- und Transportmodus",
   "Es arbeitet ausschließlich auf Schicht 7",
   "Es ersetzt die Notwendigkeit von Firewalls"),
  (0, 1, 2, 3),
  "IPsec liefert Vertraulichkeit, Integrität und Authentizität auf Schicht 3, wahlweise im Tunnel- oder Transportmodus. Eine Firewall ersetzt es nicht.",
  "Which statements about IPsec are correct?",
  ("It secures confidentiality of the payload",
   "It verifies the integrity of the packets",
   "It authenticates the remote peer",
   "It knows tunnel and transport mode",
   "It works exclusively on layer 7",
   "It removes the need for firewalls"),
  "IPsec provides confidentiality, integrity and authenticity on layer 3, either in tunnel or transport mode. It does not replace a firewall."),

M("ap2-net-r63",
  "Welche Symptome deuten auf eine Duplex- oder Geschwindigkeitsfehlanpassung hin?",
  ("Auffällig viele Kollisionen an einem Port",
   "Sehr geringer Durchsatz trotz bestehender Verbindung",
   "Zunehmende Fehlerzähler auf der Schnittstelle",
   "Eine Seite fest eingestellt, die andere auf Automatik",
   "Ein vollständig dunkler Link an beiden Enden",
   "Eine falsch eingetragene DNS-Serveradresse"),
  (0, 1, 2, 3),
  "Kollisionen, mieser Durchsatz und wachsende Fehlerzähler bei gemischter Einstellung sind das klassische Bild. Ein toter Link wäre ein Schicht-1-Problem, DNS liegt weit darüber.",
  "Which symptoms indicate a duplex or speed mismatch?",
  ("Conspicuously many collisions on a port",
   "Very low throughput despite an established link",
   "Rising error counters on the interface",
   "One side fixed, the other set to autonegotiation",
   "A completely dark link at both ends",
   "An incorrectly entered DNS server address"),
  "Collisions, poor throughput and rising error counters with mixed settings are the classic picture. A dead link would be a layer 1 problem, DNS lies far above."),

M("ap2-net-r64",
  "Welche Aussagen über Portweiterleitungen sind zutreffend?",
  ("Sie machen einen internen Dienst von außen erreichbar",
   "Sie brauchen Ziel-IP und Zielport intern",
   "Sie vergrößern die Angriffsfläche des Netzes",
   "Eine DMZ ist für solche Dienste die sicherere Lösung",
   "Sie verschlüsseln den weitergeleiteten Verkehr",
   "Sie sind für ausgehende Verbindungen erforderlich"),
  (0, 1, 2, 3),
  "Eine Weiterleitung öffnet gezielt einen Weg nach innen - genau deshalb gehört der Dienst besser in eine DMZ. Verschlüsselung entsteht dadurch nicht, und ausgehend regelt NAT das ohnehin.",
  "Which statements about port forwarding are correct?",
  ("They make an internal service reachable from outside",
   "They need an internal destination IP and port",
   "They enlarge the attack surface of the network",
   "A DMZ is the safer solution for such services",
   "They encrypt the forwarded traffic",
   "They are required for outbound connections"),
  "A forwarding rule deliberately opens a path inward - which is exactly why the service belongs in a DMZ. It creates no encryption, and outbound traffic is handled by NAT anyway."),

# ------------------------------------------------------------------ text (36)
T("ap2-net-r65", "Wie viele nutzbare Hostadressen bietet ein /26-Netz?", "62",
  "6 Hostbits ergeben 64 Adressen, abzüglich Netz- und Broadcastadresse bleiben 62.",
  "How many usable host addresses does a /26 network provide?", "62",
  "6 host bits give 64 addresses; minus network and broadcast, 62 remain."),

T("ap2-net-r66", "Welche Präfixlänge fasst vier aufeinanderfolgende /24-Netze zusammen?", "/22",
  "Zwei Bits weniger Präfix decken vier Netze ab. Das verkleinert die Routingtabelle spürbar.",
  "Which prefix length summarises four consecutive /24 networks?", "/22",
  "Two fewer prefix bits cover four networks. This noticeably shrinks the routing table."),

T("ap2-net-r67", "Wie lautet die Netzadresse zu 192.168.14.77/28?", "192.168.14.64",
  "Bei /28 beträgt die Blockgröße 16: die Grenzen liegen bei 64 und 80, also fällt 77 in den Block ab 64.",
  "What is the network address for 192.168.14.77/28?", "192.168.14.64",
  "With /28 the block size is 16: boundaries lie at 64 and 80, so 77 falls into the block starting at 64."),

T("ap2-net-r68", "Welches Präfix kennzeichnet IPv6-Link-Local-Adressen?", "fe80::/10",
  "Jede IPv6-Schnittstelle bildet eine solche Adresse automatisch; Router leiten sie nicht weiter.",
  "Which prefix identifies IPv6 link-local addresses?", "fe80::/10",
  "Every IPv6 interface forms such an address automatically; routers do not forward them."),

T("ap2-net-r69", "Wie viele Bit umfasst die VLAN-Kennung nach 802.1Q?", "12",
  "12 Bit ergeben 4096 Werte, von denen 4094 als VLAN-IDs nutzbar sind.",
  "How many bits does the 802.1Q VLAN identifier comprise?", "12",
  "12 bits give 4096 values, of which 4094 are usable as VLAN IDs."),

T("ap2-net-r70", "Welche Subnetzmaske entspricht der Präfixlänge /21?", "255.255.248.0",
  "Fünf gesetzte Bits im dritten Oktett ergeben 248, die Blockgröße beträgt damit 8.",
  "Which subnet mask corresponds to prefix length /21?", "255.255.248.0",
  "Five set bits in the third octet give 248, so the block size is 8."),

T("ap2-net-r71", "Wie viele /28-Subnetze passen in ein /24-Netz?", "16",
  "Vier zusätzliche Netzbits ergeben 2 hoch 4 gleich 16 Subnetze mit je 14 nutzbaren Adressen.",
  "How many /28 subnets fit into a /24 network?", "16",
  "Four additional network bits give 2 to the power of 4, i.e. 16 subnets with 14 usable addresses each."),

T("ap2-net-r72", "Welches Protokoll stellt ein redundantes virtuelles Gateway bereit?", "VRRP",
  "Mehrere Router teilen eine virtuelle IP; fällt der aktive aus, übernimmt ein anderer unbemerkt.",
  "Which protocol provides a redundant virtual gateway?", "VRRP",
  "Several routers share a virtual IP; if the active one fails another takes over unnoticed."),

T("ap2-net-r73", "Wie lautet die Broadcast-Adresse von 10.20.30.0/27?", "10.20.30.31",
  "Ein /27 umfasst 32 Adressen, der erste Block reicht also von .0 bis .31.",
  "What is the broadcast address of 10.20.30.0/27?", "10.20.30.31",
  "A /27 covers 32 addresses, so the first block runs from .0 to .31."),

T("ap2-net-r74", "Welche MTU nutzt klassisches Ethernet standardmäßig, in Byte?", "1500",
  "Tunnel und zusätzliche Header verringern den nutzbaren Wert und erzwingen Path-MTU-Discovery.",
  "Which MTU does classic Ethernet use by default, in bytes?", "1500",
  "Tunnels and additional headers reduce the usable value and force path MTU discovery."),

T("ap2-net-r75", "Welches Verfahren ordnet vielen internen Adressen über Ports eine öffentliche zu?", "PAT",
  "Port Address Translation, oft auch NAT Overload genannt. Die Portnummer hält die Verbindungen auseinander.",
  "Which method maps many internal addresses to one public address using ports?", "PAT",
  "Port address translation, often called NAT overload. The port number keeps connections apart."),

T("ap2-net-r76", "Wie viele nutzbare Adressen bietet ein /30-Netz?", "2",
  "Genau zwei - deshalb ist /30 der Standard für Punkt-zu-Punkt-Verbindungen zwischen Routern.",
  "How many usable addresses does a /30 network provide?", "2",
  "Exactly two - which is why /30 is the standard for point-to-point links between routers."),

T("ap2-net-r77", "Welche Präfixlänge empfiehlt IPv6 für ein einzelnes Subnetz?", "/64",
  "SLAAC bildet den Interface-Identifier aus 64 Bit, deshalb ist /64 die Regelgröße.",
  "Which prefix length does IPv6 recommend for a single subnet?", "/64",
  "SLAAC forms the interface identifier from 64 bits, which makes /64 the standard size."),

T("ap2-net-r78", "Welches Präfix ist in IPv6 für Unique Local Addresses reserviert?", "fc00::/7",
  "Es entspricht funktional den privaten IPv4-Bereichen und ist im Internet nicht routbar.",
  "Which prefix is reserved for unique local addresses in IPv6?", "fc00::/7",
  "It functionally corresponds to the private IPv4 ranges and is not routable on the internet."),

T("ap2-net-r79", "Welcher Dienst leitet DHCP-Broadcasts über eine Routergrenze weiter?", "DHCP-Relay",
  "Es nimmt die Broadcasts entgegen und schickt sie gerichtet an den Server, ergänzt um die Netzinformation.",
  "Which service forwards DHCP broadcasts across a router boundary?", "DHCP relay",
  "It receives the broadcasts and sends them unicast to the server, adding the network information."),

T("ap2-net-r80", "Wie viele Subnetze entstehen beim Wechsel von /16 auf /20?", "16",
  "Vier zusätzliche Netzbits ergeben 2 hoch 4 gleich 16 gleich große Subnetze.",
  "How many subnets result from moving from /16 to /20?", "16",
  "Four additional network bits give 2 to the power of 4, i.e. 16 equally sized subnets."),

T("ap2-net-r81", "Welcher Wert entscheidet bei mehreren Routingquellen über die bevorzugte Route?", "Administrative Distanz",
  "Je niedriger der Wert, desto vertrauenswürdiger die Quelle. Bei gleicher Quelle entscheidet danach die Metrik.",
  "Which value decides the preferred route when several routing sources exist?", "Administrative distance",
  "The lower the value, the more trusted the source. Within the same source the metric then decides."),

T("ap2-net-r82", "Wie lautet die erste nutzbare Hostadresse im Netz 172.16.8.0/22?", "172.16.8.1",
  "172.16.8.0 ist die Netzadresse, der nutzbare Bereich beginnt also direkt darüber.",
  "What is the first usable host address in the network 172.16.8.0/22?", "172.16.8.1",
  "172.16.8.0 is the network address, so the usable range begins directly above it."),

T("ap2-net-r83", "Welches Protokoll fragt Netzwerkgeräte zentral nach Zustandswerten ab?", "SNMP",
  "Werte werden über eine MIB gelesen; per Trap melden Geräte auch von sich aus Ereignisse.",
  "Which protocol centrally queries network devices for status values?", "SNMP",
  "Values are read through a MIB; devices also report events on their own via traps."),

T("ap2-net-r84", "Wie viele nutzbare VLAN-IDs stehen nach 802.1Q zur Verfügung?", "4094",
  "Von 4096 möglichen Werten sind 0 und 4095 reserviert.",
  "How many usable VLAN IDs does 802.1Q provide?", "4094",
  "Of 4096 possible values, 0 and 4095 are reserved."),

T("ap2-net-r85", "Welcher IPsec-Modus verschlüsselt das gesamte ursprüngliche Paket samt Header?", "Tunnelmodus",
  "Deshalb ist er die Wahl für Site-to-Site-VPNs; der Transportmodus schützt nur die Nutzdaten.",
  "Which IPsec mode encrypts the entire original packet including its header?", "Tunnel mode",
  "That makes it the choice for site-to-site VPNs; transport mode protects only the payload."),

T("ap2-net-r86", "Welche Präfixlänge brauchst du mindestens für 500 Hosts?", "/23",
  "Neun Hostbits ergeben 510 nutzbare Adressen; /24 mit 254 wäre zu klein.",
  "Which prefix length do you need at minimum for 500 hosts?", "/23",
  "Nine host bits give 510 usable addresses; a /24 with 254 would be too small."),

T("ap2-net-r87", "Wie heißt das Netz zwischen Internet und internem LAN für öffentlich erreichbare Dienste?", "DMZ",
  "Wird ein Dienst dort übernommen, steht der Angreifer noch immer vor einer Firewall zum LAN.",
  "What is the network between the internet and the internal LAN for public services called?", "DMZ",
  "If a service there is taken over, the attacker still faces a firewall towards the LAN."),

T("ap2-net-r88", "Welches Protokoll bündelt mehrere physische Leitungen zu einem logischen Kanal?", "LACP",
  "Das erhöht Bandbreite und Ausfallsicherheit, und Spanning Tree sieht nur noch einen Pfad.",
  "Which protocol bundles several physical links into one logical channel?", "LACP",
  "This raises bandwidth and resilience, and Spanning Tree sees only one path."),

T("ap2-net-r89", "Wie viele Hostbits bleiben bei einer Präfixlänge von /19?", "13",
  "32 minus 19 ergibt 13 Hostbits und damit 8190 nutzbare Adressen.",
  "How many host bits remain at a prefix length of /19?", "13",
  "32 minus 19 gives 13 host bits and therefore 8190 usable addresses."),

T("ap2-net-r90", "Welches Präfix umfasst in IPv6 den globalen Unicast-Bereich?", "2000::/3",
  "Weltweit routbare Adressen stammen aus diesem Block, darunter auch der Dokumentationsbereich 2001:db8::/32.",
  "Which prefix covers the global unicast range in IPv6?", "2000::/3",
  "Globally routable addresses come from this block, including the documentation range 2001:db8::/32."),

T("ap2-net-r91", "Wie viele Adressen umfasst ein /22-Netz insgesamt?", "1024",
  "10 Hostbits ergeben 2 hoch 10 gleich 1024 Adressen, davon 1022 nutzbar.",
  "How many addresses does a /22 network contain in total?", "1024",
  "10 host bits give 2 to the power of 10, i.e. 1024 addresses, of which 1022 are usable."),

T("ap2-net-r92", "Welches Verfahren lässt IPv6-Clients ihre Adresse aus dem Router-Präfix selbst bilden?", "SLAAC",
  "Der Router verteilt per Router Advertisement nur das Präfix, ein DHCP-Server ist nicht nötig.",
  "Which method lets IPv6 clients form their address from the router prefix themselves?", "SLAAC",
  "The router advertises only the prefix; a DHCP server is not required."),

T("ap2-net-r93", "Welche Firewallart merkt sich bestehende Verbindungen und lässt Antworten automatisch zu?", "Stateful Firewall",
  "Ein reiner Paketfilter bräuchte für jede Antwortrichtung eine eigene, starre Regel.",
  "Which kind of firewall remembers existing connections and permits replies automatically?", "Stateful firewall",
  "A pure packet filter would need its own rigid rule for every reply direction."),

T("ap2-net-r94", "Wie lautet die Präfixlänge zur Maske 255.255.255.252?", "/30",
  "252 entspricht 11111100, also sechs gesetzte Bits im letzten Oktett: 24 plus 6 ergibt 30.",
  "Which prefix length matches the mask 255.255.255.252?", "/30",
  "252 equals 11111100, i.e. six set bits in the last octet: 24 plus 6 gives 30."),

T("ap2-net-r95", "Welches Routingprotokoll begrenzt die Netzgröße auf 15 Hops?", "RIP",
  "Ab 16 Hops gilt ein Ziel als unerreichbar, weshalb RIP nur für kleine Netze taugt.",
  "Which routing protocol limits network size to 15 hops?", "RIP",
  "From 16 hops a destination counts as unreachable, which is why RIP suits only small networks."),

T("ap2-net-r96", "Wie viele nutzbare Adressen bietet ein /25-Netz?", "126",
  "7 Hostbits ergeben 128 Adressen, abzüglich Netz- und Broadcastadresse bleiben 126.",
  "How many usable addresses does a /25 network provide?", "126",
  "7 host bits give 128 addresses; minus network and broadcast, 126 remain."),

T("ap2-net-r97", "Welches Feld markiert Pakete für die Priorisierung durch QoS?", "DSCP",
  "Die Markierung im IP-Header steuert die Behandlung in den Warteschlangen der Router.",
  "Which field marks packets for prioritisation by QoS?", "DSCP",
  "The marking in the IP header controls how routers treat the packet in their queues."),

T("ap2-net-r98", "Wie lautet die Blockgröße im letzten Oktett bei der Präfixlänge /29?", "8",
  "Die Subnetzgrenzen liegen damit bei 0, 8, 16, 24 und so weiter.",
  "What is the block size in the last octet at prefix length /29?", "8",
  "Subnet boundaries therefore lie at 0, 8, 16, 24 and so on."),

T("ap2-net-r99", "Welcher Dienst nimmt Anfragen von außen entgegen und verteilt sie auf interne Webserver?", "Reverse Proxy",
  "Er terminiert häufig auch TLS und verbirgt die interne Struktur vor dem Internet.",
  "Which service accepts external requests and distributes them to internal web servers?", "Reverse proxy",
  "It often also terminates TLS and hides the internal structure from the internet."),

T("ap2-net-r100", "Wie viele zusätzliche Netzbits braucht man, um ein Netz in 8 Subnetze zu teilen?", "3",
  "2 hoch 3 ergibt 8, also verlängert sich das Präfix um genau drei Bit.",
  "How many additional network bits are needed to split a network into 8 subnets?", "3",
  "2 to the power of 3 gives 8, so the prefix grows by exactly three bits."),
]

build("ap2-netzwerke-subnetting.json", "Netzwerke & Subnetting", "Networks & Subnetting", Q)
